src/cc/CMakeLists.txt
The bcc build with latest clang/llvm 7.0 has the following
compilation error:
```
/home/yhs/work/llvm/build/install/lib/libclangCodeGen.a(CodeGenAction.cpp.o):
In function `clang::BackendConsumer::Initialize(clang::ASTContext&)':
CodeGenAction.cpp:(.text._ZN5clang15BackendConsumer10InitializeERNS_10ASTContextE[_ZN5clang15BackendConsumer10InitializeERNS_10ASTContextE]+0xc): undefined reference to `clang::FrontendTimesIsEnabled'
...
```
The latest clang defined clang::FrontendTimesIsEnabled in
libclangFrontend.a and used in libclangCodeGen.a.
Due to the library order specified in clang_libs.cmake:
```
set(clang_libs
${libclangFrontend}
...
${libclangCodeGen}
```
and the fact clang_libs here is used to build bcc-static,
the definition of clang::FrontendTimesIsEnabled is dropped
since nobody …
=> fix compilation with latest clang/llvm 7.0

src/cc/frontends/clang/b_frontend_action.cc, src/cc/frontends/clang/b_frontend_action.h, tests/python/test_clang.py
The bcc rewriter is currently unable to detect external pointers (i.e., to a memory address that requires calls to `bpf_probe_read`) if they are not declared as arguments, e.g., if they are retrieved through the context argument.
For example, although the two following examples translate to the same C code in the end (the bcc rewriter translates the first into the second), the `sk` pointer is recognized as an external pointer only in the first example.
```c
int test1(struct pt_regs *ctx, struct sock *sk) {
// sk is correctly recognized as an external pointer.
}
int test2(struct pt_regs *ctx) {
struct sock *sk = (struct sock *)ctx->di;
// sk is not recognized as an external pointer.
}
```
This pull request fixes that by detecting member dereferences of the context argument (i.e., the first …
=> Detect external pointers from context argument

src/cc/bpf_module.cc
The format string for `bpf_trace_printk()` gets garbled during the conversion of the LLVM IR code to the corresponding BPF object. This happens because bcc explicitly sets the data layout of the module to `e-m:e-p:64:64-i64:64-n32:64-S128` which is valid for little-endian targets only. If the arch is set to `bpf`, LLVM selects the correct data layout automatically and there is no need to set this explicitly.
Reported-by: @chandanr
Fixes: #1723
=> Fix bpf_trace_printk() for big-endian targets

src/python/bcc/__init__.py
I am getting the following error when running the tests locally (Python 2.7.14):
```pytb
======================================================================
ERROR: test_complex (__main__.TestClang)
File "../../tests/python/test_clang.py", line 40, in test_complex
b = BPF(src_file="test_clang_complex.c", debug=0)
File "/git/bcc6/src/python/bcc/__init__.py", line 311, in __init__
src_file = BPF._find_file(src_file)
File "/git/bcc6/src/python/bcc/__init__.py", line 222, in _find_file
t = b"/".join([os.path.abspath(os.path.dirname(argv0)), filename])
File "/usr/lib/python2.7/posixpath.py", line 122, in dirname
i = p.rfind('/') + 1
AttributeError: 'ArgString' object has no attribute …
```
=> Fix "'ArgString' object has no attribute 'rfind'" error

tools/old/bashreadline.py, tools/old/tcpaccept.py, tools/old/tcpconnect.py
I'm not sure whether we want to keep doing minimal maintenance on the `old/tools` scripts. From what I understand/read, we moved old tools to this location if the newer versions require some recent kernel feature. In that case, I'm guessing we should make sure they still run with the last version of bcc.
This pull request makes a few fixes to ensure that is still the case.
=> old/tools: Diverse fixes

src/python/bcc/usdt.py, tools/trace.py
Running `trace` on a binary's USDT while fetching some arguments (`$ sudo python3 trace.py -p $(pidof ruby) 'u:ruby:array__create "%d", arg1'`) fails with `argument 2: <class 'TypeError'>: wrong type`.
This PR fixes the encoding of the USDT probe name to the `get_probe_arg_ctype`, by encoding it to a bytestring and decoding it afterwards. I've tested this works in Python2 too 😄 
Cheers!
=> Fix USDT probes arguments' encoding in Python3

tools/runqlat.py, tools/runqslower.py
Run queue latency does not make much sense for idle `swapper` threads.
The same happens in `perf sched`:
* https://github.com/torvalds/linux/blob/v4.14/tools/perf/builtin-sched.c
```c
/*
* Ignore idle threads:
*/
if (!strcmp(thread__comm_str(work_list->thread), "swapper"))
return;
```
```c
static bool is_idle_sample(struct perf_sample *sample,
struct perf_evsel *evsel)
{
/* pid 0 == swapper == idle task */
if (strcmp(perf_evsel__name(evsel), "sched:sched_switch") == 0)
return perf_evsel__intval(evsel, sample, "prev_pid") == 0;
return sample->pid == 0;
}
```
=> Skip idle swapper threads, closes #1732

src/python/bcc/__init__.py
This PR fixes the encoding issue in Python3 by converting the argument passed to `find` to a bytearray.
Thanks! 😄
=> Fix `trace_fields` Python3 encoding issue

src/python/bcc/__init__.py
- Fix a crash in the python binding when trying to open a perf buffer
in python < 3.6
- See https://github.com/iovisor/bcc/issues/1744
=> Fix issue #1744.

examples/tracing/bitehist.py, examples/tracing/trace_fields.py, examples/tracing/vfsreadlat.py, src/cc/frontends/p4/compiler/topoSorting.py, src/cc/frontends/p4/test/testP4toEbpf.py
Hi!
After bumping into some minor Python3 incompatibilities that are already fixed upstream (thanks a bunch!! 😄), I decided to have a look to see if there were more! 
This PR replaces the `print` statement with the Python3 printing function. It also adds `from __future__ import print_function` where needed to have the same print semantics in Python2.
Thanks! :)
PS: I also checked scripts that don't have the import, but didn't submit a PR because these cases work fine in Python3, although the semantics are different and it might be needed in the future. These changes are [here](https://github.com/javierhonduco/bcc/commit/cd5fad2454680a853b632afa0f7514d7dad0b49e), let me know if you think it would be worth merging :).
=> Use print function for Python3 compatibility

src/python/bcc/__init__.py
Fix issue #1747.
In commit #1647, we excluded all symbols outside [_stext, _etext].
This is incorrect as it excluded module symbols as well.
This patch changed the algorithm to only skip symbols
in init sections [__init_begin, __init_end].
=> fix get_kprobe_functions

src/python/bcc/__init__.py
=> Do not print C source after BPF compile fail

src/cc/api/BPF.cc, src/cc/api/BPF.h
Currently do calculate the syscall prefix in `BPF::init`, which requires loading `kallsyms` etc. But a lot of times the functionality will not be used. This commit changes that we only calculate the syscall prefix the first time we call `get_syscall_fnname`
Also change to use the `KSym` class directly for better destruct production
=> Do not calculate syscall prefix proactively in C++ API

examples/cpp/FollyRequestContextSwitch.cc, src/cc/api/BPF.h
This PR:
- Adds `ostream` logging for USDT debug message
- Expose `init()` so that user could proactively check validness of the USDT
=> Misc fixes for C++ USDT class

introspection/CMakeLists.txt
the issue is reported at #1759.
bps does not need any C++ library functions in bcc.
It only needs libbpf. So link it with bpf-static instead
of bcc-static. This avoids pulling in any C++ module/symbolization/usdt
functions and llvm libraries.
On my local box, the binary size is reduced from ~60MB to 44KB.
=> link with bpf-static library for bps

src/cc/api/BPF.cc, src/cc/api/BPF.h, src/cc/libbpf.c, src/cc/libbpf.h
The bpf_attach_perf_event_raw API is designed to provide maximum flexibility for people to use advanced features of Kernel Perf Events with BPF. Some times specifying flags is necessary, such as if we want to use `PERF_FLAG_PID_CGROUP` to profile a container. This commit adds `extra_flag` option to C and C++ interface
I fee bad for the interface change after introducing the interface. However it was not so long time ago so I guess it should be find...:)
=> Add extra_flag option to bpf_attach_perf_event_raw

tools/xfsslower.py, tools/zfsslower.py
Since #1737, the bcc rewriter is able to track more external pointers going through maps.  xfsslower was relying on the rewriter not being able to replace some dereferences.  This commit takes this
into account and removes two unnecessary calls to `bpf_probe_read`.
Fixes #1766.
/cc @bobrik
=> xfsslower: Fix compilation error due to rewriter update

src/cc/usdt/usdt.cc
And add error message to hint if the problem is that the passed binary
path is not absolute or if the binary doesn't exist.
In case the PID is correct:
* but the binary couldn't be found, it will print:
```
HINT: Specified binary doesn't exist.
[...]
```
* but the binary is not absolute:
```
HINT: Binary path should be absolute.
[...]
```
Otherwise, it should keep behaving as before.
Let me know if there are better approaches to do this (first steps in C++ here 😄)!
=> usdt: fail when binary doesn't exist. Fixes #1749

man/man8/argdist.8, man/man8/funclatency.8, man/man8/syscount.8, tools/argdist.py, tools/argdist_example.txt, tools/funclatency.py, tools/funclatency_example.txt, tools/syscount.py, tools/syscount_example.txt
Adding "-d" (duration) trace option to argdist, funclatency and syscount functionalities. This could be helpful when tracing hot-paths in kernel for specific duration.
=> Add -d (duration) option to argdist, funclatency and syscount

src/cc/frontends/clang/b_frontend_action.cc, tests/python/test_clang.py
We should only track and rewrite external pointers from the context pointer for tracing programs.  Other types of context pointers point to e.g. packets and do not require a rewrite to a `bpf_probe_read` call.
I should have done this before, in #1724.
=> Limit dereference rewriter to tracing contexts

tools/execsnoop.py
by escaping newlines. Fixes #1037
* Before:
```
$ sudo /usr/share/bcc/tools/execsnoop
PCOMM            PID    PPID   RET ARGS
awk              9910   7831     0 /usr/bin/awk
BEGIN { print "hi" }
```
* With this patch:
```
$ sudo /usr/share/bcc/tools/execsnoop
PCOMM            PID    PPID   RET ARGS
awk              10033  7831     0 /usr/bin/awk \nBEGIN { print "hi" }
```
:warning: I haven't tested this in Python2 as I haven't managed to make it work BCC with Python2 on my machine
=> execsnoop: don't print newlines in argv

src/cc/frontends/clang/b_frontend_action.cc, src/cc/frontends/clang/b_frontend_action.h, tests/python/test_clang.py
This is essentially the same fix as #1733, but for external pointers with several levels of indirection instead of structure member dereferencing.
Currently, the bcc rewriter is unable to track external pointers if there is more than a single level of indirection (e.g., pointer to external pointer).  For example, in the following, the rewriter is unable to detect that `ptr2` doesn't need a call to bpf_probe_read, only `*ptr2` do.
```c
int test(struct pt_regs *ctx, struct sock *sk) {
struct sock *ptr1;
struct sock **ptr2 = &ptr1;
*ptr2 = sk;
return ((struct sock *)(*ptr2))->sk_daddr;
}
```
This pull request fixes this issue by tracking the levels of indirections in addition to the variable declarations (identifies each variable).  When traversing dereferences, the level of indirections is …
=> Fix dereference replacements for pointers to pointers

tools/tcplife.py
rewriter tried to rewrite an argument for a user written
bpf_probe_read and triggers a clang compilation error.
```
$ tcplife.py
/virtual/main.c:134:41: error: cannot take the address of an rvalue of type 'typeof(u64)' (aka 'unsigned long long')
...&({ typeof(u64) _val; __builtin_memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)&tp->bytes_received); _val; }));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/virtual/main.c:135:41: error: cannot take the address of an rvalue of type 'typeof(u64)' (aka 'unsigned long long')
...&({ typeof(u64) _val; __builtin_memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)&tp->bytes_acked); _val; })); …
```
=> fix tcplife.py rewriter issue

tools/zfsdist.py
The BPF.get_kprobe_functions method tests if the passed argument
matches with a line of kallsyms, which is opened in binary mode.
Therefore the regex pattern must be bytes as well.
=> zfsdist: fix for python3

src/cc/frontends/clang/b_frontend_action.cc, src/cc/frontends/clang/b_frontend_action.h
Fix issue #1730
Linux kernel commit 2bc2f688fdf8 ("Makefile: move stack-protector
availability out of Kconfig") moved CONFIG_CC_STACKPROTECTOR
from Kconfig to Makefile. Commit 44c6dc940b19 ("Makefile: introduce
CONFIG_CC_STACKPROTECTOR_AUTO") introduced CONFIG_CC_STACKPROTECTOR_AUTO.
Whether CONFIG_CC_STACKPROTECTOR is defined depends on
CONFIG_CC_STACKPROTECTOR_{AUTO,REGULAR,STRONG}. Since the clang supports
stack-protector, CONFIG_CC_STACKPROTECTOR_AUTO will imply
CONFIG_CC_STACKPROTECTOR for gcc/clang based compilation.
Such changes are introduced in 4.16. For example, the following code
is defined in linux/include/linux/sched.h,
```
pid_t                           pid;
pid_t                           tgid;
/* Canary value for the -fstack-protector GCC feature: */
unsigned long …
```
=> let rewriter add code to define CONFIG_CC_STACKPROTECTOR

tools/tcplife.py
When using tracepoints, the destination port is retrieved in host byte order and there is no need to convert it, contrary to the kprobe version.
Fixes #1788 
/cc @myllynen
=> tcplife: fix dport filter on tracepoints

src/cc/api/BPF.cc, src/cc/api/BPF.h, src/cc/libbpf.c, src/cc/libbpf.h, src/python/bcc/__init__.py
Currently, `attach_kprobe()` only allows a `kprobe` to be attached to an arch-dependent default location usually in the prologue of the function corresponding to the event. With these changes, one can attach a `kprobe` at a custom offset from the start of the function.
=> Add support for attaching kprobes at custom offsets

src/cc/frontends/clang/b_frontend_action.cc, src/cc/frontends/clang/b_frontend_action.h, tests/python/test_clang.py
The code to track assignments of external pointers was scattered between `VisitVarDecl` and `VisitBinaryOperator`. This commit defines a shared `assignsExtPtr` method.
Doing so also fixes a bug as `VisitVarDecl` was missing a case for external pointers retrieved from maps.
=> Refactor external pointer assignments

src/cc/frontends/clang/loader.cc
In 4.17 kernel, x86 build requires compiler asm-goto support. clang
does not support asm-goto and bpf program compilation started to break.
The following kernel commit
```
commit b1ae32dbab50ed19cfc16d225b0fb0114fb13025
Author: Alexei Starovoitov <ast@kernel.org>
Date:   Sun May 13 12:32:22 2018 -0700
x86/cpufeature: Guard asm_volatile_goto usage for BPF compilation
Workaround for the sake of BPF compilation which utilizes kernel
headers, but clang does not support ASM GOTO and fails the build.
```
workarounded the issue by permitting native clang compilation.
A warning message, however, is issued:
```
./arch/x86/include/asm/cpufeature.h:150:2: warning: "Compiler lacks ASM_GOTO support.
Add -D __BPF_TRACING__ to your compiler arguments" [-W#warnings]
#warning "Compiler lacks ASM_GOTO …
```
=> Add "-D __BPF_TRACING__" to frontend compilation flags

src/cc/frontends/clang/b_frontend_action.cc, tests/python/test_clang.py, tools/tcptop.py
`bpf_probe_read()` is often used to access pointees in bpf programs.
Recent rewriter has become smarter so a lot of `bpf_probe_read()`
can be replaced with simple pointer/member access.
In certain cases, `bpf_probe_read()` is still preferred though.
For example, kernel `net/tcp.h` defined `TCP_SKB_CB` as below
```
#define TCP_SKB_CB(__skb)	((struct tcp_skb_cb *)&((__skb)->cb[0]))
```
User can use below to access `tcp_gso_size` of a skb data structure.
```
TCP_SKB_CB(skb)->tcp_gso_size
```
The rewriter will fail as it attempts to rewrite `(__skb)->cb[0]`.
Instead of chasing down to prevent exactly the above pattern,
this patch detects function `bpf_probe_read()` in `ProbeVisitor` and
will skip it so `bpf_probe_read()`'s parameters will not be
rewritten. This can also help other cases where …
=> skip probe rewriter for bpf_probe_read()

src/cc/libbpf.c
The memory allocated by getline() is not freed.
This may cause some tool like clang memory
leak sanitizer complain.
=> fix a memory leak for getline()

README.md, man/man8/tcpdrop.8, src/python/bcc/tcp.py, tools/tcpdrop.py, tools/tcpdrop_example.txt
Needed this for a production issue.
This is the first tool (that I know of) to dig into the TCP and IP headers, and I've created a new tcp bcc library to help a bit with that.
=> add tcpdrop tool

src/cc/frontends/clang/tp_frontend_action.cc
Fix issue #1807
tracepoint may have a format like this:
(from syscalls/sys_enter_socket)
```
field:unsigned short common_type;	offset:0;	size:2;	signed:0;
field:unsigned char common_flags;	offset:2;	size:1;	signed:0;
field:unsigned char common_preempt_count;	offset:3;	size:1;	signed:0;
field:int common_pid;	offset:4;	size:4;	signed:1;
field:int __syscall_nr;	offset:8;	size:4;	signed:1;
field:int family;	offset:16;	size:8;	signed:0;
field:int type;	offset:24;	size:8;	signed:0;
field:int protocol;	offset:32;	size:8;	signed:0;
```
Current rewriter generates:
```
struct tracepoint__syscalls__sys_enter_socket {
u64 __do_not_use__;
int __syscall_nr;
int family;
int type;
int protocol;
};
```
This is incorrect as in the above structure, offsets of
`family`/`type`/`procotol` becomingg 12/16/20. …
=> adjust tracepoint field type based on size

tests/python/test_tools_smoke.py
If I'm not mistaken, this tool requires a kernel >= 4.7 for the `tcp_drop` function (?).
=> Smoke test for tcpdrop

docs/reference_guide.md, examples/networking/xdp/xdp_redirect_cpu.py, examples/networking/xdp/xdp_redirect_map.py, src/cc/export/helpers.h, src/cc/frontends/clang/b_frontend_action.cc, src/python/bcc/__init__.py, src/python/bcc/table.py
This patch series adds DEVMAP and CPUMAP which are necessary for bpf_redirect_map().
v2:
+ Use ArrayBase as the base class of DEVMAP and CPUMAP
+ Add an example for CPUMAP and update the reference guide
=> [V2] Add two map types for bpf_redirect_map()

tools/tcplife.py
commit 95b3d8c fixed the dport filtering of the kprobes variant by
moving the network byte order to host byte order conversation before the
filtering. Before submitting the perf event the byte order of the dport
was again converted - this commit removes this double conversion.
=> tcplife: fix dport byte order

src/cc/libbpf.c
bcc uses some func prefixes for auto load purpose. These
func prefixes include "kprobe__", "tracepoint__" and
"raw_tracepoint__". Currently we also pass this
function name as the program name to the kernel.
The kernel can only accept 16 bytes so long program
name will be truncated. For example, with bps we will see
something like
287- <raw_tracepoint>       0      2 Jun10/17:07  raw_tracepoint_
290- tracepoint             0      4 Jun10/17:08  tracepoint__soc
297- kprobe                 0      2 Jun10/17:09  kprobe__tcp_cle
Such long prefixes are unnecessarily taking the space
for the real function name. This patch removed such prefixes
before giving them to the kernel.
The result will like below:
311- <raw_tracepoint>       0      2 Jun10/17:44  sched_switch
321- tracepoint             0 …
=> remove unnecessary prefix in some prog names

src/cc/frontends/clang/b_frontend_action.cc, src/cc/frontends/clang/b_frontend_action.h, tests/python/test_clang.py
#1796 stops the whole AST traversal if it meets a `bpf_probe_read` call.  I think the original intent was to simply not rewrite the third argument, so this commit fixes it by remembering the third argument on `bpf_probe_read` call traversals and overriding `dataTraverseStmtPre` to skip the traversal of that
argument when we meet it later.
/cc @yonghong-song
=> Fix #1796 and skip probe rewriter for bpf_probe_read

src/cc/frontends/clang/b_frontend_action.cc, src/cc/frontends/clang/b_frontend_action.h, tools/execsnoop.py, tools/killsnoop.py, tools/mountsnoop.py, tools/statsnoop.py, tools/syncsnoop.py, tools/trace.py
Fix issue #1802.
On x64, the following commit (in 4.17) changed the raw parameter passed to
the syscall entry function from a list of parameters supplied in user space
to a single `pt_regs *` parameter. Also in 4.17, x64 syscall entry function
is changed from `sys_<name>` to `__x64_sys_<name>`.
```
commit fa697140f9a20119a9ec8fd7460cc4314fbdaff3
Author: Dominik Brodowski <linux@dominikbrodowski.net>
Date:   Thu Apr 5 11:53:02 2018 +0200
syscalls/x86: Use 'struct pt_regs' based syscall calling convention for 64-bit syscalls
Let's make use of ARCH_HAS_SYSCALL_WRAPPER=y on pure 64-bit x86-64 systems:
Each syscall defines a stub which takes struct pt_regs as its only
argument. It decodes just those parameters it needs, e.g:
asmlinkage long sys_xyzzy(const struct pt_regs *regs)
{
return …
```
=> generate indirect parameter assignment if arch uses syscall wrapper

tools/tcpdrop.py, tools/zfsslower.py
Make the input string of get_kprobe_functions as
bytes literal in tcpdrop and zfsslower so the
tool can be python3 compatible.
=> make tcpdrop and zfsslower python3 compatible

tools/profile.py
Remove an unnecessary call to `bpf_probe_read` in `tools/profile.py`. Since `PT_REGS_IP(&ctx->regs)` is still a direct access to context, using `bpf_probe_read` is not required.
@brendangregg Do you remember if you had a particular reason for the `bpf_probe_read` call? Maybe some issue I missed with older kernels?
=> profile: remove unnecessary bpf_probe_read call

src/cc/frontends/clang/b_frontend_action.cc, tools/biosnoop.py, tools/filelife.py, tools/fileslower.py, tools/filetop.py, tools/mdflush.py, tools/slabratetop.py
This pull request extends the scope of #1796 and #1812. If the user decides to rely on a manual call to `bpf_probe_read`, we don't try to rewrite its last argument. This is needed as the rewriter starts to recognize and rewrite more and more dereferences. In particular, it fixes #1823's builds.
=> Skip dereferences inside bpf_probe_reads calls

src/cc/frontends/clang/b_frontend_action.cc, src/cc/frontends/clang/b_frontend_action.h, tests/python/test_clang.py, tools/tcpdrop.py
Surprisingly, the rewriter wasn't able to trace external pointers returned by inlined functions until now.  This commit fixes it by adding functions that return an external pointer to `ProbeVisitor`'s set of external pointers, along with the levels of indirection.
This change requires reversing a few traversals to visit called functions before they are called. Then, we check the presence of an external pointer on return statements and retrieve that information at the call expression.
With this, #1683 is finally fixed and shouldn't require any manual call to `bpf_probe_read` anymore.
=> Trace external pointers through function returns

tools/ext4slower.py
The new Linux version (since form 4.10) uses ext4_file_read_iter(), And if the 'CONFIG_FS_DAX' 
is not set ,then ext4_file_read_iter() will call generic_file_read_iter(), else it will call 
ext4_dax_read_iter(), and trace generic_file_read_iter() will fail.
=> Modify trace function from generic_file_read_iter() to ext4_file_read_iter()

src/cc/frontends/clang/b_frontend_action.cc, tests/python/test_clang.py
For the test case in this patch below,
```
#define _(P) ({typeof(P) val = 0; bpf_probe_read(&val, sizeof(val), &P); val;})
int count_tcp(struct pt_regs *ctx, struct sk_buff *skb) {
return _(TCP_SKB_CB(skb)->tcp_gso_size);
}
```
The clang AST will consider the whole `_(TCP_SKB_CB(skb)->tcp_gso_size)`
as a MemberExpr during AST traversal. However, it will consider
the start location of the member expression not rewritable.
Without this patch, we will get an error like below:
```
/virtual/main.c:15:44: error: expected ';' after return statement
return _(TCP_SKB_CB(skb)->tcp_gso_size)); _val; });
```
Basically, the start of `bpf_probe_read()` rewritingg failed but
later part succeeded, so the code becomes uncompilable.
Previously, we did not see such issues, but as rewriter got
more smarter …
=> prevent bpf_probe_read MemberExpr rewrite if not rewritable

src/python/CMakeLists.txt, src/python/bcc/__init__.py, src/python/bcc/version.py.in
Uses cmake to create a `version.py` with the `REVISION` from cmake
If the python module should be executable without cmake (at the moment the `__init__.py` imports `version.py` which is created on the fly by cmake), I could rename `version.py.in` to `version.py` and let cmake replace the file in the build process.
=> python: add __version__ attribute to bcc module

src/cc/frontends/clang/b_frontend_action.cc, src/cc/frontends/clang/b_frontend_action.h, tests/python/test_clang.py
When the rewriter meets a dereference of a member dereference it fails to properly rewrite them into calls to `bpf_probe_read`. The reason is that Clang is unable to track the position of rewritten text, but we can accommodate this by inserting text around the dereference instead of completely rewriting it. We are already doing that for member dereference, but not for simple dereference.
=> Fix nested dereference rewrites

src/cc/frontends/clang/b_frontend_action.cc, src/cc/frontends/clang/b_frontend_action.h, tests/python/test_clang.py
Fix issue #1830.
After the rewrite, the code approximately becomes
```
&(({type _val; bpf_probe_read(&_val, sizeof(_val), &(p->m)); _val)
```
Firstly the rewriting is really unnecessary, and secondly
the compilation will fail since the addressOf cannot take address
of the rvalue _val.
This patch intends to fix the problem by avoiding
the rewriting in the first place. The implementation
assumes no nested addressOf operations which should be
true in most cases if not all.
=> avoid probe rewriting of p->m in &(p->m)

src/cc/frontends/clang/b_frontend_action.cc, src/cc/frontends/clang/b_frontend_action.h, tests/python/test_clang.py
This pull request fixes external pointer propagation in nested dereferences and the count of indirections for `addrof`s of member dereferences (`&A->b`).
In nested dereferences, a dereference of an external pointer may give a new external pointer.  For example, if `A` is an external pointer, then `*A` and `A->b` should also be considered as external pointers when appropriate (e.g., in `**A` or `*(A->b)`).
In addition, a member dereference is a dereference, so we need to count it when counting the number of indirections in `ProbeChecker`. If we don't, `*(&A->b)` won't be rewritten correctly as `&A->b` will be
considered a pointer to an external pointer.
@yonghong-song This is a different fix than the one you implemented in #1831. I think it's a more general fix, as it isn't specific to the …
=> Fix external pointer propagation in nested dereferences

README.md, man/man8/criticalstat.8, tools/criticalstat.py, tools/criticalstat_example.txt
This tool detects code sections in the kernel where IRQs or preemption
are disabled for a user-specified amount of time.
Requires a kernel built with CONFIG_DEBUG_PREEMPT and
CONFIG_PREEMPTIRQ_EVENTS.
Signed-off-by: Joel Fernandes <joel@joelfernandes.org>
=> bcc: criticalstat: Add an atomic critical section tracer

tools/criticalstat.py
While changing the stack_id to be signed, I accidentally screwed the
check for an invalid stack_id. Some reason I didn't catch this even in
my tests. This patch fixes the issue (thanks Erick Reyes for reporting).
By the way, one weirdness I see is invalid stack_id is printed as -17
when I print it in python.
When I do bpf_trace_printk, I get these ids:
```
root@localhost:/# cat /d/tracing/trace_pipe
<idle>-0     [003] .n.3   942.100225: : sid: 15
<idle>-0     [002] .n.3   943.140393: : sid: 15
kworker/3:3-1798  [003] ...3   943.422768: : sid: 6
kworker/3:3-1798  [003] ...3   943.423419: : sid: 6
kworker/3:3-1798  [003] ...3   943.423967: : sid: 6
BootAnimation-650   [003] .n.3   949.840268: : sid: 8
<idle>-0     [003] .n.3   952.360226: : sid: 15
<idle>-0     [000] ...3   953.100116: : …
```
=> criticalstat: Fix check for invalid stacks

tests/python/test_tools_smoke.py, tools/argdist.py
Fix issue #1845.
The verbose output of argdist.py is broken.
The bpf.open_uprobes/open_kprobes have been
replaced by bpf.uprobe_fds/kprobe_fds.
Fix the argdist.py and add "-v" to the argdist.py test
in test_tools_smoke.py.
=> fix verbose output of tools/argdist.py

tools/profile.py
Another leftover from #986.
`profile` failes on my `python3` setup without properly decoding:
```
juergen@samson:~/cxx/bcc → sudo /usr/share/bcc/tools/profile  -f -U 3 
File "/usr/share/bcc/tools/profile", line 321, in <module>
print("%s %d" % (";".join(line), v.value))
TypeError: sequence item 1: expected str instance, bytes found
```
=> Decode C strings into Python strings

src/cc/frontends/clang/tp_frontend_action.cc
Fix issue #1853.
Commit 7c489469a7dc ("adjust tracepoint field type
based on size") tried to fix the tracepoint format
descrepancy between declared type and actual size is 8.
The type has to be promoted to match the size.
The commit introduced a bug if the field is an array.
For exmaple, `block:block_rq_complete` tracepoint has
field rwbs:
```
field:char rwbs[8];	offset:32;	size:8;	signed:1;
```
The current implementation will incorrectly translate it
into
```
s64 rwbs[8];
```
since it considers the type is "char".
This patch fixed this issue by checking the field name
and if it is an array, rewriting will be skipped.
=> fix a bug in tracepoint struct rewriter

examples/cpp/FollyRequestContextSwitch.cc, src/cc/api/BPF.cc, src/cc/api/BPF.h, src/cc/usdt.h, src/cc/usdt/usdt.cc, tests/cc/test_usdt_probes.cc
This PR makes C++ API uses `USDT::Context` and `USDT::Probe` directly instead of customized list-of-addresses logic. This has numbers of benefits:
- C++ API now automatically support USDT-for-PID
- C++ API now supports "same USDT from different binary in same PID"
- C++ API now support semaphore when attaching and detaching
- Reduces duplicated code and logic
=> Unify and improve C++'s USDT implementation

tools/ext4dist.py, tools/tcpaccept.py
From Linux 4.10, the function .read_iter at the ext4_file_operations has 
changed to ext4_file_read_iter.
So, I add the try and except,it will first to attach ext4_file_read_iter,
if fails and will attach the generic_file_read_iter which used to pre-4.10.
=> Modify tools/ext4dist.py for 4.10+

tools/runqlat.py, tools/runqslower.py, tools/tcpaccept.py, tools/tcptracer.py
Most of these calls have been rendered useless by #1828 ("Recognize context member dereferences despite array accesses").
=> tools: remove unnecessary calls to bpf_probe_read

src/cc/frontends/clang/b_frontend_action.cc, src/cc/frontends/clang/b_frontend_action.h, tests/python/test_clang.py, tools/tcpdrop.py
Stops at any array accesses on external pointers and tries to rewrite both the array access and the member dereference if any, in one shot. With this pull request, the following C code is rewritten properly into a single `bpf_probe_read` call.
```c
int test(struct pt_regs *ctx, const struct qstr *name) {
return name->name[1];
}
```
This is based on @yonghong-song's code from #1617. I added some code to retrieve the left bracket despite Clang's lack of support for a `getLBracketLoc` function and to handle a couple cases when the base of the array access is a member dereference.
Fixes #1617.
=> Rewrite array accesses

debian/control
In recent Ubuntu, llvm 6 is available. Use that as control file
dependency option. This is a requirement to enable the Ubuntu 18.04 buildbot.
=> debian: add llvm6.0 as possible dependency

src/cc/api/BPFTable.h, tests/cc/test_hash_table.cc
Use get_value() instead of lookup() as the value as in the case of
percpu tables the ValueType is an std::vector that has to be resized
before performing the lookup function.
Add also some testing for it.
Solves https://github.com/iovisor/bcc/issues/1860
Signed-off-by: Mauricio Vasquez B <mauricio.vasquez@polito.it>
=> fix get_table_offline for percpu hash table

man/man8/profile.8, tools/profile.py, tools/profile_example.txt
Summary:
sometime it is usefull to collect stack only from single cpu
for example you have single core saturated while others dont and you
want to know whats going on there. in this diff i'm adding this ability
(network related code could be example of when single core is saturated
as usually you have 1 to 1 mappng between rx queue and cpu)
example of generated code w/ CPU specified:
```
./tools/profile.py -C 14 2 --ebpf
Sampling at 49 Hertz of all threads by user + kernel stack for 2 secs.
struct key_t {
u32 pid;
u64 kernel_ip;
u64 kernel_ret_ip;
int user_stack_id;
int kernel_stack_id;
char name[TASK_COMM_LEN];
};
BPF_HASH(counts, struct key_t);
BPF_STACK_TRACE(stack_traces, 16384);
// This code gets a bit complex. Probably not suitable for casual hacking.
int do_perf_event(struct …
```
=> [profile.py]: adding support to collect profile only from specified CPU

tools/lib/ucalls.py
Prevents the following error when tracing a java program that contains
non-ascii method name:
```
File "/usr/share/bcc/tools/lib/ucalls", line 305, in <module>
data = get_data()   # [(function, (num calls, latency in ns))]
File "/usr/share/bcc/tools/lib/ucalls", line 266, in get_data
bpf["counts"].items()))
File "/usr/share/bcc/tools/lib/ucalls", line 264, in <lambda>
kv[0].method.decode(),
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 11: ordinal not in range(128)
```
Signed-off-by: Jerome Marchand <jmarchan@redhat.com>
=> ucalls: use replace error handler

src/cc/CMakeLists.txt
I'm using libbcc in another project, and would like to use bcc_usdt_new_frompid() etc like it currently uses bcc_resolve_symname(), instead of having to rewrite the USDT stuff.
=> add usdt calls to libbcc

CMakeLists.txt, SPECS/bcc.spec, cmake/clang_libs.cmake, man/man8/CMakeLists.txt, scripts/build-rpm.sh, tests/python/test_array.py, tools/inject.py, tools/killsnoop.py, tools/wakeuptime.py
This PR contains a series of fixes to enable a working fedora28 build.
patches 1-3: python3 compat fixes
patch 4: shared-only cmake option
patch 5: rpm packaging updates
=> Fedora 28 support

src/python/bcc/table.py
BPF_MAP_TYPE_LPM_TRIE supports element deletion since kernel commit
e454cf595853 ("bpf: Implement map_delete_elem for BPF_MAP_TYPE_LPM_TRIE")
which is available in 4.15 kernels onwards.
Signed-off-by: Eyal Birger <eyal.birger@gmail.com>
=> table: remove NotImplementedError on LpmTrie __delitem__ calls

docs/reference_guide.md, src/cc/export/helpers.h, src/cc/frontends/clang/loader.cc
BCC currently requires exactly matching headers. Sometimes this is quite
inconvenient especially if the kernel version is only very slightly
different such as updates in a stable kernel. This patch gives the user
the flexibility to override the the LINUX_VERSION_CODE provided in the
linux kernel headers, so that the eBPF program may load. We also print a
message when this is done, so that the user is warned about the override
happening and that results may be unpredictable.
Also updated the docs.
Signed-off-by: Joel Fernandes <joel@joelfernandes.org>
=> clang: loader: Allow user to override kernel version

man/man8/trace.8, tools/trace.py, tools/trace_example.txt
Summary:
sometimes in probe you want to compare char* w/ some predefined value
which is not a string. e.g. setsockopt syscall has signature like this:
sys_setsockopt(int fd, int level, int optname, char* optval, int optlen)
and if you want to catch where/who is setting up specific value you are
forced to compare optval against some predefined array. it's not
possible today w/ trace.py and in this diff i'm adding such ability
Test Plan:
as example: we want to catch setsockopt when someone is setting up
IP_TOS equal to 108
```
trace.py 'sys_setsockopt(int fd, int level, int optname, char* optval,
int optlen)(level==0 && optname == 1 && STRCMP("{0x6C,0x00, 0x00,
0x00}", optval))' -U -M 1 --bin_cmp -v
```
without this new modifier:
```
static inline bool streq_0(char const *ignored, uintptr_t …
```
=> [trace.py]: allow to use STRCMP helper with binary values

src/python/bcc/__init__.py
Fix issue #1910
Otherwise, we will have a type mismatch like below:
[root@aborniakFC tools]# ./ttysnoop 1
File "./ttysnoop", line 102, in <module>
File "/usr/lib/python3.6/site-packages/bcc/__init__.py", line 337, in __init__
self._trace_autoload()
File "/usr/lib/python3.6/site-packages/bcc/__init__.py", line 1030, in _trace_autoload
event=self.fix_syscall_fnname(func_name[8:]),
File "/usr/lib/python3.6/site-packages/bcc/__init__.py", line 569, in fix_syscall_fnname
if name.startswith(prefix):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
[root@aborniakFC tools]#
=> fix python3 issue for ttysnoop.py

man/man8/sslsniff.8, tools/sslsniff.py, tools/sslsniff_example.txt
It allows sslsniff to monitor tools such as curl that uses NSS library for its SSL/TLS operations.
=> sslsniff: add NSS support

src/cc/bcc_elf.c, src/cc/bcc_proc.c, src/cc/common.cc, src/cc/frontends/b/parser.cc, src/cc/libbpf.c, src/cc/usdt/usdt.cc
This fixes a few bug uncovered by a Coverity scan: some leaks and more importantly some memory access errors.
=> Miscellaneous fixes

src/python/bcc/__init__.py, tests/python/test_stackid.py, tests/python/test_tools_memleak.py, tests/python/test_trace4.py, tests/python/test_usdt.py, tests/python/test_usdt2.py, tests/python/test_usdt3.py, tests/python/test_utils.py, tools/memleak.py
This small PR fixes several string concatenation bugs in bcc library, and changes the way some test scripts are invoked. The buildbot invocation on fc28 should exercise this.
=> python3 fixes and testing support

INSTALL.md
Looking at the repo location, Fedora 28 appears to be supported as well.  Fixing the documentation to include this.
=> Adding Fedora 28 to the list of fedora versions

tools/llcstat.py
Hardware events such as CACHE_MISSES and CACHE_REFERENCES are usually
not available on virtual machine. Print a more useful message when
this happen.
=> llcstat: print a nicer error message when hardware events are missing

src/cc/libbpf.c
When loading multiple programs, it's hard to find out which program triggered the error. This commit adds the function name to the error message.
=> Add name to program too large error message

src/python/bcc/__init__.py
fix #1921
For newer kernels, bcc tries to fd based kuprobe
attachment. In fd based kprobe attachment,
config1: for symbol
config2: for symbol offset
In python API attach_kretprobe, the offset value
is not set in lib.bpf_attach_kprobe and hence it
will be a random value and eventually causing
kretprobe attachment failure.
This is not an issue for old debugfs based attachment
as the offset will not be used if it is a retprobe.
=> fix attach_kretprobe for newer kernels

src/cc/bcc_debug.cc
LLVM commit https://reviews.llvm.org/D49741 removed
function DEARFContext::getCompileUnitAtIndex() and caused
the bcc compilation failure.
Change usage of getCompileUnitAtIndex() to the one
recommended in the above llvm commit.
=> fix compilation error with llvm trunk (8.0.0)

src/cc/frontends/clang/b_frontend_action.cc
additional fix for issue #1850
for the below case in test_clang.py;
```
int test(struct pt_regs *ctx, struct mm_struct *mm) {
return mm->rss_stat.count[MM_ANONPAGES].counter;
}
```
the current rewriter generates:
```
int test(struct pt_regs *ctx) {
struct mm_struct *mm = ctx->di;
return ({ typeof(atomic_long_t) _val;
__builtin_memset(&_val, 0, sizeof(_val));
bpf_probe_read(&_val,
sizeof(_val),
(u64)(&mm->rss_stat.count) + (MM_ANONPAGES));
_val; }).counter;
}
```
The third argument of bpf_probe_read() is incorrect.
The correct third argument should be
```
(u64)((&mm->rss_stat.count) + (MM_ANONPAGES))
```
This patch fixed the issue by adding extra parenthesis for the
outer u64 type casting.
```
int test(struct pt_regs *ctx) {
struct mm_struct *mm = ctx->di;
return ({ typeof(atomic_long_t) …
```
=> fix a rewriter bug for array subscript

src/python/bcc/utils.py
This is to support printing output by one of the tools as a json object (not part of this PR). 
Provide an optional parameter, nl=1, that controls the printing of the final new line. To suppress the new line, call as in:
printb(b, nl=0)
calling as in:
printb(b)
will preserve the final new line
=> provide a printb parameter to suppress printing a new line at the end

tools/syscount.py
It's useful to know each syscall's total latency
in that period, but not the latency of the last time
in that period.
Signed-off-by: Ahao Mu <muahao@linux.alibaba.com>
=> [tools/syscount.py]: fix total_ns wrong count

tests/python/test_usdt3.py
The poll iteration count 10 sometimes not big enough.
Now let us increase to 100 iterations, but will bail out
if the expected data have received. Hopefully this
will fix flakiness of this test.
=> fix flaky test_usdt3.py test

src/python/CMakeLists.txt
Generating sdist for both python2 and python3 at the same time can fail
as they both use the same temporary files.
Make sure that we generate sdist for each `PYTHON_CMD` sequentially.
Fixes #1934
=> Serialize python builds

tools/ext4dist.py, tools/xfsslower.py
On RHEL7 we are facing timing issues in some bcc-tools
scripts. The time subsystem might return backward timestamp
via bpf_ktime_get_ns and thus screw up latency computation.
This seems to be RHEL7 kernel issue and needs to be fixed,
however meanwhile it'd be nice if affected scripts display
sane values despite the kernel issue.
This patchset harden 2 scripts (xfsslower and ext4dist)
we saw this behaviour so far, to ensure the latency is
always > 0.
=> tools: Skip backward time entries v2

man/man8/ucalls.8, man/man8/uflow.8, man/man8/ustat.8, snapcraft/snapcraft.yaml, src/cc/bcc_proc.c, tests/python/test_utils.py, tools/lib/ucalls.py, tools/lib/ucalls_example.txt, tools/lib/uflow.py, tools/lib/uflow_example.txt, tools/lib/ustat.py, tools/lib/ustat_example.txt, tools/perlcalls.sh, tools/perlcalls_example.txt, tools/perlflow.sh, tools/perlflow_example.txt, tools/perlstat.sh, tools/perlstat_example.txt
Sort language entries while at it.
=> Add Perl support for ucalls / uflow / ustat

src/cc/api/BPF.cc, src/cc/api/BPF.h
This way, it's easier to move initialized USDT instance around without having to re-read everything.
Piggy-back a small logging fix
=> Add move constructor to C++ USDT instance

tools/trace.py
Currently, trace.py does not support "long" and "unsigned long"
types and it often caught users with a surprise and they are
not sure what is the problem. For example, for kernel function:
```
void blk_mq_delay_kick_requeue_list(struct request_queue *q, unsigned long msecs)
```
The following
```
$ sudo ./trace.py 'blk_mq_delay_kick_requeue_list(void *notused, unsigned long msecs) "msecs = %lu", msecs'
list index out of range
```
With this patch,
```
$ sudo ./trace.py 'blk_mq_delay_kick_requeue_list(void *notused, unsigned long msecs) "msecs = %lu", msecs'
PID     TID     COMM            FUNC             -
^C
$ sudo ./trace.py 'blk_mq_delay_kick_requeue_list(void *notused, unsigned long msecs) "msecs = %ld", msecs'
PID     TID     COMM            FUNC             -
^C
$ sudo ./trace.py …
```
=> support "long" and "unsigned long" type in trace.py

tools/biolatency.py
bpf_probe_read()'s third argument is no longer rewritten. Instead, use a
temporary variable (like #1973) to avoid a memory access error.
Before:
```
$ sudo biolatency -D 1
0: (79) r1 = *(u64 *)(r1 +112)
1: (7b) *(u64 *)(r10 -8) = r1
[..]
R1 invalid mem access 'inv'
HINT: The invalid mem access 'inv' error can happen if you try to
dereference memory without first using bpf_probe_read() to copy it to
the BPF stack. Sometimes the bpf_probe_read is automatic by the bcc
rewriter, other times you'll need to be explicit.
```
After, works as expected.
=> biolatency: Fix --disks bpf_probe_read()

src/cc/api/BPF.cc, src/cc/api/BPF.h, src/cc/api/BPFTable.cc, src/cc/api/BPFTable.h
This PR adds the support for the DEVMAP in the C++ APIs, which was missing in https://github.com/iovisor/bcc/pull/1810
=> [cc] Add support for Devmap

src/cc/frontends/clang/b_frontend_action.cc
The following command failed:
```
trace.py -U 'r::_do_fork (retval == -11) "%llu", ((struct task_struct *)bpf_get_current_task())->signal->rlim[RLIMIT_NPROC].rlim_cur'
```
as rewriter generates code like
```
__data.v0 = (unsigned long long)((struct task_struct *)bpf_get_current_task())->signal->rlim[RLIMIT_NPROC))); _val; }).rlim_cur;
```
Let us prevent rewriting if either base or index is not rewritable and this fixed the issue.
=> prevent array subscript expression if base/index is not rewritable

tools/opensnoop.py
Note this allows us to eliminate the `bpf_ktime_get_ns()`
call from `trace_entry()`.
=> Remove unused ts field in val_t in opensnoop.py.

src/python/CMakeLists.txt, tests/wrapper.sh.in
Fix for https://github.com/iovisor/bcc/issues/1964, more details in commit message.
=> Python build: copy files instead of creating link

src/cc/api/BPF.h, src/cc/bpf_module.cc, src/cc/bpf_module.h, src/cc/export/helpers.h, src/cc/frontends/b/codegen_llvm.cc, src/cc/frontends/b/codegen_llvm.h, src/cc/frontends/b/loader.cc, src/cc/frontends/b/loader.h, src/cc/frontends/clang/b_frontend_action.cc, src/cc/frontends/clang/b_frontend_action.h, src/cc/frontends/clang/loader.cc, src/cc/frontends/clang/loader.h, tests/cc/CMakeLists.txt, tests/cc/test_shared_table.cc
This PR is basically a rebased version of https://github.com/iovisor/bcc/pull/1172.
At that time, there was the idea of creating a new API for handling public tables, but that was a work that we never did. I am opening this PR because this new feature does not conflict nor changes the existing API, so it can be integrated easily without breaking existing applications.
Just to summarize, the idea is to have an additional visibility level for eBPF tables, a step between `public` and `private`, `shared` maps are visible among the eBPF programs that are in the same namespace defined by the user.  
This is useful when implementing very complex modules that don't fit into a single eBPF program like a firewall, maps are shared among the programs of the same firewall instance but maps on …
=> Add support for shared tables

INSTALL.md
Using the short key fingerprint as documented imports two keys:
```text
Executing: /tmp/apt-key-gpghome.hCaMwcAFSC/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys D4284CDD
gpg: key 4052245BD4284CDD: public key "Brenden Blanco <bblanco@plumgrid.com>" imported
gpg: key 27E8E08BD4284CDD: public key "Totally Legit Signing Key <mallory@example.org>" imported
gpg: Total number processed: 2
gpg:               imported: 2
```
Although this particular key [may not be malicious](https://dev.gnupg.org/T4136), it scared the hell out of me. I guess the `bblanco@plumgrid.com` key is the right one?
=> use long key fingerprint to prevent collisions

docs/kernel-versions.md
Add support in the kernel: https://github.com/torvalds/linux/commit/cc8b0b92a1699bc32f7fec71daa2bfc90de43a4d
Add support in libbpf: https://github.com/torvalds/linux/commit/48cca7e44f9f8268fdcd4351e2f19ff2275119d1
This pull request only documents the kernel.
=> Documentation: add function calls in 4.16

src/cc/usdt/usdt.cc
Hi,
Currently Context::enable_probe() discards the result of Probe::enable() even if it fails. This is something that I've already mentioned in #1998 (it didn't show any warning when tried to read semaphore value from unreadable memory location). Today I hit another case when I tried to setup USDT context by passing only path to binary without specifying PID. Here is a tiny patch that fixes this.
=> USDT: take into account the result of Probe::enable()

docs/kernel-versions.md, introspection/bps.c, src/cc/compat/linux/bpf.h, src/cc/compat/linux/virtual_bpf.h, tests/python/test_brb.c
Sync compat bpf.h and virtual_bpf.h with latest net-next versions
=> sync with latest net-next bpf headers

src/cc/frontends/clang/loader.cc
The clang commit
commit 247be3e41c41201641af01888ff0d84484c4e0f4
Author: Simon Pilgrim <llvm-dev@redking.me.uk>
Date:   Fri Oct 12 19:14:43 2018 +0000
Fix a clang::driver::ArgStringList usage I missed in rL344398. NFCI.
removed
using ArgStringList = llvm::opt::ArgStringList;
in clang:include/clang/Driver/Job.h,
and makes bcc compilation failure.
Using llvm::opt::ArgStringList fixed the issue and should
still work with previous llvm versions.
=> fix bcc build failure with latest llvm/clang trunk

src/cc/export/helpers.h, src/cc/frontends/clang/tp_frontend_action.cc
Fix issue #2010.
Alastair reported some missing cases in tp frontend action
where certain types are not adjusted.
For example, for tracepoint `syscalls:sys_enter_kill`,
the kernel format:
```
...
field:int __syscall_nr; offset:8;       size:4; signed:1;
field:pid_t pid;        offset:16;      size:8; signed:0;
field:int sig;  offset:24;      size:8; signed:0;
```
The size for "pid_t pid" is 8 bytes, but the kernel pid_t
is "int", so it is needed to change its type to "s64"
to be consistent to its size.
This patch also added conversion for gid_t and uid_t as Alastair
discovered that they are also used in some tracepoints with size 8.
For type gid_t and uid_t, the corresponding kernel type is "unsigned int",
so it should be converted to "u64".
=> correct certain tracepoint types in tp frontend action

src/cc/frontends/b/type_helper.h
On 32-bit, __uint128_t is generally not available. Removing it fixes
builds on those systems.
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>
=> frontends: disable uint128_t on 32-bit builds

src/cc/json_map_decl_visitor.cc, src/lua/bcc/table.lua, src/python/bcc/__init__.py, tests/python/test_clang.py
Fix issue #2017.
For python programs, the map data passed from C++ library
is parsed through the key/value desc types which are
generated by C++ json map declaration visitor.
The map declaration visitor visits the map key/value
declaration types and generate a string to represent
the type, which is later used by python to reconstruct
the cttype.
The map declaration already tries to add all the padding
to the type string in order to make sure C++ and python
see the same layout.
This patch further added packed support such that if
C++ json map visitor has applied padding, the python
type reconstructor is free to add _pack_=1 for structure
type since the structure is already packed.
For example, for a type,
```
struct t { char a; int b; }
```
the structure after json visitor will look like …
=> allow packed structure in bpf program in python API

src/cc/bcc_elf.c, src/cc/bcc_proc.c, src/cc/frontends/b/type_check.cc, src/cc/frontends/p4/compiler/ebpfTable.py, src/cc/libbpf.c
This fixes a few errors discovered by a coverity scan.
=> covscan: fix miscellaneaous errors

src/cc/bcc_proc.c
PR #2003 broke `/proc/pid/maps` parsing. Particularly I have the following mapping:
```
562bd52ee000-562bd5397000 r--p 00000000 103:03 49684469                  /home/zilder/pg10/bin/postgres
562bd5397000-562bd59cb000 r-xp 000a9000 103:03 49684469                  /home/zilder/pg10/bin/postgres
562bd59cb000-562bd5c58000 r--p 006dd000 103:03 49684469                  /home/zilder/pg10/bin/postgres
...
```
which can't be parsed by suggested format string as both major and minor device numbers can contain up to 3 characters.
=> Fix parsing of /proc/pid/maps

src/lua/bcc/bpf.lua, src/lua/bcc/libbcc.lua, src/python/bcc/libbcc.py
This updates the python and lua bindings for libbcc to be able to support attaching kprobes at custom offsets.
Update 03/11: Change title and description. Remove `uprobe` related changes.
~~This adds support for custom offset `uprobes`. The changes made previously for custom offset `kprobes` were also missing a few bits for the Python and Lua APIs. This also provides fixes for `powerpc64` to ensure `uprobe` events work as expected.~~
=> Update bindings for custom offset kprobes

src/cc/bcc_syms.cc
* Symbol lookup fails when the process is running on a different namespace. 
* ProcSyms already has the capability to switch mount namespaces to resolve symbols. 
* Identified bug where the BPF doesn't migrate to process mount namespace before opening the symbol files and fails to locate the file. 
* Patch makes sure that 'ProcMountNSGuard g(ps->mount_ns_instance_.get())' is created every single time a text section for the process is loaded. 
* Patch was tested by  1) creating docker container and running the process 2) running "bcc/tools/profile" script on the global PID namespace of the process 
Test - Performed a test by running bcc/tools/profile on a PID running in a container and found the resolution to be working fine. 
`#define  _GNU_SOURCE
#include <link.h>
#include <stdio.h> …
=> Fix symbol resolution across mount namespaces (#2029)

tests/lua/test_standalone.sh
This fixes the subtest that checks if `bcc-lua` depends on `libluajit`.
=> Fix the lua standalone test

src/cc/bcc_elf.c, src/cc/bcc_syms.cc, src/cc/bcc_syms.h
This makes sure that the correct entry point addresses are used when attaching `uprobes` to functions on `powerpc64` (both big and little endian).
=> Fix uprobes on powerpc64

INSTALL.md
because it doesn't have llvm 3.7 packages
=> INSTALL.md - on ubuntu bionic use llvm 6.0 

examples/networking/http_filter/http-parse-complete.c, examples/networking/http_filter/http-parse-simple.c
Fix issue #2035.
For code like
```
int i;
int j = 0;
const int last_index = payload_offset + 7;
for (i = payload_offset ; i < last_index ; i++) {
p[j] = load_byte(skb , i);
```
Here, the payload_offset is unknown. llvm 7.0 and trunk
compiler seems generating code like
```
p[0] = load_byte(skb, payload_offset)
if (payload_offset + 1 < last_index) {
p[1] = ...
...
p[6] = ...
} else {
/* do nothing */
}
/* accessing p[0], p[1], ..., p[6] */
```
The compiler did the above transformation because the potential
overflow for `last_index` and/or `payload_offset + 1` in which case
compiler preserved both branches.
This caused a problem for verifier as in the else branch
p[1] is not assigned and the verifier will reject the program.
Changing the loop to simply iterate from 0 to 6 fixed the problem. …
=> fix verifier errors in http_filter example

tools/funcslower.py
This reorders the `struct data_t` members so that the definition is consistent across the c code and the corresponding python `ct.Structure`.
Upon running the script with the arguments option, the user and kernel stack ids read from the stack maps are incorrect as they are read off the wrong structure offsets. When a stack walk is attempted on an incorrect stack id, we end up with a `KeyError`.
This has been verified as shown below.
```sh
$ sudo ./funcslower.py c:inet_pton -u1 -a1 -UK
$ ping -6 ::1
```
Before:
```
Tracing function calls slower than 1 us... Ctrl+C to quit.
COMM           PID    LAT(us)             RVAL FUNC ARGS
ping           33541    47.93                1 c:inet_pton 0xfffffff2000001a0
File "_ctypes/callbacks.c", line 315, in 'calling …
```
=> Fix funcslower stack traces when using arguments

src/cc/CMakeLists.txt, src/cc/common.cc, tests/cc/CMakeLists.txt
Fixed some compiler warnings of unused return value and type comparison with llvm-7.0.0.
It's fixed by adding -Wno-unused-result in corresponding CMakeLists.txt and static cast for type comparison.
```
/home/lecopzer/workspace/bcc/src/cc/libbpf.c:456:3: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
fgets(fmt, sizeof(fmt), f); // pos
^~~~~~~~~~~~~~~~~~~~~~~~~~
...
/home/lecopzer/workspace/bcc/src/cc/common.cc:60:11: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
if (res >= sizeof(exe_path))
~~~~^~~~~~~~~~
...
```
See the comment of the commits in detail.
=> Fix some compiler warning

tools/offwaketime.py
In folded output format when both kernel and user stacks are missing,
the message "[Missing User Stack]" is formatted incorrectly, for example:
chrome;entry_SYSCALL_64_after_hwframe;do_syscall_64;SyS_poll;do_sys_poll;poll_schedule_timeout;schedule_hrtimeout_range;schedule_hrtimeout_range_clock;schedule;--;[Missed Kernel Stack];[;M;i;s;s;e;d; ;U;s;e;r; ;S;t;a;c;k;];fio 4955989
This is because we're incorrectly appending the missing stack message in
the list of stack entries. Fix by appending the message as a single item.
Signed-off-by: Andrea Righi <righi.andrea@gmail.com>
=> offwaketime: properly format "[Missed User Stack]" with folded output

src/cc/compat/linux/bpf.h, src/cc/compat/linux/bpf_common.h, src/cc/compat/linux/virtual_bpf.h
Sync compat/linux/{bpf.h, bpf_common.h, virtual_bpf.h}
with latest bpf-next. The change in bpf_common.h are comments only.
=> sync compat headers with latest bpf-next

src/cc/bpf_module.cc
Otherwise, if llvm is built with assertion on,
we will hit the following error for a simple trace.py script like
```
-bash-4.4$ sudo ./trace.py 'SyS_nanosleep'
python: /home/yhs/work/llvm/lib/ExecutionEngine/MCJIT/MCJIT.cpp:204:
virtual void llvm::MCJIT::generateCodeForModule(llvm::Module*):
Assertion `M->getDataLayout() == getDataLayout() && "DataLayout Mismatch"'
failed.
Aborted (core dumped)
-bash-4.4$
```
=> set proper layout for the module before finalizing the object

snapcraft/Makefile, snapcraft/snapcraft.yaml
Snapcraft has an improved mechanism for wrapping python executables.
Remove all the older snapcraft legacy cruft and update for the new
snapcraft tooling.
=> snapcraft: use new snapcraft rules to clean up wrapping of executables

docs/tutorial_bcc_python_developer.md
There have been some updates the code in the examples.  The tutorial
text should match up with the current example code. In particular we
want to make ensure that the probe for the syscall functions match up
with what is currently needed for newer kernels that do not have
syscall functions uniformly start with "sys_".
=> Update the tutorial to match what is currently in the examples

examples/networking/xdp/xdp_macswap_count.py
Mostly a cut and paste of the xdp_drop_count.py with needed changes for
doing a source and destination MAC swap.
Signed-off-by: Andy Gospodarek <gospo@broadcom.com>
=> Add test script for XDP_TX action

src/cc/frontends/clang/b_frontend_action.cc, src/cc/frontends/clang/b_frontend_action.h
With latest llvm/clang, we have the following compilation errors:
```
/home/yhs/work/bcc2/src/cc/frontends/clang/b_frontend_action.cc:
In member function ‘bool ebpf::BTypeVisitor::VisitVarDecl(clang::VarDecl*)’:
/home/yhs/work/bcc2/src/cc/frontends/clang/b_frontend_action.cc:1130:52:
error: no matching function for call to ‘clang::Expr::EvaluateAsInt(llvm::APSInt&, clang::ASTContext&)’
if (I->getInit(idx)->EvaluateAsInt(res, C)) {
^
/home/yhs/work/bcc2/src/cc/frontends/clang/b_frontend_action.cc:1130:52: note: candidate is:
In file included from /home/yhs/work/llvm/build/install/include/clang/AST/Attr.h:19:0,
from /home/yhs/work/llvm/build/install/include/clang/AST/TypeLoc.h:18,
from /home/yhs/work/llvm/build/install/include/clang/AST/ASTTypeTraits.h:24,
from …
```
=> fix compilation error with latest llvm/clang

examples/networking/xdp/xdp_drop_count.py
This reverts commit 5b76047f528b56072b541c406103f07589d6efe2.
The code is actually not duplicated. It is used to process
double vlan's. See comments in:
https://github.com/iovisor/bcc/pull/1493
=> Revert "Remove duplicate code from xdp_drop_count.py (#2049)"

tools/biolatency.py, tools/biosnoop.py, tools/biotop.py
Recent -next kernels don't have blk_start_request() function
anymore. It has been removed in a recent cleanup. bio* tools should be
able to handle the lack of this probe.
=> tools: prepare block tools for the removing of legacy I/O path

src/python/bcc/syscall.py
When `ausyscall` is used as a fallback plan to generate the syscall map, the `subprocess.check_output()` call fails as the program name and arguments must be passed separately.
Fixes: 218f7482f ("Wcohen/efficiency (#2063)")
=> Fix syscall map generation via ausyscall

CMakeLists.txt, src/CMakeLists.txt
Enables linking bcc-static in binaries compiled with rtti
=> Add option to build with rtti

man/man8/biotop.8
The biotop manpage references a -p option that the tools doesn't have,
and AFAICT, never had. It's only referenced in the manpage option, not
in the synopsis, in "biotop -h" output not biotop_example.txt.
=> manpage: remove non-existent -p option from the biotop manpage

src/python/bcc/__init__.py
Improve get_kprobe_functions() to exclude more non-attachable functions
like IRQ routines and functions in kernel modules blacklisted via
NOKPROBE_SYMBOLS().
Signed-off-by: Andrea Righi <righi.andrea@gmail.com>
=> get_kprobe_functions(): detect more non-attachable functions

src/python/bcc/__init__.py
=> add arm64 kprobe function name prefix in kernel 4.19

man/man8/dbslower.8, tools/dbslower.py, tools/dbslower_example.txt
In python3, the find method requires a bytes-like object. It fixes the
following error:
$ dbslower mysql -x $(which mysqld)
File "/usr/share/bcc/tools/dbslower", line 72, in <module>
if mysql_func_name.find("COM_DATA") >= 0:
Also the -x option is currently undocumented in the man page and the
example file. So let's ix that too.
=> dbslower: fix a python3 bytes/string issue int the -x option

src/python/bcc/__init__.py
Fix https://github.com/iovisor/bcc/issues/2088
=> fix exception message format in detach_kprobe_event()

CMakeLists.txt, cmake/clang_libs.cmake, src/cc/CMakeLists.txt, src/cc/api/BPF.h, src/cc/bpf_module.cc, src/cc/bpf_module.h, src/cc/bpf_module_rw_engine.cc, src/cc/bpf_module_rw_engine_disabled.cc
Adds an option ENABLE_LLVM_NATIVECODEGEN with default value ON.
If set to off the "nativecodegen" llvm will not be enabled, thus
reducing dependencies on needed libraries (reduced text size when
building with statically linked libraries).
Code that uses native target will not be compiled reducing text size.
Currently this affects the rw_engine which needs the native target.
BPF api "rw_engine_enabled" will have default value "true" if
ENABLE_LLVM_NATIVECODEGEN="ON" and "false" if
ENABLE_LLVM_NATIVECODEGEN="OFF"
Not needed for BCC to work. It somehow brought in the interpreter and
executionengine which is needed. Those features are added instead.
=> Make dependency on LLVM native target optional

tools/trace.py
Compiler shows warning "incompatible integer to pointer conversion
initializing" while compiling bpf program.
This patch adds necessary typecast when assigning PT_REGS_PARAM vaules
to struct pt_regs pointer
=> trace.py: fix compiler warning

examples/cpp/RandomRead.cc, src/cc/CMakeLists.txt, src/cc/api/BPF.cc, src/cc/api/BPF.h, src/cc/bcc_elf.c, src/cc/bcc_elf.h, src/python/bcc/__init__.py, src/python/bcc/libbcc.py, tests/python/CMakeLists.txt, tests/python/test_free_bcc_memory.py
The main purpose of this API is to proactively release llvm/clang
.text memory which is brought in during compilation.
bcc .text memory for some other functions, e.g., attach_tracepoint,
bpf_prog_load, etc. can also be freed after all these tasks are done.
Note that such memory is reclaimable in kernel since it has
file backup. But certain applicaiton may want to reduce this
memory immediately to satisfy constraints imposed by sysadmin, etc.
The implementation uses madvise with MADV_DONTNEED.
For the case where bcc is static linked into the binary,
we do not really know the start and the end of memory regions
used by bcc, so the implementation here bluntly returned
all .text memory back to kernel. This will incur some performance
overhead as later on executed instructions will need to …
=> implement free_bcc_memory() API

man/man8/opensnoop.8, tools/opensnoop.py, tools/opensnoop_example.txt
This PR adds printing of the `flags` argument to `open(2)` and allows for filtering, e.g., to only print out files for writing.
```
$ sudo ./opensnoop.py -f O_WRONLY -f O_RDWR
PID    COMM               FD ERR FLAGS    PATH
15286  postgres            3   0 00101101 /var/run/postgresql/9.6-main.pg_stat_tmp/global.tmp
15286  postgres            6   0 00101101 /var/run/postgresql/9.6-main.pg_stat_tmp/db_0.tmp
23562  postgres           11   0 00100001 /proc/self/oom_score_adj
23562  postgres            3   0 00100002 base/16385/2601
...
```
Thanks!
=> opensnoop: print flags, enable filtering

src/cc/libbpf.c
fix issue #226
The unknown opcode typically happens if the bpf
program has an external reference which does not
get resolved. Note bcc does not even preform
relocations for maps as map_id is directly
used in bpf problem through bpf_pseudo_fd()
intrinsic.
Instead of the error:
bpf: Failed to load program: Invalid argument
unknown opcode 00
A little explanation is added like the below:
HINT: The 'unknown opcode' can happen if you referencea global
or static variable, or data in read only section.
For example,'char *p = "hello"' will result in p referencing a
read only section,and 'char p[] = "hello"' will have "hello"
stored on the stack.
=> better error meessage for error "unknown opcode"

tools/lib/ustat.py
In #2102 build there were 4 test failures on Fedora.
3 of them were due to the following traceback:
```
27: Traceback (most recent call last):
27:   File "../../tools/lib/ustat.py", line 294, in <module>
27:     Tool().run()
27:   File "../../tools/lib/ustat.py", line 286, in run
27:     self._loop_iter()
27:   File "../../tools/lib/ustat.py", line 255, in _loop_iter
27:     counts.update(probe.get_counts(self.bpf))
27:   File "../../tools/lib/ustat.py", line 114, in get_counts
27:     result[pid.value][category] = count.value
27: KeyError: 20335L
```
Seems like there is a possible inconsistency between `self.targets` and `bpf[*_counts]`:
https://github.com/iovisor/bcc/blob/dccc4f28b7404b2f77f8ad8c7ad1ea741db589f2/tools/lib/ustat.py#L107-L116
Workaround it by skipping PIDs that are not in …
=> ustat: added basic race condition protection

examples/networking/xdp/xdp_drop_count.py
I also changed it into a short loop, which I don't think improves (or degrades) the code, but at least makes it clear that the double parsing is intentional.
See #1493 and #2049.
=> Comment on duplicate code for parsing double vlans

tools/opensnoop.py, tools/solisten.py, tools/tcpaccept.py, tools/tcpconnect.py
I use next tools in one of my projects:
- opensnoop
- solisten
- tcpaccept
- tcpconnect
But i dont get output without flushing output.
Saw in execsnoop tool that bcc.utils.printb is used for flushing. Replaced standart python print function with this one.
=> Add stdout flushing to some tools

.gitignore, tools/inject.py
Works along with the kernel changes in commit af3b854492f3 ("mm/page_alloc.c: allow error injection").
=>  inject: Add support for alloc_page family of functions 

man/man8/opensnoop.8, tools/opensnoop.py, tools/opensnoop_example.txt
Hi. Nice to meet you!
UID related options supported.
I think that it is use case of a multi-tenant environment.
- The -U option include UID on output:
```sh
UID   PID    COMM               FD ERR PATH
0     27063  vminfo              5   0 /var/run/utmp
103   628    dbus-daemon        -1   2 /usr/local/share/dbus-1/system-services
103   628    dbus-daemon        18   0 /usr/share/dbus-1/system-services
103   628    dbus-daemon        -1   2 /lib/dbus-1/system-services
```
The reason for the print extension by the `-U` option is to maintain backward compatibility.
- The -u option filtering UID:
```sh
UID   PID    COMM               FD ERR PATH
1000  30240  ls                  3   0 /etc/ld.so.cache
1000  30240  ls                  3   0 /lib/x86_64-linux-gnu/libselinux.so.1
1000  30240  ls …
```
=> opensnoop: supported UID options

docs/reference_guide.md
bpf_trace_printk() does not have `fmt_size` as the second parameter in BCC.
=> docs: fix parameters of bpf_trace_printk()

src/cc/frontends/clang/kbuild_helper.cc
When ARCH is not defined, bcc get the architecture from uname. It then
modifies it to get the name of arch directory in linux source.
When ARCH is defined however, it just copy it as is, without the
translation to the arch directory. If for instance ARCH is set to
x86_64, it tries to look into the include directory
build/arch/x86_64/, which doesn't exist.
It fixes the following issue:
$ echo $ARCH
x86_64
$ /usr/share/bcc/tools/bashreadline
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from /lib/modules/4.18.0-49.el8.x86_64/build/include/linux/types.h:6:
/lib/modules/4.18.0-49.el8.x86_64/build/include/uapi/linux/types.h:5:10: fatal error: 'asm/types.h' file
not found
^~~~~~~~~~~~~
Traceback (most recent call …
=> Translate arch into source directory when ARCH is set

src/cc/bcc_elf.c
On fc29, compiling bcc from source, the following
compiler warnings are seen:
```
/home/yhs/work/bcc/src/cc/bcc_elf.c: In function ‘bcc_free_memory_with_file’:
/home/yhs/work/bcc/src/cc/bcc_elf.c:802:36: warning: unused variable ‘_fini’ [-Wunused-variable]
extern unsigned long _start, _fini;
^~~~~
/home/yhs/work/bcc/src/cc/bcc_elf.c:802:28: warning: unused variable ‘_start’ [-Wunused-variable]
extern unsigned long _start, _fini;
^~~~~~
```
These unused externs are accidentally introduced by
Commit 51480d0597cc ("implement free_bcc_memory() API").
This patch removed them.
=> remove unused extern variables

tools/opensnoop.py, tools/tcpaccept.py, tools/tcpconnect.py
The following three tools are recently changed to use
printb in order to flush out the result.
opensnoop.py, tcpaccept.py, tcpconnect.py
With python3, however, these tools have errors like below:
```
TypeError: %b requires a bytes-like object, or an object that implements __bytes__, not 'str'
File "/usr/lib/python3.6/site-packages/bcc/table.py", line 572, in raw_cb_
File "../../tools/opensnoop.py", line 248, in print_event
printb(b'%s' % event.fname.decode('utf-8', 'replace'))
```
This patch fixed printb related issues for these three tools
for python3. The python2 still works with the fix.
=> fix several printb usage with python3

src/cc/export/helpers.h
Fix issue #2119.
Kernel 5.0 added more usages of `asm goto` and llvm
does not support asm goto yet. This resulted in
compilation error for virtually any bcc script.
The workaround here is to redefine asm_volatile_goto to
```
asm volatile("invalid use of asm_volatile_goto")
```
which can pass clang.
If bpf program does not use `asm_volatile_goto`,
nothing bad will happen. The functions using
`asm_volatile_goto` will be thrown away.
If bpf program accidentally uses `asm_volatile_goto`,
a compilation error like below will be printed out:
```
<inline asm>:1:2: error: invalid register/token name
invalid use of asm_volatile_goto
^
LLVM ERROR: Error parsing inline asm
```
=> workaround kernel 5.0 asm_volatile_goto issue

tools/shmsnoop.py, tools/sofdsnoop.py
Handle keyboard interrupt to avoid backtrace printed out when user
presses Ctrl-C. Other tools have been fixed recently. Let's fix these
remaining tools.
=> tools: shmsnoop, sofdsnoop handle keyboard interrupt

src/python/bcc/syscall.py
With out the patch:
File "/root/bcc/src/python/bcc/syscall.py", line 381, in <module>
out = out.split('\n',1)[1]
During handling of the above exception, another exception occurred:
File "/root/bcc/tests/python/test_stat1.py", line 10, in <module>
File "/root/bcc/src/python/bcc/__init__.py", line 30, in <module>
from .syscall import syscall_name
File "/root/bcc/src/python/bcc/syscall.py", line 387, in <module>
raise Exception("ausyscall: command not found")
Exception: ausyscall: command not found
This is because variable 'out' is a byte object type and while split,
code is passing 'str' type.
Tested this on python3 and python2
Signed-off-by: …
=> syscall.py: Fixes python3 related error

tools/biotop.py, tools/cachetop.py, tools/criticalstat.py, tools/fileslower.py, tools/filetop.py, tools/lib/uflow_example.txt, tools/llcstat.py, tools/runqslower.py
Mostly things caught by PEP Linter. Some of them are stylistic (like "don't catch bare exception"), but others are syntactically valid:
- `signal` defined both as module name and function argument
- Function default argument has function call
- Undefined local variable `pid` should be `args.pid`
- `uflow_example.txt` has non-ASCII character
=> Misc fixes on Python tools

tools/trace.py
On x64 from kernel v4.17 onwards, an indirect table is used to
rewrite syscall parameters in trace.py. However, it only works
for arg1. For arg[2-6], the results are wrong. This patch fixes
that.
Fixes: 2da34267fcae ("generate indirect parameter assignment if arch uses syscall wrapper (#1816)")
Signed-off-by: Xiaozhou Liu <liuxiaozhou@bytedance.com>
=> trace.py: fix syscall parameter rewriting on x64

src/cc/libbpf.c, src/cc/perf_reader.c
In Android, certain flags are passed to build source code. These cause errors when building libbpf. These patches fix the issues.
=> Bcc build fixes for Android

src/cc/bpf_module.cc, src/cc/bpf_module.h
Some users uses `BPFModule` directly instead of C++ / Python API, and they would like to have similar interface of free BCC `.text` memory
=> Add free_bcc_memory to BPFModule

src/cc/bcc_elf.c
This fixes the format string used to parse the major and minor device fields in `/proc/self/maps`. These fields have hexadecimal values and hence cannot be parsed as unsigned integers.
Fixes: 51480d05 ("implement free_bcc_memory() API (#2097)")
=> Fix process map parsing when freeing bcc memory

tools/profile.py
fixes flame graph color hues, which recognize the _[k] tag. eg:
```
./profile.py -af > out.stacks
./flamegraph.pl --color=java < out.stacks > out.svg
```
=> profile.py: return kernel annotations for folded stacks

man/man8/trace.8, src/cc/api/BPF.cc, tools/trace.py, tools/trace_example.txt
Support symbol resolution for short-lived processes (#2014)
New command line options have been added to tools/trace.py to support the new BUILD_ID stackmap. List of symbol files can be added to the script to resolve symbols from build id as reported by the kernel in the stack trace. A comma separated list of symbol files can be passed to the script as shown below. 
Eg invocation to trace inet_pton(as mentioned in #2014)
python tools/trace.py -s /lib/x86_64-linux-gnu/libc.so.6,/bin/ping  'p:c:inet_pton' -U
=> support symbol resolution of short-lived process. 

README.md, man/man8/deadlock_detector.8, snapcraft/snapcraft.yaml, tests/python/test_tools_smoke.py, tools/deadlock.c, tools/deadlock.py, tools/deadlock_example.txt
This renames the `deadlock_detector.py` tool to `deadlock.py` to make
the name more diagram-friendly and to be consistent with the naming of the
other tools.
=> tools: rename "deadlock_detector" to "deadlock" (#2152)

tools/cpuunclaimed.py
Similar to runqlen.py, make proper adjustment for
cfs_rq_partial structure so it can align with
what the kernel expects.
=> fix cpuunclaimed.py with cfs_rq structure change

tools/syscount.py
In #2063, syscount's syscall mapping was moved into its own module.
Unfortunately, that broke the "print list of recognized syscalls and
exit" usage of syscount. Fix it by importing the syscall mapping from
the new module.
=> Fix tools/syscount -l

src/cc/libbpf.c
the libbpf is just sync'ed with latest bpf-next.
=> sync with latest libbpf repo

src/cc/libbpf.c, src/cc/libbpf.h
Two commits in the patch set. One added bcc_create_map_xattr() and the other added bcc_prog_load_xattr(). These two functions will be useful for creating map or loading program with extra parameters which are not available in bcc_create_map()/bcc_prog_load(), e.g., btf related parameters.
=> add bcc_create_map_xattr() and bcc_prog_load_xattr()

src/cc/CMakeLists.txt, src/cc/api/BPF.cc, src/cc/bcc_btf.cc, src/cc/bcc_btf.h, src/cc/bpf_common.cc, src/cc/bpf_common.h, src/cc/bpf_module.cc, src/cc/bpf_module.h, src/cc/frontends/clang/b_frontend_action.cc, src/cc/frontends/clang/loader.cc, src/cc/libbpf.c, src/python/bcc/__init__.py, src/python/bcc/libbcc.py
The libbpf API functions are used to parse/load
.BTF and .BTF.ext ELF sections, and retrieve
func_info and line_info for prog loading.
The LLVM cannot get remapped file source for
line_info. So a postprocessing after compilation
fixed the line_off (offset to the string table
for the line_info) in .BTF.ext and
adjusted string section in .BTF to accommodate
new source lines.
For users using python and C++ API, no changes
to their codes. If .BTF and .BTF.ext are supported
in both compiler and kernel, they will automatically
get benefit, e.g., verifier log annotated with source
code, bpftool showing source annotated jit codes, etc.
For example, with latest bpf-next and llvm trunk,
running `tcpconnect.py`, bpftool (from kernel) is able
to show the following:
```
-bash-4.4$ sudo bpftool p d …
```
=> add btf func_info and line_info support

src/cc/bcc_btf.cc, src/cc/bcc_btf.h, src/cc/bpf_module.cc, src/cc/bpf_module.h, src/cc/export/helpers.h, src/cc/file_desc.h, src/cc/frontends/clang/b_frontend_action.cc, src/cc/frontends/clang/b_frontend_action.h, src/cc/frontends/clang/loader.cc, src/cc/frontends/clang/loader.h, src/cc/libbpf.c, src/cc/table_desc.h, src/cc/table_storage.h
Added bpf support for maps so map key/value types can be
retrieved by user space introspection tool to pretty
print map key/values.
To associate maps with its key/value types, the below macro
```
BPF_ANNOTATE_KV_PAIR(name, type_key, type_val)
```
is used, similar to usage in kernel tools/testing/selftests/bpf
and tools/lib/bpf. Currently, some map types (e.g, `PERF_EVENT_ARRAY`)
do not support pretty print. But common [per_cpu] hash/array maps
are supported.
Currently, bcc create maps before llvm compilation.
To support pretty printing of maps, map creation
needs have key/value type id's which can only be
obtained after compilation. Therefore, during rewriting,
fake map fd is used. After compilation, btf is first
loaded and maps are created.
With latest bpf-next and latest trunk llvm, …
=> add btf support for maps

src/cc/CMakeLists.txt
Commit 51480d0597cc ("implement free_bcc_memory() API")
exposed bcc_elf.h as a uapi header. The original
implementation does not provide a BPFModule level
api so this header can be used to call free_bcc_memory()
for applications using BPFModule level API.
Later Commit 4c5509fc1664 ("Add free_bcc_memory to BPFModule")
added such an interface in BPFModule, so exposing this
header becomes unnecessary.
So removing bcc_elf.h from uapi headers.
=> do not expose bcc_elf.h as uapi header

examples/cpp/RandomRead.cc, src/cc/api/BPF.h, src/cc/bpf_common.cc, src/cc/bpf_common.h, src/cc/bpf_module.cc, src/cc/bpf_module.h, src/cc/libbpf.c, src/cc/libbpf.h, src/lua/bcc/bpf.lua, src/lua/bcc/libbcc.lua, src/python/bcc/__init__.py, src/python/bcc/libbcc.py, tests/cc/test_static.c, tests/python/CMakeLists.txt, tests/python/test_rlimit.py
Currently, if map_create and prog_load failed in bcc, bcc
will tries to raise MEMLOCK resource limit to INFINITY
and try again.
The map and program memory is charged against
user->locked_vm which is accumulated per user
and the MEMLOCK rlimit is set per task. This makes
hard to get a proper estimate what value to set, hence
INFINITY is the most popular value.
In production systems, there is a reason why INFINITY
may not be the best option.
- Uncontrolled prog/map memories could eat much more memory before it is noticied.
- If there is a bug in user space or kernel leaking prog/map's (not released), they will not get noticed since other bpf program/map will continue to load successfully with INFINITY MEMLOCK rlimit.
This patch provides a mechanism for python and C++ APIs to
disable bcc …
=> allow application to set rlimit for RLIMIT_MEMLOCK instead of bcc

src/cc/bpf_module.cc
When running example UseExternalMap or test test_libbcc,
the following warning showed up:
```
-bash-4.4$ sudo ./UseExternalMap
libbpf: map:control btf_key_type_size:4 != map_def_key_size:0
.....
-bash-4.4$ sudo ./test_libbcc
libbpf: map:mysharedtable btf_key_type_size:4 != map_def_key_size:0
.....
```
This is related to external maps. When the application
defines an external maps, the extra .maps.<map_name> section
gets generated. But the map is not in fake_fd_map_
as the external map does not require an explicit bpf_create_map
syscall. It merely duplicates fd from an existing map.
The warning showed up because the external map was not
in fake_fd_map_ and expected_ksize and expected_vsize are based
on fake_fd_map_ hence is 0, which does not match the real map.
There is really no reason to …
=> ignore external maps during retrieving type id's

src/cc/bcc_btf.cc
Currently, in case of error, btf__new or btf_ext__new does not
return NULL pointer. Instead, the return value looks like
ERR_PTR(-errno), and the caller needs to check the range of
return value to decide whether it is a valid pointer.
Let us define similar macros and handle return values
properly. We can restore the change if later kernel libbpf
changes the return value such that NULL pointer stands for failure.
=> handle return value properly for btf__new and btf_ext__new

src/cc/usdt/usdt.cc
This adds a couple of lexical scopes for usage with `ProcMountNSGuard` so the hint'ing works for the C interface when using `bcc_usdt_new_frompid()`. Also, add a guard for the `Context::Context(pid, path)` constructor for resolving the probes.
From the commit message:
Since the probe may be in a descendent namespace, ensure that when `stat()`ing for HINTs and resolving linked elf locations, be sure to always perform them relative to any observed mount namespace.
However, usage of the mount namespace must be surgical, since we're observing the pid with its outter identity, make sure we're not in the mount namespace when attempting to `readlink` the `/proc/<pid>/exe`
=> usdt: use ProcMountNSGuard for pid and path attach

src/cc/bpf_common.cc, src/cc/bpf_common.h, src/cc/bpf_module.cc, src/cc/bpf_module.h, src/cc/frontends/clang/b_frontend_action.cc, src/cc/frontends/clang/b_frontend_action.h, src/cc/frontends/clang/loader.cc, src/cc/frontends/clang/loader.h, src/python/bcc/__init__.py, src/python/bcc/libbcc.py, src/python/bcc/table.py, tools/tcpconnect.py
When ring buffers are opened to receive custom perf event, we have
to define the event data structure twice: once in BPF C and once
in Python. It is redundant and error-prone.
This patch implements the automatic generation of Python data structure
from the C declaration, thus making the redundant definition in Python
unnecessary. Example:
// define output data structure in C
struct data_t {
u32 pid;
u64 ts;
char comm[TASK_COMM_LEN];
};
BPF_PERF_OUTPUT(events);
...
Old way:
TASK_COMM_LEN = 16    # linux/sched.h
class Data(ct.Structure):
_fields_ = [("pid", ct.c_ulonglong),
("ts", ct.c_ulonglong),
("comm", ct.c_char * TASK_COMM_LEN)]
def print_event(cpu, data, size):
event = ct.cast(data, ct.POINTER(Data)).contents
...
New way:
def print_event(cpu, data, size):
event = …
=> generate perf event data structure in Python automatically

src/python/bcc/table.py, tools/dcsnoop.py
Add enum type support so that scripts like tools/dcsnoop.py could be
simplied.
=> add `enum` support for generating perf event data struct

src/cc/bcc_btf.cc, src/cc/bcc_btf.h, src/cc/bpf_module.cc, src/cc/bpf_module.h, src/python/bcc/__init__.py
silence BTF related warning messages by default.
The DEBUG_BTF is added to enable such warning messages.
=> implement DEBUG_BTF flag

tools/execsnoop.py, tools/offcputime.py, tools/offwaketime.py
It fixes the following errors:
$ execsnoop.py -q
PCOMM            PID    PPID   RET ARGS
File "/usr/lib/python3.6/site-packages/bcc/table.py", line 572, in raw_cb_
File "tools/execsnoop.py", line 229, in print_event
for arg in argv[event.pid]
File "tools/execsnoop.py", line 229, in <listcomp>
for arg in argv[event.pid]
$ offcputime.py -K -f 5
File "./tools/offcputime.py", line 298, in <module>
print("%s %d" % (";".join(line), v.value))
TypeError: sequence item 1: expected str instance, bytes found
$ offwaketime.py -f 5
File …
=> tools: fix some python3 bytes vs strings issues

INSTALL.md, debian/control
See  #2085 and #2116 for previous work:
While the Debian/Ubuntu packages have different package names, aside from `bpfcc-tools`/`bcc-tools`, the contents of the packages conflict and cannot be simultaneously installed or mixed with upstream packages.
Further, should one install a package declaring a dependency on `bpfcc-tools`, `libbpfcc`, etc, while the upstream packages are installed, given there's no relationship between the packages, `apt` will gladly pull down and try to install the Debian/Ubuntu packages and explode in a half-configured mess :)
This PR adds a Provides relationship between the iovisor and corresponding Debian/Ubuntu packages so the iovisor packages can satisfy dependencies (PCP is a good example, although they've since adjusted their dependencies to allow …
=> Declare provides+conflicts on Debian/Ubuntu packages

tests/python/test_usdt3.py
test_usdt3.py has been flaky for a while.
When the test failed, it looks like it did not catch
a single event.
The patch enabled debug output to print out all
the trace points before attachments so we will have
more context in case of failure. Also this debug
output seems significantly reduced flakiness
and in my fc28 I cannot reproduce the test failure
with it.
=> enable debug output for test_usdt3.py

src/cc/CMakeLists.txt, src/cc/bcc_common.cc, src/cc/bcc_common.h, src/python/bcc/libbcc.py, tests/cc/test_static.c
This avoids potential conflict with Kernel UAPI's `bpf_common.h` in certain build environment, especially considering `libbpf` now includes and installs that UAPI header file.
=> Rename bpf_common.h to bcc_common.h

docs/reference_guide.md
=> docs/reference_guide: add auto-generation of perf event data structure in Python

src/python/bcc/syscall.py
ausyscall is not available on ARM64 systems I am testing. The system is
running debian buster. All BCC tools fail as a result. Let us not fail
if ausyscall is missing.
Signed-off-by: Joel Fernandes <joelaf@google.com>
=> Fix BCC on arm64 by allowing missing ausyscall

man/man8/bashreadline.8, tools/bashreadline.py, tools/bashreadline_example.txt
The fix for **Arch Linux** came from #1851.
Have tested that the script can run on `Ubuntu 18.04.2` without any modification.
Haven't tested for other distributions.
=> fix #1851 for Arch Linux users

src/python/bcc/__init__.py, src/python/bcc/syscall.py, tools/lib/ucalls.py
Commit 218f7482f8ae refactored syscall number=>name
mapping into a separate file src/python/bcc/syscall.py.
The commit added a reference in python __init__.py,
and this will cause virtually all non x64 arch python
tools failure.
Commit bc0d472ec9d7 attempted to fix the issue by
removing the failure in syscall.py but this is not
the correct fix for arm64 as the syscall numbers
won't match.
Removing the syscall.py reference in __init__.py
should be enough to restore the previous
working behavior.
Fixes: bc0d472ec9d7 ("Fix BCC on arm64 by allowing missing ausyscall")
Fixes: 218f7482f8ae ("Wcohen/efficiency (#2063)")
=> fix a bug related to syscall.py

docs/reference_guide.md, src/cc/api/BPF.cc, src/cc/api/BPF.h, src/cc/libbpf.c, src/cc/libbpf.h, src/lua/bcc/bpf.lua, src/lua/bcc/libbcc.lua, src/python/bcc/__init__.py, src/python/bcc/libbcc.py, tests/python/CMakeLists.txt, tests/python/test_trace_maxactive.py
When a kretprobe is installed on a kernel function, there is a limit on how many parallel calls it can catch. You can change that limit with the `maxactive` parameter. Since [commit `696ced4` ("tracing/kprobes: expose maxactive for kretprobe in kprobe_events")](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=696ced4fb1d76802f864d8848aa4716633f83c17) in the Linux kernel, debugfs exposes that parameter.
This pull request exposes that parameter in bcc as well, through `bpf_attach_kprobe` in libbcc and `BPF.attach_kretprobe` at the Python level. If a `maxactive` value is given, we fallback to using debugfs to install the kprobe event, instead of the usual `perf_event_open`.
For kernels without `maxactive` supports in debugfs, the error resolution is not …
=> Expose kprobe's maxactive parameter in bcc

docs/tutorial_bcc_python_developer.md, examples/tracing/hello_perf_output.py
=> tutorial_bcc_python_developer: new way to get the event data

src/python/bcc/__init__.py
GCC 8 can split functions bodies into hot and cold regions, causing
extra symbols with a ".cold.N" suffix to be emitted. Exclude these
extra symbols and only allow the parent function to be traced.
Signed-off-by: Andrea Righi <righi.andrea@gmail.com>
=> support gcc 8's cold subfunctions

tools/tcpaccept.py
pr #1842 forgot to add filtering in the new tracepoint code so it's
incorrectly showing every sock:inet_sock_set_state event.
This patch fixes that.
=> tcpaccept: only show TCP accept event

tools/fileslower.py
fileslower was failing on newest version of bcc/tools unsure as to why right now however filetop has explicit declaration of DNAME_INLINE_LEN , adding resolves immediate issue.
=> added DNAME_INLINE_LEN to be 32 as per filetop

docs/reference_guide.md
540adea3809f "error-injection: Separate error-injection from kprobe",
merged in v4.16, changed the name of BPF_ALLOW_ERROR_INJECTION
to just ALLOW_ERROR_INJECTION.
Update the name to help readers grepping the kernel code.
=> docs/reference_guide: Update kernel macro name

src/python/bcc/__init__.py
Fix issue #2240.
In 5.0, the following commit
```
commit a38d1107f937ca95dcf820161ef44ea683d6a0b1
Author: Matt Mullins <mmullins@fb.com>
Date:   Wed Dec 12 16:42:37 2018 -0800
bpf: support raw tracepoints in modules
```
renamed the function bpf_find_raw_tracepoint() to
bpf_get_raw_tracepoint(). The bcc relies on checking
bpf_find_raw_tracepoint() in /proc/kallsyms to detect
whether raw_tracepoint is supported in kernel or not.
We do not have better mechanism to detect raw_tracepoint
support without additional syscalls. So tentatively,
let us just check bpf_get_raw_tracepoint() ksym as well
for raw_tracepoint support.
=> fix b.support_raw_tracepoint for 5.0 kernel

src/cc/bcc_debug.cc, src/cc/bcc_debug.h, src/cc/bpf_module.cc, src/cc/bpf_module.h
The following llvm change in trunk (9.0)
https://reviews.llvm.org/D58194
breaks bcc build.
```
[ 76%] Building CXX object src/cc/CMakeFiles/bcc-static.dir/bpf_module.cc.o
/home/yhs/work/bcc/src/cc/bcc_debug.cc: In member function ‘void ebpf::SourceDebugger::dump()’:
/home/yhs/work/bcc/src/cc/bcc_debug.cc:207:23: error: no matching function for call to ‘llvm::DWARFDebugLine::LineTable::getFileLineInfoForAddress(uint64_t, const char*, llvm::DILineInfoSpecifier::FileLineInfoKind, llvm::DILineInfo&) const’
LineInfo);
^
/home/yhs/work/bcc/src/cc/bcc_debug.cc:207:23: note: candidate is:
In file included from /home/yhs/work/llvm/build/install/include/llvm/DebugInfo/DWARF/DWARFContext.h:24:0,
from /home/yhs/work/bcc/src/cc/bcc_debug.cc:22: …
```
=> fix a compilation issue with latest llvm trunk (9.0)

examples/cpp/CMakeLists.txt, examples/cpp/pyperf/CMakeLists.txt, examples/cpp/pyperf/Py36Offsets.cc, examples/cpp/pyperf/PyPerf.cc, examples/cpp/pyperf/PyPerfBPFProgram.cc, examples/cpp/pyperf/PyPerfLoggingHelper.cc, examples/cpp/pyperf/PyPerfLoggingHelper.h, examples/cpp/pyperf/PyPerfType.h, examples/cpp/pyperf/PyPerfUtil.cc, examples/cpp/pyperf/PyPerfUtil.h
This is a tool attaches BPF program to CPU Perf Events for profiling. The BPF program understands CPython internal data structure and hence able to walk actual Python stack-trace, as oppose to strac-trace of the CPython runtime itself as we would normally get with Linux `perf`.
To use the tool, just run the `PyPerf` binary:
- Use `-d` / `--duration` to specify intended profiling duration, in milliseconds. Default value, if not specified, is `1000ms`.
- Use `-c` / `--sample-rate` to specify intended profiling sample rate, same as `-c` argument of Linux `perf`. Default value, if not specified, is `1e6`.
You can also use `-v` / `--verbose` to specify logging verbosity `1` or `2` for more detailed information during profiling.
The tool is a prototype at this point is by no mean mature. It …
=> Add PyPerf, example of profiling Python using BPF

examples/tracing/disksnoop.py, examples/tracing/hello_fields.py, examples/tracing/hello_perf_output.py, examples/tracing/mallocstacks.py, examples/tracing/mysqld_query.py, examples/tracing/nodejs_http_server.py, examples/tracing/strlen_count.py, examples/tracing/sync_timing.py, examples/tracing/tcpv4connect.py, examples/tracing/trace_fields.py, examples/tracing/trace_perf_output.py, examples/tracing/urandomread-explicit.py, examples/tracing/urandomread.py
Switch to printb to get rid of the prefix 'b' of the byte arrays.
Also handle the KeyboardInterrupt exception for some scripts to avoid the code tracing when stopping the program.
=> Fix the output of example scripts with python3 and handle KeyboardInterrupt

src/cc/libbpf.c
=> Fix error message printing in create_kprobe_event

man/man8/tcpaccept.8, tools/tcpaccept.py, tools/tcpaccept_example.txt
- add option `-T': include time column on output (HH:MM:SS)
- add option `-P PORT': only trace port specified
- add RPORT colume on output
=> enhance tcpaccept

examples/cpp/pyperf/CMakeLists.txt, examples/cpp/pyperf/PyPerf.cc, examples/cpp/pyperf/PyPerfDefaultPrinter.cc, examples/cpp/pyperf/PyPerfDefaultPrinter.h, examples/cpp/pyperf/PyPerfLoggingHelper.h, examples/cpp/pyperf/PyPerfSampleProcessor.h, examples/cpp/pyperf/PyPerfType.h, examples/cpp/pyperf/PyPerfUtil.cc, examples/cpp/pyperf/PyPerfUtil.h
This PR mainly contains two pars:
- Add a common interface `PyPerfSampleProcessor` that can be passed to `PyPerfUtil` to handle samples from the profiling. This way, users could use customized logic to log / aggregate / output the result samples.
- Abstract current printing logic to a specific `PyPerfDefaultPrinter` that is used by the default CLI main, and add parsing for enum values.
=> Improve PyPerf sample handling and output

tools/filetop.py
While testing, it is noticed that sometimes filetop can miss
certain heavy-weight activity. This is because it sorts by only a single
column. So for example, if writes are flooding, then it will be way down
in the filetop list and not displayed at all for the default maxrows of
20 and default sort of rbytes. It is better instead to sort by all
columns, by default. This will help catch them.
Test:
Start a bash and do: while true; do echo "asdfasdf" >> testfile; done
Run filetop. Without patch no activity is displayed due to other small
reads on the system. With the path they are.
Fixes issue: https://github.com/iovisor/bcc/issues/2252
Signed-off-by: Joel Fernandes (Google) <joel@joelfernandes.org>
=> filetop: Avoid missing important entries

src/cc/usdt.h, src/cc/usdt/usdt.cc, src/cc/usdt/usdt_args.cc, tests/cc/test_usdt_args.cc
Approach and code shamelessly borrowed from "422db709: Add basic USDT
support for powerpc64".
=> Add basic USDT support for s390x

docs/reference_guide.md
Since KeyboardInterrupt is not handled anymore, update the example code
and the link to the example scripts to reflect the change.
Also fix the link to 'trace_fields' example scripts.
=> docs/reference_guide: update the examples to reflect the recent change

src/cc/bpf_module.h
struct bpf_insn is used (as a pointee) in bpf_module.h,
but no definition or forward declaration can be found
by just looking at this file.
definition is not needed as it is used as a pointee.
providing a forward declaration here.
=> add forward declaration of bpf_insn in bpf_module.h

src/cc/bcc_btf.cc, src/cc/bcc_btf.h
For remapped files (the main bpf program file and helpers.h),
the llvm compiler does not have the source so bcc did the
adjustment/patching after the compilation for lines in .btf.ext
line_info.
If a particular line in the main file or helpers.h is referenced
in the line_info table, the line itself will be added to
string table. If too many lines are added into the string table,
the string table may become too big (>= 64KB), and libbpf/kernel
will reject it.
In my instance with a Facebook internal bpf program, after all
referenced lines are added, the string table is 67KB.
This patch added checking during string table adjustment
to avoid overflow against the kernel limit.
=> avoid overflowing btf stringtable during btf line adjustment

snapcraft/bcc-wrapper, snapcraft/snapcraft.yaml
Make changes to accommodate the move to core18 snaps. Rename
the wrapper script to bcc-wrapper so it is less generic. Fix
up the wrappering of bcc tools. Remove libc cruft from snap
and explicitly state the staging packages required.
This builds cleanly from a Ubuntu 18.04 bionic environment.
=> snapcraft: updates to snapcraft 2.37 and core18 snaps

src/python/bcc/table.py
When using killsnoop with Python 3, I get the following errors:
```pybt
TIME      PID    COMM             SIG  TPID   RESULT
File "_ctypes/callbacks.c", line 232, in 'calling callback function'                                                                 
File "/usr/lib/python3.7/site-packages/bcc/table.py", line 676, in raw_cb_                                                           
File "/usr/share/bcc/tools/killsnoop", line 124, in print_event                                                                      
event = b["events"].event(data)                                                                                                    
File "/usr/lib/python3.7/site-packages/bcc/table.py", line 654, in event …
```
=> fix string re being used on bytes for Python 3

src/cc/bcc_btf.cc
In bcc_btf.cc, new_btf_sec is allocated with something like
```
new_btf_sec = new uint8_t[tmp_sec_size]
```
Since the allocation is an array, the deletion should be
```
delete[] new_btf_sec
```
instead of
```
delete new_btf_sec
```
This patch fixed the problem.
=> delete allocated array properly

INSTALL.md
This PR updates INSTALL.md per the discussion in #1153. One of the flags mentioned no longer exists in the kernel, and was replaced with a different flag.
=> Clarify kernel configuration flags

tools/cachestat.py
TypeError: argument should be integer or bytes-like object, not 'str'
Signed-off-by: Adrian Ratiu <adrian.ratiu@collabora.com>
=> tools/cachestat: fix python 3 str/bytes type error

src/cc/frontends/clang/kbuild_helper.cc
Commit 28949f17e0 ("Translate arch into source directory when ARCH is set")
moved $ARCH processing earlier in the function so $ARCH gets processed
by the the same logic which parses the uname_machine value.
This introduced two bugs breaking ARCH=arm64 cross-compilation:
1. The arch.compare(0, 3, "arm") test matches both $ARCH=arm and $ARCH=arm64
leading to builds which always include from "arch/arm/include" instead
of "arch/arm64/include".
2. The only way arch == arm64 is if $ARCH=aarch64. uname returns aarch64
but the rest of the compiler logic expects $ARCH=arm64.
This fixes the above bugs by moving the "aarch64" test earlier than
the "arm" test and also accepting ARCH=arm64.
Fixes: 28949f17e0 ("Translate arch into source directory when ARCH is set (#2122)")
Signed-off-by: Adrian Ratiu …
=> clang/kbuild_helper: fix arm64 cross compilation

src/cc/CMakeLists.txt
This is based on discussion in netdev regarding to libbpf repo
packaging:
https://lore.kernel.org/bpf/20190325202009.GA14511@krava/T/#t
The libbpf repo https://github.com/libbpf/libbpf contains
the linux:tools/lib/bpf codes plus some other uapi and auxiliary
headers. It is natural for libbpf repo to generate a
libbpf.{a,so} installable as a package.
To avoid conflicts, let us rename bcc libbpf.{a,so}
to libbcc_bpf.{a,so}.
=> rename libbpf.{a,so} to libbcc_bpf.{a,so}

docs/reference_guide.md
There are no examples of how to use perf_submit in skb programs. This commit explains that a skb can be used as a ctx.
Signed-off-by: Oriol Arcas <oriol@starflownetworks.com>
=> doc: explain how to use perf with skb programs

src/cc/CMakeLists.txt
It's useful to have all the bcc symbols in one place when statically
linking against bcc. This patch adds all the symbols from
libbcc-loader-static into libbcc. This is in line with how
libbcc-lua-static does it as well.
=> Add libbcc-loader-static.a symbols into libbcc.a

src/cc/CMakeLists.txt
Ref: https://github.com/iovisor/bpftrace/pull/410
=> cmake: expose bcc_elf.h in the API headers

tools/tcpaccept.py
Fixes #2304.
On Linux 4.16 and later, sock:inet_sock_set_state tracepoint was
used for efficency, but it may output wrong PIDs. This is because
sock:inet_sock_set_state may run outside of process context.
Hence, we stick to kprobes until we find a proper solution.
=> tcpaccept: remove sock:inet_sock_set_state tracepoint code

man/man8/stackcount.8, tools/stackcount.py, tools/stackcount_example.txt
Add the -c option to trace events happened only the requested CPU.
Update command line, man and example.
Signed-off-by: Dima Stepanov <dimastep@yandex-team.ru>
Signed-off-by: Yury Kotov <yury-kotov@yandex-team.ru>
=> stackcount: add -c option for CPU only events

man/man8/offcputime.8
In commit 66bf2e8e (offcputime: one symbol cache per process, improve
pid/tid handling, 2016-07-31) the '-f' option was documented again
probably with the intent of following the order of options in the
synopsis, but it was already documented.
Remove the fist instance and keep the new one to follow the same order
of the synopsis, but use the original description.
=> man: remove duplicated description of '-f' option from offcputime.8

man/man8/stackcount.8, tools/stackcount.py, tools/stackcount_example.txt
=> stackcount: do per-pid statistics only if -P is provided

man/man8/profile.8, tools/profile.py, tools/profile_example.txt
tools/profile already supports "-p PID" to filter on PID (tgid in kernel).
Now add "-L TID" to profile thread with this TID only (pid in kernel).
=> tools/profile: add -L option to support filtering on TID

src/cc/bcc_proc.c
This allows for elf notes to be read from a memfd_backed "file".
If the inode number of a file descriptor matches exactly the inode number in the memory map, we know that it is a memory backed file descriptor (this can also be verified against `name` in this context, using `strstr(name, '/memfd')`, but this is less performant than comparing the inode number).
For such file descriptors, we can return a path that is relative to the pid and use that, as `/memfd:NAME` is not a file that can be checked later on. In such cases, we will return a path like `/proc/PID/fd/FDNUM`, where FDNUM corresponds to the file descriptor with that matches the inode number.
The practical application for this is that probes that are dynamically created via a library such as libstapsdt can be scoped to the …
=> Support loading elf notes from memfd backed map

tools/memleak.py
Fix printing of stacktraces. Example:
Before this patch:
Attaching to kernel allocators, Ctrl+C to quit.
[14:11:43] Top 10 stacks with outstanding allocations:
8 bytes in 1 allocations from stack
b'pcpu_alloc+0x3d8 [kernel]\n\t\tpcpu_alloc+0x3d8 [kernel]\n\t\tperf_trace_event_init+0xc9 [kernel]\n\t\tperf_trace_init+0x69 [kernel]\n\t\tperf_tp_event_init+0x1b [kernel]\n\t\tperf_try_init_event+0x42 [kernel]\n\t\tperf_event_alloc+0x620 [kernel]\n\t\t__do_sys_perf_event_open+0x188 [kernel]\n\t\tdo_syscall_64+0x48 [kernel]\n\t\tentry_SYSCALL_64_after_hwframe+0x44 [kernel]'
16 bytes in 1 allocations from stack
b'pcpu_alloc+0x3d8 [kernel]\n\t\tpcpu_alloc+0x3d8 [kernel]\n\t\tbpf_prog_alloc+0x33 [kernel]\n\t\tbpf_prog_load+0xf5 [kernel]\n\t\tperf_event_for_each_child+0x34 …
=> tools: fix stacktraces formatting in memleak.py

src/python/bcc/__init__.py
When executing funccount with python3, the following error showed.
File "funccount.py", line 299, in <module>
Tool().run()
File "funccount.py", line 261, in run
self.probe.load()
File "funccount.py", line 191, in load
bpf_text += self._generate_functions(trace_count_text)
File "funccount.py", line 143, in _generate_functions
tracepoints = BPF.get_tracepoints(self.pattern)
File "/usr/lib/python3.7/site-packages/bcc/__init__.py", line 772, in get_tracepoints
if re.match(tp_re, tp):
File "/usr/lib64/python3.7/re.py", line 173, in match
return _compile(pattern, flags).match(string)
TypeError: cannot use a bytes pattern on a string-like object
This commit convert 'tp_re' from bytes to string to avoid the crash.
=> Convert bytes to string for re in get_tracepoints()

src/cc/bcc_proc.c
As @palmtenor points out, https://github.com/iovisor/bcc/pull/2314#discussion_r276495408, the original PR misses freeing the memory that it allocates for a string on the error path (where the directory listing fails) resulting in a potential memory leak.
I had considered just using a separate buffer for the directory string, but decided to malloc it so I could reuse the buffer for building the full path while still retaining access to the string. If there's a reason to prefer that approach I can modify this PR according, which would eliminate the need to bother with freeing this string buffer as it would be stack-allocated instead.
=> Fix possible memory leak in error path when elf notes are backed by a memfd path

tools/execsnoop.py, tools/opensnoop.py, tools/tcpaccept.py, tools/tcpconnect.py
While mixing print(end="") with printb(), some messages may miss due to
the underlying buffer handling in python 3.
For example:
PID    COMM               FD ERR PATH
/proc/18849/cmdline
4109   tmux: server       67   0 /proc/18849/cmdline
4109   tmux: server       67   0 /proc/18849/cmdline
4109   tmux: server       67   0 /proc/18849/cmdline
The PID, COMM, FD, and ERR are printed with print(end=""), and those of
the first instance was eaten by printb() which outputs PATH.
The following scripts mix print(end="") and printb() for the same line:
tools/execsnoop.py
tools/opensnoop.py
tools/tcpaccept.py
tools/tcpconnect.py
Those scripts work fine with python 2 but some messages may miss while
using python 3.
This commit converts print(end="") to printb(nl="") to avoid the
inconsistent …
=> tools: don't mix print(end="") with printb()

src/cc/bcc_usdt.h, src/cc/usdt.h, src/cc/usdt/usdt.cc
fixes #2275
I aimed for the most minimal changeset I could in order to avoid provider collisions.
I have successfully used this code in https://github.com/iovisor/bpftrace/pull/508 to be able to probe a function that would otherwise have a collision with another provider:
As you can see, `testprobe2` is defined on both the `tracetest` and `tracetest2` providers:
```
bpftrace -l 'usdt:./tracetest'
usdt:./tracetest:tracetest:testprobe
usdt:./tracetest:tracetest:testprobe2
usdt:./tracetest:tracetest2:testprobe2
```
Using the old API (`bcc_usdt_enable_probe`):
```
bpftrace -e 'usdt::tracetest2:testprobe2 { @[probe]++ }' -p ${PID}
Attaching 1 probe...
Found duplicate provider (tracetest2) for underspecified probe (testprobe2)
Found 2 duplicate providers for underpecified probe …
```
=> Add bcc_usdt_enable_fully_specified_probe to avoid usdt provider collisions

src/cc/frontends/clang/kbuild_helper.cc, src/cc/frontends/clang/kbuild_helper.h, src/cc/frontends/clang/loader.cc
BCC right now relies on the filesystem to have kernel headers however
this is quite a hindrance to embedded and Android systems, and even
distros that may not have the kernel headers for the running kernel.
This patch makes use of the new /proc/kheaders.tar.xz archive that is
proposed upstream: https://lore.kernel.org/patchwork/patch/1059427/
The approach involves creating a temporary directory containing the
headers and compiling from there. It is used as a last resort if headers
could not be found by other means.
Testing shows this adds around 400ms to start up time of BCC, however
the cost is 0 if the headers already exists in /lib. For
Android/embedded systems, the cost of 400ms is acceptable considering
otherwise the tools just remain broken. A clang virtual filesystem
approach was …
=> loader: Add support for reading kernel headers from /proc

tools/dbslower.py
there is no member called delta on struct data_t, which can cause print errors when using dbslower.py
=> type error on tools/dbslower.py

src/cc/libbpf.c, src/cc/perf_reader.c
Per discussion in #2338, this fixes a build error on Alpine Linux (musl).
Upstream libbpf PR: https://github.com/libbpf/libbpf/pull/41
=> Support build on Alpine Linux

man/man8/vfscount.8, tools/dbslower.py, tools/vfscount.py, tools/vfscount_example.txt
Just like vfsstat.py. I think the args time is good for us to analysis.If we need to know the number of vfs call during a period of time, the previous implement can't tell the details.
=> vfscount.py: add args time

src/cc/bcc_debug.cc
Add corresponding ifdef macro to get ride of the follow warning.
/home/lecopzer/workspace/mybcc/src/cc/bcc_debug.cc: In member function ‘void ebpf::SourceDebugger::dump()’:
/home/lecopzer/workspace/mybcc/src/cc/bcc_debug.cc:186:16: warning: unused variable ‘SectionID’ [-Wunused-variable]
unsigned SectionID = get<2>(section.second);
^~~~~~~~~
=> Fix compile warning

snapcraft/bcc-wrapper, snapcraft/snapcraft.yaml
The python wrapper hack was not working for non-python scripts.
Fix this by patching the python executable path in the python scripts
once the source is fetched.
=> snapcraft: remove python path wrapper hack

src/cc/compat/linux/virtual_bpf.h, src/cc/export/footer.h, src/cc/export/helpers.h
I encountered the following error in a script attempting to trace zfs.
In file included from /virtual/main.c:6:
In file included from /export/home/delphix/zfs/include/sys/zio.h:35:
In file included from /export/home/delphix/zfs/include/sys/zfs_context.h:38:
In file included from /export/home/delphix/zfs/include/spl/sys/condvar.h:33:
/export/home/delphix/zfs/include/spl/sys/time.h:41:9: warning: 'SEC' macro
redefined [-Wmacro-redefined] #define SEC 1
^
/virtual/include/bcc/helpers.h:54:9: note: previous definition is here
^
I added the BPF prefix bcc to avoid similar naming conflicts,
=> 2357 SEC macro redefined error

tools/memleak.py
This pull request changes `memleak.py` to use `BPF_HASH` instead of `BPF_TABLE`. It's probably better for tools to use the appropriate bcc macros in case we ever want to change their definitions (e.g., new `map.helper` function specific to that map type).
=> memleak: use BPF_HASH macro

src/cc/libbpf.c
I try to reduce the same code inside `bpf_attach_[k,u]probe` by adding a new `bpf_attach_probe()` interface without changing their behaviors.
I've tested it by `test_libbpf` and run some `tool/` using [k,u]probe.
Please tell me if any regression happens.
Also I revise some comment using "new" word.
=> Merge implementation of bpf_attach_[k,u]probe

man/man8/capable.8, tools/capable.py, tools/capable_example.txt
The audit filter value has been changed from simply checking
for 0 to checking the LSB against 0.
Since Linux 5.1 kernels got a second bit defined (in
https://github.com/torvalds/linux/blob/v5.1/include/linux/security.h#L65)
the simple check filtered this as well.
This new bit is shown in an own column and can be filtered out by a flag.
=> cap_capable: Display options correctly, add filter for INSETID

src/cc/bcc_btf.cc, src/cc/bcc_btf.h, src/cc/bpf_module.cc
Two commits here:
1. Set DataSec Size properly as LLVM sets to 0 due to lack of information.
2. For section name like `maps/...`, remove `maps/` prefix as the kernel
does not expect '/'. This is can removed later if the kernel starts to support
'/'.
=> Support BTF DataSec Properly

src/cc/frontends/clang/tp_frontend_action.cc, src/cc/frontends/clang/tp_frontend_action.h
Compiling bcc with latest clang built from trunk, I got
the following warning:
In file included from /home/yhs/work/bcc/src/cc/frontends/clang/tp_frontend_action.cc:32:
/home/yhs/work/bcc/src/cc/frontends/clang/tp_frontend_action.h:53:22: warning: private field 'C' is not used
[-Wunused-private-field]
clang::ASTContext &C;
^
This patch removed this unused field.
=> remove unused field in tp_frontend_action.h

docs/tutorial_bcc_python_developer.md, examples/tracing/disksnoop.py
disksnoop does not execute properly on kernels 5.0+ because `blk_start_request` no longer exists in `block/blk-core.c`. I added the check found in the biolatency tool that checks the existence of the kprobe before it attaches.
For the other commit, the text read "user-defined static tracing" which does not match the acronym USDT, so I changed it to the standard "user statically-defined tracing".
=> Fix small things from the python developer tutorial

docs/tutorial_bcc_python_developer.md, examples/tracing/task_switch.c, examples/tracing/task_switch.py
PR addressing Issue #2380 
Lesson 16 spent a lot of text discussing `BPF_TABLE`, but the code doesn't use `BPF_TABLE` at all. Rather, it uses `BPF_HASH`, which users should already be quite familiar with by the end of the tutorial. As a result, I cut out the text explaining `BPF_TABLE`.
I also separated the BPF C code into a separate file, since the tutorial was already written as though that was the case (it discusses `task_switch.c` but that file did not exist).
=> Revise python tutorial lesson 16 to make sure tutorial text and code match

man/man8/capable.8, tools/capable.py, tools/capable_example.txt
The TID and the INSETID bit are the less interesting
fields and keeping them out allows to reduce the line
length below 80 characters.
Closes https://github.com/iovisor/bcc/issues/2392
I have updated the example description since I anyway found out that one had the TID column and the other not.
=> capable: Hide TID and INSETID columns by default

src/cc/frontends/clang/kbuild_helper.h, src/cc/frontends/clang/loader.cc
In upstream kernel, the path has been renamed as the kheaders got moved
to sysfs. Let us update BCC with the new path.
Signed-off-by: Joel Fernandes (Google) <joel@joelfernandes.org>
=> build: Rename kheaders location from proc to sys

man/man8/execsnoop.8, tools/execsnoop.py, tools/execsnoop_example.txt
Add a -T option to include a time column on output (HH:MM:SS) and update manpage
and example file accordingly.
=> tools/execsnoop: add -T option

src/cc/frontends/clang/kbuild_helper.cc, src/cc/libbpf.c
These commits fix two compiler warnings about silent string truncations when building up pathnames using snprintf.
In the case of `bpf_attach_probe` I chose the minimal fix. However, I'm somewhat confused why `fname` and `buf` have different sizes in the first place. `create_probe_event` assumes that it generates paths of up to _PATH_MAX_ characters, but then `bpf_attach_probe` assumes that the result (including the "/id" suffix) fits into 256 characters. Maybe it might make sense to either shrink `buf`, enlarge `fname` to _PATH_MAX_ or allocate `fname` with malloc based on the runtime length of the `buf` path.
=> Fix compiler warnings

src/cc/syms.h
This is pretty standard practice these days as it ensures you don't
accidentally create a new method that doesn't override the base class
method. It also helps document the fact you're overriding methods.
=> Tag overridden functions with override

docs/reference_guide.md, src/cc/api/BPFTable.h, src/cc/bpf_module.cc, src/cc/export/helpers.h, src/cc/frontends/clang/b_frontend_action.cc, src/cc/frontends/clang/b_frontend_action.h, src/cc/table_storage.h, tests/cc/CMakeLists.txt, tests/cc/test_pinned_table.cc
Define a map to be loaded from a pinned path through
the new macro `BPF_TABLE_PINNED(..., "/sys/fs/bpf/xyz");`
instead of creating a new map.
Internally the path is appended to the section attribute
with a delimiter. The approach of adding a new pinned_path
pointer field to the table struct seemed promising but
caused more troubles than the percieved cleanless may be worth.
=> Support pinned maps through BPF_TABLE_PINNED macro

src/cc/syms.h
Fix the following compiler warning:
In file included from /home/yhs/work/bcc/src/cc/bcc_syms.cc:34:
/home/yhs/work/bcc/src/cc/syms.h:68:16: warning: 'refresh' overrides a member function but is not marked 'override'
[-Winconsistent-missing-override]
virtual void refresh();
^
/home/yhs/work/bcc/src/cc/syms.h:45:16: note: overridden virtual function is here
virtual void refresh() = 0;
^
/home/yhs/work/bcc/src/cc/syms.h:145:16: warning: 'refresh' overrides a member function but is not marked 'override'
[-Winconsistent-missing-override]
virtual void refresh();
^
/home/yhs/work/bcc/src/cc/syms.h:45:16: note: overridden virtual function is here
virtual void refresh() = 0;
=> fix a compiler warning

man/man8/trace.8, tools/trace.py
Currently, the trace tool only supports accurate timestamps from trace start (through the monotonic clock within BPF directly), and local time HH:ss (through calls to Python's datetime when printing the record). I had a need to get accurate real-time timestamps which this PR implements.
I realize that this can only ever be approximate since you need to relate monotonic time to real time somehow, and I do that by querying the real time at trace start directly after the same is done for getting the monotonic time at trace start. The hope is that the error is small enough. An improvement would be to query both times within C/C++ to avoid any Python overhead between both calls, but that could be done in the future if there is need as that needs more effort.
Sample when using …
=> Add option to print unix timestamp in trace tool

src/cc/libbpf.h
Function bpf_obj_get_info_by_fd() is used in
src/cc/frontends/clang/b_frontend_action.cc
to support pinned maps.
The file src/cc/frontends/clang/b_frontend_action.cc
includes src/cc/libbpf.h which does not have
a prototype for the function. This may cause
issues in certain build system. Let us put
the prototype in src/cc/libbpf.h as the bcc C
visible API functions are all defined in this file.
=> declare bpf_obj_get_info_by_fd() in src/cc/libbpf.h

man/man8/btrfsslower.8, tools/btrfsslower.py, tools/btrfsslower_example.txt
If a user is granted sudo access only to btrfsslower.py and not kill or timeout, then user is unable to easily limit the runtime of btrfsslower.py. The optional cli argument stops execution of program after specified number of seconds passes.
=> Add cli argument to limit run time

tools/runqslower.py
The state member of task_struct is volatile and it's use as the last
parameter of bpf_probe_read (const void *) triggers the following
clang warning (LLVM 8):
/virtual/main.c:56:42: warning: passing 'volatile long *' to parameter of type 'const void *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
bpf_probe_read(&state, sizeof(long), &prev->state);
^~~~~~~~~~~~
1 warning generated.
Tracing run queue latency higher than 10000 us
TIME     COMM             PID           LAT(us)
An explicit cast fixes the warning.
=> tools: fix runqslower warning

examples/cpp/pyperf/PyPerfUtil.cc, src/cc/api/BPFTable.cc, src/cc/bcc_elf.c, src/cc/bcc_elf.h, src/cc/bcc_syms.cc, src/cc/bcc_syms.h, src/cc/syms.h, src/cc/usdt/usdt_args.cc, src/lua/bcc/libbcc.lua, tests/cc/test_c_api.cc
This patch adds a new API to bcc_elf.h, bcc_elf_foreach_sym_lazy. This
helper avoids storing symbol names in string format, as for large
binaries this data can get quite large.
Instead we store the location in the ELF binary where we can later find
the string. Later on, we can load these strings on demand and cache them
in case they're accessed again.
This patch also makes lazy resolution the default for regular ELF
binaries, where regular means not perfmap or VDSO.
This closes #2421 .
=> Lazily symbolize regular ELF binaries

src/cc/bcc_syms.h, src/cc/libbpf.c, src/cc/usdt/usdt.cc
The following compilation warnings are fix:
...
/home/yhs/work/bcc/src/cc/libbpf.c:548:12: warning: comparison of distinct pointer types ('typeof (name_len - name_offset) *' (aka 'unsigned long *')
and 'typeof (16U - 1) *' (aka 'unsigned int *')) [-Wcompare-distinct-pointer-types]
min(name_len - name_offset, BPF_OBJ_NAME_LEN - 1));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/yhs/work/bcc/src/cc/libbpf/include/linux/kernel.h:28:17: note: expanded from macro 'min'
(void) (&_min1 == &_min2);
...
/home/yhs/work/bcc/src/cc/bcc_syms.h:71:34: warning: declaration of 'struct mod_info' will not be visible outside of this function [-Wvisibility]
int _bcc_syms_find_module(struct mod_info *info, int enter_ns, void *p);
...
/home/yhs/work/bcc/src/cc/usdt/usdt.cc:486:14: warning: unused …
=> fix various compilation warnings

src/cc/export/helpers.h
In src/cc/export/helpers.h, we tried to
define asm_volatile_goto to something else
if it is defined through uapi bpf.h.
#ifdef asm_volatile_goto
#undef asm_volatile_goto
#define asm_volatile_goto(x...) asm volatile("invalid use of asm_volatile_goto")
#endif
It is possible that due to different kernel configurations,
asm_volatile_goto may not be defined after uapi bpf.h.
To prevent compilation errors, let us unconditionally
define asm_volatile_goto here.
=> fix asm_volatile_goto issue again

src/lua/bpf/bpf.lua
At various points in the compiler code, an attempt to load the BPF
program is made. In order to do this, a bpf() syscall needs to happen
with BPF_PROG_LOAD as the first argument (Consult the bpf man page,
under the 'eBPF programs' section). The module ljsyscall does
this via the bpf_prog_load function.
At the time of writing, this function is declared in the file:
syscall/linux/syscalls.lua
In the repo:
https://github.com/justincormack/ljsyscall.git
=> Use bpf_prog_load function from ljsyscall module in LuaJIT compiler

src/cc/bcc_proc.c, src/cc/bcc_proc.h, src/cc/bcc_syms.cc, src/cc/syms.h, tests/cc/test_c_api.cc
Raghavendra Rao reported that memleak does not display
proper name of the related kernel module, but just the
"kernel" string, like here for xfs module functions:
131072 bytes in 4 allocations from stack
..
bvec_alloc+0x92 [kernel]
bio_alloc_bioset+0x13f [kernel]
xfs_add_to_ioend+0x2df [kernel]
xfs_do_writepage+0x148 [kernel]
write_cache_pages+0x171 [kernel]
xfs_vm_writepages+0x59 [kernel]
do_writepages+0x43 [kernel]
...
The kernel resolver code is parsing /proc/kallsyms, which
already has the module information in.
This patch is adding support to parse the module info
from /proc/kallsyms and initialize the module with
proper value.
Above memleak backtrace now looks like:
131072 bytes in 4 allocations from stack
bvec_alloc+0x92 [kernel]
bio_alloc_bioset+0x13f [kernel] …
=> Report proper module on kernel backtrace

tools/solisten.py
Since its conversion to printb, solisten has suffers from yet another python2/3 bytes/str issue:
File "/usr/lib/python3.6/site-packages/bcc/table.py", line 581, in raw_cb_
File "/usr/share/bcc/tools/solisten", line 176, in print_event
event.lport, address,
TypeError: %b requires a bytes-like object, or an object that implements __bytes__, not 'str'
This patch fix the issue on python3. The tools still works on python2.
=> tools: fix printb usage in solisten

examples/cpp/pyperf/PyPerfUtil.cc, src/cc/api/BPFTable.cc, src/cc/bcc_syms.cc, src/cc/usdt/usdt_args.cc
This turns on lazy symbolization by default. Symbol names will be
resolved the first time they're requested and then cached for future
access. This can reduce bcc memory usage by quite a bit in certain
workloads.
=> Turn on lazy symbolize by default

man/man8/tcpconnect.8, tools/tcpconnect.py, tools/tcpconnect_example.txt
Add -c to count all active connections per dest ip/port so we can
easily spot the heavy outbound connection attempts.
Tracing connect ... Hit Ctrl-C to end
^C
LADDR                 RADDR:RPORT             CONNECTS
192.168.10.50    <-> 172.217.21.194:443         70
192.168.10.50    <-> 172.213.11.195:443         34
192.168.10.50    <-> 172.212.22.194:443         21
[...]
=> tools/tcpconnect: add option -c to count connects

man/man8/vfscount.8, tools/vfscount.py
Since commit a2e71a9eb71a ("vfscount.py: add args time (#2344)"),
vfscount does not show any output when it is interrupted by a key
press, which is the only way out when no time limit is specified. I
assume the exit() that has been added in the keyboard interrupt
handler is there so that no output is displayed when the program has
been interrupted early when a time limit has been specified. But since
the tool still invite the user to use Ctrl-C to end the tracing in
that case, it seems more consistent to show an output in that case
too.
This patch removes the exit() and the tools always show a result at
the end. It also adds the duration argument to the synopsis and the
option section in the man page.
=> tools: fix vfscount output when no duration is specified

tools/offwaketime.py
`offwaketime` reports target and waker PIDs inversely. This patch fixes this issue.
This issue is reported in #2487
=> offwaketime: Fix incorrect target and waker PIDs

src/cc/usdt/usdt.cc
If I have a tracepoint that I know is in my binary and not in some shared lib, I might do:
```cpp
std::vector<USDT> USDTs;
USDTs.emplace_back(
"/proc/42/exe",
42,
"my_provider",
"my_sdt_name",
"on_usdt_event");
```
Unfortunately this has been broken since my big change / refactor in #2324 . Why? Because that change attempts to prefix `/proc/PID/root` to everything, and if the process is in a container w/ a different pid namespace than root, `/proc/42/root/proc/42/exe` is unlikely to mean anything and almost certainly won't mean the same thing as `/proc/42/exe`.
Let's not prefix `/proc/PID/root` to procfs paths. Then the above case will be unbroken.
=> Don't prepend /proc/PID/root to user-supplied USDT binary paths starting with /proc already

examples/networking/xdp/xdp_drop_count.py, src/cc/bcc_common.cc, src/cc/bcc_common.h, src/cc/bpf_module.cc, src/cc/bpf_module.h, src/python/bcc/__init__.py, src/python/bcc/libbcc.py, tests/cc/test_static.c
This pull request implements hardware offload support in bcc.
To offload maps and programs to the device, `map_ifindex` (for `bpf$BPF_MAP_CREATE`) and `prog_ifindex` (`bpf$BPF_PROG_LOAD`) need to be set to the index of the network interface at creation time. This support requires a number of changes, some **breaking to the bcc APIs**.
Changes to the Python methods `load_func` and `BPF` are backward-compatible. Changes to `bpf_module_create_b`, `bpf_module_create_c`, `bpf_module_create_c_from_string`, and `bcc_func_load`, and `BPFModule::BPFModule` are not. I'm not sure which of these we want to avoid or there's a better way; I'm opening this pull request to start the discussion.
I've also updated the `xdp_drop_count.py` example to support hardware offload with the new `-H device` option.
=> Support for hardware offload

tools/stackcount.py
fix for one of the problems mentioned in https://github.com/iovisor/bcc/issues/2512
=> stackcount: fix TypeError

FAQ.txt
Just a quick fix for a thing I noticed while reading the FAQ and trying things out...
The package is called bcc, and not bpf:
```
```
If that is not available then the error message thrown by the Python interpreter reads
```
ModuleNotFoundError: No module named 'bcc'
```
and not `No module named 'bpf'`, as currently indicated by the FAQ.
=> FAQ: fix error message

INSTALL.md
Wow! Fedora 30 has bcc binaries in its standard repo. Having this documented in INSTALL.md would have saved me some hassle, so here I am adding it for others... :-)
=> INSTALL.md: add install instructions for Fedora 30+

docs/reference_guide.md
Fixed the BPF_PERCPU_ARRAY description in reference_guide.md to include information about maximum element size. This is in regards to #2519 .
=> Fix BPF_PERCPU_ARRAY description

src/cc/frontends/clang/loader.cc
Upstream change https://reviews.llvm.org/D66797 (in llvm 10)
changed signature of CreateFromArgs(). Compiled with latest upstream,
we will have compilation error like:
```
/home/yhs/work/bcc/src/cc/frontends/clang/loader.cc:343:57:
error: ‘cargs’ was not declared in this scope; did you mean ‘ccargs’?
343 |   if (!CompilerInvocation::CreateFromArgs( invocation0, cargs.  diags))
|                                                         ^~~~~
|                                                         ccargs
```
Adjust bcc codes to use the new func signature.
=> fix compilation errors with clang CreateFromArgs() change

src/python/bcc/__init__.py
Fix issue #989
When module is cleaned up, let us also close all bpf program
file descriptors to avoid fd leaking.
=> Fix a file descriptor leak when module is deleted

FAQ.txt
The problem described in https://github.com/iovisor/bcc/issues/2525, where `bfp()` system calls failed with EPERM, was solved by lifting the kernel lockdown. Thanks to @deg00 for telling us. This adds a corresponding FAQ entry.
=> FAQ: Add Q&A about kernel lockdown

examples/cpp/CGroupTest.cc, examples/cpp/CMakeLists.txt
How to run this test:
0. Make sure you have cgroup2 mounted:
$ mount -t cgroup2
cgroup on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime)
1. Create a test cgroup in cgroup2 fs:
$ sudo mkdir /sys/fs/cgroup/unified/test
2. Run this program in a bash:
$ sudo CGroupTest /sys/fs/cgroup/unified/test
3. In another bash window, do the following:
$ echo $$ > /sys/fs/cgroup/unified/test/cgroup.procs
$ run some other commands
4. You should be able to see lots of prints like:
'file ... was opened!'
=> Add sampe code for cgoup test

INSTALL.md
Commit message:
```
Add a note about the kernel lockdown challenge
to the "Fedora 30 and newer" section.
Motivation: Fedora 30 users are likely to follow
the instructions in the "Fedora 30 and newer"
section of INSTALL.md. They will run into the
kernel lockdown challenge.
```
=> INSTALL.md: Fedora 30: note about kernel lockdown

debian/changelog
the main changes from v0.10.0 to v0.11.0 tag:
* Support for kernel up to 5.3
* Corresponding libbpf submodule release is v0.0.5
* Fix USDT issue with multi-threaded applications
* Fixed the early return behavior of lookup_or_init
* Support for nic hardware offload
* Fixed and Enabled Travis CI
* A lot of tools change with added new options, etc.
=> debian changelog for v0.11.0 tag

src/cc/export/helpers.h
Here's the upstream commit that introduced `asm_inline`:
* https://github.com/torvalds/linux/commit/eb111869301e15b737315a46c913ae82bd19eb9d
Without this patch BCC fails with the following:
```
$ sudo /usr/share/bcc/tools/opensnoop
In file included from /virtual/main.c:2:
In file included from include/uapi/linux/ptrace.h:142:
In file included from ./arch/x86/include/asm/ptrace.h:5:
./arch/x86/include/asm/segment.h:254:2: error: expected '(' after 'asm'
alternative_io ("lsl %[seg],%[p]",
^
./arch/x86/include/asm/alternative.h:240:2: note: expanded from macro 'alternative_io'
asm_inline volatile (ALTERNATIVE(oldinstr, newinstr, feature)   \
^
include/linux/compiler_types.h:210:24: note: expanded from macro 'asm_inline'
^
```
=> Redefine asm_inline for Linux 5.4+, Fixes #2546

tools/gethostlatency.py, tools/gethostlatency_example.txt
Was taking a look around earlier and noticed there was a copied comment from tcpaccept.py in gethostlatency.py. Figured would PR a fixed comment.
=> Fix Erroneous "gethostlatency" Comments

INSTALL.md
Fix issue #2261.
In INSTALL.md document that source code with libbpf submodule
will be released as well for each bcc release in the future.
=> document the release info related to libbpf submodule

man/man8/trace.8, tools/trace.py, tools/trace_example.txt
This patch added cgroup based filtering in trace.py.
If a cgroup path is specified by the user, one cgroup
array map will be added to the program:
```
BPF_CGROUP_ARRAY(__cgroup, 1);
```
Each probe will have a filter like below:
```
if (__cgroup.check_current_task(0) <= 0) { return 0; }
```
to filter out any events not happening in the cgroup
hierarchy as specified by the user.
The trace.py updated the `__cgroup` map with user provided
cgroup path information before attaching bpf functions
to events for probe function(s).
An example like below:
```
$ trace.py -v -c /sys/fs/cgroup/system.slice/workload.service \
'__x64_sys_nanosleep' '__x64_sys_clone'
PID     TID     COMM            FUNC
3191578 3191583 BaseAgentEvents __x64_sys_nanosleep
3191578 3191579 FutureTimekeepr __x64_sys_clone …
```
=> support cgroup level tracing in trace.py

man/man8/shmsnoop.8
```
juergen@lemmy:~ → shmtool open --size 10
```
Snoop:
```
[bcc]# shmsnoop.py  
PID    COMM                SYS              RET ARGs
37903  shmtool          SHMGET               38 key: 0x0, size: 10, shmflg: 0x780 (IPC_CREAT|IPC_EXCL|0600)
37903  shmtool          SHMCTL                0 shmid: 0x38, cmd: 2, buf: 0x7ffea25edd50
```
=> man: COMM describes the process name, not the parent process name

src/cc/bcc_debug.cc
llvm commit https://reviews.llvm.org/D66795
changed the signature of function `createMCAsmInfo()`.
```
-  MCAsmInfo *createMCAsmInfo(const MCRegisterInfo &MRI,
-                             StringRef TheTriple) const {
+  MCAsmInfo *createMCAsmInfo(const MCRegisterInfo &MRI, StringRef TheTriple,
+                             const MCTargetOptions &Options) const {
```
Did similar adjustment in bcc to ensure compilation success.
=> fix compilation errors with latest llvm trunk

src/cc/frontends/clang/b_frontend_action.cc
Commit 82f4302a651a ("introduce map.lookup_or_try_init()")
introduced new API map.lookup_or_try_init(). A compile time
warning is introduced if old map.lookup_or_init() is used
to discourage the usage.
The API is still supported and documentation already
recommends using the new one. So let us drop the
warning.
=> remove the warning for map.lookup_or_init()

tools/cpudist.py
This change fixes the cpudist tool to avoid issue when too many tasks
are running.
Fixes #2567 -- cpudist stop working when there are too many fork
=> cpudist: create sufficiently large hash table to avoid missing tasks

docs/reference_guide.md, src/cc/api/BPF.cc, src/cc/api/BPF.h, src/lua/bcc/bpf.lua, src/lua/bcc/sym.lua, src/python/bcc/__init__.py
This enables to attach uprobe to offset (similar to iovisor/bpftrace#803.)
`attach_kprobe()` already supported it with`event_off`.
This does not check an offset, e.g., whether the offset is the middle of the instruction or not. Currently `attach_kprobe()` also does not perform any check.
It is nice if we can integrate bpftrace's offset check (what above PR does) with bcc, but I think it will be separate PR.
=> Support attaching uprobe to offset

docs/reference_guide.md
See my trouble in [#2590](https://github.com/iovisor/bcc/issues/2590).
I think some explanations should be added to the function `get_syscall_fnname` in reference_guide.
=> Add a supplementary explanation to function `get_syscall_fnname`

docs/reference_guide.md, src/cc/api/BPF.cc, src/cc/api/BPF.h, tests/cc/test_usdt_probes.cc
Looking for early feedback here before I write tests / flesh this out more.
Consider this scenario: I'm hoping to attach USDTs to many short-lived processes, let's say 30. I want to gather data from USDT handlers on these processes for 5 seconds. It's guaranteed that at least one of the processes that was alive when I constructed the vector of USDTs to pass into `BPF::init` will not be alive by the time the 5 seconds are up. I'm OK with this and would still like to gather as much data as possible.
If the process dies after `USDT::init()` is successful but before `attach_usdt` is called, we're already OK because we can handle each `StatusTuple` independently outside of `bcc`. Similarly, if process dies between `attach_usdt` and `detach_usdt` calls, we're fine for same reason.
But if it …
=> Add allow_partial_usdt_init param so partial init of USDT vector is possible

docs/reference_guide.md
virtual_bpf.h instead of bpf.h
src/cc/compat/linux/bpf.h -> src/cc/compat/linux/virtual_bpf.h
There is no bpf.h under compat/linux/
=> docs/reference_guide.md: update doc

docs/kernel-versions.md
There are a few more drivers supporting XDP now.
=> docs: update XDP driver list

tools/mountsnoop.py
in 4.17+ kernels, syscall parameters are wrapped in the first
parammeter in pt_regs. So put the 5th parameter in the
syscall__ parameter list so it can be handled properly
by the rewriter.
=> fix a bug in mountsnoop.py with 4.17+ kernels

src/cc/bcc_elf.h
Closes #2601.
I confirmed that now CMake's [check_symbol_exists](https://github.com/iovisor/bpftrace/blob/fc2af891503061708e455f8de0d89c96554abd4d/CMakeLists.txt#L72) worked correctly when compiling bpftrace.
=> Include stddef.h for size_t in bcc_elf.h

README.md, man/man8/lockstat.8, snapcraft/snapcraft.yaml, tests/python/test_tools_smoke.py, tools/lockstat.py, tools/lockstat_example.txt, tools/offwaketime.py
Adding lockstat tool to trace kernel mutex lock events and
display locks statistics and displays following data:
```
Caller    Average Spin           Count        Max spin      Total spin
pipe_wait+0xa9             708        13062320           86318      9254917935
pipe_write+0x35             465        13062622           86105      6081839337
pipe_read+0x3f             408        13062615           83390      5335451713
unix_dgram_recvmsg+0xd0            2613              52           20699          135900
rtnetlink_rcv_msg+0x264            2083              68           18544          141688
psi_avgs_work+0x2e            2536             437           16887         1108366
Caller    Average Hold           Count        Max hold      Total hold
_vm_unmap_aliases+0xdb           98228 …
```
=> Add lockstat tool

src/cc/bcc_exception.h
The `TRY2` macro is very useful for wrapping methods that return a StatusTuple, and is defined in the same header as StatusTuple (and is therefore visible when including `BPH.h`). However, the macro is written in such a way that it only works from within the `ebpf` namespace, which limits its usefulness in other projects. This makes it so I can use the `TRY2` macro in my own project.
=> Make TRY2 macro work outside of ebpf namespace

src/cc/bcc_exception.h
I ran into this while trying to write a method that takes a const StatusTuple reference, these methods should be marked const. I also fixed an unnecessary string copy in msg.
=> Make StatusTuple code and msg methods const

INSTALL.md
clang/llvm has moved from old svn with git mirror to
github based source control. The new github address is
https://github.com/llvm/llvm-project
which includes clang, llvm and other related projects.
This patch updated instruction how to build clang/llvm library
with new llvm-project setup.
=> update INSTALL.md for new llvm source compilation

docs/reference_guide.md, src/cc/api/BPF.cc, src/cc/api/BPF.h, src/cc/api/BPFTable.cc, src/cc/api/BPFTable.h, src/cc/bpf_module.cc, src/cc/bpf_module.h, src/cc/export/helpers.h, src/cc/frontends/clang/b_frontend_action.cc, src/cc/frontends/clang/b_frontend_action.h, src/cc/table_storage.h, src/python/bcc/table.py, tests/cc/CMakeLists.txt, tests/cc/test_map_in_map.cc, tests/python/test_map_in_map.py
Add BPF_MAP_TYPE_HASH_OF_MAPS and BPF_MAP_TYPE_HASH_OF_MAPS
supports in bcc. Two new constructs below are introduced
to bpf program:
```
BPF_HASH_OF_MAPS(map_name, "inner_map_name", max_entries)
BPF_ARRAY_OF_MAPS(map_name, "inner_map_name", max_entries)
```
In the above, "inner_map_name" is for metadata purpose and there
must be a map defined in bpf program with map name "inner_map_name".
Both python and C++ APIs are added.
For python, a new Table API get_fd() is introduced to get
the fd of a map so that the fd can be used by a map-in-map
do update. The get_fd() is already exposed as API function
in C++. For C++, without get_fd(), we will need to
templatize basic functions like update_value etc, which
I feed too heavy weight. Because of C++ using get_fd()
mechanism, so I exposed similar …
=> Add map-in-map support

src/cc/json_map_decl_visitor.cc
Previously, `__attribute__((aligned(sizeof(...))))` would cause the type inside `sizeof()` to be appended after the JSON type information for the struct in some clang versions, generating invalid JSON. Inhibit attribute traversal, since we only want to visit the fields.
I'm not that familiar with C++ nor the internals of clang and bcc, so review with extreme prejudice. :)
I've tested that this fixes the issue for me, but I'm not sure if this is the best way to fix this. Since we *only* want to look at the fields, it might be better to just inhibit *all* child traversal for `RecordDecl`, since we manually iterate the fields anyway.
I am not sure what would be the best way to do that, though, since I have no idea what's going on with clang's AST traversal: Given that `TraverseRecordDecl` …
=> Do not traverse attributes during JSON generation (Fixes #2605)

tools/deadlock.c, tools/memleak.py, tools/old/profile.py, tools/stackcount.py, tools/stacksnoop.lua, tools/trace.py, tools/wakeuptime.py
Do not use BPF_F_REUSE_STACKID if the stack id is used
together with process specific info like
pid/tgid/comm. Using BPF_F_REUSE_STACKID may cause
stack id pointing to a different stack later on.
=> do not use BPF_F_REUSE_STACKID incorrectly

tools/lockstat.py
When I used `tools/lockstat.py`,  `R2 type=map_value expected=fp` happened.  As the [issue #347](https://github.com/iovisor/bcc/issues/347) describes.
=> fix bug for lockstat.py #347

src/cc/json_map_decl_visitor.cc, tests/python/test_clang.py
The JSON generated for enums wasn't being handled, and caused
exceptions. Since the enum values aren't needed (and would've been
useless without the associated numerical values, anyway), just use the
matching integer type instead.
---
`Traverse*()` shouldn't really be called from inside `Visit*()`, but all the other methods are doing it too, so... The original enum code seems to have been a workaround for a problem caused by that, so the whole thing should probably be fixed at some point.
=> Use integer types for enums in JSON (Fixes #2615)

cmake/FindLibBpf.cmake, src/cc/CMakeLists.txt
@yonghong-song I thought we could use source packaged within
package build, but it's not the case.. it seems we can use libbpf-static
instead just as fine, with the uapi exception (described below)
I made sure this time and prepared [bcc fedora build](https://koji.fedoraproject.org/koji/taskinfo?taskID=39395362) with this change. Works nicely on all supported archs.
thanks,
jirka
---
Currently when building with CMAKE_USE_LIBBPF_PACKAGE we assume
that 'source' package is available to build libbcc_bpf libraries.
However It turned on that using debugsource (in Fedora) package is
not suitable or even possible, so we are switching to use the
libbpf-static package instead.
Adding libbpf-static package detection and removing source
package detection.
Using ar to extract objects from archive and …
=> Use libbpf-static instead of libbpf-debugsource for CMAKE_USE_LIBBPF_PACKAGE

man/man8/filetop.8
In the man pages of filetop, the field of FILE is missing
=> man: fix the field of filetop

man/man8/btrfsslower.8, man/man8/ext4slower.8, man/man8/fileslower.8, man/man8/nfsslower.8, man/man8/xfsslower.8, man/man8/zfsslower.8
Below filenames currently come from dentry->d_name.name
* btrfsslower
* ext4slower
* fileslower
* nfsslower
* xfsslower
* zfsslower
=> man: fix the explanation of filename

man/man8/runqslower.8
The runqslower man page obviously derived from the man page of
runqlat. It seems that a reference to runqlat in the NAME section has
been overlooked.
=> man: fix a reference to runqlat in runqslower man page

README.md, man/man8/klockstat.8, snapcraft/snapcraft.yaml, tests/python/test_tools_smoke.py, tools/klockstat.py, tools/klockstat_example.txt
The current lockstat.py is tracing three kernel functions
```
mutex_lock_enter(), mutex_unlock_enter(), mutex_lock_return()
```
for kernel locking statistics.
There are some other efforts trying to get user lock stats by
tracing e.g. pthread locking primitives. For example,
Sasha Goldshtein's linux-tracing-workshop
https://github.com/goldshtn/linux-tracing-workshop
is referenced in bcc/docs/tutorial_bcc_python_developer.md.
It has a tool called lockstat.py which traces pthread_mutex_init
to collect some lock statistics for userspace locks.
In bcc, in the past, we also had an effort to gather userspace
lock statistics with the same name lockstat.py.
https://github.com/iovisor/bcc/pull/1268
In the future, bcc could have a lockstat tool tracing userspace
locks. So let us rename the current …
=> rename tool lockstat.py to klockstat.py

examples/lua/memleak.lua, examples/lua/offcputime.lua, examples/tracing/mallocstacks.py, examples/tracing/stacksnoop.py
When the application bundles stack id with process specific
info (like pid, comm, etc.), BPF_F_REUSE_STACKID should not
be used as it may associate wrong stack with processes.
This patch corrected several such uses in examples/
directory.
=> remove inproper usage of BPF_F_REUSE_STACKID in examples

debian/changelog
the main changes from v0.11.0 to v0.12.0 tag:
* Support for kernel up to 5.4
* klockstat tool to track kernel mutex lock statistics
* cmake option CMAKE_USE_LIBBPF_PACKAGE to build a bcc shared library
linking with distro libbpf_static.a
* new map.lookup_or_try_init() API to remove hidden return in
map.lookup_or_init()
* BPF_ARRAY_OF_MAPS and BPF_HASH_OF_MAPS support
* support symbol offset for uprobe in both C++ and python API,
kprobe already has the support
* bug fixes for trace.py, tcpretrans.py, runqslower.py, etc.
=> debian changelog for v0.12.0 tag

src/python/bcc/__init__.py
Ever since Linux kernel commit aa0d6e70d, kprobes on s390 could no longer
be found due to a change in symbol names.
Symptom:
$ ./tools/execsnoop.py
cannot attach kprobe, probe entry may not exist
[...]
Signed-off-by: Stefan Raspl <raspl@linux.ibm.com>
=> Fix s390 kprobes support

tools/filetop.py
This fixes a regression from c2b371d56b8bbaf9c7d01b88830193ecd1ee4e12 where the author forgot to update the help output.
=> fix -h output for --sort option

README.md, man/man8/compactsnoop.8, snapcraft/snapcraft.yaml, tests/python/test_tools_smoke.py, tools/compactsnoop.py, tools/compactsnoop_example.txt, tools/old/compactsnoop.py
compactsnoop traces the compact zone system-wide, and print various details.
Example output:
```
COMM           PID    NODE ZONE         ORDER MODE       LAT(ms)           STATUS
zsh            23685  0    ZONE_DMA     -1    SYNC      0.025444         complete
zsh            23685  0    ZONE_DMA32   -1    SYNC      3.925823         complete
zsh            23685  0    ZONE_NORMAL  -1    SYNC    113.975603         complete
zsh            23685  1    ZONE_NORMAL  -1    SYNC      81.57143         complete
zsh            23685  0    ZONE_DMA     -1    SYNC       0.02774         complete
zsh            23685  0    ZONE_DMA32   -1    SYNC      4.631926         complete
zsh            23685  0    ZONE_NORMAL  -1    SYNC    113.975706         complete
zsh            23685  1    ZONE_NORMAL  -1 …
```
=> add tool: compactsnoop

man/man8/klockstat.8, tools/klockstat.py
- args.caller needs to be bytes not string
- also filter calls with missing stack info
- clarify man page a bit
=> klockstat: fix caller filter

src/cc/libbpf.c
Such prefixes are currently removed for kprobes, tracepoints, and raw tracepoints, but not for kretprobes.  This pull request removes it for kretprobe as well, for consistency.
One consequence of this change is that a bcc tool or script with both `kprobe__some_func` and `kretprobe__some_func` will now load both BPF programs under the same name, i.e., `some_func`. I don't know if that's an issue (?)
=> Remove kretprobe__ prefix from program names

.gitignore, docs/filtering_by_cgroups.md, examples/cgroupid/Dockerfile, examples/cgroupid/Makefile, examples/cgroupid/cgroupid.c, tools/execsnoop.py, tools/execsnoop_example.txt, tools/opensnoop.py, tools/opensnoop_example.txt
Add a new option --cgroupmap in execsnoop and opensnoop to only display results from processes that belong to one of the cgroups whose id, returned by bpf_get_current_cgroup_id(), is in a pinned BPF hash map.
Examples of commands:
```
```
Cgroup ids can be discovered in userspace by the system call name_to_handle_at(); an example of C program doing that is available in examples/cgroupid/cgroupid.c.
More complete documentation is added in docs/filtering_by_cgroups.md
The documentation is independent from Kubernetes. However, my goal is to use this feature in Kubernetes: I am preparing to use this in Inspektor Gadget to select specific Kubernetes pods, depending on a Kubernetes label selector. Kubernetes pods matching the label selector can come and go during the execution of the bcc tools; …
=> tools: cgroup filtering in execsnoop/opensnoop

introspection/CMakeLists.txt, src/cc/CMakeLists.txt
also add dependency of zlib in a couple of places
as libbpf starts to use zlib directly.
=> sync with latest libbpf

man/man8/bashreadline.8, man/man8/biosnoop.8, man/man8/drsnoop.8, man/man8/filelife.8, man/man8/gethostlatency.8, man/man8/killsnoop.8, man/man8/mountsnoop.8, man/man8/opensnoop.8, man/man8/statsnoop.8, man/man8/syncsnoop.8
Several man pages state that Linux 4.5 is required because the tool relies on the `bpf_perf_event_output` helper.  However, `bpf_perf_event_output` was introduced in Linux 4.4.
In addition, mountsnoop requires Linux 4.8 because it now uses the `bpf_get_current_task` helper.
=> man: fix required kernel version in man pages

src/cc/CMakeLists.txt
A typo occured in libbpf_uapi path from src/cc/CMakeLists.txt which
made compat linux uapi headers failed to copy.
fixes #2674 
Signed-off-by: Caspar Zhang <caspar@linux.alibaba.com>
=> fix libbpf_uapi path typo

src/cc/CMakeLists.txt
This should help embed libbcc into bpftrace:
* https://github.com/iovisor/bpftrace/issues/342
As well as other tools like ebpf_exporter, so that there is no longer a requirement to have a particular version libbcc installed.
cc @dalehamel, @danobi
=> Package static archives, closes #1938

tests/cc/test_map_in_map.cc
fix issue #2679 where test_map_in_map.cc has a
compilation error on ppc64le due to conflicting
type __u64. Let us just remove the typedef.
=> fix test_map_in_map.cc compilation error

src/cc/bcc_btf.cc
bcc does not use these types yet. Let us sanitize them
with int/void-pointer types so old kernels can continue
to work with latest llvm compiler.
=> sanitize btf VAR and DATASEC types

man/man8/runqslower.8, tools/runqslower.py, tools/runqslower_example.txt
Closes: #2607
Option for --pid or --tid tracing.
Enable group leader level tracing.
* --pid <pid>:
will trace every task that has <pid> as group leader.
Meaning it will trace the parent and its direct children.
* --tid <tid>:
will trace the given thread
Update example file.
=> tools/runqslower.py: Option for --pid or --tid

src/cc/api/BPF.h, src/cc/api/BPFTable.h, src/cc/export/helpers.h, src/cc/frontends/clang/b_frontend_action.cc, tests/cc/CMakeLists.txt, tests/cc/test_sk_storage.cc
kernel sk local storage is introduced at 5.2.
https://github.com/torvalds/linux/commit/6ac99e8f23d4b10258406ca0dd7bffca5f31da9d
this patch supports BPF_MAP_TYPE_SK_STORAGE in bcc.
tested C++ user space APIs and loading of the bpf programs
using helpers map.sk_storage_get() and map.sk_storage_delete().
=> support BPF_MAP_TYPE_SK_STORAGE map

tools/offcputime.py
pid/tid is already set to be mutually exclusive in
python's arg parser so no need for this check manually.
=> tools/offcputime.py: Redundant arg check

INSTALL.md
Packages are currently broken on Ubuntu Eon. See #2676 and #2678.
=> Add Ubuntu Eon incompatibility note

INSTALL.md
- Add updated list of dependencies to build on Ubuntu Eon (19.10)
- Add Ubuntu version numbers for increased clarity
- Capitalize release names to match official branding
=> Ubuntu Eon build dependencies and version numbers

src/cc/api/BPFTable.cc
Some old compiler may complain about this. Let us only use simple expression.
=> avoid complex expression in struct member initializer

src/cc/bcc_debug.cc
Upstream patch
https://reviews.llvm.org/D72172
changed function signature for MCInstPrinter method printInst().
Make adjustment in bcc as well.
=> update usage of MCInstPrinter printInst() for llvm10

FAQ.txt
Ubuntu 19.10 with secure boot enabled doesn't allow the kernel lockdown to be lifted by echo, even from root:
```
```
dmesg says:
```
This sysrq operation is disabled from userspace.
```
I pressed Alt-PrtScr-x and that worked:
```
sysrq: Disabling Secure Boot restrictions
Lifting lockdown
```
I can now run eBPF tools, such as execsnoop-bpfcc.
=> Secure Boot:  physical keypress to disable lockdown

src/cc/bcc_btf.cc, src/cc/bcc_btf.h
The llvm patch https://reviews.llvm.org/D71638 extends
BTF_KIND_FUNC to include scope of the function,
static, global and extern, with btf_type->info vlen
encoding since vlen is always 0 before the extension.
This patch did the sanitization so that the
bcc with latest llvm can still work on older kernels.
=> sanitize BTF_KIND_FUNC

introspection/CMakeLists.txt
CentOS 6 support was added in #1504 and inadvertently reverted in #1763 leading to builds failing due to undefined reference to `clock_gettime`.
```
Scanning dependencies of target bps
[ 22%] Building C object introspection/CMakeFiles/bps.dir/bps.c.o
[ 22%] Linking C executable bps
CMakeFiles/bps.dir/bps.c.o: In function `print_prog_info':
bps.c:(.text+0x32): undefined reference to `clock_gettime'
bps.c:(.text+0x13b): undefined reference to `clock_gettime'
collect2: error: ld returned 1 exit status
introspection/CMakeFiles/bps.dir/build.make:95: recipe for target 'introspection/bps' failed
make[2]: *** [introspection/bps] Error 1
CMakeFiles/Makefile2:651: recipe for target 'introspection/CMakeFiles/bps.dir/all' failed
make[1]: *** [introspection/CMakeFiles/bps.dir/all] Error 2
```
To …
=> Fix CentOS 6 support.

tools/bpflist.py
Let bpflist to list `raw-tracepoints` and do not let to list raw files (e.g., formerly, the `vim bpf-woo` process will be listed).
=> Bpflist fix

src/cc/bcc_debug.cc
The following changes from llvm 10
https://github.com/llvm/llvm-project/commit/6fdd6a7b3f696972edc244488f59532d05136a27#diff-37c83c70858df19cb097e36b13b7c112
changed MCDisassembler::getInstruction() signature.
Do the corresponding change in bcc_debug.cc to fix the issue.
=> fix llvm compilation error

docs/kernel-versions.md
I found that a redundant space caused a rendering error ([link](https://github.com/iovisor/bcc/blob/master/docs/kernel-versions.md#main-features)).
Signed-off-by: Masanori Misono <m.misono760@gmail.com>
=> docs: remove a redundant space

INSTALL.md
This package has been removed from the repositories.
=> Remove python2-bcc from list of AUR packages

examples/networking/simulation.py
test test_brb.py failed on fc31 with the following error messages:
```
File "./test_brb.py", line 162, in test_brb
disable_ipv6=True)
File "/home/yhs/work/bcc/tests/python/simulation.py", line 94, in _create_ns
disable_ipv6)
File "/home/yhs/work/bcc/tests/python/simulation.py", line 68, in _ns_add_ifc
ns_ipdb.interfaces.lo.up().commit()
File "/usr/local/lib/python3.7/site-packages/pyroute2/ipdb/interfaces.py", line 1078, in commit
raise error
File "/usr/local/lib/python3.7/site-packages/pyroute2/ipdb/interfaces.py", line 859, in commit
transaction.wait_all_targets()
File "/usr/local/lib/python3.7/site-packages/pyroute2/ipdb/transactional.py", line 507, in wait_all_targets
raise CommitException('target %s is not set' % key) …
```
=> fix a bug in networking/simulation.py

tools/profile.py
./profile.py -adf -p `pgrep -n main` 5
File "./profile.py", line 342, in <module>
print("%s %d" % (b";".join(line).decode('utf-8', 'replace'), v.value))
TypeError: sequence item 5: expected a bytes-like object, str found
=> fix line TypeError

docs/kernel-versions.md, introspection/bps.c, src/cc/compat/linux/virtual_bpf.h, src/cc/libbpf.c
Sync to latest libbpf repo. New helper bpf_jiffies64
and new program type BPF_PROG_TYPE_EXT is added.
=> sync to latest libbpf repo

.github/workflows/bcc-test.yml, .gitignore, Dockerfile.tests, examples/networking/simulation.py, tests/cc/test_c_api.cc, tests/cc/test_usdt_probes.cc, tests/python/test_brb2.py, tests/python/test_debuginfo.py, tests/python/test_stackid.py, tests/python/test_tools_smoke.py, tests/python/test_trace3.py, tests/python/test_usdt.py, tests/python/test_usdt2.py, tests/python/test_usdt3.py, tests/python/utils.py, tests/wrapper.sh.in
Run BCC test suite with github actions
With this commit, pushes to branches can trigger tests directly on
Github Actions.
Here it will be able to test against kernel 4.14 and 5.0.0, which correspond
to the latest Ubuntu LTS kernel releases.
Tests are run for both Debug and Release modes.
Tests run inside docker, in an ubuntu 19.04 container base.
For the github workflow:
- The test_libbcc suite is run first, to potentially fail fast on these faster
unit tests.
- The Python test suite is run
Some of these tests are allowed to fail, but the failure is still reported:
- In catch2 tests, using the [!mayfail] tag, where this will be displayed in
the test summary
- In Python unittests, using the `@mayFail("Reason")` decorator, which is
introduce for consistency with catch2. These will report …
=> GitHub actions

src/cc/api/BPF.cc, src/cc/api/BPF.h, src/cc/usdt.h, tests/python/test_usdt.py, tests/python/test_usdt2.py, tests/python/test_usdt3.py
This PR is per the discussion in #2715.
Changing the default behavior to use inode only matching fixes these test failures on github actions, as the USDT tests now run in docker (and on overlayfs). Because of this I've been able to remove the `@mayFail` decorator from the python USDT tests, as they now pass.
=> Make inode-only matching default, reverse USDT kludge

tools/klockstat.py
Currently we display the caller symbol in stack,
which ends up with output below when we enable stack:
Caller   Avg Hold  Count   Max hold Total hold
b'flush_to_ldisc+0x22'      56112      2     103914     112225
b'flush_to_ldisc+0x22'
b'process_one_work+0x1b0'
b'worker_thread+0x50'
b'kthread+0xfb'
Skipping one more symbol in stack to fix that:
Caller   Avg Hold  Count   Max hold Total hold
b'flush_to_ldisc+0x22'       1893      2       2765       3787
b'process_one_work+0x1b0'
b'worker_thread+0x50'
b'kthread+0xfb'
Signed-off-by: Jiri Olsa <jolsa@kernel.org>
=> tools/klockstat.py: Do not display symbol twice for stack

src/cc/frontends/clang/b_frontend_action.cc
llvm 11.0 required explicit conversion from StringRef to std::string.
The patch is
https://github.com/llvm/llvm-project/commit/777180a32b61070a10dd330b4f038bf24e916af1
This patch made a compatible change which works for old llvm
as well.
=> fix compilation error due to latest llvm change

src/python/bcc/__init__.py
Since commit 115b959d86
("Fix a file descriptor leak when module is deleted (#2530)"), we
observe the following exceptions during python exit:
Error in atexit._run_exitfuncs:
File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
func(*targs, **kargs)
File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 1366, in cleanup
os.close(fn.fd)
OSError: [Errno 9] Bad file descriptor
which occurs for python programs issuing a call to 'cleanup()', or using
the 'with bcc.BPF(...)' code pattern.
BPF's 'cleanup' is registered to be invoked atexit. Alas, commit
115b959d86 introduced an 'os.close(fn.fd)' call for each func loaded (to
prevent accidental FD leakage).
Problem is, that the 'self.funcs' dict entries are NOT deleted, making
subsequent calls …
=> bcc.BPF.cleanup(): Ensure self.funcs items get deleted during cleanup

src/cc/export/helpers.h
Fix issue #2734.
In 4.18 and later, when CONFIG_FUNCTION_TRACER is defined, kernel Makefile adds
-DCC_USING_FENTRY. Let do the same for bpf programs.
=> define CC_USING_FENTRY if CONFIG_FUNCTION_TRACER is defined

src/cc/frontends/clang/b_frontend_action.cc, tools/tcptop.py
Fix issue #2352.
Corresponding llvm bug: https://bugs.llvm.org/show_bug.cgi?id=41918.
If the element type is array type, the rewriter may generate code like
addr = ({ typeof(__u8 [16]) _val; __builtin_memset(&_val, 0, sizeof(_val));
bpf_probe_read(&_val, sizeof(_val), (u64)&daddr->s6_addr); _val; })
for something like
addr = daddr->s6_addr;
where s6_addr is an array.
The above code has an issue then as addr is pointing to some data
which is out of scope, which meaning compiler is free to use the space.
Let us disable such transformation until we find a good solution.
=> prevent rewriting for array element type

tools/offwaketime.py
That seems to be unintentional break. This pull request just restores offwaketime functionality.
=> Fix offwaketime regression introduced by #ac00ac

src/cc/api/BPF.cc, src/cc/api/BPF.h, src/cc/api/BPFTable.cc, src/cc/api/BPFTable.h, src/cc/bpf_module.cc, src/cc/bpf_module.h, src/cc/export/helpers.h, src/cc/frontends/clang/b_frontend_action.cc, tests/cc/CMakeLists.txt, tests/cc/test_cg_storage.cc, tests/cc/test_sock_table.cc
This patch supports sockmap, sockhash and cgroup_local_storage
maps. Two C++ APIs, attach_func and detach_func are also
added to allow to attach program to cgroups. So this makes
using C++ APIs for cgroup based networking applications
easier to integrate with bpf programs.
The unit testing is rough as it needs some work to set up
cgroups and establish TCP connections to really test the
result of map operations. But still all supported map
operations in kernel and in C++ APIs are tested syntacically.
=> support sockmap/sockhash/cgroup_local_storage maps

debian/control
#1968 marked the `libbcc` debian package as being architecture-independent by setting the `Architecture` field to `all`. However, the `libbcc` package contains shared objects which are architecture-dependent. One of the consequences is that a corresponding `-dbgsym` package is not generated when `libbcc` is generated.
This changes the `Architecture` from `all` to `any`, which indicates the package supports all architectures, but must be built independently for each one. It also causes a `libbcc-dbgsym` package to be built with the debug info stripped from `libbcc`.
I don't have other architectures handy to test with, but I built the packages on amd64 and found that install cleanly, that some of the basic BCC tools work correctly:
```
bcc-lua_0.12.0-1-delphix-2020.02.08.11.34.22_all.deb …
```
=> libbcc debian package is architecture-dependent

snap/snapcraft.yaml
Also need libfl-dev to build on other non-x86 targets
=> snapcraft: add missing libfl-dev dependency

CMakeLists.txt
The LLVM package provides a Cmake flag "LLVM_DIR", but there is no analogue for specifying the search for clang libraries or headers in this same way.
This PR introduces this, so that the following usage is valid:
```
cmake -DLLVM_DIR=${SOME_PATH_TO_LLVM}/lib/cmake/llvm
cmake -DCLANG_DIR=${SOME_PATH_TO_CLANG}
```
Note that LLVM_DIR points to the Cmake files for LLVM, and CLANG_DIR, points to a root director of a clang install, which has both "/lib" and "/include" in it, there is no need to load any CMake files for this and clang doesn't seem to export a cmake file for this / nor is it needed with the processing of clang libs below.
I happen to need this in order to override the LLVM and Clang paths to point to embedded ones, when building bpftrace for android …
=> Allow specifying clang base directory

tools/tcpconnlat.py
1. Wirte a simple go, just print pid and get some website.
```go
func main() {
pid := os.Getpid()
fmt.Println(pid)
response, err := http.Get("http://www.baidu.com")
// ....
}
```
```bash
./main
3581
```
2. But when run `tcpconnlat`, we just go tid 3585, (not pid 3581)
```bash
#./tcpconnlat
PID    COMM         IP SADDR            DADDR            DPORT LAT(ms)
3585   main         4  10.0.2.15        180.101.49.11    80    60.68
```
3. So run `./tcpconnlat -p 3581` not work
I have tested this situation under kernel 3.10 and 5.0.9.
=> fix pid filter bug

tools/stackcount.py, tools/stackcount_example.txt
This patch fixes issue #2748. The bug was that address-to-symbol resolution
didn't work for user-space stacks without the `-P` (per-pid) flag when tracing
single, isolated processes. The current documentation of the `-P` option
indicates that it's used to "display stacks separately for each process",
and this doesn't match with the intended usage.
This patch has two parts:
- Fix `tools/stackcount.py` to explicitly set perpid to True if `-p <pid>`
is used
- Remove the `-P` option from the example of tracing single, isolated process
in `tools/stackcount_example.txt`, since the usage of the option can
be confusing (and unnecessary after the current change)
=> tools/stackcount: Fix address resolution for user-space stack

tools/offwaketime.py, tools/profile.py
When combining delmiiter and folding options: `profile -d -f`, this exception is thrown:
```
File "./profile", line 337, in <module>
line.extend(b["-"] if (need_delimiter and k.kernel_stack_id >= 0 and k.user_stack_id >= 0) else [])
File "/usr/local/lib/python2.7/dist-packages/bcc/__init__.py", line 508, in __getitem__
self.tables[key] = self.get_table(key)
File "/usr/local/lib/python2.7/dist-packages/bcc/__init__.py", line 493, in get_table
raise KeyError
KeyError
```
This change eliminates the delimiter when folding is enabled.
=> tools/profile: fix kernel delimiter when folding

tools/execsnoop.py
The execsnoop documentation mispelled 'execsnoop' as 'opensnoop'.
Bug introduced by https://github.com/iovisor/bcc/pull/2651
=> tools: fix confusion between execsnoop and opensnoop

debian/changelog
* Support for kernel up to 5.5
* bindsnoop tool to track tcp/udp bind information
* added compile-once run-everywhere based libbpf-tools, currently
only runqslower is implemented.
* new map support: sockhash, sockmap, sk_storage, cgroup_storage
* enable to run github actions on the diff
* cgroupmap based cgroup filtering for opensnoop, execsnoop and bindsnoop.
* lots of bug fixes.
=> debian changelog for v0.13.0 tag

docs/filtering_by_cgroups.md, man/man8/execsnoop.8, man/man8/opensnoop.8, man/man8/tcpaccept.8, man/man8/tcpconnect.8, man/man8/tcptracer.8, tools/tcpaccept.py, tools/tcpaccept_example.txt, tools/tcpconnect.py, tools/tcpconnect_example.txt, tools/tcptracer.py, tools/tcptracer_example.txt
List of tcp tools updated: tcpaccept, tcpconnect, tcptracer.
This is the same pattern used initially in #2651 (opensnoop, execsnoop) and then in #2749 (bindsnoop).
=> tools: add option --cgroupmap to tcp tools

examples/cpp/RandomRead.cc, src/cc/api/BPF.cc, src/cc/api/BPF.h, src/cc/libbpf.c, src/cc/libbpf.h
libbpf already supported this, so this just adds the wrapper in the C++ API.
=> C++ API: add support for raw tracepoints

libbpf-tools/README.md
Add links to BPF CO-RE blog posts, explainint what it is, how to use it, and
giving practical recommendations on how to convert BCC BPF program to
libbpf-based one.
=> libbpf-tools: add links to BPF CO-RE posts

man/man8/execsnoop.8, tools/execsnoop.py, tools/execsnoop_example.txt
Add flags to display UID and filter by UID.
It's the same options used in `opensnoop` and `drsnoop`.
=> tools: execsnoop add -U (--print-uid) and -u (--uid) flags

examples/networking/http_filter/http-parse-complete.py
The example wasn't working on my machine, just like in issue #2169
Aside from indentation and other formatting, the only things I changed were the toHex and printUntilCRLF functions, and using bytes instead of strings in some places.
=> Fix the python part of the http-parse-complete example

docs/reference_guide.md, src/cc/CMakeLists.txt, src/cc/bcc_btf.cc, src/cc/bcc_libbpf_inc.h, src/cc/bpf_module.cc, src/cc/export/helpers.h, src/cc/frontends/clang/b_frontend_action.cc, src/cc/libbpf.c, src/cc/libbpf.h, src/python/bcc/__init__.py, tests/cc/CMakeLists.txt, tools/klockstat.py, tools/opensnoop.py, tools/vfsstat.py
Kernel added new probe called trampoline allowing to probe
almost any kernel function when BTF info is available in
the system.
Adding the interface under 'kfunc' name, which allows to
probe function entry and 'kretfunc' name, which allows to
trace function return.
The main benefit is really low overhead which is really low
for trampolines (please see commit for klockstat.py
with perf comparison).
Another benefit is the ability of kretfunc probe to access
function arguments, so some tools might need only one program
instead of entry/exit ones (please see commit for
opensnoop.py changes).
=> Introduce {attach|detach}_kfunc API

src/cc/bcc_exception.h
The first step of #2697 (StatusTuple can have canonical error code).
Please suggest additional error code needed in BCC code base. So far I come up with 5.
This PR's purpose is to update StatusTuple to have a enum code, in addition to the integer code. This allows existing code to continue work, and other community members to continue work with the more familiar APIs.
Once this PR is submitted, I'll start to change existing code to use the new APIs. Hopefully further revise StatusTuple according to the learning gained in the process.
=> Update StatusTuple to use enum Code

INSTALL.md
As an Ubuntu user, using Ubuntu 19.10, it seems to work. The commands are just copied from the "openSUSE - Source" section: https://github.com/iovisor/bcc/blob/0f92c845a7deb60e97f49425f181d7b7e9daf56b/INSTALL.md#install-and-compile-bcc-2
I think python3 should be the default in the future, but I'll make this PR before doing so.
=> doc: add python3 doc to "Ubuntu - Source" section in INSTALL.md

src/python/bcc/usdt.py
`USDT#enable_probe()` raises exceptions when the attaching process is not built with USDT probes, but its message does not say the right suggestions, as `enable_probe_or_bail` does.
With this PR, the two methods, `enable_probe` and `enable_probe_or_bail` share their error message, which suggests a possible cause.
before:
```
failed to enable probe '%s'; a possible cause
can be that the probe requires a pid to enable
```
after:
```
Failed to enable USDT probe '%s':
the specified pid might not contain the given language's runtime,
or the runtime was not built with the required USDT probes. Look
for a configure flag similar to --with-dtrace or --enable-dtrace.
To check which probes are present in the process, use the tplist tool.
```
=> usdt.py: improve error messags for enable_probe()

src/python/bcc/usdt.py
This is a proposal to change the behavior of `USDT#enable_probe_or_bail()`: print error messages to `stderr`, instead of `stdout`. I think this PR is the expected behavior, but because it breaks backward compatibility, feel free to reject it.
=> usdt.py: print errors to stderr in enable_probe_or_bail()

src/cc/usdt.h, src/cc/usdt/usdt_args.cc, tests/cc/test_usdt_args.cc
One of the USDT probes for OpenJDK on AArch64 has an argument as an
offset from the stack pointer register like "8@[sp, 112]". This causes
the argument parser to fail:
Parse error:
8@x22 8@x20 8@x23 8@x0 8@x26 8@x27 8@[sp, 112] 8@[sp, 120]
------------------------------------------^
The error message then repeats forever.
Changed ArgumentParser_aarch64::parse_register so it accepts either
"xNN" or "sp" and outputs the register name rather than the register
number. The stack pointer is in a separate field `sp` in `struct pt_regs`
rather than in the `regs[]` array. See:
https://elixir.bootlin.com/linux/latest/source/arch/arm64/include/asm/ptrace.h#L160
Note that the parser currently accepts "x31" and converts that into a
reference to `regs[31]` but that array only has 31 elements. Made x31 …
=> usdt: fix parsing sp register in arguments on AArch64

src/python/bcc/table.py
I believe this is more helpful for those who develop BPF tools with the Python binding.
=> table.py: print error messages to stderr and exit(1) instead of exit(0) for fatal errors

.github/workflows/bcc-test.yml, Dockerfile.ubuntu
This is optional: this GitHub Action will only attempt to publish the
container image if the GitHub repository has been configured with GitHub
secrets (e.g. https://github.com/iovisor/bcc/settings/secrets).
The GitHub secrets can be configured as follows:
- DOCKER_PUBLISH = 1
- DOCKER_IMAGE = docker.io/myorg/bcc
- DOCKER_USERNAME = username
- DOCKER_PASSWORD = password
This is intended to make it easy for anyone to fork iovisor/bcc on
GitHub and publish custom container images with bcc.
-----
Open questions:
- I see that the built image is big: 1.3GB. Are there other attempts to build bcc container images with a smaller size?
- Dockerfile.ubuntu keeps the sources and the .deb files but didn't install them. Is it currently used somewhere? I couldn't find it in the bcc repository.
=> GitHub Actions: optionally publish container image

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/trace_helpers.c, libbpf-tools/trace_helpers.h
Re-implement internals of ksyms cache to minimize memory overhead and
allocations. Addr is also changed to be unsigned long.
fscanf() can be further optimized into manual parsing, but it's low enough
overhead right now that I felt like readibility is more important.
Benchmarking ksyms loading/parsing parts:
BEFORE:
$ /usr/bin/time ./test
0.03user 0.04system 0:00.08elapsed 98%CPU (0avgtext+0avgdata 6968maxresident)k
0inputs+0outputs (0major+1512minor)pagefaults 0swaps
AFTER:
$ /usr/bin/time ./test
0.02user 0.03system 0:00.06elapsed 100%CPU (0avgtext+0avgdata 9508maxresident)k
0inputs+0outputs (0major+2106minor)pagefaults 0swaps
RSS goes down from 9.5MB to <7MB, while CPU time went up about 20ms.
=> libbpf-tools: optimize ksyms cache

src/cc/bcc_usdt.h, src/cc/usdt/usdt.cc, src/python/bcc/libbcc.py, src/python/bcc/usdt.py, tests/python/test_usdt3.py, tools/trace.py
`USDT#enable_probe()` cannot enable probes if its basename is not unique, so providing a way to use fully-specified names (e.g. "provider:probe") is inevitable for some cases.
At first, I have created a path as https://github.com/iovisor/bcc/pull/2791, but I prefer this style to keep C API tidy. Sorry for annoying.
=> python binding: allow fully-specified probe names for USDT#enable_probe()

man/man8/capable.8, tools/capable.py, tools/capable_example.txt
`--cgroupmap` is the same option already introduced in other tools (execsnoop, opensnoop, and others)
Some processes can do a lot of security capability checks, generating a lot of ouput. In this case, the --unique option is useful to only print once the same set of capability, pid (or cgroup if --cgroupmap is used) and kernel/user stacks (if -K or -U are used).
```
```
Documentation (man page and example text) updated.
=> tools: add option --cgroupmap and --unique to capable.py

Dockerfile.ubuntu
Before this patch, Dockerfile.ubuntu was generating an oversized image.
```
Uncompressed size      Compressed size
Before this patch:     1.3GB                  390MB
After this patch:      250MB                  110MB
```
-----
Follow up to https://github.com/iovisor/bcc/pull/2797
=> Reduce container image size with multi-stage builds

libbpf-tools/.gitignore, libbpf-tools/drsnoop.bpf.c, libbpf-tools/opensnoop.bpf.c, libbpf-tools/opensnoop.c, libbpf-tools/runqslower.bpf.c
Remove BPF_F_CURRENT_CPU definitions, which are now provided by vmlinux.h
after 1aae4bdd7879 ("bpf: Switch BPF UAPI #define constants used from BPF
program side to enums") commit in kernel.
Fix potential uninitialized read warning in opensnoop.
Also add opensnoop to .gitignore.
=> libbpf-tools: small clean ups across all tools

libbpf-tools/Makefile
BPF code is compiled with -target bpf, but for PT_REGS_PARM macro (and by
induction for BPF_KPROBE/BPF_KRETPROBE macros as well), it's important to know
what's the target host original architecture was, to use correct definition of
struct pt_regs. Determine that based on output of `uname -m` (taking into
account that both x86_64 and x86 are defined as x86 internally for kernel).
Reported-by: Wenbo Zhang <ethercflow@gmail.com>
=> libbpf-tools: determine target host architecture

tools/tcpstates.py
The tracepoint inet_sock_set_state only exists in kernels 4.15.
Backported the bpf tracepoint to use kprobes on older kernels.
=> Backport tcpstates to kernels < 4.15

CMakeLists.txt, INSTALL.md
It is a typical mistake to mix adding "-DCMAKE_INSTALL_PREFIX=/usr " and not when we develop BCC.
Let's set the right default and forget the option.
=> Make -DCMAKE_INSTALL_PREFIX=/usr as the default

src/cc/bcc_syms.cc, tests/cc/test_usdt_probes.cc
Like in https://github.com/iovisor/bcc/commit/5ce16e478a98442b7687e9f5139c1cdb27051ce6 we need to not prepend /proc/PID/root multiple times.
This is because for containerized processes, paths like:
`/proc/2593844/root/proc/2593844/root/usr/local/bin/memcached`
May be invalid if process in in a different PID namespace.
=> Do not prepend /proc multiple times in bcc_resolve_symname

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/xfsslower.bpf.c, libbpf-tools/xfsslower.c, libbpf-tools/xfsslower.h
- Parse `fsync`'s offset to `start` and size to `end - start` instead of zero; 
=> libbpf-tools: add CO-RE xfsslower

tools/opensnoop.py
Commit c347fe6c9f75 ("Support kfunc in opensnoop.py") introduces an
alternative probe on do_sys_open() with kfuncs instead of kprobes. This
new implementation is used if the kernel supports it. But it removed the
--cgroupmap filter added in commit b2aa29fa3269 ("tools: cgroup
filtering in execsnoop/opensnoop").
This patch adds the --cgroupmap filter in the kfunc implementation.
-----
Note: I didn't test it yet; I will need to get a newer kernel first, see https://github.com/iovisor/bcc/pull/2726#issuecomment-601095997.
/cc @olsajiri
=> opensnoop: fix --cgroupmap with kfunc

tools/tcptop.py
Fixes the following error on aarch64:
; struct sock *sk = ctx->regs[0]; int copied = ctx->regs[1];
0: (79) r8 = *(u64 *)(r1 +8)
...
; struct ipv6_key_t ipv6_key = {.pid = pid};
79: (63) *(u32 *)(r10 -48) = r7
; struct ipv6_key_t ipv6_key = {.pid = pid};
80: (7b) *(u64 *)(r10 +8) = r9
invalid stack off=8 size=8
processed 96 insns (limit 1000000) max_states_per_insn 0 total_states 7 peak_states 7 mark_read 4
=> tools: fix alignment of ipv6_key_t in tcptop

tools/cachetop.py
currently with ascending sort the useful information
is commonly beyond the bottom of the terminal window
and it is necessary to reverse the sort manually every execution.
Signed-off-by: Mark Kogan <mkogan@redhat.com>
=> cachetop: Change the default sort order to Descending

tools/capable.py
9d7feeed87c5 ("tools: add option --unique to capable.py") introduced a
compilation error when the --unique flag is passed.
Signed-off-by: Mauricio Vásquez <mauricio@kinvolk.io>
=> tools/capable: fix compilation error

introspection/CMakeLists.txt
On Android there is no standalone rt library and relevant symbols are provided
by libc (bionic).
=> make -lrt linking optional

examples/networking/http_filter/http-parse-complete.py
resolves #2848 
problem
-----------
http-parse-complete.py error out on my debian 10.3 machine.
with error log 
```
##dev@debian:~/git/bcc/examples/networking/http_filter$ sudo python http-parse-complete.py -i wlp3s0
binding socket to 'wlp3s0'
File "http-parse-complete.py", line 191, in <module>
ip_src = int(toHex(ip_src_str), 16)
File "http-parse-complete.py", line 37, in toHex
hv = hex(ch).replace('0x', '')
TypeError: hex() argument can't be converted to hex
```
root cause
-------------
in line
```
hv = hex(ch).replace('0x', '')
```
hex as per [python documetation](https://docs.python.org/3/library/functions.html#hex)
first argument is expeted of type int
but ch is of type str
so we can use ord() to convert it appropriately.
=> http-parse-complete.py toHex funtion has error

libbpf-tools/opensnoop.bpf.c, libbpf-tools/opensnoop.c, libbpf-tools/opensnoop.h
* allow passing `0` as valid uid
* fix type of `targ_uid`
Also wanted to say, that there is another way to implement UID filtering, that will support `0` UID. According to [kernel source][uid_valid] there is only one invalid UID, it is `(uint)-1` which should be `UINT_MAX`. So instead of adding another variable, like I did, it possible to check if `targ_uid` is `UINT_MAX` (or `-1`), but I don't think we should be stingy on variables in this case.
[uid_valid]: https://github.com/torvalds/linux/blob/master/include/linux/uidgid.h#L113
=> libbpf-tools: CO-RE opensnoop minor improvements

examples/cpp/FollyRequestContextSwitch.cc, src/cc/api/BPF.cc, src/cc/api/BPF.h, tests/cc/test_usdt_probes.cc
It's bothering to write a loop such as:
```c++
for (auto &probe : probes) {
ret = bpf->attach_usdt(probe);
if (!ret.ok()) {
std::cerr << "attach_usdt: " << ret.msg() << std::endl;
return EXIT_FAILURE;
}
}
```
So I think it makes sense when the BPF.h provides a way to enable/disable all the USDTs at once.
=> [C++] add BPF::enable_usdt(void) and disble_usdt(void) to handle all the USDT at once

examples/tracing/nflatency.py
This adds a kprobe / kretprobe for chasing down slow netfilter hooks. Since, often, the slowest hooks are on connection initialization and teardown, it is bucketed by TCP flags. (rather than dive deep in to conntrack)
Signed-off-by: Casey Callendrello <cdc@redhat.com>
=> examples/tracing: add nflatency - netfilter hook metrics

tests/python/CMakeLists.txt, tests/python/test_lpm_trie.py
test_lpm_trie.py has been in the repo for quite some time,
but is not included in the unit test.
The issue https://github.com/iovisor/bcc/issues/2860
exposed an issue involved in using together with BTF,
which requires the key type to be a structure.
Let add it as a unit test so we can be sure
lpm_trie map is supported properly by bcc.
=> add test_lpm_trie.py test

src/cc/bpf_module.cc
To fix the issue (https://github.com/iovisor/bcc/issues/2827)
which exposed a problem with aarch64 frontend and bpf backend
regarding __int128 type, the following llvm patch
https://reviews.llvm.org/D76587
landed to explicitly support i128 type in bpf layout spec.
Adjust the layout string in bpf_module JIT compilation
accordingly.
=> adjust layout string in JIT with llvm11 128bit spec support

src/cc/bcc_syms.cc, tests/python/CMakeLists.txt, tests/python/test_uprobes2.py
Quoting https://refspecs.linuxbase.org/elf/elf.pdf:
```
Symbol table entries for different object file types have slightly different
interpretations for the st_value member.
- In relocatable files, st_value holds alignment constraints for a symbol
whose section index is SHN_COMMON.
- In relocatable files, st_value holds a section offset for a defined symbol.
That is, st_value is an offset from the beginning of the section that st_shndx
identifies.
- In executable and shared object files, st_value holds a virtual address. To
make these files' symbols more useful for the dynamic linker, the section offset
(file interpretation) gives way to a virtual address (memory interpretation) for
which the section number is irrelevant.
```
This is a problem in practice as well. I run into this while …
=> Translate virtual addresses to binary addresses for shared libs as well.

examples/tracing/io_latencies.py
This adds flexible low overhead latency percentile monitoring for block
devices which can be useful in understanding and debugging IO related
issues.
Signed-off-by: Tejun Heo <tj@kernel.org>
=> examples/tracing: add io_latencies - IO latency distribution monitor

src/cc/api/BPF.h, tests/cc/test_usdt_probes.cc
I need to access attributes for `class USDT`, and it's natural to provide them.
=> add attribute readers to class USDT (C++ API)

libbpf-tools/README.md
Hi there
I added a tiny section to the README on re-compiling your kernel to get BTF type info in there. I [struggled](https://github.com/iovisor/bcc/issues/2872)  a bit and maybe its a bit clearer now
=> Added kernel recompile guidance for  libbpf CO-RE

src/cc/frontends/b/codegen_llvm.cc, src/cc/frontends/b/codegen_llvm.h
The llvm CreateCall used in bcc is deprecated in llvm 11:
https://reviews.llvm.org/D76269
The llvm CreateMemCpy is changed in llvm 11 as well:
https://reviews.llvm.org/D71473
This caused bcc compilation error.
/home/yhs/work/bcc/src/cc/frontends/b/codegen_llvm.cc: In member function
‘ebpf::StatusTuple ebpf::cc::CodegenLLVM::emit_log(ebpf::cc::Method CallExprNode*)’:
/home/yhs/work/bcc/src/cc/frontends/b/codegen_llvm.cc:691:39: error: no matching function for call to
‘llvm::IRBuilder<>::CreateCall(llvm::Value*&, std::vector<llvm::Value*, std::allocator<llvm::Value*> >&)’
expr_ = B.CreateCall(printk_fn, args);
^
...
/home/yhs/work/bcc/src/cc/frontends/b/codegen_llvm.cc: In member function
‘virtual ebpf::StatusTuple ebpf::cc::CodegenLLVM::visit_string_exp_node(ebpf::cc::StringExprNode*)’: …
=> fix llvm 11 compilation issues

src/cc/bcc_elf.c, src/cc/bcc_syms.cc, src/cc/bcc_syms.h, src/cc/frontends/clang/arch_helper.h, tests/cc/test_c_api.cc
Earlier, it was assumed that ELF ABI v2 is used only on little-endian `powerpc64` environments but it seems this ABI can be used independently of endianness.
It is expected that any C preprocessor that conforms to the ELF ABI v2 specification must predefine the `_CALL_ELF` macro and set its value to 2.
Instead of looking at `__BYTE_ORDER__` to determine whether to use the Local Entry Point (LEP) of symbols, one should look at the `_CALL_ELF` macro instead as this is ABI-related.
Similarly, `_CALL_ELF` should be used only for determining the ABI version and not the endianness.
=> Fix ELF ABI and endianness checks for powerpc64

docs/reference_guide.md, docs/tutorial_bcc_python_developer.md, examples/cpp/RecordMySQLQuery.cc, examples/lua/bashreadline.c, examples/lua/strlen_count.lua, examples/lua/usdt_ruby.lua, examples/tracing/mysqld_query.py, examples/tracing/nodejs_http_server.py, examples/tracing/strlen_count.py, examples/tracing/strlen_snoop.py, src/cc/export/helpers.h, src/cc/frontends/clang/b_frontend_action.cc, tools/bashreadline.py, tools/biosnoop.lua, tools/biosnoop.py, tools/dbslower.py, tools/execsnoop.py, tools/funcslower.py, tools/gethostlatency.py, tools/lib/ucalls.py, tools/lib/uflow.py, tools/lib/ugc.py, tools/lib/uobjnew.py, tools/lib/uthreads.py, tools/mountsnoop.py, tools/mysqld_qslower.py, tools/opensnoop.py, tools/sslsniff.py, tools/statsnoop.py, tools/ttysnoop.py
Hi @yonghong-song, @brendangregg, @4ast, all
[RFC 0/1] Support bpf_probe_read_user in bcc tools
bcc tracks the function arg pointers and then converts the pointer
deferences (both user and kernel pointer) into the bpf_probe_read().
However this is not valid for architecture which has overlapping address
space. To overcome this issue, the bpf_probe_read_{user/kernel} variant
was introduced.
Few Feasible solution for separation of user probe read and the kernel
probe read:
Approach 1 (temporary approach):
1. Explicitly use bpf_probe_read_user() for copying the user-space var
into the ebpf stack. Like kernel/bpf/samples/.
-  Make changes in the tools and examples.
- For backward compatibility, when kernel version < 5.5, convert
bpf_probe_read_user call to bpf_probe_read(). Atleast the tools …
=> bcc: Use bpf_probe_read_user in tools and provide backward compatibility

examples/perf/ipc.py
Added example for collecting performance counter data at custom user space application probes or USDT probes.
=> Add perf event data collection example for an userspace application

examples/usdt_sample/usdt_sample.md, src/cc/usdt/usdt.cc
Make it clear which file the USDT runtime files to find and suggest a
fix.
=> USDT: make path failure message more explicit

src/cc/libbpf.c, src/python/bcc/__init__.py, src/python/bcc/utils.py, tools/argdist.py, tools/argdist_example.txt, tools/trace.py, tools/trace_example.txt
This pull request provides the following:
- Add bpf_probe_read_user support to trace.py and argdist.py
- Refactoring of STRCMP probe generation code
- Fix bpf_has_kernel_btf
Thank you
=> Bcc tools fixes

tools/argdist.py
Fix for the issue discussed in https://github.com/iovisor/bcc/issues/2907/
=> Bug #2907 - Fix argdist filtering option for USDT probes

examples/cpp/CMakeLists.txt, tests/cc/CMakeLists.txt
I use clang-8.0.1 and gcc-8.3.1 to compile bcc-0.12.0,
without -fPIC, will get errors like this:
/usr/bin/ld: CMakeFiles/test_libbcc.dir/test_libbcc.cc.o: relocation
R_X86_64_32S against symbol `_ZTVN5Catch21LegacyReporterAdapterE' can
not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/test_libbcc.dir/test_c_api.cc.o: relocation
R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE
object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/CGroupTest.dir/CGroupTest.cc.o: relocation
R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE
object; recompile with -fPIC
=> add -fPIC to compile examples/cpp and tests/cc

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/vfsstat.bpf.c, libbpf-tools/vfsstat.c, libbpf-tools/vfsstat.h
The vfsstat tool actually doesn't need to use CO-RE, add it as an
example of using batch functions to read/update arrays.
Signed-off-by: Anton Protopopov <a.s.protopopov@gmail.com>
=> libbpf-tools: convert BCC vfsstat to libbpf-based version

Dockerfile.tests
Github actions are failing because the docker image used for testing is based
in Ubuntu 19.04 that is EOL now. This commit downgrades the version used for
testing to 18.04 that is LTS. It also installs the "util-linux" package that
includes the "unshare" command.
=> Fix github actions tests

README.md, man/man8/dirtop.8, tools/dirtop.py, tools/dirtop_example.txt
This tools is about reporting IOs per directory.
That's a clone of filetop but works in a different way :
- user specify a glob to select a list of directories to watch
- dirtop extracts the inode_id of the selected directories
- the bpf program receives the list of top directories to consider
- when vfs_{read|write} occurs, the bpf program check
if one of the parents is part of the list we search for
- if it matches, the io is accounted
On the python side, the program will reconcilate IOs per directory and print stats.
While filetop list the programs and filename, dirtop only list the directory name.
A typical usages looks like :
[root@host]: dirtop.py -d '/hdfs/uuid/*/yarn'
13:53:09 loadavg: 51.64 43.66 39.18 36/3019 38944
PATH …
=> tools/dirtop: Adding dirtop utility

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/execsnoop.bpf.c, libbpf-tools/execsnoop.c, libbpf-tools/execsnoop.h
Hi, I've made version of `execsnoop` using libbpf, but currently it lacks few essential parts (printing `args` and relative timestamps). I just wanted to ask few questions before implementing them.
To implement argument printing I need hash table (or some balanced tree) and wanted to ask if it would be okay if I add some library ([like this one](https://github.com/attractivechaos/klib/blob/master/khash.h)). Or maybe it would be better to use `hsearch` from glibc. Or, as another variant, implement it in CPP and use STL. To be honest, I would prefer to add header only library, since `hsearch` lacks some features  and CPP version will require libstd on host machine, library in the same time could be reused by other tools.
Also, it seems, there is a possibility of **memory leak** in current …
=> WIP: libbpf-tools: add CO-RE execsnoop

src/cc/export/helpers.h, tools/klockstat.py, tools/opensnoop.py
The KFUNC_PROBE macro is using "void" as return type, this is causing problems
in some tools that have a filtering enable that returns 0.
Reproducer: (Notice that it requires BTF support)
```
$ python opensnoop.py --pid 5
/virtual/main.c:33:21: error: void function '____kretfunc__do_sys_open' should not return a value [-Wreturn-type]
if (pid != 5) { return 0; }
^      ~
...
```
Signed-off-by: Mauricio Vásquez <mauricio@kinvolk.io>
FIxes changes made in https://github.com/iovisor/bcc/pull/2726.
=> Fix KFUNC_PROBE return value

docs/special_filtering.md, man/man8/bindsnoop.8, man/man8/capable.8, man/man8/execsnoop.8, man/man8/opensnoop.8, man/man8/profile.8, man/man8/tcpaccept.8, man/man8/tcpconnect.8, man/man8/tcptop.8, man/man8/tcptracer.8, src/python/bcc/containers.py, tools/bindsnoop.py, tools/bindsnoop_example.txt, tools/capable.py, tools/capable_example.txt, tools/execsnoop.py, tools/execsnoop_example.txt, tools/opensnoop.py, tools/opensnoop_example.txt, tools/profile.py, tools/profile_example.txt, tools/tcpaccept.py, tools/tcpaccept_example.txt, tools/tcpconnect.py, tools/tcpconnect_example.txt, tools/tcptop.py, tools/tcptop_example.txt, tools/tcptracer.py, tools/tcptracer_example.txt
In previous patches, I added the option --cgroupmap to filter events
belonging to a set of cgroup-v2. Although this approach works fine with
systemd services and containers when cgroup-v2 is enabled, it does not
work with containers when only cgroup-v1 is enabled because
bpf_get_current_cgroup_id() only works with cgroup-v2. It also requires
Linux 4.18 to get this bpf helper function.
This patch adds an additional way to filter by containers, using mount
namespaces.
Note that this does not help with systemd services since they normally
don't create a new mount namespace (unless you set some options like
'ReadOnlyPaths=', see "man 5 systemd.exec").
My goal with this patch is to filter Kubernetes pods, even on
distributions with an older kernel (<4.18) or without cgroup-v2 enabled.
- This …
=> tools: add filtering by mount namespace

man/man8/exitsnoop.8, tools/exitsnoop.py, tools/exitsnoop_example.txt
`sched_process_exit` tracepoint is called when thread terminates.
So exitsnoop shows line per each thread termination if the process
is multi-thread process. This is not useful when people wants to
know why process terminates, not thread.
So this changes exitsnoop default behavior which traces process termination
instead of thread termination. And add `--per-thread` option which behaves
as original exitsnoop implementation.
I suppose `exitsnoop` should check both PID and TID as default behavior because its documentations says **Trace all process termination** but current implementation **traces all thread termination**. However I'm not sure that there is no problem to change default behavior for backward compatibility.
=> tool: trace process termination by default

src/cc/frontends/b/lexer.h
There are warnings in lexer.h:
> .../iovisor/bcc/src/cc/frontends/b/lexer.h:54:35: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘const counter_type’ {aka ‘const int’} [-Wsign-compare]
54 |     for (size_t i = begin.line; i <= end.line; ++i)
=> fix: avoid -Wsign-compare warnings

man/man8/killsnoop.8, tools/killsnoop.py, tools/killsnoop_example.txt
I was recently using killsnoop to troubleshoot some weird signal behaviour and found that I had to run killsnoop over long periods of time in order to catch the behaviour. A problem I ran into was that filtering for signals I was looking for vs all other signals getting sent around in the system required either logging everything to a file and parsing from there, or running a forked version of killsnoop to filter on the signal.
This PR includes a change to allow optional filtering of the signal that is passed to kill() to help reduce noise in cases like this.
I haven't updated the examples as I'm not sure if this will be considered useful, but happy to do so if this gets the green light.
=> Add killsnoop arg for filtering on signal

src/cc/frontends/clang/b_frontend_action.cc
Fix issue #537.
The bcc rewriter does not have enough information to do
proper rewriting from:
```
#define PKT_LEN_ADD 1
ip->tlen += PKT_LEN_ADD;
```
to
```
bpf_dins_pkt(skb, (u64)ip+2, 0, 16, PKT_LEN_ADD);
```
So instead of generate incorrect code
which caused compilation error. Let return an error
earlier with helper comments so users know what to do.
With this patch, we will have
```
/virtual/main.c:20:17: error: cannot have macro at the end of expresssion,
workaround: put perentheses around macro "(MARCO)"
ip->tlen += PKT_LEN_ADD;
^
```
=> return failure if rewriter cannot rewrite properly

CMakeLists.txt, src/cc/export/helpers.h, src/cc/libbpf.c, src/python/bcc/__init__.py, tests/python/test_clang.py
Adding the 'lsm__' prefix check for loaded program
and set BPF_LSM_MAC as expected_attach_type if the 
program name matches.
This way we can load LSM programs via bcc interface.
The program attach can be done by existing kfunc API:
bpf_attach_kfunc
bpf_detach_kfunc
It will be used in upcomming bpftrace change that
adds lsm probes.
=> Adding support to load lsm programs

man/man8/offwaketime.8, tools/offwaketime.py, tools/offwaketime_example.txt
Since offwaketime is really an amalgamation of offcputime and wakeuptime
there is no reason why it shouldn't support the --state argument of the
former.
=> offwaketime: Add support for --state

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/cpudist.bpf.c, libbpf-tools/cpudist.c, libbpf-tools/cpudist.h, libbpf-tools/trace_helpers.c, libbpf-tools/trace_helpers.h
- Implement cpudist, which is consistent with https://github.com/iovisor/bcc/blob/master/tools/cpudist_example.txt
- Add a new helper `print_log2_hist` in `trace_helpers`
- Add a general dictionary (based on the glibc's binary search tree) in `trace_helpers`
- Add a bpf helper `bpf_log(l)` in `helpers.h`
- Add  `-Wno-unused-result` to CFLAGS to ignore warnings caused by `asprintf`.
=> libbpf-tools: add CO-RE cpudist

tools/biolatpcts.py
The travis-ci flags a python warning:
```
$ flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
./tools/biolatpcts.py:123:5: F821 undefined name 'die'
die()
^
1     F821 undefined name 'die'
```
Let us fix it with proper error message and then exit().
=> silence a python travis-ci warning

Dockerfile.ubuntu
modprobe and rmmod are used to load the kheaders module as a last option
when kernel headers are not found. The modprobe command is missing in the
docker image and scroipts are failing:
$ /usr/share/bcc/tools/execsnoop --mntnsmap /sys/fs/bpf/mnt_ns_set
sh: 1: modprobe: not found
Unable to find kernel headers. Try rebuilding kernel with CONFIG_IKHEADERS=m (module)
...
Signed-off-by: Mauricio Vásquez <mauricio@kinvolk.io>
=> Docker: add kmod dependency to docker container

tools/runqslower.py
This is a minor fix... I was using `runqslower` when I noticed that the help text indicated that the latency parameter was in milliseconds, when it's actually in microseconds. This change fixes that, and I also fixed a typo in that line while I was there.
=> Fix runqslower to indicate that the latency param is in microseconds.

src/cc/bcc_usdt.h, src/cc/usdt.h, src/cc/usdt/usdt.cc
While debugging a high memory consumption issue in bpftrace, I noticed
that a USDT::Context object can take ~10M per instance [0]. Along with
the new --usdt-file-activation feature in bpftrace
( https://github.com/iovisor/bpftrace/pull/1317 ), bpftrace can
potentially hold onto many dozens of USDT:Context instances, causing
memory issues.
While reducing the amount of memory USDT::Context uses is one option,
we can potentially side step it by allowing the usdt semaphore count to
be set independently. Before, the only way to increment the count (by 1)
is to call bcc_usdt_enable*(). bcc_usdt_enable*() has checks that limit
it to a single increment per context. The only way to decrement the
count is by calling bcc_usdt_close() which naturally only allows for
one decrement.
With independent …
=> usdt: Add helpers to set semaphore values

src/cc/usdt/usdt.cc
This makes bcc_usdt_addsem*() more consistent with the bcc_usdt_enable*()
interface where if a USDT::Context was not constructed with a pid the
semaphore enablement nops.
=> usdt: Have Context::addsem_probe() nop if pid not specified

src/python/bcc/__init__.py
Python 3 will complain about mixing strings and bytes in `os.path.join`
```sh
$ python3
Python 3.8.2 (default, Apr 27 2020, 15:53:34)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from bcc import BPF
>>> BPF.find_exe(b"bash")
File "<stdin>", line 1, in <module>
File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 281, in find_exe
exe_file = os.path.join(path, bin_path)
File "/usr/lib/python3.8/posixpath.py", line 90, in join
genericpath._check_arg_types('join', a, *p)
File "/usr/lib/python3.8/genericpath.py", line 155, in _check_arg_types
raise TypeError("Can't mix strings and bytes in path components") from None
TypeError: Can't mix strings and bytes in path components
```
Adding `encode()` should …
=> fix: encode path to bytes in python3

libbpf-tools/cpudist.c, libbpf-tools/drsnoop.c, libbpf-tools/execsnoop.c, libbpf-tools/execsnoop.h, libbpf-tools/filelife.c, libbpf-tools/filelife.h, libbpf-tools/opensnoop.c, libbpf-tools/runqslower.c, libbpf-tools/syscount.c, libbpf-tools/trace_helpers.c, libbpf-tools/trace_helpers.h, libbpf-tools/vfsstat.c, libbpf-tools/xfsslower.c
- extract `bump_memlock_rlimit` and put into `trace_helpers.c`
- extract `get_ktime_ns` and put into `trace_helpers.c`
- Resort struct's fields by alignment size instead of field size
=> libbpf-tools: refactor, move public methods to trace_helpers.c

docs/reference_guide.md
Fixes an incorrect link to kretfunc documentation section and fixes example to use proper macro
=> Fix typos in kretfunc documentation

docs/tutorial_bcc_python_developer.md, examples/tracing/sync_timing.py
As a new-person going through the tutorial myself, I thought it might be a little clearer to use the NULL macro in checks like these.  This could be accompanied by a _thing to learn_ in lesson four to the effect of:  _The verifier requires that pointer values derived from a map lookup must be checked for a null value before they can be dereferenced and used_
=> Explicitly use NULL macro in dref check

tools/dbstat.py, tools/klockstat.py
The current default value of interval (99999999999) in dbstat is too
high to be used in the sleep() function in python 3. I couldn't find a
authoritative source on the issue, but it seems the max value is
2^63/10^9 (9223372036). Anyway, 99999999 is the de facto standard for
a very big number here, so just use that. It's over 3 years, that
should be enough.
For consistency, I also change a couple of value in klockstat even
though they didn't overflow.
It fixes the following error:
$ dbstat mysql
Tracing database queries for pids  slower than 0 ms...
File "./dbstat", line 112, in <module>
sleep(args.interval)
OverflowError: timestamp too large to convert to C _PyTime_t
=> dbstat: fix overflowing timestamp

INSTALL.md
Recent changes in Alpine have made it possible to build bcc without ugly patches, so it seems like a good time to add the instructions here. I'm hopeful that the Python 3 caveats can be removed soon and that the tools will work out of the box on more systems. It should be fairly easy to get up and running, though.
=> Add install steps for Alpine Linux

examples/networking/xdp/xdp_drop_count.py, examples/networking/xdp/xdp_macswap_count.py, examples/networking/xdp/xdp_redirect_cpu.py, examples/networking/xdp/xdp_redirect_map.py, examples/tracing/nflatency.py, src/cc/frontends/clang/kbuild_helper.cc, tests/python/test_clang.py, tools/tcplife.lua, tools/tcplife.py, tools/tcpstates.py
On newer kernels, networking tools fail with `include/net/flow_offload.h:304:4: error: use of undeclared identifier 'KBUILD_MODNAME'`.
This patch adds a default compiler flag to define `KBUILD_MODNAME`, similar to https://github.com/iovisor/bpftrace/pull/716.
=> Fix KBUILD_MODNAME errors on newer kernels

src/cc/export/helpers.h
Fix issue #2976.
The LSM_PROBE program return value is fixed with value 0.
This is not correct. The return value is meaningful for
LSM_PROBE programs. Return proper value provided by the
bpf program itself.
=> fix LSM_PROBE return value

docs/reference_guide.md
This pull request adds documentation for LSM probes for `reference_guide.md`. The documentation describes how to use the `LSM_PROBE` macro, provides example usage, and describes what kernel configuration options need to be set in order for LSM probes to work properly.
=> Add LSM probe documentation

libbpf-tools/syscount.bpf.c
It causes build failure on my system due to trying to include GCC-specific
header. It doesn't seem to be necessary, though, so remove it.
=> libbpf-tools: remove unnecessary header include from syscount.bpf.c

src/python/bcc/__init__.py
I neglected to add cleanup logic for LSM probes in #2979. This patch fixes the mistake.
=> Add missing LSM probe cleanup

src/cc/frontends/clang/b_frontend_action.cc
Currently, bcc rewriter uses bpf_probe_read_kernel() for implicitly specified
kernel memory read. This is not totally correct. Some user memory in kernel
data structure may be accessed. bpf_probe_read_kernel() may fail with
later kernels. Let us revert back to old bpf_probe_read().
=> bpf: use bpf_probe_read in implicitly generated kernel mem read

docs/kernel-versions.md, src/cc/libbpf.c
kernel-versions.md lists ringbufs as being supported in 5.7+. They are in fact supported in **5.8+**. This pull request changes it to 5.8 and adds an entry for the ringbuf map itself.
=> [Documentation] Fix kernel version for ringbuf and add ringbuf to maps table

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/bitesize.bpf.c, libbpf-tools/bitesize.c, libbpf-tools/bitesize.h, libbpf-tools/bits.bpf.h, libbpf-tools/cpudist.bpf.c
- Based on https://github.com/iovisor/bcc/blob/master/tools/bitesize.py, add a comm filter.
- Extract `log/log2` into a BPF-only helper header `bits.bpf.h`.
=> libbpf-tools: add CO-RE bitesize

tools/vfsstat.py
After #2978, `vfsstat.py` causes verifier to complain due to missing return values from `KFUNC_PROBE`s. This pull request adds explicit return values to these BPF programs.
=> Fix KFUNC_PROBE calls in vfs_stat.py by adding a return value

src/cc/api/BPF.h, src/cc/api/BPFTable.h, src/cc/export/helpers.h, src/cc/frontends/clang/b_frontend_action.cc, src/cc/libbpf.c, src/cc/libbpf.h, tests/cc/CMakeLists.txt, tests/cc/test_queuestack_table.cc
This PR aims to introduce helpers to declare Queue/Stack maps. I have supported also
the creation of shared/public/pinned ones, as for the "traditional" tables.
In clang frontend I have added both declaration of maps type/queue, type/stack and all the operations
supported so far by these new maps (push/pop/peek).
Possible declarations introduced:
* BPF_QUEUESTACK(<"queue"/"stack">, <name>, <leaf_type>, <max_entries>, \<flags>)
* BPF_QUEUESTACK_SHARED(...)
* BPF_QUEUESTACK_PINNED(...)
* BPF_QUEUESTACK_PUBLIC(...)
* BPF_QUEUE(\<name>, <leaf_type>, <max_entries>)
* BPF_QUEUE(\<name>, <leaf_type>, <max_entries>, \<flags>)
* BPF_STACK(\<name>, <leaf_type>, <max_entries>)
* BPF_STACK(\<name>, <leaf_type>, <max_entries>, \<flags>)
Signed-off-by: Simone Magnani <simonemagnani.96@gmail.com> …
=> Introducing Queue/Stack helpers and clang frontend

tools/memleak.py
memleak -p PID will failed on Android
https://android.googlesource.com/platform/bionic/+/master/libc/bionic/malloc_common.cpp#196
=> valloc and pvalloc is deprecated in bionic on Android

src/cc/bcc_elf.c
Paths that are passed to find_debug_via_symfs often start with /proc/PID/root/
prefix which is followed by actual path. This breaks symfs symbol resoultion.
Symfs directory usually does not contain proc subdirectory and subdirectories
for each pid.
Here are examples of stack traces I got when tracing dlopen on Android before:
```
7acc558ef8 dlopen+0 (/system/lib64/libdl.so)
7a2222f988 EglThreadState::GetProcAddress(char const*)+64 (/vendor/lib64/egl/libGLESv2_adreno.so)
7ac8e3ecbc eglGetProcAddress+540 (/system/lib64/libEGL.so)
7acb824a58 GrGLMakeAssembledGLESInterface(void*, void (* ()(void, char const*))())+8136 (/system/lib64/libhwui.so)
7acb83a9b0 GrGLCreateNativeInterface()+48 (/system/lib64/libhwui.so)
7acb63443c 0x7acb63443c ([unknown])
7acb9cd33c 0x7acb9cd33c ([unknown]) …
```
=> Fix symbol resolution via symfs

docs/reference_guide.md, docs/tutorial_bcc_python_developer.md, examples/lua/kprobe-latency.lua, examples/tracing/bitehist.py, examples/tracing/disksnoop.py, tools/biosnoop.lua, tools/biosnoop.py, tools/biotop.py, tools/old/biosnoop.py
Starting from kernel version 5.8.0, the block layer function "blk_account_io_completion" is not available anymore as kprobe attach function. This makes errors occur when running some of the BCC tools and examples in kernel version >= 5.8.0. Therefore, we propose to use function "blk_account_io_done" instead in every kprobe attachment, because this function is compatible to previous kernel versions.  
This pull request changes "blk_account_io_completion" to "blk_account_io_done" at everywhere the former function occurs, including the doc files.
=> Replace kprobe function "blk_account_io_completion"

man/man8/memleak.8, tools/memleak.py, tools/memleak_example.txt
Profiling in memory part is hard to be accurate because of BPF infrastructure.
memleak keeps misjudging memory leak on the complicated environment which has
the action of free in hard/soft irq.
For example, in my misjudged case:
640 bytes in 10 allocations from stack
--
__kmalloc+0x178 [kernel]
__kmalloc+0x178 [kernel]
xhci_urb_enqueue+0x140 [kernel]
usb_hcd_submit_urb+0x5e0 [kernel]
This result looks like kernel doesn't free urb_priv. However, it's not true.
The reason for this leak is because xhci hw irq interrupts during the BPF program.
BPF program is not finished on that CPU, and xhci_irq() will call xhci_urb_free_priv()
before the end. But the kernel doesn't permit this isr to go into BPF program again.
Because BPF infrastructure(trace_call_bpf) denied this action.
So we miss this …
=> memleak: Add workaround to alleviate misjudgments when free is missing

src/python/bcc/libbcc.py, src/python/bcc/perf.py
`bcc.libbcc.bcc_symbol_option` class defined at `libbcc.py` is different from the structure defined at `bcc_syms.h`
The former lacks of `.lazy_symbolize` field. So, the field is added to the class.
And also `perf_event_attr` defined at `perf.py` is different from the structure defined at `vmlinux.h`
So, missing fields are added to the class.
=> Add .lazy_symbolize field to bcc_symbol_option

docs/reference_guide.md, src/python/bcc/__init__.py, src/python/bcc/table.py, tests/python/CMakeLists.txt, tests/python/test_queuestack.py
This pull request adds Python API support for #2993. It also adds documentation for BPF and Python APIs.
Changes:
- added QueueStack table type
- small changes to BPF.get_table() make QueueStack work properly
- added documentation
- added unit tests for Python API
=> Add Python API and documentation for Queue/Stack Tables

src/cc/frontends/clang/b_frontend_action.cc, src/cc/frontends/clang/b_frontend_action.h
Commit f579bf8d60c8 ("bpf: use bpf_probe_read in implicitly
generated kernel mem read") unconditionally use bpf_probe_read()
for implicit kernel memory read in bpf programs.
This won't work for s390 with recent kernels since s390 has
overlap user/kernel addresses and bpf_probe_read() is not
available any more.
This patch partially reverted Commit f579bf8d60c8 such
that for s390, bpf_probe_read_kernel() will be used
while other architectures bpf_probe_read() is used.
=> use bpf_probe_read_kernel for implicit kernel mem read on s390

tests/cc/test_queuestack_table.cc
This PR fixes the Kernel version check in test_queuestack_table.cc .
The correct one, as discussed in #3013, is 4.20 (not 5.0).
Signed-off-by: Simone Magnani <simonemagnani.96@gmail.com>
=> fix cc queue/stack test kernel version

docs/reference_guide.md
Update the reference_guide to spell out for implicit
kernel memory access, when rewriter uses bpf_probe_read()
(for non-s390) and when using bpf_probe_read_kernel()
(for s390).
=> update reference_guide for implicit kmem access rewriting

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/biolatency.bpf.c, libbpf-tools/biolatency.c, libbpf-tools/biolatency.h, libbpf-tools/blk_types.h
- implement [biolatency](https://github.com/iovisor/bcc/blob/master/tools/biolatency.py) with `BTF_PROG_TYPE_TRACING` instead of `kprobes`
- extract string filter to `bits.bpf.h`
- modify makefile to add *bpf.h as *.bpf.o's dep for re-build detection
=> libbpf-tools: add CO-RE biolatency

man/man8/tcpconnect.8
Add -u and -U options to the synopsis.
Move their description frome the example to the description section.
Add a description to --mntnsmap option.
=> man: fix tcpconnect man page

docs/reference_guide.md, examples/tracing/hello_perf_output_using_ns.py
This PR completes the work done for [PID filtering issues when running bpf script inside container ](https://github.com/iovisor/bcc/issues/1329).
- Added  bpf_get_ns_current_pid_tgid helper to developer reference documentation. 
- Added example cloning hello_perfoutput.py as hello_perfoutput_using_ns.py replacing  bpf_get_current_pid_tgid() with the new helper  bpf_get_ns_current_pid_tgid().
=> Add example for new helper bpf_get_ns_current_pid_tgid() to documentation.

libbpf-tools/maps.bpf.h, libbpf-tools/tcpconnect.bpf.c, libbpf-tools/tcpconnect.c
On ubuntu 18.04, I got several compile errors, so I did this fix up.
1.  Use `asm-generic/error.h` instead of `error.h` to fix error:
> /usr/include/linux/errno.h:1:10: fatal error: 'asm/errno.h' file not found
2. Initial global vals to fix errors, eg:
> libbpf: invalid relo for 'filter_ports_len' in special section 0xfff2; forgot to initialize global var?..
> Error: failed to open BPF object file: 0
> Makefile:66: recipe for target '.output/tcpconnect.skel.h' failed
3. Ignore `EINTR` error info, eg: after `Ctrl-C` I got
> Error polling perf buffer: -4
=>  libbpf-tools: fix tcpconnect compile errors

man/man8/trace.8, tools/trace.py, tools/trace_example.txt
Offset support for kprobes and uprobes are provided by the API of the BCC. However the tools/trace.py currently has no support for invoking that.
This modification let the user define the offset where the kprobe or uprobe should be injected. The format is simple: `func_name+offset` where the offset could be decimal (objdump like) or hexadecimal.
This modification let the trace user to read register values in the middle of the function (#2150) or access the correct callstack where the base pointer already set (#2555) (both after manual assembly analysis, this patch dont support the variable name resolution nor function prologue analysis of the binary)
=> Offset support for uprobe and kprobe in tools/trace.py

src/cc/CMakeLists.txt
add_definitions seems to be trying to misparsing the arguments in LLVM_DEFINITIONS in any of them has an equal sign in. I ran into the problem with `-D_GLIBCXX_USE_CXX11_ABI=0`.
separate_arguments turns LLVM_DEFINITIONS into a cmake list and add_compile_options adds the items in the list to the compiler options without trying to do any additional parsing. This fixed my build problem.
=> Fixes a problem when LLVM_DEFINITIONS contains a definition with an `=`

libbpf-tools/tcpconnect.c, libbpf-tools/tcpconnect.h
The __int128 is not defined for 32-bit platforms, see [1], so replace it by
a portable array of __u8.
The usage of this type came from the original tcpconnect.py, and __int128 is
still used in most (if not all) original BCC tools to store IPv6 addresses.
[1] https://github.com/iovisor/bcc/issues/3044
Signed-off-by: Anton Protopopov <a.s.protopopov@gmail.com>
=> libbpibbpf-tools: fix tcpconnect types usage

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/readahead.bpf.c, libbpf-tools/readahead.c, libbpf-tools/readahead.h
The output looks like:
```sh
Tracing fs read-ahead ... Hit Ctrl-C to end.
^C
Readahead unsued/total pages: 96/473288
msecs               : count    distribution
0 -> 1          : 473191   |****************************************|
2 -> 3          : 1        |                                        |
```
=> libbpf-tools: add CO-RE readahead

libbpf-tools/tcpconnlat.c, libbpf-tools/tcpconnlat.h
As https://github.com/iovisor/bcc/pull/3051  and https://github.com/iovisor/bcc/issues/3044  mentioned 
> The __int128 is not defined for 32-bit platforms, see [1], so replace it bya portable array of __u8.
so fix this as @aspsk did.
=> libbpf-tools: fix tcpconnlat types usage

src/python/bcc/__init__.py
The trampoline support check in bcc does not work properly,
so the feature is detected even on architectures that do not
support it - all archs other than x86_64.
We are checking for bpf_trampoline_link_prog to exist in
kernel, which works fine on x86_64 to check if the feature
is supported, but it's global function, so it exists also
in other archs even when the feature is not supported
so it returns True also on other archs.
Adding explicit x86_64 check to support_kfunc function.
=> Forbid trampolines for archs other than x86_64

man/man8/funccount.8, tools/funccount.py, tools/funccount_example.txt
A typical case of this feature: count timer setting on a x86 server
for each CPU:
for i in `seq 0 39`;
do ./funccount.py -i 1 lapic_next_deadline -d 5 -c $i;
done
Then we can know the timer setting is balanced of not and do some
futher work.
=> tools/funccount: support funccount on specified CPU

src/python/bcc/__init__.py
You can use
b.attach_perf_event(ev_type=PerfType.RAW, ...)
to attach perf raw event for profiling.
Signed-off-by: Edward Wu <edwardwu@realtek.com>
=> Extend PerfType members

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/biostacks.bpf.c, libbpf-tools/biostacks.c, libbpf-tools/biostacks.h, libbpf-tools/trace_helpers.c, libbpf-tools/trace_helpers.h
```sh
etcd           12849  sda
bpf_prog_df594d080d725b41_fentry__blk_account_io_start
bpf_prog_df594d080d725b41_fentry__blk_account_io_start
bpf_trampoline_38122
blk_account_io_start
generic_make_request
submit_bio
ext4_io_submit
ext4_writepages
do_writepages
__filemap_fdatawrite_range
file_write_and_wait_range
ext4_sync_file
vfs_fsync_range
do_fsync
__x64_sys_fdatasync
do_syscall_64
entry_SYSCALL_64_after_hwframe
16 -> 31         : 0        | …
```
=> libbpf-tools: add CO-RE biostacks

src/python/bcc/__init__.py
Some data may be left in the trace buffer, and the format cannot be
parsed by trace_fields(), which whill cause an abnormality in the
system.
Re-running the program cannot solved, only restart kernel.
Call trace:
File "/usr/lib/python2.7/site-packages/kwaibcc/__init__.py", line 1273, in trace_fields
pid, cpu, flags, ts = line[:ts_end].split()
ValueError: need more than 2 values to unpack
Prevent problems with exception handling.
Signed-off-by: Chen Guanqiao <chen.chenchacha@foxmail.com>
=> fix the exits abnormal due to trace buffer

tests/cc/test_usdt_args.cc
Fixes #3077
Signed-off-by: Rafael Fonseca <r4f4rfs@gmail.com>
=> tests: only run arg parser test on supported arches

tools/memleak.py
memleak tool reports a failed allocation as a leak,
because the NULL address is never freed.
Signed-off-by: Amir Goldstein <amir73il@gmail.com>
=> memleak: fix false positive on failed allocations

man/man8/tcprtt.8, tools/tcprtt.py, tools/tcprtt_example.txt
This program traces TCP RTT(round-trip time) to analyze the quality of
network, then help us to distinguish the network latency trouble is
from user process or physical network.
=> tools/tcprtt: add tcprtt to trace the RTT of TCP

README.md, man/man8/swapin.8, man/man8/tcpsynbl.8, man/man8/threadsnoop.8, tools/swapin.py, tools/swapin_example.py, tools/tcpsynbl.py, tools/tcpsynbl_example.txt, tools/threadsnoop.py, tools/threadsnoop_example.txt
I selected a few bpftrace tools from BPF Performance Tools to port to bcc and include, as they covered some missing visibility for real world issues.
I don't think it's appropriate to port any more or many more over: every bcc tool that gets created does not belong in bcc, as we'd end up with hundreds of unmaintained and broken tools, and intimidating clutter for the newcomer. bcc should have the top 100 most useful tools.
The full set of book tools is in its own repository: https://github.com/brendangregg/bpf-perf-tools-book
=> Selected tools from BPF Performance Tools

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/hardirqs.bpf.c, libbpf-tools/hardirqs.c, libbpf-tools/hardirqs.h
The output looks like: 
```
Tracing hard irq event time... Hit Ctrl-C to end.
^C
HARDIRQ                    TOTAL_usecs
nvme0q1                             33
ens33                               18
ahci[0000:02:05.0]                  76
nvme0q5                             17
nvme0q13                            14
nvme0q2                             31
nvme0q4                             61
nvme0q7                             16
```
```
Tracing hard irq event time... Hit Ctrl-C to end.
^C
HARDIRQ                    TOTAL_count
nvme0q1                              3
nvme0q5                              1
nvme0q4                              3
nvme0q7                              4
ens33                                4
nvme0q3                              3
nvme0q13 …
```
=> libbpf-tools: add hardirqs

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/softirqs.bpf.c, libbpf-tools/softirqs.c, libbpf-tools/softirqs.h
```
Tracing soft irq event time... Hit Ctrl-C to end.
16:34:08
SOFTIRQ          TOTAL_usecs
timer                    168
net_rx                  1251
tasklet                   22
sched                   1005
rcu                      212
```
Or
```
Tracing soft irq event time... Hit Ctrl-C to end.
softirq = timer
0 -> 1          : 152      |****************************************|
2 -> 3          : 20       |*****                                   |
4 -> 7          : 7        |*                                       |
softirq = net_rx
4 -> 7          : 0        | …
```
=> libbpf-tools: add softirqs

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/runqlen.bpf.c, libbpf-tools/runqlen.c, libbpf-tools/runqlen.h, libbpf-tools/trace_helpers.c, libbpf-tools/trace_helpers.h
The output looks like:
`./runqlen -C 1 1`
```
Sampling run queue length... Hit Ctrl-C to end.
cpu = 0
runqlen       : count     distribution
0          : 0        |                                        |
1          : 94       |****************************************|
2          : 5        |**                                      |
cpu = 1
runqlen       : count     distribution
0          : 61       |****************************************|
1          : 38       |************************                |
cpu = 2
runqlen       : count     distribution
0          : 41       |****************************            |
1          : 58       |****************************************|
cpu = 3
runqlen       : count     distribution
0          : 42       |***************************** …
```
=> libbpf-tools: add runqlen

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/numamove.bpf.c, libbpf-tools/numamove.c
With test workloads, the output looks as below:
```
TIME          NUMA_migrations NUMA_migrations_ms
02:54:41                31576                  0
02:54:42                31705                  0
02:54:43                31450                  3
02:54:44                31572                  0
02:54:45                30984                  0
02:54:46                31543                  0
02:54:47                31686                  1
02:54:48                31593                  0
02:54:49                31530                  4
02:54:50                31322                 11
02:54:51                31710                  0
02:54:52                31675                  0
02:54:53                31622                  2
02:54:54                31630                  4
``` …
=> libbpf-tools: add numamove

examples/tracing/strlen_hist_ifunc.py
Already there is strlen_hist.py as a nice example of uretprobe. But it can
not work correctly if strlen is indirect function(IFUNC). So
strlen_hist_ifunc.py is introduced to show how to use uprobe/uretprobe for
indirect functions.
=> Add uretprobe example for indirect function

README.md, man/man8/readahead.8, tools/readahead.py, tools/readahead_example.txt
This tool provides two read-ahead cache statistics to understand the read-ahead cache performance for the system:
-  Number of pages in the cache which are left unaccessed
-  Age of pages in the cache along with their count presented as a histogram 
This tool is based on the `readahead` example in @brendangregg 's BPF Performance Tools Book.
=> tool: add readahead bcc tool

tools/funclatency.py, tools/funclatency_example.txt
the tool funclatency does not provide average latency of function traced. 
add avg latency and output like this:
```
Tracing 1 functions for "do_sys_open"... Hit Ctrl-C to end.
^C     usecs               : count     distribution
0 -> 1          : 91       |*************************************   |
2 -> 3          : 32       |*************                           |
4 -> 7          : 98       |****************************************|
8 -> 15         : 3        |*                                       |
16 -> 31         : 1        |                                        |
avg = 3 usecs, total: 773 usecs, count: 225
=> add average function latency

tools/slabratetop.py
The following kernel commit moves struct memcg_cache_params from
include/linux/slab.h to mm/slab.h.
commit 9adeaa226988b97bc15928e12f40a9863134467c
Author: Waiman Long <longman@redhat.com>
Date:   Mon Sep 23 15:33:49 2019 -0700
mm, slab: move memcg_cache_params structure to mm/slab.h
The memcg_cache_params structure is only embedded into the kmem_cache of
slab and slub allocators as defined in slab_def.h and slub_def.h and used
internally by mm code.  There is no needed to expose it in a public
header.  So move it from include/linux/slab.h to mm/slab.h.  It is just a
refactoring patch with no code change.
...
The commit is in kernel v5.4, causing a compiler error when including
slub_def.h or slab_def.h in slabratetop's bpf program.
Add an empty definition of the struct in slabratetop's …
=> slabratetop: Add memcg_cache_params struct def

tools/tcpdrop.py
For v6 connections, tcpdrop.py would report the source and destination addresses swapped - tcp_drop() covers the input path, where the source of the received packet is the daddr stored in the socket.  The destination of the received packet is the local address. This commit swaps them to be correct and leaves a comment since it is not obvious (they can be removed).
=> Fix tcpdrop v6 source (remote) and dest (local) address

tools/tcptracer.py
On IPv6, tcptracer ports always appears as zeros:
Tracing TCP established connections. Ctrl-C to end.
T  PID    COMM             IP SADDR            DADDR            SPORT  DPORT
X  7055   nc               4  127.0.0.1        127.0.0.1        49476  9999
C  7074   nc               4  127.0.0.1        127.0.0.1        49478  9999
X  7074   nc               4  127.0.0.1        127.0.0.1        49478  9999
C  7085   nc               6  [::]             [0:0:0:1::]      0      0
X  7085   nc               6  [::]             [0:0:0:1::]      0      0
C  7086   nc               6  [::]             [0:0:0:1::]      0      0
This seems related to alignment issue wrt to the __int128 type in
tcp_ipv6_event_t structure. Moving the u8 field ip to the end of the
structure fixes the issue.
Fixes #2781
=> tools: tcptracer: fix alignement in tcp_ipv6_event_t

docs/reference_guide.md, examples/cpp/CMakeLists.txt, examples/cpp/SkLocalStorageIterator.cc, examples/cpp/TaskIterator.cc, src/cc/export/helpers.h, src/cc/libbpf.c, src/cc/libbpf.h
bpf iterator is introduced in linux kernel 5.8.
https://lore.kernel.org/bpf/20200509175859.2474608-1-yhs@fb.com/
In 5.8, iterator support for task, task_file, bpf_map, netlink_sock
and ipv6_route. In 5.9, tcp, udp and hash/array/sk_local_storage
map iterators are implemented.
This patch added necessary interface to support bpf_iter in bcc.
A few C++ APIs are added to bcc. Two bpf_iter examples,
task and sk_local_storage_map, are added to illustrate how
bpf iterator can be implemented. Python interface can be added
later if there is a need.
=> add C++ bpf_iter support

docs/reference_guide.md
https://github.com/iovisor/bcc/commit/5fe35766ac0e2860c7e6c1694a2338365e9497a6 missed a code closure and now the reference guide doesn't render well.
=> docs: Add missing code block closure

INSTALL.md
`bcc`, `bcc-tools`, and `python-bcc` were recently moved from the AUR to the official Arch repositories, so the installation instructions need to be updated.
I also removed the note about upgrading to kernel 4.3.1-1. The `linux-lts` package was upgraded from 4.1.21 to 4.4.7 by [this commit](https://github.com/archlinux/svntogit-packages/commit/20d5e134c5154161886d4f049811c9b30cd6544b#diff-3e341d2d9c67be01819b25b25d5e53ea3cdf3a38d28846cda85a195eb9b7203a) in April 2016. Considering that `linux-lts` trails behind the other Arch kernel packages (`linux`, `linux-zen`, `linux-hardened`), I think that any Arch installation that is still in use can be assumed to be on a kernel later than 4.3.1
=> Update installation instructions for Arch Linux

tests/python/test_usdt2.py
I test test_usdt2.py on aarch64 with kernel-5.9-rc5,
gcc-9.2.1 and glibc2.30.
with the current range of 3, always get failure:
======================================================================
FAIL: test_attach1 (__main__.TestUDST)
File "test_usdt2.py", line 170, in test_attach1
self.assertTrue(self.evt_st_6 == 1)
AssertionError: False is not true
Ran 1 test in 1.068s
FAILED (failures=1)
=> set larger range to get probes evnet for test_usdt2.py

libbpf-tools/runqlen.bpf.c, libbpf-tools/softirqs.bpf.c
Hello,
when building libbpf-tools with make I got the following error for runqlen:
```
BPF      runqlen.bpf.o
GEN-SKEL runqlen.skel.h
libbpf: invalid relo for 'hists' in special section 0xfff2; forgot to initialize global var?..
Error: failed to open BPF object file: Relocation failed
make: *** [Makefile:77: .output/runqlen.skel.h] Error 255
make: *** Deleting file '.output/runqlen.skel.h'
```
softirqs failed with similar errors:
```
BPF      softirqs.bpf.o
GEN-SKEL softirqs.skel.h
libbpf: invalid relo for 'counts' in special section 0xfff2; forgot to initialize global var?..
Error: failed to open BPF object file: Relocation failed
make: *** [Makefile:77: .output/softirqs.skel.h] Error 255
make: *** Deleting file '.output/softirqs.skel.h'
```
I've managed to fix the errors by initializing …
=> libbpf-tools: initialize global structs in runqlen and softirqs

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/llcstat.bpf.c, libbpf-tools/llcstat.c, libbpf-tools/llcstat.h
The output looks like below:
```
Running for 20 seconds or Hit Ctrl-C to end.
PID      NAME             CPU     REFERENCE         MISS    HIT%
1547     containerd       16          25000            0 100.00%
5810     kworker/u82:0    11           5000         5000   0.00%
0        swapper/22       22         255000        20000  92.16%
3387     kube-controller  27         220000        10000  95.45%
2263     node_exporter    23           5000            0 100.00%
23288    apiservice-kick  30          60000        15000  75.00%
40592    kubelet          19         120000        15000  87.50%
40443    etcd             5           75000         5000  93.33%
23099    kubectl          38          10000            0 100.00%
4467     node_exporter    8           95000        25000  73.68%
40130 …
```
=> libbpf-tools: add llcstat

tools/dirtop.py
Catch TypeError raised by Python3 glob and fall back to Python2 interface. Fixes #3137
=> Fix python2.7 support for dirtop tool

tools/netqtop.py, tools/tcprtt.py
Otherwise, we have:
...
File "bcc/tools/netqtop.py", line 54
print(hd.center(COL_WIDTH)),
^
TabError: inconsistent use of tabs and spaces in indentation
...
File "bcc/tools/tcprtt.py", line 117, in <module>
bpf_text = bpf_text.replace(b'LPORTFILTER', b'')
TypeError: replace() argument 1 must be str, not bytes
...
=> fix python3 compatible issue for netqtop and tcprtt tools

.github/workflows/bcc-test.yml, .github/workflows/publish.yml, .gitignore, Dockerfile.ubuntu, debian/control, scripts/build-deb.sh, scripts/docker/auth.sh, scripts/docker/build.sh, scripts/docker/push.sh, scripts/git-tag.sh
This enables pushing docker images to quay.io, but I will need to have github admin of iovisor/bcc become an admin of the quay repository, in order to add the necessary secret for this to push the images.
I believe this will be very useful, for projects that need an up-to-date image pulled from CI on github actions, and make it easy to bisect revisions, using the docker repo as an artifact repository. In addition to docker images (for distribution purposes only, really), this also publishes debian packages as part of a tarball in the github actions output https://github.com/dalehamel/bcc/actions/runs/311964261
This builds on  @alban 's approach of guarding the image build with a variable, but replaces the explicit variable by detecting if `QUAY_TOKEN` is present or absent. The generic …
=> Push additional build artifacts in CI

.github/workflows/publish.yml
I noticed that https://github.com/iovisor/bcc/runs/1284916926?check_suite_focus=true failed when #3141 was merged, because I missed the check on a step to upload the artifacts.
Please merge to fix CI @yonghong-song, sorry I missed this.
=> Guard artifact upload with environment variable

debian/control, scripts/docker/build.sh
Following up on #3141 I noticed that the debian builds are preferring the older versions of LLVM / clang rather than the newer ones.
It appears that this is because of the order in which they are specified in the debian control file. Debian's packaging system seems to just short circuit this conditional - the first one it finds that satisfies is what it uses.
Rather than specify the clang and LLVM packages in ascending order, this specifies them in descending order. This should prefer the newest available LLVM / clang for a given debian distribution.
Prior to this, bcc debian packages would be built (statically) linking to LLVM as follows:
- Ubuntu 16.04: LLVM 3.7
- Ubuntu 18.04: LLVM 6.0
- Ubuntu 20.04: LLVM 6.0
And with this change, bcc will be built with the following linkages:
- …
=> Llvm package order

src/python/bcc/table.py
Importing Abstract Base Classes (ABCs) from the collections module is [deprecated since Python 3.3](https://docs.python.org/3/library/collections.abc.html), it [emits a warning since Python 3.8](https://github.com/python/cpython/commit/c66f9f8d3909f588c251957d499599a1680e2320), and it will stop working in Python 3.10.
Try importing MutableMapping from collections.abc (the preferred way since Python 3.3) and, in case of error (Python < 3.3) fall back to importing it from collections.
This patch eliminates warnings in Python 3.8+ while preserving compatibility with Python < 3.3.
=> python: import ABCs from collections.abc

Dockerfile.tests, Dockerfile.ubuntu, INSTALL.md, man/man8/tcpconnect.8, scripts/bpf_demo.ks.erb, scripts/build-rpm.sh, tools/tcpconnect.py, tools/tcpconnect_example.txt
often i'd like to be able to track DNS domains that were associated with an IP at the time of connect.  So, I wired up a simple and hopefully low-overhead kprobe to udp_recvmsg that will capture DNS response packets and put them into a cache dictionary in user space.  When connect syscalls come in, then it will look for a corresponding DNS query in the cache.  It will also note the time delta between when the DNS response was received and when the connect happened.
This requires dnslib and expiringdict python packages.  dnslib is already required by an example in the bcc tree: https://github.com/iovisor/bcc/blob/b0bf04ac4042a6c004b15dcc5e40e12ae78020f9/examples/networking/dns_matching/dns_matching.py but I couldn't find anywhere to add these dependencies for a core tool.  Looking for help …
=> add DNS correlation to connect tracking

INSTALL.md
To compile the software on Ubuntu 20.04 I had trouble compiling the source because my OS is missing the `FlexLexer.h` library. This package is supplied by `libfl-dev`.
I'm not sure if this is the best approach for it but worked in my case.
OS Info:
```
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=20
DISTRIB_CODENAME=ulyana
DISTRIB_DESCRIPTION="Linux Mint 20 Ulyana"
NAME="Linux Mint"
VERSION="20 (Ulyana)"
VERSION_CODENAME=ulyana
UBUNTU_CODENAME=focal
```
=> docs(INSTALL): add libfl-dev to ubuntu dependencies

src/cc/api/BPF.cc, src/cc/api/BPF.h, src/cc/bcc_elf.c, src/cc/bcc_elf.h, src/cc/bcc_usdt.h, src/cc/libbpf.c, src/cc/libbpf.h, src/cc/usdt.h, src/cc/usdt/usdt.cc, tests/cc/CMakeLists.txt, tests/cc/test_usdt_probes.cc, tests/cc/usdt_test_lib.cc, tests/python/include/folly/tracing/StaticTracepoint-ELFx86.h, tests/python/include/folly/tracing/StaticTracepoint.h, tests/python/test_usdt.py, tests/python/test_usdt2.py, tests/python/test_usdt3.py
This argument allows callers to tell the kernel to manage USDT semaphore
counts. It's better than fiddling with the counts in userspace b/c if
the userspace program crashes then the semaphore count does not get
decremented.
It's also better b/c the kernel can activate the semaphore for all
processes that have the target mapped into memory. Currently with bcc,
you have to provide the pid of each process you want to activate a
semaphore for and then bcc will go poke /proc/pid/mem at the right
offset.
=> uprobe: Add ref_cnt_offset arg to bpf_attach_uprobe

debian/changelog
* Support for kernel up to 5.9
* usdt: add uprobe refcnt support
* use newer llvm/clang versions in debian packaging if possible
* add bpf iterator C++ support
* new bcc tools: tcprtt, netqtop, swapin, tcpsynbl, threadsnoop
* tcpconnect: add DNS correlation to connect tracking
* new libbpf-tools: llcstat, numamove, runqlen, runqlat, softirgs, hardirqs
* doc update, bug fixes and some additional arguments for tools
=> update debian changelog for release v0.17.0

src/cc/export/helpers.h, src/cc/frontends/clang/arch_helper.h, src/cc/frontends/clang/b_frontend_action.cc, src/cc/frontends/clang/loader.cc
Fix #3150
On x86_64, for syscalls, the calling convension is to use
r10 instead of rcx for the 4th parameter. I have verified this
with disassembling vmlinux codes.
https://www.systutorials.com/x86-64-calling-convention-by-gcc/
bcc previously used rcx for the 4th parameter for all cases.
This patch fixed the issue by using r10 for syscalls.
A macro PT_REGS_PARM4_SYSCALL() is also introduced in helpers.h
to access the 4th parameter for r10.
=> use correct arch register for the 4th param of x86_64 syscalls

src/cc/bpf_module.cc, src/cc/bpf_module_rw_engine.cc, src/cc/frontends/clang/b_frontend_action.cc
With latest llvm12 trunk, we got two compilation bugs.
Bug #1:
/home/yhs/work/bcc/src/cc/frontends/clang/b_frontend_action.cc:
In member function ‘void ebpf::BFrontendAction::DoMiscWorkAround()’:
/home/yhs/work/bcc/src/cc/frontends/clang/b_frontend_action.cc:1706:31:
error: ‘class clang::SourceManage’ has no member named ‘getBuffer’; did you mean ‘getBufferData’?
rewriter_->getSourceMgr().getBuffer(rewriter_->getSourceMgr().getMainFileID())->getBufferSize(),
^~~~~~~~~
getBufferData
This is due to upstream change https://reviews.llvm.org/D89394.
To fix, follow upstream examples in https://reviews.llvm.org/D89394.
Bug #2:
/home/yhs/work/bcc/src/cc/bpf_module.cc: In member function ‘int ebpf::BPFModule::finalize()’:
/home/yhs/work/bcc/src/cc/bpf_module.cc:470:11:
error: ‘class …
=> fix compilation issues with latest llvm12 trunk

tools/offcputime.py
When using non-folded output, some of the strings would
be printed as raw byte arrays on python3, like this:
b'finish_task_switch'
b'__schedule'
b'schedule'
b'worker_thread'
b'kthread'
b'ret_from_fork'
-                kworker/u16:1 (22022)
2267942
This commit updates the code to treat these as utf8 strings,
consistent with all the other strings printed from this tool.
=> tools/offcputime: Fix python3 string output

examples/cpp/CMakeLists.txt, examples/cpp/KFuncExample.cc
This patch added a kfunc/kretfunc C++ example to
show how the new trampoline based kprobe/kretprobe
can be used in C++ based applications.
=> add a C++ kfunc/kretfunc example

.github/workflows/publish.yml, Dockerfile.ubuntu
https://github.com/iovisor/bcc/pull/3128 broke the release process, as it tries to install packages that are not available on ubuntu xenial (16.04)
This should repair this problem by checking the version and not installing this libraries on ubuntu xenial
=> Drop ubuntu xenial support from release, it is EOL

docs/kernel-versions.md
sk_lookup programs allow intercepting socket lookup per namespace.
=> Add sk_lookup to kernel-versions.md

libbpf-tools/syscall_helpers.c
Fix the following warning when building libbpf-tools:
syscall_helpers.c: In function ‘init_syscall_names’:
syscall_helpers.c:63:2: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
63 |  fgets(buf, sizeof(buf), f);
|  ^~~~~~~~~~~~~~~~~~~~~~~~~~
We're not interested in the return value of the first call to fgets, because we
want to skip the first line and in the case of error it will be caught by the
following call to fgets. A funny note is that we can't say just "(void) f()" to
suppress the warning, so I wrote it as "(void) !!f()", which works.
Signed-off-by: Anton Protopopov <a.s.protopopov@gmail.com>
=> libbpf-tools: syscall_helpers: fix a warning

libbpf-tools/execsnoop.bpf.c
=> bcc/libbpf-tools: Fix user probe read references of execsnoop

tools/opensnoop.py
This is a workaround for #3190
=> tools/opensnoop: Use bpf_probe_read_user explicitly

README.md
The markup version of the readme that is displayed for the main page in this repo contains the following bad links:
Status code [404:NotFound] - Link: https://github.com/iovisor/bcc/blob/master/tools/swapin_example.txt
Status code [404:NotFound] - Link: https://github.com/iovisor/bcc/blob/master/tools/vfscount.c
Status code [404:NotFound] - Link: https://github.com/iovisor/bcc/blob/master/tools/vfsstat.c
@yonghong-song requested removing stale links. I was unable to find any actual matching files to link to so removed these.
However possible the vfsstat.c one could be re-adding pointing to "libbpf-tools/vfsstat.c" ??
Should resolve issue #3189
=> The README file in this repo has some bad links - [404:NotFound]

src/cc/frontends/clang/b_frontend_action.cc
I'm writing a tool that streams unstructured data. Tried to use ringbuf but sadly it's available only since 5.8, which I don't have running now :(
So I'm using `BPF_PERF_OUTPUT` and trying to pass an array like:
```
unsigned char buf[16] = ...;
output.perf_submit(ctx, buf, sizeof(buf));
```
but it crashes libbcc.
Now that I understand the issue, changing the code to use `&buf` avoids it, but I think it's worth fixing the crash anyway.
This commit adds the first use of the `getTypePtrOrNull` to bcc, I'm not sure in which LLVM version it was added, but I checked and it exists at least since [LLVM 3](https://github.com/llvm/llvm-project/blob/llvmorg-3.0.0/clang/include/clang/AST/Type.h#L505), which is old enough, I guess.
I tested `opensnoop` which makes use of the autogenerated perf data …
=> Fix perf_submit() calls with array arg1 crashing libbcc

tests/python/test_array.py
since glibc-2.31, the syscall of sleep is clock_nanosleep instead of
nanosleep
=> tests/test_array.py: add clock_nanosleep to attach point

tools/netqtop.c
Net device driver uses 'skb_record_rx_queue' to mark rx queue
mapping during receiving a packet. Also need to call
'skb_get_rx_queue' to get rx queue id.
=> tools/netqtop: fix rx queue id

docs/reference_guide.md, man/man8/biolatency.8, tools/biolatency.py, tools/biolatency_example.txt
In it's current form, storing the histogram data and analyzing the same for a large set of machines is difficult.
With this flag, it is possible to store the histogram as a dictionary/json file which can be imported easily to be analyzed with libraries like Pandas. 
```
{
0: 0, 
2: 0, 
4: 0, 
8: 0, 
16: 0, 
32: 0, 
64: 13, 
128: 44, 
256: 41, 
512: 14, 
1024: 27, 
2048: 1, 
4096: 10,  
8192: 0
}
```
```
[
{'interval-start': 0, 'interval-end': 1, 'count': 0}, 
{'interval-start': 2, 'interval-end': 3, 'count': 5}, 
{'interval-start': 4, 'interval-end': 7, 'count': 143}
]
```
```
{
'ts': '2020-12-30 14:49:37', 
'val_type': 'msecs', 
'data': 
[
{'interval-start': 0, 'interval-end': 1, 'count': 2}, 
{'interval-start': 2, 'interval-end': 3, 'count': 1}
], 
'flags': 'Sync-Write'
}
```
=> biolatency.py Add -j flag

docs/reference_guide.md, src/python/bcc/table.py, tools/biolatency.py
Refer to the conversation in PR: https://github.com/iovisor/bcc/pull/3196
=> Refactoring print_json_hist

src/cc/frontends/b/codegen_llvm.cc
With latest llvm trunk (llvm12), I hit the following compilation
error:
```
...
[ 17%] Building CXX object src/cc/frontends/b/CMakeFiles/b_frontend.dir/codegen_llvm.cc.o
/home/yhs/work/bcc/src/cc/frontends/b/codegen_llvm.cc: In member function
‘virtual ebpf::StatusTuple ebpf::cc::CodegenLLVM::visit_table_decl_stmt_node(ebpf::cc::TableDeclStmtNode*)’:
/home/yhs/work/bcc/src/cc/frontends/b/codegen_llvm.cc:1122:37:
error: ‘class llvm::Module’ has no member named ‘getTypeB yName’; did you mean ‘getName’?
StructType *decl_struct = mod_->getTypeByName("_struct." + n->id_->name_);
^~~~~~~~~~~~~
getName
```
This is due to llvm patch https://reviews.llvm.org/D78793 which
changed how to use getTypeByName(). This patch adjusted the usage
in bcc based on this patch.
Signed-off-by: Yonghong Song …
=> fix compilation error with latest llvm12 trunk

examples/cpp/CMakeLists.txt, examples/cpp/pyperf/CMakeLists.txt, src/cc/CMakeLists.txt, tests/cc/CMakeLists.txt
The current upstream split does not work very well, as the SONAME is mangled so
nothing recognises it. Applications link against libbcc, not libbcc_no_bpf.
Remove it entirely, and switch the libbcc.so to dynamically
link with libbpf if CMAKE_USE_LIBBPF_PACKAGE is set.
=> Remove libbcc-no-libbpf shared library, change libbcc linkage instead

src/cc/frontends/clang/b_frontend_action.cc
Found by valgrind.
```
Conditional jump or move depends on uninitialised value(s)
at 0xBABD86: ebpf::ProbeVisitor::IsContextMemberExpr(clang::Expr*) (b_frontend_action.cc:590) 
by 0xBA9CEB: ebpf::ProbeVisitor::assignsExtPtr(clang::Expr*, int*) (b_frontend_action.cc:263) 
by 0xBAAA9F: ebpf::ProbeVisitor::VisitBinaryOperator(clang::BinaryOperator*) (b_frontend_action.cc:410)
by 0xC15B29: clang::RecursiveASTVisitor<ebpf::ProbeVisitor>::WalkUpFromBinaryOperator(clang::BinaryOperator*) (StmtNodes.inc:181)
```
=> ProbeVisitor: Valgrind Conditional jump or move depends on uninitialised value(s)

tools/offcputime.py
I think the current `offcputime.py` counts not only events properly filtered in but also some events with short duration due to regressing value from `bpf_ktime_get_ns()`.
bcc version: latest on git
kernel version: CentOS7, 3.10.0-1127.18.2.el7
I was developing my own version of offcputime.py that produces events for each long offcpu event including duration of the task stayed off-cpu.
After getting some samples, I realized that in some cases duration (`u64 delta = bpf_ktime_get_ns() - *tsp`) is insanely large number and figured out that it is due to negative numbers printed as unsigned 64bit.
I thought there should be the same issue exists in `offcputime.py` and modified it as below:
```diff
diff --git a/tools/offcputime.py b/tools/offcputime.py
index 068c7076..11d8a4d8 100755
--- …
```
=> tools/offcputime Filter out negative offcpu duration

src/cc/frontends/clang/loader.cc
test_clang.py: test_jump_table will get failed with error messgae:
bpf: Failed to load program: Invalid argument
unknown opcode a0
processed 0 insns (limit 1000000) max_states_per_insn 0 total_states 0
peak_states 0 mark_read 0
HINT: The 'unknown opcode' can happen if you reference a global or
static variable, or data in read-only section. For example, 'char *p =
"hello"' will result in p referencing a read-only section, and 'char p[]
= "hello"' will have "hello" stored on the stack.
=> aarch64: turn off jump table optimization during jit compilation

examples/cpp/KModRetExample.cc, src/cc/api/BPF.cc, src/cc/api/BPF.h, src/cc/bpf_module.cc, src/cc/bpf_module.h, src/cc/export/helpers.h, src/cc/libbpf.c
Add support for tracing program with BPF_MODIFY_RETURN
attachment type. This is used for security oriented bpf
programs which can modify return values for certain
kernel functions:
- whitelisted for error injection by checking
within_error_injection_list including all syscalls.
- lsm security function (prefix "security_").
Also extended load_func() API to allow specify bpf program
is sleepable and this will permits to use some sleepable
helpers like bpf_copy_from_user() and d_path().
=> add support kfunc/modify_return bpf programs

cmake/FindLibBpf.cmake
On some distro, static libraries are shipped in a separate package.
Look for either a static or dynamic libbpf, and only fail if neither is found.
=> cmake: look for either static or dynamic libraries

tests/python/test_brb.py
If iperf is not installed or installed at a location that is not
in PATH as recgnized by Python, then 'test_brb' will fail while
test_brb2 success.
test_brb:
ERROR: test_brb (__main__.TestBPFSocket)
File "test_brb.py", line 200, in test_brb
nsp_server = NSPopenWithCheck(ns2_ipdb.nl.netns, ["iperf", "-s", "-xSC"])
File "/root/rpmbuild/BUILD/bcc/tests/python/utils.py", line 63, in __init__
has_executable(name)
File "/root/rpmbuild/BUILD/bcc/tests/python/utils.py", line 18, in has_executable
raise Exception(name + ": command not found")
Exception: iperf: command not found
Ran 1 test in 2.546s
FAILED (errors=1)
test_brb2:
CRITICAL:root:WARNING! Test test_brb (__main__.TestBPFSocket) failed, but marked as passed because it is decorated with @mayFail. …
=> Fix freezing of 'test_brb' if iperf is not found

tests/lua/test_standalone.sh
[root@openEuler bcc]# cd src/lua/
[root@openEuler lua]# ./bcc-lua ../../../examples/lua/offcputime.lua -d 1 >/dev/null 2>/dev/null
[root@openEuler lua]# ./bcc-lua ../../../examples/lua/offcputime.lua -d 1
./bcc-lua: cannot open ../../../examples/lua/offcputime.lua: No such file or directory
stack traceback:
[C]: in function 'dofile'
bcc.lua:6338: in function <bcc.lua:6288>
[C]: at 0x557532f676b0
[root@openEuler lua]#
=> correct the path of offcputime.lua

tests/cc/test_cg_storage.cc
The BPF_MAP_TYPE_PERCPU_CGROUP_STORAGE type is only supported in the version of the kernel >=4.20, causing the bpf_init function failed on the low kernel version.
test/cc/test_cg_storage.cc
`TEST_CASE("test percpu cgroup storage", "[percpu_cgroup_storage]") {
{
const std::string BPF_PROGRAM = R"(
BPF_PERCPU_CGROUP_STORAGE(cg_storage1, long long);
BPF_PERCPU_CGROUP_STORAGE(cg_storage2, long long);
int test(struct bpf_sock_ops *skops)
`
after modify, the test case can be executed successfully :
3/43 Test  #3: test_libbcc ......................   Passed   18.58 sec
Start  4: test_libbcc_no_libbpf
4/43 Test  #4: test_libbcc_no_libbpf ............   Passed   18.46 sec
Start  5: py_test_stat1_b
=> test:Fix the test_libbcc/test_libbcc_no_libbpf testcase failure when the kernel version is lower than 4.20

libbpf-tools/Makefile
We plan to put those tools in separate rpm, so we need a way to install them.
Adding install target with standard DESTDIR and prefix make variables.
=> Add install target to libbpf-tools

CMakeLists.txt
Meet the following compiler error:
/mnt/trace-tools/eBPF/bcc/src/cc/frontends/clang/b_frontend_action.cc:
In member function bool
ebpf::BTypeVisitor::VisitVarDecl(clang::VarDecl*):]
/mnt/trace-tools/eBPF/bcc/src/cc/frontends/clang/b_frontend_action.cc:1449:18:
error: BPF_MAP_TYPE_RINGBUF was not declared in this scope; did you mean
BPF_MAP_TYPE_QUEUE?
1449 | map_type = BPF_MAP_TYPE_RINGBUF; | ^~~~~~~~~~~~~~~~~~~~ |
BPF_MAP_TYPE_QUEUE
make[2]: ***  [src/cc/frontends/clang/CMakeFiles/clang_frontend.dir/build.make:95:
rc/cc/frontends/clang/CMakeFiles/clang_frontend.dir/b_frontend_action.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1065: src/cc/frontends/clang/CMakeFiles/clang_frontend.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
This because, submodule libbpf can't sync when do …
=> cmake: sync submodule libbpf when do cmake.

libbpf-tools/readahead.bpf.c, libbpf-tools/readahead.c
Fix readahead, support 5.10+ kernel,  mentioned in https://github.com/iovisor/bcc/issues/3224
=> libbpf-tools: fix readahead, support v5.10+ kernel

docs/reference_guide.md
Hello! I'm new to `BPF_TABLE` and its variants and found their relationships are not clearly explained in the reference. So I'd like to add some docs about it.
=> docs/reference_guide.md: explain the relationship between BPF_TABLE and its wrapper macros

docs/tutorial_bcc_python_developer.md
I'm not familiar with the kernel, I just looked these commits up and was confused by the mention that the bug is still not fixed.
Apparently that kernel bug is fixed in 4.8-rc3 and what broke there is fixed in 4.8.10
according to https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.8.10
mentioned as:
bpf: fix htab map destruction when extra reserve is in use
Fixes: a6ed3ea65d98 ("bpf: restore behavior of bpf_map_update_elem")
=> Mention kernel version which fixed the bug

src/cc/api/BPF.cc
It was something like: "Unable to enable USDT %sprovider:probe from binary  PID 1234 for
probe handle_probe".
=> fix a typo in error messages in BPF::attach_usdt()

tools/slabratetop.py
slabtoprate fails on 5.10 kernels because of a missing kasan_reset_tag
declaration. We need to include the kasan header file.
Fixes the following error:
In file included from /virtual/main.c:12:
include/linux/slub_def.h:181:27: warning: implicit declaration of function 'kasan_reset_tag' is invalid in C99 [-Wimplicit-function-declaration]
return reciprocal_divide(kasan_reset_tag(obj) - addr,
^
include/linux/slub_def.h:181:48: error: invalid operands to binary expression ('int' and 'void *')
return reciprocal_divide(kasan_reset_tag(obj) - addr,
~~~~~~~~~~~~~~~~~~~~ ^ ~~~~
1 warning and 1 error generated.
File "/usr/share/bcc/tools/slabratetop", line 115, in <module>
File "/usr/lib/python3.9/site-packages/bcc/__init__.py", line 364, …
=> tools: include kasan header in slabtoprate

src/cc/frontends/clang/b_frontend_action.cc
Commit 12107c6936c6 ("use correct arch register for the
4th param of x86_64 syscalls") tries to use proper syscall
specific registers on x86_64 as its 4th param for syscall
is different from non-syscall. Unfortunately, the
implementation also uses syscall arch. register
for non-syscall kernel functions, which is incorrect.
This patch fixed the issue by using syscall arch
registers only for syscalls.
Reported-by: zhenwei pi <pizhenwei@bytedance.com>
Fixes: 12107c6936c6 ("use correct arch register for the 4th param of x86_64 syscalls")
=> fix incorrect arch register use for kprobe func with more parameters

src/cc/frontends/b/loader.cc
When building with c++14, `std::make_unique` is available. This surfaces a bug in the code whereby the `src/cc/frontends/b/loader.cc` breaks like:
```
FAILED: src/cc/frontends/b/CMakeFiles/b_frontend.dir/loader.cc.o 
/home/myuser/mason/mason_packages/linux-x86_64/llvm/11.0.0/bin/clang++    -fPIC -stdlib=libc++ -std=c++14 -Wall  -fno-rtti -fPIC -DBCC_PROG_TAG_DIR='"/var/tmp/bcc"' -DLLVM_MAJOR_VERSION=11 -O3 -DNDEBUG -I/home/myuser/mason/mason_packages/linux-x86_64/llvm/11.0.0/include/../tools/clang/include -I../src -Isrc -Isrc/cc -I../src/cc -Isrc/cc/frontends/b -I../src/cc/frontends/b -I../src/cc/frontends/clang -I/home/myuser/mason/mason_packages/linux-x86_64/llvm/11.0.0/include -I/home/myuser/mason/mason_packages/linux-x86_64/elfutils/0.170/include -I../src/cc/compat    -D_GNU_SOURCE …
```
=> Fix compile error: call to 'make_unique' is ambiguous

README.md, man/man8/virtiostat.8, tools/virtiostat.py, tools/virtiostat_example.txt
Add a new tool virtiostat to trace VIRTIO devices IO statistics.
Although we have already had iostat(to show block device statistics),
iftop(to show network device statistics), other devices of VIRTIO
family(Ex, console, balloon, GPU and so on) also need tools for each
type. virtiostat works in virtio lower layer, and it could trace all
the devices.
=> tools/virtiostat: add virtiostat tool

docs/reference_guide.md, src/cc/libbpf.c, src/python/bcc/libbcc.py, src/python/bcc/table.py, tests/python/CMakeLists.txt, tests/python/test_map_batch_ops.py
After a discussion with @yonghong-song in PR https://github.com/iovisor/bcc/pull/3173 , I have added the support of batch lookup and delete.
In bcc, I have added items_lookup_and_delete_batch(). Feel free to propose a better name.
Batch works fine, I get all the map with a single BPF call.
But I still see race condition while it is not supposed to be. I have tested with kernel 5.8 and 5.11.0-051100rc2. This is annoying since this is the issue I wanted to address. Any help on this would be appreciated. 
Can you review the code please ?
=> add bpf_map_lookup_and_delete_batch in bcc

src/python/bcc/__init__.py, src/python/bcc/usdt.py
For usdt with semaphore, user needs to provide pid in order
to create a usdt since enabling semaphore requires write to
virtual memory of the user process.
For attachment to corresponding usdt uprobe, we can pass
valid pid to perf_event_open() syscall so usdt is only
triggered for this process, or pass pid -1 permits usdt is
to triggered for all processes.
There are use cases for usdt to be triggered for other
processes than just one process. For example, for python
usdt function__entry/function__return, users may want to
trace usdt of a particular python process and all its
children processes.
C++ already has API to permit ignoring pid during attachment.
attach_usdt(const USDT& usdt, pid_t pid = -1)
This patch added similar functionality to python with an
additional parameter to BPF …
=> Allow python usdt attachment with pid -1

docs/reference_guide.md, examples/networking/xdp/xdp_macswap_count.py, src/cc/export/helpers.h, tests/cc/test_array_table.cc, tests/cc/test_bpf_table.cc, tests/cc/test_hash_table.cc, tests/python/test_percpu.py
Add a `BPF_PERCPU_HASH` helper macro for the `percpu_hash` maps similar to the one that already exists for the `percpu_array` maps.
=> Added helpers for BPF_PERCPU_HASH

INSTALL.md
It's required by BCC. Opted to make it built-in rather than a module in the snippet.
=> Enable kernel headers through /sys/kern/kheaders.tar.xz

src/cc/bcc_usdt.h, src/cc/usdt.h, src/cc/usdt/usdt_args.cc, src/python/bcc/libbcc.py, tests/cc/test_usdt_args.cc
[Systemtap](https://sourceware.org/systemtap/wiki/UserSpaceProbeImplementation) defines the size of an argument as either 1, 2, 4, or 8 bytes (signed or unsigned). Thus the constant variable should be stored in a `long long` instead of an `int` to ensure 8 bytes size.
I've opted for `long long` here rather than `int64_t` to match with `strtoull`'s type.
I've kept this as a signed integer for backwards compatibility, and I've used `strtoull` for the conversion as it correctly handles both the maximum unsigned value and negative values. The sign of the _size_ argument indicates whether the _constant_ value stored is signed or unsigned.
Note: 16-byte constants are possible but AFIK only from non-standard types like `__int128`.
This patch doesn't support that case.
=> Increase storage size of usdt argument constants to 64 bits

INSTALL.md
The current install steps for Debian from source is out of date,
use the distribution name sid instead of jessie, stretch, buster
due to the latter always change, update and simplify the install
steps like other distributions which is clear and always right.
Signed-off-by: Tiezhu Yang <yangtiezhu@loongson.cn>
=> INSTALL.md: Update and simplify the install steps for Debian from source

src/python/bcc/utils.py, tools/funccount.py
`BPF.find_exe` requires a string to match against `PATH`, and the `USDT` constructor requires a string for the `path` parameter, so that it can be encoded. However, the `ArgString` class returns a `bytes` from the `__str__` method. With Python 3, these type mismatches cause errors.
The fix modifies `ArgString` to return a `str` from `__str__` and uses that to pass a `str` in `funccount.py`.
=> Use string type for funccount comparison to PATH elements

tools/wakeuptime.py
=> fix wakeuptime's raw_tp: get awakened task from ctx not current

tools/biosnoop.py, tools/biotop.py
Commit 95c9229ea9f029a1b9e8dcbe86fc67f037c0dfa2 replaced the
blk_account_io_completion kprobe with blk_account_io_done. Unfortunately
the req->__data_len field is 0 in blk_account_io_done, therefore we need
to save the __data_len field in blk_start_request
Resolves #3099
=> biotop and biosnoop: save __data_len at blk_start_request

src/cc/frontends/b/codegen_llvm.cc
Upstream (llvm13) patch
https://reviews.llvm.org/D97223
changed function signature for CreateAtomicRMW().
The error message:
```
/home/yhs/work/bcc/src/cc/frontends/b/codegen_llvm.cc:
In member function ‘ebpf::StatusTuple ebpf::cc::CodegenLLVM
::emit_atomic_add(ebpf::cc::MethodCallExprNode*)’:
/home/yhs/work/bcc/src/cc/frontends/b/codegen_llvm.cc:720:75:
error: no matching function for call to
‘llvm::IRBuilder<>::CreateAtomicRMW(llvm::AtomicRMWInst::BinOp,
llvm::Value*&, llvm::Value*&, llvm:: AtomicOrdering)’
AtomicRMWInst::Add, lhs, rhs, AtomicOrdering::SequentiallyConsistent);
^
In file included from /home/yhs/work/bcc/src/cc/frontends/b/codegen_llvm.cc:31:
/home/yhs/work/llvm-project/llvm/build/install/include/llvm/IR/IRBuilder.h:1721:18:
note: candidate:
‘llvm::AtomicRMWInst* …
```
=> fix a llvm-triggered compilation error

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/funclatency.bpf.c, libbpf-tools/funclatency.c, libbpf-tools/funclatency.h, libbpf-tools/uprobe_helpers.c, libbpf-tools/uprobe_helpers.h
This is a port of BCC's funclatency.  Usage:
---------
Time functions and print latency as a histogram
Usage: funclatency [-h] [-m|-u] [-p PID] [-d DURATION] [ -i INTERVAL ]
[-T] FUNCTION
Choices for FUNCTION: FUNCTION         (kprobe)
LIBRARY:FUNCTION (uprobe a library in -p PID)
:FUNCTION        (uprobe the binary of -p PID)
-m, --milliseconds         Output in milliseconds
-u, --microseconds         Output in microseconds
-p, --pid=PID              Process ID to trace
-d, --duration=DURATION    Duration to trace
-i, --interval=INTERVAL    Summary interval in seconds
-T, --timestamp            Print timestamp
-?, --help                 Give this help list
--usage                Give a short usage message
-V, --version              Print program version
Mandatory or optional arguments to …
=> libbpf-tools: add funclatency

INSTALL.md
Otherwise the `make` fails with lack of `FlexLexer.h` error.
=> Add required libfl-dev in Ubuntu Bionic

man/man8/tcpconnect.8, tools/tcpconnect.py, tools/tcpconnect_example.txt
LPORT information will help in uniquely identifying a socket.
For example, this info will be of much help when analyzing a tcpdump.
As suggested by @brendangregg,  using '-L' option to print LPORT
=> tools: add option to include 'LPORT' in tcpconnect otuput

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/cachestat.bpf.c, libbpf-tools/cachestat.c
```sh
➜  libbpf-tools git:(cachestat) ✗ sudo ./cachestat -T 5 5
TIME         HITS   MISSES  DIRTIES HITRATIO   BUFFERS_MB  CACHED_MB
18:45:47   368311        0   211705  100.00%          131       1602
18:45:52   375358      955   165521   99.75%          135       2101
18:45:57   437604        0     9110  100.00%          135       2101
18:46:02   209939       37      169   99.98%          135       2101
18:46:07   534768        0     1033  100.00%          135       2102
```
=> libbpf-tools: add cachestat

tools/tcpstates.py
The adress of struct sock, which are used as the map key, are often
reused. When it happens random duration appears in the MS field for
new connections (CLOSE->SYN_SENT and LISTEN->SYN_RECV
transitions). Let's forget about the socket when the connection is
closed.
=> tcpstates: forget sockets when connection is closed

examples/tracing/task_switch.py, tests/python/test_trace2.py, tools/cpudist.py, tools/offcputime.py, tools/offwaketime.py, tools/runqlat.py, tools/runqslower.py
When buildiing kernel with GCC10 [2] in Debian on an Arm64 machine, it was
found the new "inter-procedural optimization improvements" [1] makes symbol
name 'finish_task_switch' changed to 'finish_task_switch.isra.0'.
Details:
The results, when built with gcc 9.3:
nm ../linux.buildout/kernel/sched/core.o | grep finish_task_switch
0000000000001288 t finish_task_switch
However, when built with gcc 10.2:
nm ../linux.buildout/kernel/sched/core.o | grep finish_task_switch
00000000000012d0 t finish_task_switch.isra.0
The same symbols (with xxx.isra.0 or without, respectively of course) also
appear in final file 'System.map' and in '/proc/kallsyms' when booting. This
negatively impact the tracing tools commonly used in kernel debugging, such
as bcc tools offcputime and runqlat. They hardcode …
=> In GCC10.2 suffix '.isra.0' was appended to 'finish_task_switch'

man/man8/virtiostat.8, tools/virtiostat.py, tools/virtiostat_example.txt
Add device driver/name filter for virtiostat.
=> tools/virtiostat: add filter

libbpf-tools/errno_helpers.c, libbpf-tools/execsnoop.bpf.c, libbpf-tools/execsnoop.c, libbpf-tools/funclatency.c, libbpf-tools/map_helpers.c, libbpf-tools/syscall_helpers.c, libbpf-tools/syscount.c, libbpf-tools/tcpconnect.bpf.c, libbpf-tools/tcpconnect.c, libbpf-tools/uprobe_helpers.c, libbpf-tools/vfsstat.c
Fix all the found instances of declaring loop variable inside for() construct,
which is not supported in C89 standard, which is what libbpf-tools are trying
to adhere to, both in user-space and BPF source code. It actually causes
compilation errors on some versions of GCC, as reported by customers in
private conversations.
Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
=> libbpf-tools: fix non-C89-compliant for loop variable declarations

man/man8/tcpconnlat.8, tools/tcpconnlat.py, tools/tcpconnlat_example.txt
Listing LPORT information is useful while troubleshooting latency issue with tcpdump.
This commit is adding a '-L' option to list the same.
Also updated the man pages and example files.
+++
PID    COMM         IP SADDR            LPORT  DADDR            DPORT LAT(ms)
2734   cups-browsed 4  192.168.8.95     53564  192.168.5.17     631   40.00
2734   cups-browsed 4  192.168.8.95     53566  192.168.5.17     631   39.69
2734   cups-browsed 4  192.168.8.95     53572  192.168.5.17     631   40.05
3467   python3      6  ::1              39340  ::1              3000  0.02
3467   python3      4  127.0.0.1        60846  127.0.0.1        3000  0.04
+++
=> tools: add option to include 'LPORT' in tcpconnlat, update man pages

FAQ.txt
libbcc.so is actually installed to /usr/lib64 instead of
/usr/local/lib in my computer system:
$ find /usr -name libbcc.so
/usr/lib64/libbcc.so
And also we can find out bcc-python:
$ find /usr/lib -name bcc
/usr/lib/python2.7/site-packages/bcc
It is better to use one line command to export environment
variable LD_LIBRARY_PATH and PYTHONPATH.
Signed-off-by: Tiezhu Yang <yangtiezhu@loongson.cn>
=> FAQ: Update LD_LIBRARY_PATH and PYTHONPATH

libbpf-tools/cachestat.bpf.c, libbpf-tools/funclatency.bpf.c
fix error when make libbpf-tools
```
libbpf: invalid relo for 'targ_tgid' in special section 0xfff2; forgot to initialize global var?..
Error: failed to open BPF object file: Relocation failed
make: *** [Makefile:88: .output/funclatency.skel.h] Error 255
make: *** Deleting file '.output/funclatency.skel.h'
```
=> libbpf-tools: initialize global variables in cachestat and funclatency

CMakeLists.txt, cmake/FindCompilerFlag.cmake
The recent linux distros already support PIE so it shouldn't be a
problem to remove "-no-pie". To avoid issue#782, we can make
"-no-pie" optional and disable it by default, so that the user can
enable "-no-pie" if really necessary.
=> cmake: make "-no-pie" optional

debian/changelog
* Support for kernel up to 5.11
* allow BCC as a cmake subproject
* add LPORT support in tcpconnlat and tcpconnect
* added bpf_map_lookup_and_delete_batch support
* new tools: virtiostat
* new libbpf-tools: cpufreq, funclatency, cachestat
* add install target to libbpf-tools
* a few lua fixes
* doc update and bug fixes
=> update debian changelog for release v0.19.0

libbpf-tools/Makefile, src/cc/export/helpers.h, src/cc/frontends/clang/arch_helper.h, src/cc/frontends/clang/b_frontend_action.cc, src/cc/frontends/clang/kbuild_helper.cc, src/cc/frontends/clang/loader.cc
In order to fix the following errors when running bpf program
on the MIPS Loongson64 platform, add some basic support, with
this patch, running hello_world.py can get the expected result.
root@linux:/home/loongson/bcc# python examples/hello_world.py
In file included from <built-in>:3:
In file included from /virtual/include/bcc/helpers.h:51:
In file included from include/uapi/linux/if_packet.h:5:
arch/mips/include/uapi/asm/byteorder.h:17:3: error: "MIPS, but neither __MIPSEB__, nor __MIPSEL__???"
#error "MIPS, but neither __MIPSEB__, nor __MIPSEL__???"
^
In file included from <built-in>:3:
In file included from /virtual/include/bcc/helpers.h:53:
In file included from include/linux/log2.h:12:
In file included from include/linux/bitops.h:32:
In file included from …
=> bcc: Add some basic support for MIPS

tools/dcsnoop.py, tools/dcstat.py
The lookup_fast function can be rename lookup_fast.constprop.x by gcc
constant propagation optimization and that breaks dcstat and
dcsnoop. Let's look for both name using a regular expression.
=> tools: handle renamed lookup_fast function in dcache tools

libbpf-tools/cpudist.bpf.c
To fix https://github.com/iovisor/bcc/issues/3293 metioned.
=> libbpf-tools: use raw_tp sched_switch instead of kprobe

libbpf-tools/biolatency.bpf.c, libbpf-tools/biosnoop.bpf.c, libbpf-tools/bitesize.bpf.c
Block IO tracepoints block_rq_insert and block_rq_issue are changed by this [commit](https://github.com/torvalds/linux/commit/a54895fa057c67700270777f7661d8d3c7fda88a).
For linux 5.10:
https://github.com/torvalds/linux/blob/v5.10/include/trace/events/block.h#L209
For > linux 5.10
https://github.com/torvalds/linux/blob/v5.11-rc1/include/trace/events/block.h#L206
This change break the libbpf-tools `biolatency`, `biosnoop` and `bitesize`:
```
libbpf: load bpf program failed: Permission denied
libbpf: -- BEGIN DUMP LOG ---
libbpf: 
arg#0 type is not a struct
Unrecognized arg#0 type PTR
; int BPF_PROG(block_rq_insert, struct request_queue *q, struct request *rq)
0: (79) r6 = *(u64 *)(r1 +8)
func 'block_rq_insert' doesn't have 2-th argument
invalid bpf_context access off=8 size=8
processed 1 …
```
=> libbpf-tools: fix for block io tracepoints changed

man/man8/funclatency.8, tools/funclatency.py, tools/funclatency_example.txt
add `-l level` option to support nested or recursive functions.
without `-l` option, funclatency tool worked as before.
```
typedef struct {
u64 ip;
u64 start_ts;
} func_cache_t;
/* LIFO */
typedef struct {
u32          head;
func_cache_t cache[STACK_DEPTH];
} func_stack_t;
BPF_HASH(func_stack, u32, func_stack_t);
```
cache stack(LIFO) per pid.
=> tools/funclatency: support nested or recursive functions

libbpf-tools/ext4dist.bpf.c, libbpf-tools/ext4dist.c
Fix below minor issues of ext4dist
* Fix the check of the existence of module BTFs
* Initialize the global variable
=> libbpf-tools: fix some minor issues of ext4dist

docs/reference_guide.md, src/cc/libbpf.c, src/python/bcc/libbcc.py, src/python/bcc/table.py, tests/python/test_map_batch_ops.py
Add **bpf_map_lookup_batch** and **bpf_map_delete_batch** in bcc
* add bpf_map_lookup_batch in bcc
* add bpf_map_delete_batch in bcc
* add test_map_batch_ops.py to test batch lookup and delete on map
* add items_lookup_batch() and items_delete_batch()  in the reference guide
The bpf_map_delete_batch in table.py is not using bpf_map_delete_batch from libbcc. It rather uses bpf_map_lookup_and_delete_batch without using the return values. I did not succeed in writing bpf_map_delete_batch with only one BPF syscall with  BPF_MAP_DELETE_BATCH. I doubt this is possible.
bpf_map_delete_batch could be used to improve the table.clear() (less system calls) but it would only works for kernel v5.6 and later. How do you you manage this ? Do you let the kernel dependencies management in libbpf ?
=> add bpf_map_lookup_batch and bpf_map_delete_batch in bcc

src/cc/export/helpers.h
These are two common kernel macros to manipulate data
structures. Let us add them to helpers.h so bpf program
can use them.
=> add macros offsetof and container_of

src/cc/api/BPFTable.cc, src/cc/api/BPFTable.h
This is useful when BPFStackTable is used by a long running program to
limit the memory usage, by removing the cached symbols of an exited
process.
=> Add BPFStackTable::free_symcache() to free the symbol cache for an PID

tools/funclatency.py
BUG:
funclatency memcpy -i 2
nsecs               : count     distribution
16 -> 31         : 0        |                                        |
32 -> 63         : 0        |                                        |
64 -> 127        : 0        |                                        |
128 -> 255        : 0        |                                        |
256 -> 511        : 0        |                                        |
512 -> 1023       : 0        |                                        |
1024 -> 2047 …
=> tools/funclatency: Should clear() after display that is what we want

src/python/bcc/__init__.py
Since commit 75f20a15 ("Use string type for comparison to PATH
elements"), src_file isn't working anymore. Somehow, two wrongs
(ArgString __str__() returning a bytes object and joining a bytes and
what was supposed to be a string) did make a right.
It fixes the following error in netqtop and deadlock:
File "/usr/share/bcc/tools/netqtop", line 207, in <module>
b = BPF(src_file = EBPF_FILE)
File "/usr/lib/python3.6/site-packages/bcc/__init__.py", line 335, in __init__
src_file = BPF._find_file(src_file)
File "/usr/lib/python3.6/site-packages/bcc/__init__.py", line 255, in _find_file
t = b"/".join([os.path.abspath(os.path.dirname(argv0.__str__())), filename])
TypeError: sequence item 0: expected a bytes-like object, str found
=> Fix BPF(src_file="foo")

man/man8/biolatency.8, tools/biolatency.py, tools/biolatency_example.txt
Sometimes log2 range is not enough for throughput tuning.
Especially a little difference in performance downgrade.
Also, this extension uses two bpf helper bpf_map_lookup_elem().
It's a cost on embedded system, therefore it's better to be an option.
Signed-off-by: Edward Wu <edwardwu@realtek.com>
=> tools/biolatency: Extend average/total value

docs/reference_guide.md, src/cc/libbpf.c, src/python/bcc/libbcc.py, src/python/bcc/table.py, tests/python/test_map_batch_ops.py, tests/python/test_queuestack.py
This pr aims at introducing:
* items_update_batch: batch operation to update multiple key-value pairs at the same time
* Queue/Stack itervalues: to lookup all values consequently
Signed-off-by: Simone Magnani <simonemagnani.96@gmail.com>
=> introduced map batch update in Python and Queue/Stack itervalues utility

src/cc/export/helpers.h
This reverts commit cda7acdbddb19a5a258f881711845e41463dabbf.
This will tigger ugly compilation macro redefined warnings:
```
$ sudo ./biolatency.py
In file included from /virtual/main.c:3:
In file included from include/linux/blkdev.h:5:
In file included from include/linux/sched.h:12:
In file included from arch/x86/include/asm/current.h:6:
In file included from arch/x86/include/asm/percpu.h:45:
include/linux/kernel.h:992:9: warning: 'container_of' macro redefined [-Wmacro-redefined]
#define container_of(ptr, type, member) ({                              \
^
/virtual/include/bcc/helpers.h:48:9: note: previous definition is here
#define container_of(ptr, type, member)                         \
^
1 warning generated.
Tracing block device I/O... Hit Ctrl-C to end.
```
Revert now and let us …
=> Revert "add macros offsetof and container_of"

docs/reference_guide.md, src/cc/bpf_module.cc, src/cc/frontends/clang/b_frontend_action.cc, src/cc/frontends/clang/b_frontend_action.h, src/cc/libbpf.c, src/cc/libbpf.h, src/cc/table_storage.h, tests/cc/test_pinned_table.cc
resolve https://github.com/iovisor/bcc/issues/3373
In function `VisitVarDecl`. If bpf_obj_get() returns an invalid fd, marked `pinned_id` to -1.
In function `create_maps`. If `pinned_id` less than 0, create a new map, if `pinned_id` is -1 pin map fd to specified file.
=> feature: support create new map and pin it to bpffs as file(BPF_TABLE_PINNED)

src/cc/export/bpf_workaround.h, src/cc/exported_files.cc, src/cc/frontends/clang/kbuild_helper.cc
As reported in #3366, on newer kernels bcc complains about macro
redefinition when compiling bpf programs:
```
include/linux/compiler-clang.h:46:9: warning: '__HAVE_BUILTIN_BSWAP64__' macro redefined [-Wmacro-redefined]
\#define __HAVE_BUILTIN_BSWAP64__
^
<command line>:5:9: note: previous definition is here
\#define __HAVE_BUILTIN_BSWAP64__ 1
```
Since these macros are passed in as `-D` cflags, they appear first
before any \#define statements in code. Since an [upstream kernel
patch](https://lore.kernel.org/linux-csky/20210226161151.2629097-1-arnd@kernel.org/)
added these defines in a kernel header, we see the warning.
This patch moves these definitions to a separate 'virtual' header that's included
after virtual_bpf.h and adds an ifndef guard. As a result, newer kernels
with the patch …
=> Move HAVE_BUILTIN_BSWAP includes to separate header

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/offcputime.bpf.c, libbpf-tools/offcputime.c, libbpf-tools/offcputime.h, libbpf-tools/trace_helpers.c, libbpf-tools/trace_helpers.h, libbpf-tools/uprobe_helpers.c, libbpf-tools/uprobe_helpers.h
Compared with the previous version, raw_tp/sched_switch is used instead of kprobe/finish_task_switch, because the latter has symbolic name problems under gcc 10 https://github.com/iovisor/bcc/issues/3293.
Functionally compared with the old version, the following features are missing, will be completed in subsequent PR.
Todo list
The output looks like below:
```
bpf_prog_f8f33eb3e61e9447_sched_switch
bpf_prog_f8f33eb3e61e9447_sched_switch
bpf_trace_run3
__bpf_trace_sched_switch
__schedule
schedule
futex_wait_queue_me
futex_wait
do_futex
__x64_sys_futex
do_syscall_64
entry_SYSCALL_64_after_hwframe
runtime.futex
runtime.notesleep
runtime.stopm
runtime.findrunnable
runtime.schedule
runtime.park_m
runtime.mcall
[unknown]
-                containerd (1172)
69917
```
Signed-off-by: Wenbo Zhang …
=> libbpf-tools: add offcputime

src/cc/frontends/clang/loader.cc
The intent of #3391 was to have `bpf_workaround.h` included after
`bpf.h` when compiling bcc headers. However, that PR only added the file
to the `headers_` map of files that can be included. To actually
include, need to adjust compiler input flags as well.
Fixes: d089013e ("Move HAVE_BUILTIN_BSWAP includes to separate header")
=> loader: include bpf_workaround.h header

libbpf-tools/trace_helpers.c, libbpf-tools/trace_helpers.h, libbpf-tools/vfsstat.bpf.c, libbpf-tools/vfsstat.c
=> bcc/libbpf-tools: Use fentry for vfsstat

src/cc/bcc_debug.cc
MCContext and InitMCObjectFileInfo name/signatures
are changed due to upstream patch
https://reviews.llvm.org/D101462
Adjust related codes in bcc_debug.cc properly to resolve
the compilation error for llvm13.
=> fix llvm compilation errors

debian/changelog
* Support for kernel up to 5.12
* Some basic support for MIPS
* added bpf_map_lookup_batch and bpf_map_delete_batch support
* tools/funclatency.py support nested or recursive functions
* tools/biolatency.py can optionally print out average/total value
* fix possible marco HAVE_BUILTIN_BSWAP redefine warning for kernel >= 5.10.
* new tools: virtiostat
* new libbpf-tools: ext4dist
* doc update and bug fixes
=> update debian changelog for release v0.20.0

SPECS/bcc+clang.spec, SPECS/bcc.spec, scripts/build-release-rpm.sh
Hi, I've tried to build bcc-0.19 rpm package on CentOS 7, but it's not working fine.
It looks seems the LLVM version is older in rpm build spec and I've tried changing the LLVM version to 7.0.1.
It's worked for the following environments.
* `Linux 0e0614f3 5.4.56-200.el7.x86_64 #1 SMP Sat Aug 8 21:08:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* `CentOS Linux release 7.8.2003 (Core)`
=> Fix RPM build error

src/cc/bcc_exception.h
Probably not a real issue but it doesn't hurt to initialize this field to suppress warnings.
```
1. member_decl: Class member declaration for code_.
Code code_;
2. Uninitialized scalar field (UNINIT_CTOR). uninit_member: Non-static class member code_ is not initialized in this constructor nor in any functions that it calls.
StatusTuple(int ret) : ret_(ret) {}
```
=> GCC 7: Coverity 'Uninitialized scalar field'

libbpf-tools/opensnoop.c
aarch64 has no open syscall, do not attempt to trace it.
Fixes #3344.
Sorry for the delay, here it is.
I've successfully tested opensnoop with the patch on aarch64 debian.
=> libbpf-tools/opensnoop: disable open on aarch64

libbpf-tools/Makefile
Add LIBBPF_OBJ dependence to `%.o'.
When libbpf-tools built in parallel (with `make -j`) sometimes
`map_helpers.o' is built before `libbpf.a' causing build error:
```
$ make -j8 -C libbpf-tools BPFTOOL=/usr/sbin/bpftool
...
make: Entering directory '/usr/src/RPM/BUILD/bcc-0.19.0/libbpf-tools'
CC       map_helpers.o
In file included from map_helpers.c:7:
./map_helpers.h:6:10: fatal error: 'bpf/bpf.h' file not found
^~~~~~~~~~~
...
make: Leaving directory '/usr/src/RPM/BUILD/bcc-0.19.0/libbpf-tools'
INSTALL  bpf.h libbpf.h btf.h xsk.h libbpf_util.h bpf_helpers.h bpf_helper_defs.h bpf_tracing.h bpf_endian.h bpf_core_read.h libbpf_common.h
...
INSTALL  libbpf.a
error: Bad exit status from /usr/src/tmp/rpm-tmp.63536 (%build)
```
Fixes: #3412
=> libbpf-tools: Fix build dependence for parallel builds

tools/btrfsdist.py, tools/ext4dist.py, tools/nfsdist.py, tools/xfsdist.py, tools/zfsdist.py
This PR fixes PID filtering in 
- btrfsdist.py
- ext4dist.py
- nfsdist.py
- xfsdist.py
- zfsdist.py
For background, see #3407 .
=> tools: filter using PID intead of TID

tools/gethostlatency.py, tools/solisten.py, tools/sslsniff.py, tools/tcpdrop.py
This PR fixes PID filtering in
* gethostlatency.py
* solisten.py
* sslsniff.py
* tcpdrop.py
For background, see #3407 .
=> tools: filter/display using PID intead of TID

libbpf-tools/cachestat.c, libbpf-tools/cpufreq.c, libbpf-tools/ext4dist.c, libbpf-tools/funclatency.c, libbpf-tools/numamove.c, libbpf-tools/readahead.c, libbpf-tools/runqlen.c, libbpf-tools/softirqs.c, libbpf-tools/vfsstat.c
reslove https://github.com/iovisor/bcc/issues/3406
Have `skel->rodata or skel->bss or skel->data` , and used after loading.
* cachestat
* cpufreq
* ext4dist
* funclatency
* numamove
* readahead
* runqlen
* softirqs
* vfsstat
Have `skel->rodata or skel->bss or skel->data` , but not used after loading. Or don't have `skel->rodata and skel->bss and skel->data`
* biolatency
* biopattern
* biosnoop
* bitesize
* cpudist
* drsnoop
* execsnoop
* filelife
* gethostlatency
* hardirqs
* llcstat
* offcputime
* opensnoop
* runqlat
* runqslower
* syscount
* tcpconnect
* tcpconnlat
* xfsslower
=> Libbpf-tools/add check BPF_F_MMAPABLE is supported

libbpf-tools/biolatency.c, libbpf-tools/biopattern.c, libbpf-tools/biosnoop.c, libbpf-tools/biostacks.c, libbpf-tools/bitesize.c, libbpf-tools/cachestat.c, libbpf-tools/cpudist.c, libbpf-tools/cpufreq.c, libbpf-tools/drsnoop.c, libbpf-tools/execsnoop.c, libbpf-tools/ext4dist.c, libbpf-tools/filelife.c, libbpf-tools/hardirqs.c, libbpf-tools/llcstat.c, libbpf-tools/numamove.c, libbpf-tools/offcputime.c, libbpf-tools/readahead.c, libbpf-tools/runqlat.c, libbpf-tools/runqlen.c, libbpf-tools/runqslower.c, libbpf-tools/softirqs.c, libbpf-tools/syscount.c, libbpf-tools/tcpconnect.c, libbpf-tools/tcpconnlat.c, libbpf-tools/vfsstat.c, libbpf-tools/xfsslower.c
`ext4dist` did not parse `-h` option, this PR fixes it.
```
$ sudo ./ext4dist -h
./ext4dist: invalid option -- 'h'
Try `ext4dist --help' or `ext4dist --usage' for more information.
```
=> libbpf-tools: parse -h option

libbpf-tools/tcpconnect.h
Hi! Please consider updating `tcpconnect` to use `__u32 af` instead of `int af` so it's less error prone to decode an address family on Go side, for example https://github.com/marselester/libbpf-tools/blob/master/cmd/tcpconnect/main.go.
=> Update tcpconnect to use "__u32 af" instead of "int af"

examples/networking/xdp/xdp_drop_count.py, examples/networking/xdp/xdp_macswap_count.py, src/python/bcc/__init__.py
resolve https://github.com/iovisor/bcc/issues/3445
add `XDP_FLAGS*` to `__init__.py`
I will add documentation in the following PR.
=> feature: add `XDP_FLAGS*` in python lib

src/cc/libbpf.c
before adjust
```
$./examples/networking/xdp/xdp_drop_count.py lo
bpf: Attaching prog to lo: Operation not supportedTraceback (most recent call last):
File "./examples/networking/xdp/xdp_drop_count.py", line 139, in <module>
b.attach_xdp(device, fn, flags)
File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 766, in attach_xdp
% (dev, errstr))
Exception: Failed to attach BPF to device lo: No such file or directory
```
after adjust
```
$./examples/networking/xdp/xdp_drop_count.py lo
bpf: Attaching prog to lo: Operation not supported
File "./examples/networking/xdp/xdp_drop_count.py", line 139, in <module>
b.attach_xdp(device, fn, flags)
File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 766, in attach_xdp
% (dev, errstr))
Exception: …
```
=> adjust: bpf_attach_xdp report nicer error

man/man8/ttysnoop.8, tools/ttysnoop.py, tools/ttysnoop_example.txt
- Kernel commit [1] changed arguments of tty_write function, changing the probe function to new prototypes.
- Use array map to store data
- Adding the possibility to define transmitting data size (--datasize option) and number of times we ask for this amount (--datacount option).
=> Fix ttysnoop for kernel > v5.11 and other config changes

src/cc/bcc_debug.cc
Current llvm trunk (https://github.com/llvm/llvm-project)
will cause the following compilation errors:
```
/home/yhs/work/bcc/src/cc/bcc_debug.cc: In member function ‘void ebpf::SourceDebugger::dump()’:
/home/yhs/work/bcc/src/cc/bcc_debug.cc:135:75: error: no matching function for call to
‘llvm::MCContext::MCContext(llvm::Triple&, std::unique_ptr<llvm::MCAsmInfo>::pointer,
std::unique_ptr<llvm::MCRegisterInfo>::pointer, llvm::MCObjectFileInfo*,
std::unique_ptr<llvm::MCSubtargetInfo>::pointer, std::nullptr_t)’
MCContext Ctx(TheTriple, MAI.get(), MRI.get(), &MOFI, STI.get(), nullptr);
^
......
```
This is because upstream patch https://reviews.llvm.org/D101921
refactored MCObjectFileInfo initialization and changed MCContext
constructor signature.
This patch fixed the issue by following the …
=> Fix a llvm compilation error

man/man8/hardirqs.8, tests/python/test_tools_smoke.py, tools/old/hardirqs.py
The hardirqs tool is not working properly in recent kernels.
I tested it with kernel 5.4/5.8/5.11, all compiled but has no output.
This commit migrates hardirqs to use kernel tracepoints instead of kprobes, 
just as we already made to softirqs.
```shell
sudo ./hardirqs.py  -C  1 10
Tracing hard irq events... Hit Ctrl-C to end.
HARDIRQ                    TOTAL_count
enp0s31f6                            1
iwlwifi                              3
i915                                14
HARDIRQ                    TOTAL_count
iwlwifi                              2
xhci_hcd                             5
i915                                26
...
```
```shell
sudo ./hardirqs.py  -d 1 10 
Tracing hard irq event time... Hit Ctrl-C to end.
hardirq = 'i801_smbus'
usecs               : count …
```
=> hardirqs: Migrate to kernel tracepoint

man/man8/deadlock.8, tools/deadlock.c, tools/deadlock.py, tools/deadlock_example.txt
https://github.com/iovisor/bcc/issues/3453
support specifies maxnum of threads and edge cases.
The default size of memory that deadlock needs to allocate is too large. Sometimes this will cause OOM for particular system, or the memory limit has been exceeded.
```
[16536.857153] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-0.slice/session-1.scope,task=trace.py,pid=4971,uid=0
[16536.857622] Out of memory: Killed process 4971 (trace.py) total-vm:470116kB, anon-rss:0kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:528kB oom_score_adj:0
```
=> tools/deadlock: support specifies maxnum of threads and edge cases

tools/cpudist.py
When calculating the ONCPU  time, prev has left the CPU already. It is not necessary to judge whether the process state is TASK_RUNNING or not.
=> cpudist.py: fix ONCPU calculation

docs/reference_guide.md
Add a description of the `debug` parameter for `BPF(..., debug=0)`. (`DEBUG_BTF`)
=> docs: update description of bcc python BPF()

libbpf-tools/Makefile
Packagers need to be able set linker options according to their
distribution guidelines.
=> libbpf-tool: don't ignore LDFLAGS

docs/reference_guide.md, src/python/bcc/table.py, tests/python/test_map_batch_ops.py
Hello,
Here is a partial PR in order to :
- add items_lookup_batch() on subset keys
- add items_lookup_and_delete_batch() on subset keys
- add docstring on items_*_batch()
- update the reference_guide.md
This is a partial PT because I am stuck with items_lookup_batch and items_lookup_and_delete_batch on a subset. Sometimes tests are Ok and sometimes they fails. See the output of tests.
``` 
python git:(add_subset_for_batch_ops) ✗ sudo python3 ./test_map_batch_ops.py
...F....
======================================================================
FAIL: test_lookup_and_delete_batch_subset (__main__.TestMapBatch)
File "./test_map_batch_ops.py", line 94, in …
```
=> finish to add support of subset in items_*_batch()

docs/reference_guide.md
Hi all,  this PR will resolve #3414.
I wrote the document about `attach_xdp`, but I am a beginner at eBPF and XDP. 
I am assuming that multiple calls to attach_xdp will overwrite the previous one and not run, is this correct? Is this correct and should I write this?
Can you give me the advice to improve the quality of documents?
Best Regards.
=> Add attach_xdp to reference_guide.md

docs/reference_guide.md, src/cc/export/helpers.h, tests/cc/test_sock_table.cc
I think one of the main reasons for providing `sockhash` is because people want to use more flexible keys. So I think we need to provide a way for users to define their own key types.
=> libbcc: support BPF_SOCKHASH specify the key type

src/cc/json_map_decl_visitor.cc
clang 13+ has removed this in favour of a pair of llvm::toString
() helpers inside StringExtras.h to improve compile speed by avoiding
hits on <string> header
Signed-off-by: Khem Raj <raj.khem@gmail.com>
=> Remove APInt/APSInt toString() std::string variants for llvm >= 13
