iovisor/bcc

examples/hello_world.py, src/bpf.py
=> Add simple single file example

src/cc/b_frontend_action.cc, src/cc/bpf_helpers.h
=> Remove BPF_LL_OFF usage

tests/cc/test_xlate1.py
=> Fix test_xlate1 when systems have no default tc

tests/cc/test_call1.py
=> Fix test_call1 for systems without default qdisc

src/cc/CMakeLists.txt, src/cc/kbuild_helper.h
=> fix build with gcc < 4.9

README.md
=> Drop 'experimental' from README.md

CMakeLists.txt
just update PATH to include 'llvm-config' from your local
llvm build directory.
=> build without have to install llvm/clang

src/cc/export/helpers.h, tests/cc/CMakeLists.txt, tests/cc/test_brb.c, tests/cc/test_brb.py
=> add a bridge-router-bridge test with router implemented as a namespace

tests/cc/test_brb.c, tests/cc/test_brb.py
=> use 64bit ulonglong to represent mac address

examples/vlan_learning.c, examples/vlan_learning.py, src/cc/export/helpers.h, src/cc/libbpf.c
* Create a simulation of a physical network with multiple vlans, which
can accept and distribute connections from multiple clients in
overlapping subnets. The program will assign to a worker based on mac
address.
* Remove a hardcoded SO_ATTACH_BPF literal, and fix one spacing
=> Add a Learning VLAN program example

FAQ.txt, README.md
Add more instructions detailing the need to install kernel headers
=> Update readme and FAQs

tests/cc/test_brb.py, tests/cc/test_brb2.py
=> reduce test time for test_brb and test_brb2

examples/hello_world.py, src/cc/export/helpers.h
=> Automatically compute sizeof in bpf_trace_printk

FAQ.txt, src/cc/export/helpers.h
=> add get_current_pid/tgid/uid/gid/comm helpers

examples/vlan_learning.py, src/python/bpf/__init__.py, tests/cc/test_brb.py, tests/cc/test_brb2.py, tests/cc/test_call1.py, tests/cc/test_stat1.py, tests/cc/test_trace1.py, tests/cc/test_trace2.py, tests/cc/test_trace3.py, tests/cc/test_xlate1.py
* Add [] support in BPF.Table class
* Remove uses of lookup/update
* Add del support
=> Make python table accesses more pythonic

examples/vlan_learning.py
* Breakage from previous commit
=> Remove update() call from vlan example

examples/simulation.py, examples/tc_neighbor_sharing.py, examples/vlan_learning.py
* Create a class for the examples to share, helps with IPDB cleanup and
namespace creation.
=> Move shared example code into simulation.py

INSTALL.md, README.md
=> Update README.md examples and INSTALL.md

examples/simulation.py, examples/tunnel_monitor/monitor.c
* Ignore exceptions and continue cleanup of dead children
* Set loopback interface up
=> Bugfix for simulation.py

src/cc/b_frontend_action.cc
=> use running linux version number for feature availability checking

examples/vlan_learning.c, examples/vlan_learning.py, src/cc/compat/linux/bpf.h, src/cc/export/helpers.h
=> simply vlan_learning example with newer vlan_push/pop helpers

examples/distributed_bridge/main.py, examples/distributed_bridge/simulation.py, examples/distributed_bridge/tunnel.c, examples/distributed_bridge/tunnel.py, src/cc/compat/linux/bpf.h, src/cc/export/helpers.h
vxlan + multicast based multitenant bridge
=> Dist bridge

examples/distributed_bridge/main.py, examples/distributed_bridge/tunnel_mesh.c, examples/distributed_bridge/tunnel_mesh.py
Run 'sudo python ./main.py mesh'
=> full mesh vxlan example without multicast

examples/distributed_bridge/main.py
=> import "input" from "builtins" for python v2/v3 compatibility

examples/distributed_bridge/tunnel.c, examples/distributed_bridge/tunnel_mesh.c, src/cc/compat/linux/bpf.h, src/cc/export/helpers.h
=> update tunnel_key prototypes

src/cc/bpf_module.cc
=> fix incorrect DataLayout

examples/distributed_bridge/main.py, examples/distributed_bridge/tunnel.py, examples/distributed_bridge/tunnel_mesh.py
=> Assign ip address to br

examples/distributed_bridge/tunnel_mesh.py
=> fix tunnel_mesh.py

examples/simulation.py
o There are still some cases when ctrl-c is pressed, the program does not exit
gracefully, with a however lower probability. In my random manual experiments,
one in ten cases it still hangs and needs further ctrl-z.
=> better clean up of created namespace/interfaces if ctrl-c is pressed

INSTALL.md
https://llvm.org/bugs/show_bug.cgi?id=24154
Build from source until it's resolved. Another plan is to provide
binary package.
=> llvm 3.7+ deb is broken

src/cc/export/helpers.h
=> Flags for 4.3 were accidentally committed, revert

INSTALL.md
=> Add INSTALL.md instructions for using Ubuntu binary build

INSTALL.md, examples/simple_tc.py
o Also suggest task_switch.py to try with libbcc package
=> Add one line desc output for simple_tc

examples/distributed_bridge/main.py, examples/distributed_bridge/tunnel_mesh.py
=> add connectivity validation in distributed bridge examples

examples/distributed_bridge/main.py, examples/simulation.py
=> Fixing more ctrl-c problem

examples/distributed_bridge/main.py, examples/simulation.py
=> clean up potential conflict veth before creating new one in create_ns

tests/cc/test_brb2.c
Sometimes background noise fails the test
=> test_brb2: only account for IP and ARP packets

examples/distributed_bridge/main.py
Sometimes it takes longer for ns to complete configuration.
=> distributed_bridge: wait for ns comes up before validating traffic

examples/distributed_bridge/main.py
=> distributed_bridge: check ip address before validating traffic

examples/CMakeLists.txt, examples/distributed_bridge/CMakeLists.txt
=> add vlan_learning and distributed_bridge in libbcc package

examples/distributed_bridge/main.py, examples/distributed_bridge/tunnel_mesh.py
=> add dhcp support for tunnel-mesh

examples/hello_world.py, src/python/bpf/__init__.py
=> Add BPF python helpers for reading trace_pipe

tests/cc/test_stat1.py
=> Add test case for clearing of maps from python

examples/distributed_bridge/main.py
The feature allows to have a bit cleaner code.
This particular code piece is just a proposal, it wasn't tested, though the feature itself is working and covered by the the CI. Actually, it was made after this sample script, but may be useful in other cases as well.
=> examples: use IPDB `wait_ip()` feature

src/python/bpf/__init__.py
=> Fix print() breakage in python 2.7 environments

examples/distributed_bridge/main.py, examples/distributed_bridge/tunnel_mesh.py
=> Add gretap support for full mesh tunnel

Dockerfile.centos6, SPECS/bcc.spec
=> Add beta RPM spec and docker script for centos

README.md, examples/task_switch.py
=> Minor change to task_switch example syntax

SPECS/bcc.el6.spec, SPECS/bcc.el7.spec, SPECS/bcc.f22.spec
=> Include missed spec files in s/bpf/bcc/ rename

examples/disksnoop.py, src/python/bcc/__init__.py, tools/syncsnoop
=> Shorten trace_readline_fields to trace_fields

README.md
suggested rework of README to show off capabilities sooner, and list contents.
=> some README rework

README.md
=> sync readme hello_world.py example with actual implementation

tests/cc/test_xlate1.c, tests/cc/test_xlate1.py
Support for act_bpf is available in 
https://github.com/svinota/pyroute2 starting from 70051b2
=> Change test_xlate1 to use act_bpf instead of cls_bpf

examples/bitehist.c, examples/disksnoop.c, examples/disksnoop.py, man/man8/biosnoop.8, tools/biosnoop, tools/biosnoop_example.txt
Basic biosnoop. Still working on an different version that pulls in ext4 info via dentry...
=> biosnoop and disk updates

README.md
need to remember this step for new tools!
=> add biosnoop to README

tests/cc/test_clang.py
=> Add a better test case for nested probe reads

src/cc/export/helpers.h
This code is from Alexei's tracex2. :)
=> add bpf_log2 functions

src/python/bcc/__init__.py, tools/funclatency
=> Add custom formatter function to print_log2_hist

src/cc/frontends/clang/b_frontend_action.cc, tests/cc/test_clang.py
Calls to functions were propagating the needs_probe state, causing map
values to require a probe_read improperly. Although there may be a use
case for this, generally it will not be needed and should be solved
differently.
Fixes: #256
=> Mask function calls from influencing probe_read

src/python/bcc/__init__.py, tests/cc/CMakeLists.txt, tests/cc/test_array.py, tests/cc/test_stat1.py
This set fixes two bugs related to table/array indexing.
=> Fixes for table indexing and clear()

src/python/bcc/__init__.py
=> Make KeyboardInterrupt catch more aggressive

tools/tcpv4connect
=> handle return value in kretprobe handler for tcpv4connect

SPECS/Dockerfile.el6, SPECS/Dockerfile.el7, SPECS/Dockerfile.f22, SPECS/bcc.el6.spec, SPECS/bcc.el7.spec, SPECS/bcc.f22.spec, debian/changelog, scripts/build-deb.sh
=> Update tag to v0.1.7

SPECS/bcc.spec, cmake/version.cmake, debian/python-bcc.install, debian/rules
These fixes are manually included in the released 0.1.7 packages, but
will help with future builds.
=> Fixes for deb/rpm packaging

INSTALL.md, src/cc/export/helpers.h
=> Add bpf() syscall feature check and readme update

tests/cc/simulation.py
=> Fixup broken symlink tests/cc/simulation.py

CMakeLists.txt, SPECS/bcc.spec, debian/bcc-tools.install, debian/control, man/CMakeLists.txt, man/man8/CMakeLists.txt, tools/CMakeLists.txt
Package tools into /usr/share/bcc/tools
Ticket: #291
=> Add bcc-tools package

src/cc/frontends/p4/compiler/ebpfProgram.py, src/cc/frontends/p4/compiler/ebpfTable.py, src/cc/frontends/p4/compiler/topoSorting.py
=> p4: fixed bugs in control-flow generation

src/cc/CMakeLists.txt
Signed-off-by: Alexei Starovoitov <ast@kernel.org>
=> make sure LDFLAGS are propagated as well

src/cc/bpf_common.cc, src/cc/bpf_common.h, src/cc/bpf_module.cc, src/cc/bpf_module.h, src/cc/frontends/clang/loader.cc, src/cc/frontends/clang/loader.h, src/python/bcc/__init__.py, tests/cc/test_clang.py
Example:
b = bcc.BPF("myprog.c", cflags=["-DMYCUSTOMFLAG1", ...])
=> Add ability to set custom cflags when loading programs

tools/biolatency, tools/biosnoop, tools/biosnoop_example.txt
convert tabs to spaces. No functional changes.
=> fix pep8 lint errors in biolatency and biosnoop

tools/biolatency_example.txt, tools/funccount, tools/funclatency, tools/hardirqs, tools/hardirqs_example.txt, tools/killsnoop, tools/killsnoop_example.txt, tools/opensnoop, tools/opensnoop_example.txt, tools/pidpersec, tools/softirqs, tools/softirqs_example.txt, tools/syncsnoop, tools/syncsnoop_example.txt, tools/tcpaccept, tools/tcpaccept_example.txt, tools/tcpconnect, tools/tcpconnect_example.txt, tools/vfscount, tools/vfscount_example.txt, tools/vfsstat, tools/vfsstat_example.txt
=> fix pep8 lint errors in the rest of the tools

src/cc/bpf_module.cc, src/cc/frontends/clang/b_frontend_action.cc, src/cc/shared_table.cc, src/cc/shared_table.h, src/cc/table_desc.h
=> Close fd and unshare when public map is destructed

tools/offcputime, tools/stackcount, tools/stacksnoop
=> stack walker typo and improvement

tools/offcputime.py
=> Add decode() to ascii string in offcputime.py

README.md, man/man8/bashreadline.8, tools/bashreadline.py, tools/bashreadline_example.txt
Snoop bash commands system wide!
=> bashreadline

tests/python/test_dump_func.py
=> Update test_dump_func to be python3 compatible

README.md, man/man8/cachestat.8, tools/cachestat.py, tools/cachestat_example.txt
Added cachestat tool, man page and exmaple file.
=> Added cachestat tool

tools/offwaketime.py
also remove tab and unused import
=> use __builtin_memcpy() instead of unrolled loop

src/cc/export/helpers.h
=> Add bpf_get_prandom_u32 to helpers

tools/runqlat.py
=> Fix for improper includes in runqlat.py

tools/old/tcpaccept.py, tools/old/tcpconnect.py
Needed updated versions for developing some new tcp tools.
=> tcp to bpf_perf_output

README.md, man/man8/btrfsdist.8, man/man8/btrfsslower.8, tools/btrfsdist.py, tools/btrfsdist_example.txt, tools/btrfsslower.py, tools/btrfsslower_example.txt
Extending the BPF love to btrfs.
=> 2 tools: btrfsdist, btrfsslower

src/cc/export/helpers.h
=> Fix syntax error in bpf_get_prandom_u32

man/man8/statsnoop.8, tools/old/statsnoop.py, tools/statsnoop.py
moved current version to old, updated man page.
=> migration of statsnoop to use bpf_perf_event

man/man8/filelife.8, tools/old/filelife.py
Looks ok with testing. Not sure how to test the -p option at the moment but looks a straight forward update.
=> Migrated filelife to bpf_perf_event

tools/argdist.py
This fixes one of the issues mentioned in #374.
=> Print traceback only if verbose mode was requested

debian/changelog, scripts/build-deb.sh, scripts/build-release-rpm.sh, scripts/build-rpm.sh, scripts/git-tag.sh
=> Prepare debian changelog for v0.1.8 tag

src/python/bcc/__init__.py, tests/cc/test_probe_count.py
The number of open probes has bitten users already, so lets enforce a
limit with a meaningful(ish) message.
=> Enforce limit of 1000 open [uk]probes

src/cc/export/proto.h
=> Add v6 headers to proto.h

src/cc/compat/linux/bpf.h, src/cc/export/helpers.h
Pull in bpf.h from upstream, and update helpers accordingly.
=> Update headers with 4.5+ features

tools/dcstat.py, tools/memleak.py
Syntax and dict usages fixups in dcstat.py and memleak.py
Fixes: #433, #434
=> Fix python3 incompatibilities

src/cc/frontends/clang/b_frontend_action.cc, src/cc/frontends/clang/b_frontend_action.h, src/cc/perf_reader.c, tests/python/test_stackid.py, tools/trace.py
See individual commit messages.
=> miscellaneous cleanups to C++ and tools/trace

.clang-format, scripts/git-clang-format, scripts/style-check.sh, tests/CMakeLists.txt
This change adds a test for ensuring that changed files conform to some form of style guideline. Currently, that style is LLVM's.
=> Add infra and ctest for code style formatting

examples/networking/distributed_bridge/tunnel_mesh.c, examples/networking/distributed_bridge/tunnel_mesh.py, src/cc/bpf_module.cc, src/cc/frontends/clang/b_frontend_action.cc, src/python/bcc/__init__.py, tests/python/test_clang.py, tests/python/test_histogram.py, tests/python/test_stackid.py
This fixes several issues in the clang frontend and some python lib and tests.
Fixes: #510
=> Fixes for clang frontend bugs and misc

src/cc/CMakeLists.txt, src/cc/frontends/b/codegen_llvm.cc
=> fix llvm 3.9 build

INSTALL.md
=> Lua installation instructions.

examples/networking/dns_matching/dns_matching.c, examples/networking/dns_matching/dns_matching.py
Add new example with test case for for unroll, as requested at iovisor-dev@lists.iovisor.org.
=> Add new example with test case for for unroll, as requested.

examples/networking/http_filter/http-parse-complete.c, examples/networking/http_filter/http-parse-complete.py, examples/networking/http_filter/http-parse-simple.py
Invalid access fixed. 
Parameter for specify the interface added.
=> http_filter fixes

src/cc/libbpf.c
This diff fixes a few fd leaks after reading files under /sys/kernel/debug/tracing.
=> Fix a few fd leaks

tools/fileslower.py, tools/stacksnoop.lua, tools/stacksnoop.py
This PR updates `fileslower` and  `stacksnoop` (both Python and Lua) to use BPF_PERF_OUTPUT instead of the trace pipe. The only noticeable differences in output are:
a) `COMM` is more reliable. More often than not when reading the trace pipe this would be set to `<...>`. `bpf_get_current_comm()` works all the time, as far as I can tell.
b) The `TIME(s)` column is relative to the program's start, rather than the timestamp embedded in the lines read from the trace pipe.
c) Renamed the `SYSCALL` column to `FUNCTION` since we may not be tracing a syscall.
This goes towards #540. I didn't fix the PID/TID issue I raised in #547 — will do that in another PR.
=> Use BPF_PERF_OUTPUT for fileslower and stacksnoop

tools/offcputime.py, tools/old/offcputime.py
We should extract pid before THREAD_FILTER
=> Fix tools[/old]/offcputime -p PID

man/man8/offcputime.8
=> Update manpage for offcputime

tools/offcputime.py
=> offcputime -f: don't miss backtrace bounds

tools/offcputime.py
* offcputime: change user/kernel stack order
* offcputime: add the `-d` option
Closes #559
=> Change kernel/user stacks order

README.md, examples/tracing/urandomread.py, examples/tracing/urandomread_example.txt
Not just an example, but a nice example. :)
closes #567
=> A tracepoint example

tools/cachetop.py, tools/cachetop_example.txt
This will make it easier to visualize what is the sorting field
and order
=> [cachetop] Display sorting field and order.

src/cc/frontends/clang/loader.cc
=> fix build with llvm 4.0

docs/tutorial_bcc_python_developer.md
I was confused by this when I first started. The compiler will complain about the helper functions having wrong arguments, which is not very obvious what went wrong. Talked with @4ast offline, he suggested adding this to the Tutorial.
=> Add some explanation for functions in BPF program in Tutorial

README.md, man/man8/sslsniff.8, tools/sslsniff.py, tools/sslsniff_example.txt
Add tool as talked in iovisor-dev 'BCC: bpf_probe_read read function arguments'
=> Tool to sniff data contents before encrypted with OpenSSL

src/cc/CMakeLists.txt, src/cc/bpf_module.cc
=> fix build with 4.0 llvm trunk

tools/biosnoop.py
=> fix biosnoop after kernel change

debian/changelog
=> Prepare debian changelog for v0.2.0 tag

tools/offcputime.py
There are situations, specially when using non-folded mode, where we are
interested only in very high latencies that happen due to blocking.
While we can certainly filter out the very small ones out of the output, it is a
lot more convenient to do this from the tool itself, as it would be difficult
from an external filter to do this in one pass.
But if we are to discard unused measurements, we can do even better: we can
change the bpf code itself not to grab those traces, and gain a bit of
efficiency in scenarios in which we are only concerned about peak latencies.
This scheme can be easily extended to also allow a maximum cap in the latencies
we are interested in.
After this patch is applied, the options -m and -M can be used to set those
limits respectively.
Fixes: #588
=> [offcputime] allow for the speficication of a threshold for collection

man/man8/filelife.8, tools/filelife.py
=> fix filelife missing output

README.md, man/man8/ttysnoop.8, tools/ttysnoop.py, tools/ttysnoop_example.txt
=> add ttysnoop

src/cc/export/proto.h
Signed-off-by: Deepa Kalani <dkalani@plumgrid.com>
=> Add vxlan gbp header

tools/argdist.py, tools/cpudist.py, tools/execsnoop.py, tools/funclatency.py, tools/gethostlatency.py, tools/hardirqs.py, tools/memleak.py, tools/mountsnoop.py, tools/offcputime.py, tools/softirqs.py, tools/solisten.py, tools/stacksnoop.py, tools/tplist.py, tools/trace.py
I ran pep8 with the recommended settings on all the tools and fixed all issues. (There are a couple with funccount and stackcount that will be merged as part of an earlier PR, so not repeated here.)
This resolves #745.
=> Tools lint cleanup

README.md, man/man8/reset-trace.8, tools/reset-trace.sh, tools/reset-trace_example.txt
=> add reset-trace

src/cc/CMakeLists.txt, src/cc/perf_reader.h
=> perf_reader: install perf_reader.h

examples/tracing/urandomread-explicit.py
=> Fix Tracepoint example

docs/reference_guide.md, docs/tutorial_bcc_python_developer.md
Found using [mwic](http://jwilk.net/software/mwic).
=> docs: Fix typos

tools/tcplife.py
Testing and catching more combinations (#788). It's a useful tool, but TCP stack implementation-dependent. It's probably going to have to be like this until we have stable TCP probes.
Testing from server and client, and both server-closed and client-closed, and remote and loopback...
```
PID   COMM       LADDR           LPORT RADDR           RPORT TX_KB RX_KB MS
9273  nc         100.66.11.247   51180 100.66.13.214   7002  46156     0 524.99
9274  nc         100.66.11.247   51182 100.66.13.214   7002  54970     0 653.29
9275  nc         100.66.11.247   7002  100.66.13.214   13632     0 92700 1102.04
9276  nc         100.66.11.247   7002  100.66.13.214   13638     0 64428 677.35
9277  sshd       100.66.11.247   22    100.72.22.151   45544     3     3 2431.24
9345  curl       100.66.11.247 …
```
=> tcplife.py: Catch passive closed by server, #788

man/man8/biotop.8, tools/biotop.py
=> biotop.py: fix compiler error on newer kernels

examples/tracing/hello_perf_output.py
=> hello_perf_output: match the data type of pid

tools/tcplife.py
Found some sessions not reported correctly, sorry. The more I fix this, the more comments I'll add.
=> tcplife: reorder logic to catch missed timestamps

tools/profile.py
... I'll do a separate ticket for adding -t for TID.
=> profile: -p should match user PID

src/cc/BPF.cc
This Diff:
- Make sure program loads happen after initial checks on attaching, so that we don't have to deal with unloading the programs for these simple error cases.
- Close program FDs on destruction, so that they won't leak.
=> Make sure program FDs get cleaned up correctly

man/man8/offwaketime.8, tools/offwaketime.py, tools/offwaketime_example.txt
Update for userspace stacks plus various changes from offcputime.
Some minor tweaks to feedback to offcputime.
Tested on an ubuntu virtualbox VM. I see lots of incomplete/corrupted/unreportable stacks which may need further investigation/checks.
=> offwaketime: update with get_stackid fixes #437

README.md, docs/reference_guide.md, man/man8/runqlat.8, man/man8/runqlen.8, src/python/bcc/table.py, tools/runqlen.py, tools/runqlen_example.txt
=> add runqlen tool

src/python/bcc/table.py
print_linear_hist() was limited to an index of 65, as I copied that bit from print_log2_hist(). Improve limit and error message.
=> Improve linear histogram limit, and improve error message.

snapcraft/snapcraft.yaml
=> snapcraft: add cpuunclaimed to snapcraft wrapper rules

man/man8/statsnoop.8, tools/statsnoop.py
(People are starting to study these to learn from; so doing some tidy up).
=> statsnoop: refactor

src/cc/libbpf.c
Beginners are hitting these errors, so I tried adding some hints to the output. What do we think? More hints can be added (there's also the list in Documentation/networking/filter.txt).
Eg, sample output:
```
[...]
61: (7b) *(u64 *)(r10 -480) = r1
62: (7b) *(u64 *)(r10 -488) = r1
63: (7b) *(u64 *)(r10 -496) = r1
64: (7b) *(u64 *)(r10 -504) = r1
65: (7b) *(u64 *)(r10 -512) = r1
66: (7b) *(u64 *)(r10 -520) = r1
invalid stack off=-520 size=8
HINT: Looks like you exceeded the BPF stack limit. This can happen if you allocate too much local variable storage. For example, if you allocated a 1 Kbyte struct (maybe for BPF_PERF_OUTPUT), busting a max stack of 512 bytes.
File "./bashreadline-stack.py", line 52, in <module>
b.attach_uretprobe(name="/bin/bash", …
```
=> add some error hints

tools/cpudist.py
=> cpudist: remove unused Tracepoint import

SPECS/bcc.spec
Not all architectures have luajit supported.  The bcc configure and
build were already was set up to make the luajit dependent parts
optional.  The bcc.spec now makes the luajit dependent parts optional
too allowing Fedora 25 builds on ppc64, ppc64le, and aarch64.  This
change has been tested and allows the resulting srpm to build on the
Fedora koji build system for the newly added architectures.
Signed-off-by: William Cohen <wcohen@redhat.com>
=> Allow RPMS to be built on ppc64 and aarch64 by making luajit optional

docs/kernel-versions.md
=> docs: fix "BPF attached to sockets" commit link

src/cc/libbpf.c
switch bcc to use single instance per bcc process, fixed issue #940
instance dir is bcc_pid, fixed issue #940
=> switch bcc to use single instance per bcc process, fixed issue #940

tools/trace.py
xrange does not exist in py3 and was replaced by range.
=> trace: fix for python3

tools/uobjnew.py, tools/ustat.py
See: https://www.python.org/dev/peps/pep-3113/
=> fixes #962 - fix lambda on both py2 and py3

tools/ucalls.py
Fix some compatibility issues with python3.
=> Fix ucalls

tools/argdist.py, tools/cpudist.py
This reverts commit a112514cba8e4844c405e3f1bd341289c4d2a158.
The changes the commit reverted are legit and should not have been
removed.
=> Revert "undo rebase"

INSTALL.md
=> Fix minor error in test instructions

docs/kernel-versions.md
Update of BPF features list, following the release of kernel 4.10.
=> docs: Update eBPF features list

src/cc/bcc_syms.cc
`ProcSyms::Module::find_addr` incorrectly resolves symbols when
functions are nested in each other. Specifically, this was discovered
with libpthread, where there are multiple symbols for `write`,
and `write_nocancel` is strictly nested inside `write`. Fix by
explicitly going backward until we reach a matching symbol -- see
details in `ProcSyms::Module::find_addr` comments.
/cc @markdrayton
=> cc: Handle nested functions correctly when resolving symbols

src/cc/bcc_syms.cc
When a symbol lies within a module, and that module doesn't have
debuginfo (or doesn't even have an ELF header), the symbol will
always be resolved as [unknown]. However, the /tmp/perf-PID.map
(perf map) for that process might actually have an entry for that
symbol, if it was dynamically generated by some external tool.
This commit changes the resolution process such that if the desired
address lies in a module but that module doesn't have debuginfo,
we keep trying to resolve it in subsequent modules (including the
perf map). If we resolve it successfully using the perf map, the
reported symbol information will have the original module's name,
so we don't lose fidelity.
The motivation for this change is the way symbols work with .NET
Core on Linux. The runtime binaries are compiled …
=> cc: Retry symbol resolution using perfmap

src/python/bcc/__init__.py
Signed-off-by: Gabriel Ganne <gabriel.ganne@enea.com>
Signed-off-by: Romain Ly <romain.ly@enea.com>
=> add XDP return values to python interface

tools/old/offwaketime.py
happened to want this on a 4.4 system...
=> offwaketime.py for older kernels

debian/changelog
=> Prepare debian changelog for v0.3.0 tag

tools/tcplife.lua
=> tcplife for Lua.

tools/solisten.py
Replaces the `netaddr` library with `socket`. `netaddr` isn't installed by
default on several distributions.
Fixes #1035.
/cc @brendangregg @goldshtn
=> solisten: replace netaddr with socket library

docs/reference_guide.md, docs/tutorial_bcc_python_developer.md
Fix the documentation mistakes introduced in #1076
=> Fix some documentation mistakes

src/cc/BPF.cc, src/cc/BPF.h, src/cc/perf_reader.c, tools/offwaketime_example.txt
This PR consists of:
- Moving non-templated function in C++ API from header to source code
- C++ API style improvements
- Fix format string warning in `perf_reader`
- Fix `offwaketime` documentation typo
=> Miscellaneous style and code layout improvements

man/man8/runqlat.8, tools/runqlat.py, tools/runqlat_example.txt
=> runqlat add --pidnss option

docs/kernel-versions.md
Add a link to the proposed generic XDP feature to the list of XDP features.
=> docs: add generic XDP to XDP compatible list

cmake/FindLuaJIT.cmake
Added the default include path of luajit2.1 for the FindLuaJIT module of cmake.
=> Added the include path of luajit2.1 for the FindLuaJIT module of cmake.

snapcraft/snapcraft.yaml
Minor sorting of the yaml tool list and sync it to the latest
updates in tools
=> Sync snapcraft yaml with tools and ensure list is sorted alphabetically

tests/python/test_clang.py, tools/sslsniff.py, tools/wakeuptime.py
This PR contains several misc fixes for 2 tools and 1 test that either were
failing the verifier or crashing the process on my system.
=> Miscellaneous tools and test fixes

src/cc/libbpf.c
explicit the type of the nlattr
=> bfp, xdp: make type explicit

src/cc/bcc_syms.cc
#1002 is an awesome fix for nested functions. However it causes that for unknown symbols, we will bascially go through the entire list of symbols, which could be bad for large binaries / perf maps.
This change fixes the issue.
cc @markdrayton @goldshtn
=> Avoid walking all symbols for unknown address

src/python/bcc/__init__.py, src/python/bcc/table.py
This is a follow-up to #1200. More context are discussed there.
This commit changes:
- BPF `PERF_EVENT_ARRAY ` supports delete operation unlike regular array maps. Use that on clean-up instead of the "fake" delete from `ArrayBase`.
- Python `PerfEventArray` class is used for both `perf_submit / bpf_perf_event_output` and `perf_read / bpf_perf_event_read`. Differentiate them on clean-up and do proper clean-up respectively.
- Clean-up `PerfEventArray` instances on `BPF` instance exit.
For most of our script tools, this won't make a big difference since they just exit after finish running. But for more complicated and continuous use cases this would be helpful.
=> Improve PerfEventArray clean up

tests/python/test_usdt.py
=> Add probe result verification for usdt unit test

tests/python/test_uprobes.py
Treat strings as bytes. This is independent of the larger refactor
(#1139) from which it is cherry-picked)
=> test: python3 fix for test_uprobes

docs/reference_guide.md, src/cc/export/helpers.h, tests/python/test_percpu.py
Tiny patch to add helpers for PERCPU_ARRAY.
=> Added helpers for BPF_PERCPU_ARRAY

docs/kernel-versions.md
And fix a typo: direct_action -> direct-action
I could not find a tree with ARM32 JIT applied (just the [mail stating](https://www.spinics.net/lists/netdev/msg440291.html) it was applied). If someone has a link, please do not hesitate to replace mine.
=> docs: update features list

src/cc/BPF.cc, src/cc/BPF.h, src/cc/BPFTable.cc, src/cc/BPFTable.h, src/cc/libbpf.h
Another change to bring the C/C++ API more in line with the Python one.
=> Add open_perf_event to the C/C++ API

tools/lib/ucalls.py
Signed-off-by: Geneviève Bastien <gbastien@versatic.net>
=> tools: Add some documentation to lib/ucalls.py output

src/cc/compat/linux/bpf.h, src/cc/compat/linux/virtual_bpf.h
This pull request updates bpf.h and virtual_bpf.h to 4.13-rc1.
=> Update bpf.h and virtual_bpf.h to 4.13-rc1

docs/tutorial_bcc_python_developer.md
Update tutorial to change the file name.
=> Update obsolete file name bitesize -> bitehist

CODEOWNERS
=> Add MAINTAINERS file with list of code owners

CODEOWNERS
=> Add /tests/ to CODEOWNERS

examples/networking/vlan_learning/vlan_learning.c
=> examples: fix vlan_learning example

docs/tutorial_bcc_python_developer.md, examples/tracing/sync_timing.py
Modified the docs and example to make a fix for https://github.com/iovisor/bcc/issues/139
=> Fix for bug in lesson 4 of the Python developer tutorial

snapcraft/snapcraft.yaml
=> Add missing nfsdist and nfsslower to snap

tests/python/test_debuginfo.py
The first symbol from `/proc/kallsyms` is read by `test_debuginfo` and the name obtained here is compared against the name obtained from the `BPF.ksym()` library call. In some architectures such as `powerpc64le`, a kernel symbol may have multiple aliases that refer to the same address. So, to avoid the test from failing, we need to compare the name returned by `BPF.ksym()` against all possible aliases for the given address in `/proc/kallsyms` and look for a match.
=> Fix 'test_debuginfo' from failing if a kernel symbol has multiple aliases

examples/networking/dns_matching/dns_matching.c, examples/networking/dns_matching/dns_matching.py
Also mentioned about this in my previous PR.
=>  examples:dns_matching: make it work as a DNS sniffer

src/cc/bcc_syms.cc
This is an attempt to address #1373. I'm not sure why it would happen or if it's indeed the reason of that `SEGFAULT` but it definitely could be.
@diamond-lizard If you could try if this patch solves your issue?
=> Avoid potential SEGFAULT when resolving Kernel symbols

src/cc/compat/linux/bpf.h, src/cc/compat/linux/virtual_bpf.h
=> sync src/cc/compat/linux headers with latest net-next

debian/changelog
=> Prepare debian changelog for v0.4.0 tag

src/python/bcc/table.py
=> Exit on EPIPE

tools/mdflush.py
[Starting Linux 4.14](https://github.com/torvalds/linux/commit/74d46992e0d9dee7f1f376de0d56d31614c8a17a), there's one less indirection layer to get the
disk name.
=> mdflush: fix for Linux 4.14

tools/bashreadline.py, tools/bpflist.py, tools/dbslower.py, tools/lib/ucalls.py, tools/memleak.py, tools/nfsslower.py, tools/sslsniff.py, tools/tcptop.py, tools/tcptracer.py, tools/trace.py
Would it be possible to enable Travis CI for the repo **before** merging this pull request?
=> Linter cleanups

src/cc/CMakeLists.txt
Make sure libbpf.so is also versioned.
=> Add soname to libbpf.so

docs/tutorial_bcc_python_developer.md
Sorry, nitpick, but it was confusing me a bit while going through it.
=> Consistently use spaces in C in Python tutorial

src/cc/frontends/clang/b_frontend_action.cc
Kernel Commit 29e48ce87f1e ("task_struct: Allow randomized layout")
(https://patchwork.kernel.org/patch/9797817/)
permits to randomize a section of kernel task_struct data
structure. This only takes effect when CONFIG_GCC_PLUGINS and
CONFIG_GCC_PLUGIN_RANDSTRUCT are set.
When randomization does not happen, an anonymous struct
is introduced in task_struct data structure by gcc when compiling
the kernel. To make field offset compatible, task_struct will
have the same anonymous struct. The patch is at
http://www.spinics.net/lists/kernel/msg2644958.html.
Otherwise, bpf program may get wrong data from the kernel.
Currently, bcc bpf_probe_read rewriter does not support
anonymous struct/union. For example, with the above
compiler-clang.h patch, examples/tracing/task_switch.py
will have the …
=> change frontend rewriter to better handle anonymous struct/union

src/cc/libbpf.c
After https://github.com/torvalds/linux/commit/f91840a32deef5cb1bf73338bc5010f843b01426, BPF support all perf events including `HW_CACHE`, `RAW` and dynamic PMU events etc. This commit updates the check in BCC that only allows `HARDWARE` and `SOFTWARE` events. Also updates error message to be more informative from user feedback.
=> Update perf event type and config checks

INSTALL.md
Update info about installing stable packages
for Ubuntu Xenial in INSTALL.md
Fixes:#1440
=> Update info about Ubuntu Xenial in INSTALL.md

README.md, introspection/bps_example.txt, man/man8/bps.8
This patch adds a man page for bps.c and also introduces
bps in README.md
Signed-off-by: Martin KaFai Lau <kafai@fb.com>
=> man/bps: Add a man page for introspection/bps.c

debian/changelog
=> Prepare debian changelog for v0.5.0 tag

src/cc/libbpf.c
=> Do not print to stderr if user specified log buffer

src/python/bcc/table.py, tests/python/test_histogram.py
When there are multiple fields in the secondary key of a histogram
(e.g. output the bio latency for each combination of disk and blk cgroup),
if the buckets are not sorted before the iteration, the output order
of tables often does not meet our expectations.
So provide a way to sort them.
=> histogram: support sorting bucket before dumping table

src/cc/compat/linux/bpf.h, src/cc/compat/linux/virtual_bpf.h
=> sync bpf compat headers with latest net-next

src/cc/bcc_elf.c
The patch fixed issue #1528. The linker ld.gold may generate
a probe with invalid virtual address if the section which the probe
relocates against is discarded.
Instead of failing, a simple checking is added such that
if the probe virtual address is less than the address of the first
instruction, print out a warning and ignore this probe.
=> usdt: ignore location with incorrect probe virtual address

man/man8/tcpaccept.8, man/man8/tcpretrans.8
Hi,
I noticed a couple of small naming mismatches when I was looking through the man pages. This patch fixes the ones I noticed.
=> Small fixes to some man pages for bcc tools

docs/tutorial.md
I added a few trace.py examples in tutorial.md which I encountered inside Facebook. I thought they are useful to give people a sense how trace.py may help them solve their particular issue without writing a full-fledged python/C++ BCC programs. In the future, more examples about trace.py, argdist.py, funccount.py can be added based on real use cases.
cc @brendangregg @goldshtn Please review and suggest a better place if you think tutorial.md is not appropriate. 
=> Add a few trace.py examples in tutorial.md

tools/trace.py, tools/trace_example.txt
there is no straight forward example of how to use filtering for situation when you are using custom function's signature. this diff is adding it
=> adding filtering example to trace.py help

src/cc/perf_reader.c
Fix issue #1533.
Currently, there exist a race condition between perf_reader
buffer munmap and read if they are happening in two different
threads, crash is possible as in issue #1533.
thread 1                    thread 2
perf_reader_event_read      ...
detach_probe
munmap
access ring buffer
detach_probe may happen as part of bpf object cleanup process at which point
thread 1 is still alive. In this case, accessing ring buffer may
cause segfault since the original mmap'ed memory is not available
any more.
It is hard to fix such races outside bcc since user
calls kprobe_poll which has valid BPF object when it is called,
but race happens inside the kprobe_poll.
This patch adds a state of the ring buffer and the read will
not happen once the state comes to the munmap.
Signed-off-by: Yonghong …
=> fix a race condition between perf_reader munmap and read

man/man8/funccount.8
Finish man page update for b03d9eb25e72.
=> Update man page for funccount

src/cc/frontends/clang/CMakeLists.txt, src/python/bcc/table.py, tools/opensnoop.py
Here are 3 miscellaneous patches while I prepare the broader set of changes for making BCC work with BPFd.
=> Miscellaneous BCC patches

examples/cpp/TCPSendStack.cc, examples/lua/memleak.lua, examples/lua/offcputime.lua, examples/tracing/mallocstacks.py, examples/tracing/stacksnoop.py, src/cc/export/helpers.h, tools/memleak.py, tools/offcputime.py, tools/offwaketime.py, tools/old/profile.py, tools/profile.py, tools/stacksnoop.lua, tools/wakeuptime.py
small fixes in examples/cpp/TCPSendStack.cc and tools/profile.py
=> Small fixes

docs/reference_guide.md, examples/networking/tunnel_monitor/monitor.c, src/cc/export/helpers.h, tests/python/test_brb.c, tests/python/test_call1.c, tests/python/test_clang.py
These commits are mainly to document bpf_tail_call(). For convenience, a new macro, BPF_PROG_ARRAY, is defined to replace BPF_TABLE("prog"), and a new section is created to introduce BPF_PROG_ARRAY.
=> Document bpf_tail_call()

tests/cc/test_c_api.cc
This will allow the bcc to be built on Alpine without additional
patches to musl.
=> Do not rely on RTLD_DI_ORIGIN

src/cc/perf_reader.c
Currently running "trace.py --max-events #" (shortname "trace.py -M #")
will hang like below:
```
-bash-4.2$ sudo ./trace.py -M 2 'SyS_futex'
PID     TID     COMM            FUNC
137727  138229  IOThreadPool0   SyS_futex
138250  151288  OBC Dispatcher  SyS_futex
^C^Z
[1]+  Stopped                 sudo ./trace.py -M 2 'SyS_futex'
-bash-4.2$
```
The hang happens in perf_reader_free.
Commit cd5d4a6ce519 ("fix a race condition between perf_reader
munmap and read") fixed a race condition by adding some coordination
between perf_reader_event_read and perf_reader_free.
In this case, however, the callback function inside perf_reader_event_read
never returns and actually calling exit(). This is because
the maximum number of perf_events have been received. The exit()
is calling BPF object cleanup() …
=> fix hang with "trace.py --max-events #"

src/cc/bpf_module.cc
bcc utilizes MCJIT to generate final code and the code
is actually runnable in the process. This, however,
may have negative memory consumption impact.
All data will be actually allocated in memory.
For example, the following large array,
```
#define TCP6_RXMIT_BUCKET_BITS 18
struct tcp6_rxmit_tbl {
__u64 buckets[1 << TCP6_RXMIT_BUCKET_BITS];
};
BPF_ARRAY(rxmit_marking_map, struct tcp6_rxmit_tbl, 1);
```
is added to examples/cpp/HelloWorld.cpp.
Internally, bcc will define a structure type rxmit_marking_map_table
with members `struct tcp6_rxmit_tbl leaf` and a variable
with this structure type. (see src/cc/export/helpers.h),
so that rw_engine can traverse the type to generate
proper sscanf/snprintf functions.
Even with rw_engine is disabled, the RSS still increased
from 6MB to 12MB. The …
=> free llvm engine/context memory when rw_engine is not used

tools/biosnoop.lua
These fixes were introduced in `biosnoop.py` in #675 and #889 but never ported to `biosnoop.lua`. Copy the fixes over and now `biosnoop.lua` works as well.
=> Port fixes of biosnoop from Python to Lua

LINKS.md
Updates the `LINKS.md` file with links to recent articles on LWN.net.
=> Links to recent articles on LWN.net

docs/reference_guide.md, docs/tutorial.md
fix some spelling mistakes in doc
=> fix some spelling errors

docs/reference_guide.md, man/man8/inject.8, tools/inject.py, tools/inject_example.txt
Added the optional probability of failure discussed at #1633, additionally updated some documentation to reflect patches getting into mainline.
=> Add features/docs for inject (4.17)

tools/runqlat.py
Currently runqlat.py installs kprobes on enqueue_task_*() and finish_task_switch() kernel functions,
however, enqueue_task_*() are not good kprobe points, because a task could be moved from one
runqueue to another, in which case enqueue is called twice.
Ideally, we should switch to tracepoints `sched_wakeup`, `sched_wakeup_new` and `sched_switch`,
which is basically what `perf sched` uses. However, the tgid is not exposed via these tracepoints
yet and current is set after trace_sched_switch(). So I pick the internal kernel functions which
calls these tracepoints.
=> Use better kprobes for runqlat.py

tools/offwaketime.py
Currently, `offwaketime.py` uses the same TGID for symbol resolution. But I think the waker and target theoretically could belong to different TGID and we would get wrong symbols. I wonder if this would help for #1679 (@joelagnel can you try?), but it's the right thing to do anyways.
Also improve documentation a bit.
=> Fix offwaketime PID / TGID handling

tools/offcputime.py, tools/offwaketime.py
Same change as #1692 but for `offwaketime.py`
=> Refactor offwaketime stack id error handling

tools/profile.py
Same as #1692 and #1704, for `profile.py`
=> Refactor profile.py stack id error handling

examples/cpp/RecordMySQLQuery.cc, examples/cpp/TCPSendStack.cc, src/cc/api/BPF.cc, src/cc/api/BPF.h, src/cc/api/BPFTable.cc, src/cc/api/BPFTable.h
- Add type check in table constructor
- `clang-format` files
- Fix `TCPSendStack` example's stack id error handling
=> Misc improvements to C++ API and example

src/cc/frontends/clang/b_frontend_action.cc, src/cc/frontends/clang/b_frontend_action.h, tests/python/test_clang.py
This pull request removes a limitation of #1285, which added initial support for tracking external pointers through maps. There are still limitations with the tracking of external pointers through maps though; the rewriter is still unable to track external pointers if they are passed as members of a structure itself used as a map value or if they are passed through two successive maps (although the latter should be fairly uncommon).
Currently, `MapVisitor` only detects maps with external pointers as values if the value was directly passed from a function's argument. For example, in the following, the rewriter is currently unable to detect `currsock` has an external pointer as value because an intermediate variable is used instead of passing directly `sk` as the map's value.
```c
int …
```
=> Trace all external pointers passed through a first map

debian/bcc-tools.install
=> Add introspection to bcc-tools deb package

debian/changelog
=> Prepare debian changelog for v0.6.0 tag

src/cc/frontends/clang/b_frontend_action.cc, src/cc/frontends/clang/b_frontend_action.h, tests/python/test_clang.py
Somehow github did not merge pull request #1836 properly which is stacked on top of #1831. Maybe stacked pull request does not work? Here, I created a separate pull request for the remaining code of #1836.
=>  Fix external pointer propagation in nested dereferences

src/python/bcc/__init__.py
The KeyboardInterrupt exception should not be handled by the library since it is not related to bpf but rather to an interactive user interaction.
Moreover, handing it by calling the exit function impedes the caller from properly handling the exception depending on the context.
=> Remove handling of KeyboardInterrupt exception

tools/zfsslower.py
Leftover from #986.
Fixes output of raw `bytearrays`. Before:
```
➜ bcc git:(zfsslower-string-decode) sudo /usr/share/bcc/tools/zfsslower 1
Tracing ZFS operations slower than 1 ms
TIME     COMM           PID    T BYTES   OFF_KB   LAT(ms) FILENAME
18:06:30 b'geth'        27155  S 0       0           7.28 b'13502236.ldb'
18:06:30 b'geth'        27155  S 0       0           7.29 b'13502236.ldb'
18:06:30 b'geth'        27155  S 0       0           3.35 b'13502237.ldb'
18:06:30 b'geth'        27155  S 0       0           3.35 b'13502237.ldb'
18:06:31 b'geth'        27155  S 0       0           6.43 b'13502238.ldb'
18:06:31 b'geth'        27155  S 0       0           6.44 b'13502238.ldb'
```
After:
```
➜ bcc git:(zfsslower-string-decode) sudo tools/zfsslower.py 1 …
```
=> Decode C strings into Python strings

INSTALL.md
Ensure dnf points to correct  package name.
=> Fedora-28 install step

src/python/bcc/__init__.py
Tries to resolve issues like #1777. Check if the autoloaded kprobe name looks like a syscall and then replace with correct prefix.
cc @yonghong-song @pchaigno
=> Improve Python autoload syscall name handling

man/man8/llcstat.8, tools/llcstat.py
=> Mention perf as universal counting tool in llcstat

docs/reference_guide.md, docs/tutorial.md, docs/tutorial_bcc_python_developer.md, examples/tracing/mallocstacks.py, examples/tracing/strlen_count.py, examples/tracing/task_switch.py, tools/cachestat.py, tools/cachetop.py, tools/hardirqs.py, tools/llcstat.py, tools/offcputime.py, tools/offwaketime.py, tools/profile.py, tools/softirqs.py, tools/stackcount.py, tools/tcpretrans.py, tools/tcpsubnet.py, tools/tcptop.py, tools/vfscount.py, tools/wakeuptime.py
Update scripts under `tools/` to use `$map.increment` and documentation examples.
- The 1st commit replaces the increments by 1
- The 2nd commit replace increments of steps bigger than 1, as introduced in #1897 
- The 3rd one updates the documentation
cc/ @bobrik
=> Update scripts to use `increment`

docs/kernel-versions.md, introspection/bps.c, src/cc/compat/linux/bpf.h, src/cc/compat/linux/virtual_bpf.h, src/cc/export/helpers.h, src/cc/libbpf.c
=> sync header to latest net-next

tools/argdist.py
Signed-off-by: Ahao Mu <muahao@linux.alibaba.com>
=> [tools/argdist.py] Fix a wrong place of help info

INSTALL.md
Added in RHEL 7.6 Beta information
=> updated for RHEL

tools/tcpaccept.py, tools/tcpconnect.py, tools/tcpconnlat.py, tools/tcpdrop.py, tools/tcplife.py, tools/tcpretrans.py, tools/tcpstates.py, tools/tcptop.py
Finish the conversion started with commit 36ce1124.
Minor tweaks to make the tools consistent within themselves.
=> tcp tools: finalize data type conversion

Dockerfile.ubuntu, debian/control
Tested:
- Ubuntu/arm64 [this PR]
- Debian/arm64 [not covered by this PR]
- Ubuntu/amd64 [no regression]
- Debian/amd64 [no regression]
=> Enable Ubuntu/arm64 deb packaging

src/cc/api/BPFTable.cc, src/cc/api/BPFTable.h, tests/cc/test_bpf_table.cc
get_offline_table is missing in the BPFTable class.
=> cc: add BPFTable::get_offline_table

tools/cachestat.py, tools/lib/ucalls.py, tools/lib/uflow.py, tools/lib/ugc.py, tools/lib/uobjnew.py, tools/lib/ustat.py, tools/lib/uthreads.py, tools/tcpsubnet.py
Use argparse in cachestat, add --ebpf support.
Add --ebpf support for u* tools, finalize language sorting.
Remove sole --ebpf string on usage line in tcpsubnet.
=> tools: continue adding --ebpf support

INSTALL.md
As per https://github.com/iovisor/bcc/issues/1854#issuecomment-407492446
=> Update INSTALL.md to include Ubuntu Bionic (18.04)

tools/killsnoop.py
=> fix killsnoop.py srr/bytes type error

src/cc/bcc_syms.cc
Please see issue #1998 for details.
=> Fix USDT semaphore address calculation for PIE

man/man8/capable.8, tools/capable.py, tools/capable_example.txt
In addition, prevent capable from reporting itself in the trace.
Signed-off-by: Andrea Righi righi.andrea@gmail.com
=> capable: add user and kernel stack trace options

man/man8/inject.8, tools/inject.py
Signed-off-by: Nicolas Saenz Julienne <nsaenzjulienne@suse.de>
=> inject: add option to limit number of overrides

examples/networking/xdp/xdp_drop_count.py
Also, fix an incorrect indentation in the same block.
Fixes https://github.com/iovisor/bcc/issues/2048
=> Remove duplicate code from xdp_drop_count.py

man/man8/tcpstates.8, tools/tcpstates.py, tools/tcpstates_example.txt
Add a -Y/--journal flag to tcpstates.py, which logs events to the
systemd journal.
=> tcpstates: Add systemd journal logging.

docs/kernel-versions.md, src/cc/compat/linux/bpf.h, src/cc/compat/linux/virtual_bpf.h, src/cc/export/helpers.h, src/cc/libbpf.c
The header file will be in sync with the 4.21 rc1.
=> sync with latest net-next bpf uapi headers

docs/tutorial.md
=> tutorial: align the header in opensnoop

tools/tcpaccept.py
=> tools: allow tcpaccept filter via PID

INSTALL.md
=> INSTALL.md: add new Ubuntu bpfcc-tools package name

debian/changelog
debian changelog for v0.8.0 tag
=> Prepare debian changelog for v0.8.0 tag

src/cc/libbpf.c
Recently kernel libbpf was imported in bcc. It makes some of the
libbcc code redundant. This patch modifies libbcc functions to use
libbpf APIs.
=> use libbpf APIs in libbcc

src/cc/libbpf.c
Use libbpf api bpf_set_link_xdp_fd() to attach xdp program to an
interface.
=> use libbpf api in bpf_attach_xdp

INSTALL.md
Sign-Off-By Travis Davies <trdavies@amazon.com>
=> Add installation instructions for Amazon Linux 1 AMI

src/cc/bcc_elf.c
bcc on Ubuntu picks up the glibc binary instead of the debuginfo file
because find_debug_via_debuglink() doesn't handle symbolic or hard
links when checking if two paths point to the same file.
Add a helper, same_file() which uses the device and inode to check if
the two paths do point to the same file.
Signed-off-by: Anton Blanchard <anton@ozlabs.org>
=> Fix debuginfo search on Ubuntu

examples/tracing/bitehist.py
Add an example of linear histogram, which might be useful to newcomers.
And also update the comments.
=> examples/tracing/bitehist.py: add example of linear histogram

tools/ext4dist.py
- Dynamically handle different ext4_file_operations
(avoid wasting extra cycles).
- make the code pep8 compliant
- clarify comments
Signed-off-by: Andrea Righi <righi.andrea@gmail.com>
=> ext4dist: code cleanup (#2181)

examples/networking/simple_tc.py, examples/networking/simulation.py, examples/networking/tc_perf_event.py, examples/networking/xdp/CMakeLists.txt
Minor fixes for the networking example scripts
=> Fix network examples

debian/changelog
debian changelog for v0.9.0 tag
=> Prepare debian changelog for v0.9.0 tag

README.md, man/man8/drsnoop.8, tests/python/test_tools_smoke.py, tools/drsnoop.py, tools/drsnoop_example.txt
Trace direct reclaim and print details including issuing PID.
=> add a new bcc tool drsnoop

man/man8/biosnoop.8, tools/biosnoop.py, tools/biosnoop_example.txt, tools/biotop.py
I also cleaned up the output logic.
=> biosnoop: add -Q for queued time

man/man8/bitesize.8, tools/bitesize.py
Sorry, should have used issue. insert rarely fires.
=> bitesize: switch to insert tracepoint

tools/memleak.py
Add an ability to trace percpu allocations using the memleak tool.
Example:
./memleak.py --percpu
Attaching to kernel allocators, Ctrl+C to quit.
[14:15:46] Top 10 stacks with outstanding allocations:
8 bytes in 1 allocations from stack
pcpu_alloc+0x3d8 [kernel]
pcpu_alloc+0x3d8 [kernel]
perf_trace_event_init+0xc9 [kernel]
perf_trace_init+0x69 [kernel]
perf_tp_event_init+0x1b [kernel]
perf_try_init_event+0x42 [kernel]
perf_event_alloc+0x620 [kernel]
__do_sys_perf_event_open+0x188 [kernel]
do_syscall_64+0x48 [kernel]
entry_SYSCALL_64_after_hwframe+0x44 [kernel]
16 bytes in 1 allocations from stack
pcpu_alloc+0x3d8 [kernel]
pcpu_alloc+0x3d8 [kernel]
bpf_prog_alloc+0x33 [kernel]
bpf_prog_load+0xf5 [kernel]
perf_event_for_each_child+0x34 [kernel]
_perf_ioctl+0x1d7 [kernel] …
=> tools: add percpu allocator tracing to memleak

docs/reference_guide.md
Hopefully not a very controversial change but happy to make any changes which would help get this merged in :)
=> Add timeout to perf_buffer_poll docs

docs/tutorial_bcc_python_developer.md
A sentence was leftover from before we could auto-generate the Python data structure.
=> tutorial_bcc_python_developer: Finish auto-generated update

docs/kernel-versions.md, introspection/bps.c, src/cc/compat/linux/virtual_bpf.h, src/cc/export/helpers.h, src/cc/libbpf.c
sync to latest libbpf and update other parts of bcc as well.
=> sync to latest libbpf

examples/networking/xdp/xdp_macswap_count.py
Signed-off-by: forrestchen <forrestchen@tencent.com>
=> fix proto compare bug in example

debian/changelog
=> Prepare debian changelog for v0.10.0 tag

README.md, man/man8/exitsnoop.8, tools/exitsnoop.py, tools/exitsnoop_example.txt
This is a resubmission of https://github.com/iovisor/bcc/pull/2349 from an Instana, Inc. fork.
This PR also has updates as suggested by @brendangregg, and a refactor by @JeroenSoeters of Insatana to allow import as a python module.
=> tools: Added exitsnoop: Trace all process termination

snapcraft/Makefile, snapcraft/bcc-wrapper
Minor fixes to snapcraft builds
=> A couple of snapcraft fixes

src/cc/compat/linux/virtual_bpf.h
=> sync with latest libbpf repo

src/python/bcc/__init__.py
Instead of having two different code paths for code passed in as a
string (via the text parameter) and code passed in via file (via the
src_file parameter), load the contents of src_file into the text
variable and handle both in the same code path.
This fixes issue #2385.
=> Handle the text and src_file the same way in the BPF constructor

INSTALL.md, src/cc/common.h
Fixes build errors with some compilers.
Signed-off-by: Kyle Zhang <kyle@smartx.com>
=> Use the STL's make_unique if available

tools/btrfsslower.py
Datetime comparisons requires the use of timedelta.
=> Error in time comparison

introspection/bps.c, src/cc/compat/linux/virtual_bpf.h
=> sync to latest libbpf repo

tools/bashreadline.py
Prevents the output of non-bash readlines when bash is dynamically
linked. Refs #1851.
=> bashreadline: Filter out non-bash COMMs

src/cc/bcc_elf.c
Symfs is a file path prefix that needs to be prepended to full path of a library
to compute location of corresponding debuginfo. It will allow bcc users to
provide debug symbols if only they can write to at least one directory. Nothing
else needs to be assumed regarding the system bcc runs on.
My intention is to make debuginfo lookup work on Android in one form or another.
None of the gdb rules works out of the box:
- native libraries are often managed by Android apps themselves and uncompressed
by apps into private directories. Sideloading debuginfo into those directories
might not be feasible. What's more it's desirable to remove data like
debuglink from release builds of mobile apps. At the same time those builds
are the most interesting ones to investigate with bcc.
- there is no /usr …
=> Support perf's symfs mechanism for debuginfo lookup.

README.md
=> Changed Link to HTTPS

tools/drsnoop_example.txt, tools/runqslower_example.txt
the 'min_us' should be in 'us', not 'ms'
=> Mod: the 'min_us' is in us, not ms

src/cc/bcc_btf.cc
The following test case failed:
```
-bash-4.4$ cat test.py
#!/usr/bin/python
prog="""
BPF_ARRAY(array1, u64, 1);
BPF_ARRAY(array2, u64, 1);
"""
b=BPF(text=prog, debug=0x20)
-bash-4.4$ sudo ./test.py
libbpf: Error loading BTF: Invalid argument(22)
libbpf: magic: 0xeb9f
version: 1
flags: 0x0
hdr_len: 24
...
[57] DATASEC array size=176 vlen=2
type_id=47 offset=0 size=88
type_id=49 offset=0 size=88 Invalid offset
Loading .BTF section failed
-bash-4.4$
```
The reason is the data offset in DataSec VarInfo
(e.g., type_id=47 offset=0 size=88) always have
offset=0 since JIT won't do a final relocation
for the record. Assign offset properly
in bcc_btf before loading btf to the kernel.
With this patch, test case can load btf properly.
```
-bash-4.4$ cat test.py
#!/usr/bin/python …
```
=> assign offset properly for btf DataSec

tools/tcpretrans.py
If tracepoint tcp:tcp_retransmit_skb exists (kernel version >=4.15)
we use tracepoint instead of kprobe for efficiency.
Co-authored-by: Runlong Lin <linrunlong@bytedance.com>
=> tools/tcpretrans: add tracepoint support

tools/runqslower.py
Closes: #2588
It is was observed that the same PID can show up many
times to many unrelated processes. The exact cause of
this is unknown but highly likely (speculation) a race condition.
Removing the default (if supported) raw tracepoint option along
with the raw tracepoint code.
=> tools/runqslower.py: Fix raw tracepoint code

src/cc/libbpf.c
A privileged user can load bpf program whose size is at most
BPF_COMPLEXITY_LIMIT_INSNS (which is larger than BPF_MAXINSNS) in 
Linux 5.3 (https://github.com/torvalds/linux/commit/c04c0d2b968ac45d6ef020316808ef6c82325a82).
Currently, however, `bcc_prog_load_xattr()` return error if  a bpf
program size is larger than BPF_MAXINSNS before loading the program. To
cope with this, change the function so that first trying to load a bpf
program and print an error message if bpf_program_load_xattr() fails
with -E2BIG.  This strategy is the same as libbpf's [`load_program`](https://github.com/libbpf/libbpf/blob/9ef191ea7dca6815e75dab341f2f7a346d979c66/src/libbpf.c#L3792).
The Error message should use BPF_COMPLEXITY_LIMIT_INSNS when
appropriate, but it is not defined in uapi headers yet. …
=> Support a BPF program larger than BPF_MAXINSNS

man/man8/trace.8, tools/trace.py, tools/trace_example.txt
add filter of process name and msg
=> Trace add filter

introspection/CMakeLists.txt, src/cc/compat/linux/virtual_bpf.h
sync with latest upstream libbpf version 0.0.6.
=> sync with latest libbpf

src/cc/frontends/clang/b_frontend_action.cc, tests/python/test_clang.py
The rewriter tracks, with `nb_derefs`, the number of indirections of external pointers, to rewrite only the appropriate dereference into a call to `bpf_probe_read`.
In `ProbeChecker`, however, `nb_derefs` has a different meaning: it counts the number of dereferences encountered. This difference resulted in an error when `ProbeChecker` is traversing the right-hand side of an assignment. This pull request fixes the error and adds tests for the two cases of assignments: (1) when the right-hand side is an external pointer with several indirection levels and (2) when it is a call to a function returning an external pointer with several indirection levels.
This pull request also changes `ProbeSetter` and `assignsExtPtr` to count dereferences instead of addrof in an effort to use `nb_derefs` …
=> rewriter: Fix tracking of pointers with several indirections

docs/kernel-versions.md
=> docs: add BPF trampoline to the kernel features

src/cc/libbpf.c, tests/cc/test_usdt_probes.cc
On the legacy path, for kernels that don't support creating uprobes via
the perf_event_open (kernels prior to e12f03d), the path to the probe is
already absolute, including /proc/PID/root prefix. Unless the target process
is running within the host PID namespace, this path will be invalid.
This should fix #2558 for older kernels
Older kernels (in my case, 4.14 on Chromium-based OS) use this branch to initialize probes:
https://github.com/iovisor/bcc/blob/ae5a169a0e9e47b57b7e3a8cc2c514e7ad4f3813/src/cc/libbpf.c#L1023-L1028
Rather than the newer (default) approach:
https://github.com/iovisor/bcc/blob/ae5a169a0e9e47b57b7e3a8cc2c514e7ad4f3813/src/cc/libbpf.c#L1020-L1021
The path specified by `config1` was modified in https://github.com/iovisor/bcc/pull/2324 to prepend `/proc/PID/root`, to …
=> Don't enter target process mount NS for uprobes

docs/reference_guide.md, src/cc/api/BPF.cc, src/cc/api/BPF.h, src/cc/api/BPFTable.cc, src/cc/api/BPFTable.h, src/cc/export/helpers.h, src/cc/frontends/clang/b_frontend_action.cc, src/python/bcc/table.py
This PR adds support for XSKMAP. 
Ref for the code: https://github.com/iovisor/bcc/pull/1979/commits/814024f6094409e0166d431c784d05a09cc78f65 and https://github.com/iovisor/bcc/commit/87a873f74afe931757290283aed44c6c0b8558f4
addresses https://github.com/iovisor/gobpf/issues/193 and part of https://github.com/iovisor/bcc/issues/2460
=> Add XSKMAP support

src/cc/frontends/clang/b_frontend_action.cc
Fix #2739.
The issue exposed an issue that to rewrite
CODE1: __u8 byte = daddr->s6_addr[4];
will segfault and to rewrite
CODE2: __u8 byte = (daddr->s6_addr)[4];
will be okay.
For CODE1, the clang did not give enough information to find the text
which contains the left bracket "[", given base "daddr->s6_addr"
and subscript "4". For CODE2, the clang is able to get the information
successfuly.
I think if we really go inside the base "daddr->s6_addr" and gets to
its member field "s6_addr", we can find the needed information
for the text range containing "[". Let us fix the segfault first
and if really desirable, we can try to enhance later for CODE1 patterns.
=> Do not rewrite array subscripts if invalid sourceloc range

INSTALL.md
based on the following request: https://github.com/iovisor/bcc/pull/2686#issuecomment-578008483
=> correctly describe installation situation for Ubuntu

src/cc/api/BPF.cc, src/cc/api/BPFTable.cc, src/cc/api/BPFTable.h, src/cc/bpf_module_rw_engine.cc, src/cc/frontends/b/codegen_llvm.cc, src/cc/frontends/b/printer.cc, src/cc/frontends/b/type_check.cc
With the following shell command:
$ find src -type f -regex '.*\.\(h\|cc\)' -exec sed -i 's/StatusTuple(0)/StatusTuple::OK()/' {} \;
=> Replace StatusTuple(0) with StatusTuple::OK()

INSTALL.md
I was going through the process of building LLVM and Clang and stumbled upon this gem, https://forums.aws.amazon.com/thread.jspa?threadID=318439.
Lo and behold, it's there and it drastically simplifies my life.
=> chore: include Amazon Linux 2 binary option in INSTALL

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/filelife.bpf.c, libbpf-tools/filelife.c, libbpf-tools/filelife.h
=> libbpf-tools: add CO-RE filelife

examples/tracing/mallocstacks.py
1. to print information about size.
2. using perf_submit now.
3. validating segmentation fault due to missing check before stack walk.
=> Improved mallocstack

examples/networking/http_filter/http-parse-simple.py
Fix https://github.com/iovisor/bcc/issues/2168
Signed-off-by: Jean-Philippe Menil <jpmenil@gmail.com>
=> http-parse-simple.py: fix wrong start position

tools/filelife.py
Update filelife pid filter;  
u32 pid = bpf_get_current_pid_tgid() >> 32;
=> Update filelife pid filter

examples/tracing/biolatpcts.py, examples/tracing/biolatpcts_example.txt, man/man8/biolatpcts.8, tools/biolatpcts.py, tools/biolatpcts_example.txt
Expand the example into more fully developed tool and add documentation and simplified example as suggested in #2861.
=> Expand io_latencies example to iolatpcts tool

INSTALL.md
related: 
https://github.com/iovisor/bcc/issues/2678
https://github.com/iovisor/bcc/pull/2747
=> Improve ubuntu installation description

debian/changelog
added changelog for release v0.14.0
=> prepare for release v0.14.0

tools/nfsdist.py
add ability to detect if the nfsv4 symbols are availabe or not and fall back to nfsv3.
=> add nfs v3 support to nfsdist.py

src/python/bcc/__init__.py
With lockdown enabled one sees the following:
```
$ sudo /usr/share/bcc/tools/funccount -Ti 1 run_timer_softirq
[Errno 1] Operation not permitted: '/sys/kernel/debug/tracing/../kprobes/blacklist'
```
Which is accompanied by the following in `dmesg`:
```
[Fri May 29 22:12:47 2020] Lockdown: funccount: debugfs access is restricted; see man kernel_lockdown.7
```
Since blacklist is not a required feature, let's make
reading from it optional, so that bcc can work out of the box.
=> Make reading blacklist from debugfs optional

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/drsnoop.c, libbpf-tools/errno_helpers.c, libbpf-tools/errno_helpers.h, libbpf-tools/filelife.c, libbpf-tools/syscall_helpers.c, libbpf-tools/syscall_helpers.h, libbpf-tools/syscount.bpf.c, libbpf-tools/syscount.c, libbpf-tools/syscount.h, libbpf-tools/xfsslower.c
This PR converts BCC syscount to BPF CO-RE version and fixes some simple typos
=> Syscount libbpf

README.md, man/man8/funcinterval.8, tools/funcinterval.py, tools/funcinterval_example.txt
Time interval between the same function as a histogram.
Referenced from funclatency.
=> tools: Add funcinterval bcc tool.

man/man8/offwaketime.8, tools/offwaketime.py, tools/offwaketime_example.txt
Here's multi PID/TID support for offwaketime tool.
=> Add support for multiple PID/TID for offwaketime

tools/opensnoop.py
Fix stupid bug introduced by myself.
Signed-off-by: Mauricio Vásquez <mauricio@kinvolk.io>
=> tools/opensnoop: Fix compilation problem

src/cc/compat/linux/virtual_bpf.h
sync with libbpf version 0.0.9.
=> sync with libbpf v0.0.9

src/cc/api/BPFTable.cc
Signed-off-by: Gaurav Singh <gaurav1086@gmail.com>
Remove duplicate expression.
=> [BPFTable] clear_table_non_atomic: Remove duplicate macro

debian/changelog
added changelog for release v0.15.0
=> prepare for release v0.15.0

tools/profile.py
When we do stack traces via stackmaps, hash collisions (-EEXIST) may indicate
that the map size is too small. Not -ENOMEM.
=> tools/profile: fix suggestion about when to increase stack-storage-size

INSTALL.md
Signed-off-by: Lorenzo Fontana <fontanalorenz@gmail.com>
Was working on something related to BPF_LSM and found this annoying so I decided to fix it :)
=> docs: fix Ubuntu Eoan spelling

src/cc/bcc_elf.c
Logic for looking up debug file in bcc_elf_symbol_str and foreach_sym_core
differ. This commit factors out relevant code from foreach_sym_core and reuses
it in bcc_elf_symbol_str.
Without this change symfs symbolication of stack traces captured by trace.py on
Android does not work very well. Bpftrace which does not use lazy symbol name
lookup is not affected though.
Stack traces captured with trace.py without this commit:
```
6475    6515    RenderThread    _ZN10EglDisplay10InitializeEv
b'EglDisplay::Initialize()+0x0 [libGLESv2_adreno.so]'
b'[unknown] [libEGL.so]'
b'[unknown] [libhwui.so]'
b'[unknown] [libhwui.so]'
b'[unknown] [libhwui.so]'
b'[unknown] [libhwui.so]'
b'[unknown] [libhwui.so]'
b'[unknown] [libhwui.so]'
b'[unknown] [libutils.so]'
b'[unknown] [libc.so]'
b'[unknown] [libc.so]' …
```
=> fix debug file lookup in bcc_elf_symbol_str

src/cc/frontends/clang/kbuild_helper.cc
The current order of include paths could cause the following error:
In file included from /virtual/main.c:3:
In file included from include/linux/sched.h:13:
In file included from include/linux/pid.h:4:
In file included from include/linux/rculist.h:10:
In file included from include/linux/rcupdate.h:38:
In file included from include/linux/spinlock.h:50:
In file included from include/linux/preempt.h:80:
In file included from /lib/modules/4.12.14-197.45-default/build/arch/s390/include/generated/asm/preempt.h:1:
include/asm-generic/preempt.h:10:42: error: no member named 'preempt_count' in 'struct thread_info'
return READ_ONCE(current_thread_info()->preempt_count);
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
include/linux/compiler.h:349:34: note: expanded from macro 'READ_ONCE' …
=> Adjust the order of linux kernel header include paths

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/biopattern.bpf.c, libbpf-tools/biopattern.c, libbpf-tools/biopattern.h
=> libbpf-tools: add CO-RE biopattern

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/tcpconnlat.bpf.c, libbpf-tools/tcpconnlat.c, libbpf-tools/tcpconnlat.h
=> libbpf-tools: add CO-RE tcpconnlat

docs/tutorial_bcc_python_developer.md
Signed-off-by: zhuangqh <zhuangqhc@gmail.com>
=> doc: fix mismatched link

tools/capable.py
This commit adds the support of below capabilities.
* CAP_PERFMON
* CAP_BPF
* CAP_CHECKPOINT_RESTORE
=> tools/capable: support new capabilities

examples/networking/http_filter/http-parse-complete.c, examples/networking/http_filter/http-parse-simple.c, examples/networking/vlan_filter/data-plane-tracing.c
=> fix retruning typo

INSTALL.md
The Amazon Linux 1 instructions don't work, we end up with compiler errors like so:
<details><summary>build log</summary>
<p>
../../src/cc/frontends/clang/libclang_frontend.a(b_frontend_action.cc.o): In function `ebpf::BTypeVisitor::genParamIndirectAssign(clang::FunctionDecl*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, char const**)':
b_frontend_action.cc:(.text+0x1edc): undefined reference to `clang::Rewriter::getRewrittenText[abi:cxx11](clang::SourceRange) const'
../../src/cc/frontends/clang/libclang_frontend.a(b_frontend_action.cc.o): In function `ebpf::BTypeVisitor::genParamDirectAssign(clang::FunctionDecl*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, char const**)':
b_frontend_action.cc:(.text+0x3412): …
=> Add instructions on how to install amazon linux 2 from source

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/runqlat.bpf.c, libbpf-tools/runqlat.c, libbpf-tools/runqlat.h, libbpf-tools/trace_helpers.c, libbpf-tools/trace_helpers.h
=> libbpf-tools: add runqlat

README.md, man/man8/tcprtt.8, tools/tcprtt.py, tools/tcprtt_example.txt
@brendangregg would you please review this PR?
=> Tcprtt: add --byladdr/--byraddr

tools/biolatency.py
This reverts commit 87792ce6b783941ea1d8bcd29812a55520930c95.
Let us have a consensus about how bcc tools should interact with
external signals etc. before applying such changes to this tool
and other tools.
=> Revert "tools/biolatency: Handle signals from user"

tools/bindsnoop.py, tools/tcpconnect.py
The correct key to use is "tig" instead of "pid".
=> tools: Use correct key key when deleting item from map

tools/sslsniff.py
Fix https://github.com/iovisor/bcc/issues/3126
Signed-off-by: keyolk <chanhun.jeong@navercorp.com>
=> sslsniff: fix comparing bytes to string

tools/netqtop.py
fixed python3 compatible issue referred in #3139 and [pr#3048](https://github.com/iovisor/bcc/pull/3048#issuecomment-710483485)
=> fix netqtop python3 compatible

tools/biolatpcts.py
* When exit is requested through SIGINT, TERM or HUP, output the latency
distribution one more time before exiting.
* Interpret negative interval as infinite.
Combined, this allows using biolatpcts to measure the overall latency
distribution between two events.
=> tools/biolatpcts: Support measuring overall latencies between two events

tools/biolatpcts.py
SIGUSR1's behavior is the same - print and start a new interval. SIGUSR2
triggers output without starting a new interval and can be used to monitor
progress without affecting the accumulation of data points.
=> tools/biolatpcts: Add accumulative reporting on SIGUSR2

INSTALL.md
=> Add build-from-source instructions for Arch Linux

docs/reference_guide.md
https://github.com/iovisor/bcc/issues/3177
=> doc: adjust bpf_ktime_get_ns() document description

docs/tutorial.md
=> Update URL in tutorial documentation [minor]

docs/kernel-versions.md
Document this limitation reported in #347 and #3186
=> 4.18 - Pass map values to map helpers

libbpf-tools/README.md
This blog post shares my experience about writing BPF applications with libbpf. I hope it is helpful to people who are interested in libbpf and inspires them to further develop and improve BPF applications with libbpf.  
Thank you for always give me help!
=> libbpf-tools: update README add a blog link

docs/kernel-versions.md, introspection/bps.c, src/cc/compat/linux/virtual_bpf.h, src/cc/export/helpers.h, src/cc/libbpf.c
with necessary helper definitions and documentations etc.
=> sync with libbpf v0.3

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/cpufreq.bpf.c, libbpf-tools/cpufreq.c, libbpf-tools/cpufreq.h, libbpf-tools/runqlen.c, libbpf-tools/trace_helpers.c, libbpf-tools/trace_helpers.h
The output looks like below:
```sh
➜  libbpf-tools git:(cputools-2) ✗ ./cpufreq -d 10
Sampling CPU freq system-wide & by process. Ctrl-C to end.
...
...
microk8s-kubect : count     distribution
2400       : 1        |****************************************|
2600       : 0        |                                        |
2800       : 0        |                                        |
3000       : 1        |****************************************|
kubelet       : count     distribution
1200       : 26       |****************************************|
1400       : 0        |                                        |
1600       : 0        |                                        |
1800       : 0        |                                        |
2000       : 0        | …
```
=> libbpf-tools: add cpufreq

tests/python/test_histogram.py
kernel commit(cf25e24db61cc) rename tsk->real_start_time to
start_boottime, so test_hostogram will get failed on kernel>=5.5
=> test/test_histogram.py: fix test failed on kernel-5.10

tools/offcputime.py
Follow-up of #3227. Print a warning message when an event skipped by negative duration.
Example output:
```
$ ~/offcputime.py -m 100000 120 >/dev/null                             
WARN: Skipped an event with negative duration: pid:0, tgid:0, off-cpu:660164416, on-cpu:659169004
WARN: Skipped an event with negative duration: pid:0, tgid:0, off-cpu:1821207496, on-cpu:1820210588
WARN: Skipped an event with negative duration: pid:9, tgid:9, off-cpu:1916307467, on-cpu:1916214463
```
=> tools/offcputime Warn user when an event skipped by negative duration

libbpf-tools/runqlen.c
fix similar bugs  refer to https://github.com/iovisor/bcc/pull/3131
=> libbpf-tools: fix runqlen's error handling logic

tools/wakeuptime.py
wakeuptime currently uses kprobes to trace schedule(). Switch to using
tracepoints if available.
Also, in some builds, try_to_wake_up() may get optimized away causing
the script to fail altogether.
With this switch, we however see stack trace entries related to BPF too
in the end for each trace. While correct, it takes up screen real estate
for each backtrace.
target:          InputThread
ffffffffaf000107 secondary_startup_64_no_verify
ffffffffb12495f1 start_kernel
ffffffffaf10e609 cpu_startup_entry
ffffffffaf10e40b do_idle
ffffffffaf946849 cpuidle_enter
ffffffffaf946577 cpuidle_enter_state
ffffffffafc00d02 asm_sysvec_apic_timer_interrupt
ffffffffafbbbc86 sysvec_apic_timer_interrupt
ffffffffaf0dcc32 irq_exit_rcu
ffffffffaf02bc47 do_softirq_own_stack
ffffffffafc01112 asm_call_irq_on_stack …
=> tools/wakeuptime: Switch to using tracepoints if available

libbpf-tools/biolatency.c, libbpf-tools/biopattern.c, libbpf-tools/biosnoop.c, libbpf-tools/biostacks.c, libbpf-tools/bitesize.c, libbpf-tools/cpudist.c, libbpf-tools/drsnoop.c, libbpf-tools/execsnoop.c, libbpf-tools/filelife.c, libbpf-tools/hardirqs.c, libbpf-tools/llcstat.c, libbpf-tools/opensnoop.c, libbpf-tools/runqlat.c, libbpf-tools/runqslower.c, libbpf-tools/softirqs.c, libbpf-tools/syscount.c, libbpf-tools/tcpconnlat.c
=> libbpf-tools: fix some tools error info and usage

libbpf-tools/readahead.c
Follow the suggestions mentioned here : https://github.com/iovisor/bcc/pull/3253
=> libbpf-tools: minor fixes for readahead

tools/trace.py
Using `trace` with the `-n` or `-f` option gives me a `TypeError: string argument without an encoding`. This is due to bare use of the `bytes` constructor to convert a string. The [docs](https://docs.python.org/3.6/library/functions.html#func-bytearray) for `bytes` refer to `bytearray` which states "If it is a string, you must also give the encoding".
For `-n`, the comparison is the only place that `self.name` is used, so I moved the the conversion to the `__init__` method. For `-f`, the compared `msg` is already a string (because `self.python_format` is a string), so the conversion is unnecessary.
I've also made some minor cleanups such as removing redundant backslashes and semicolons.
=> Fix bytes - strings confusion in trace tool

examples/networking/xdp/xdp_drop_count.py, examples/networking/xdp/xdp_macswap_count.py, examples/networking/xdp/xdp_redirect_cpu.py, examples/networking/xdp/xdp_redirect_map.py
Signed-off-by: yeya24 <yb532204897@gmail.com>
Clean up some style issues and remove the unused `xdp_dummy` function.
=> Cleanup the style and unused function in XDP examples

libbpf-tools/llcstat.c, libbpf-tools/numamove.c, libbpf-tools/readahead.c, libbpf-tools/xfsslower.c
=> libbpf-tools: fix error handling and cleanup

libbpf-tools/biolatency.c, libbpf-tools/biopattern.c, libbpf-tools/biosnoop.c, libbpf-tools/biostacks.c, libbpf-tools/bitesize.c, libbpf-tools/cpudist.c, libbpf-tools/cpufreq.c, libbpf-tools/drsnoop.c, libbpf-tools/execsnoop.c, libbpf-tools/filelife.c, libbpf-tools/funclatency.c, libbpf-tools/hardirqs.c, libbpf-tools/llcstat.c, libbpf-tools/numamove.c, libbpf-tools/opensnoop.c, libbpf-tools/readahead.c, libbpf-tools/runqlat.c, libbpf-tools/runqlen.c, libbpf-tools/runqslower.c, libbpf-tools/softirqs.c, libbpf-tools/syscount.c, libbpf-tools/tcpconnect.c, libbpf-tools/tcpconnlat.c, libbpf-tools/vfsstat.c, libbpf-tools/xfsslower.c
Fix it as https://github.com/iovisor/bcc/pull/3303 mentioned.
=> libbpf-tools: fix bug report address

examples/cpp/CMakeLists.txt, introspection/CMakeLists.txt, tests/cc/CMakeLists.txt
Signed-off-by: Mariusz Barczak <mariusz.barczak@intel.com>
=> Allow to use BCC as a cmake sub-project

docs/reference_guide.md
As discussed in the mailing list: https://lists.iovisor.org/g/iovisor-dev/topic/bcc_and_passing_packet_from/81425283?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,81425283
=> doc: add perf_submit_skb() documentation

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/ext4dist.bpf.c, libbpf-tools/ext4dist.c, libbpf-tools/ext4dist.h, libbpf-tools/trace_helpers.c, libbpf-tools/trace_helpers.h
```sh
➜  libbpf-tools git:(ext4dist) ✗ sudo ./ext4dist  1 5
Tracing ext4 operation latency... Hit Ctrl-C to end.
operation = 'read_iter'
0 -> 1          : 257      |****************************************|
2 -> 3          : 12       |*                                       |
4 -> 7          : 2        |                                        |
operation = 'write_iter'
0 -> 1          : 79       |***                                     |
2 -> 3          : 831      |****************************************|
4 -> 7          : 543      |**************************              |
8 -> 15         : 105      |*****                                   |
16 -> 31         : 5        | …
```
=> libbpf-tools: add ext4dist

libbpf-tools/biolatency.bpf.c
stabilizing llibbpf-tools/biolatency since TP_PROTO & TP_ARGS for block_rq_insert and block_rq_issue tracepoints has been changed; 
see https://github.com/torvalds/linux/commit/a54895fa changes
=> [libbpf-tools]block tracepoints no longer have struct request_queue arg

docs/reference_guide.md
=> fix minor typo

libbpf-tools/trace_helpers.c, libbpf-tools/trace_helpers.h
add discussed helpers https://github.com/iovisor/bcc/pull/3347#discussion_r612096999
=> libbpf-tools: add two helpers

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/gethostlatency.bpf.c, libbpf-tools/gethostlatency.c, libbpf-tools/gethostlatency.h
```shell
$ sudo ./gethostlatency
TIME        PID    COMM                 LATms      HOST            
22:35:13    694482 node                 4.20       dc.services.visualstudio.com
22:35:17    694482 node                 1.47       default.exp-tas.com
...  
```
=> libbpf-tools: add gethostlatency

tools/bindsnoop.py
Signed-off-by: chenhengqi <chenhengqi@outlook.com>
=> tools: fix typo in help message

tools/statsnoop.py
This PR is a first step to #3407 and fix #3332 .
=> tools: display PID intead of TID in statsnoop.py

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/statsnoop.bpf.c, libbpf-tools/statsnoop.c, libbpf-tools/statsnoop.h
```shell
sudo ./statsnoop -x -t -p 3534689
TIME       PID        COMM                 RET  ERR  PATH
0.000000   3534689    YDService            -1   2    /proc/2111125
0.000021   3534689    YDService            -1   2    /proc/2111125
0.000029   3534689    YDService            -1   2    /proc/2111126
```
=> libbpf-tools: add statsnoop

tools/bashreadline.py, tools/cachetop.py, tools/dcsnoop.py, tools/killsnoop.py, tools/llcstat.py, tools/mdflush.py, tools/mysqld_qslower.py, tools/wakeuptime.py
This is the last PR to resolve #3407 
=> tools: filter/display using PID instead of TID

libbpf-tools/biosnoop.bpf.c, libbpf-tools/gethostlatency.bpf.c, libbpf-tools/gethostlatency.c
=> libbpf-tools: fix misuse of bpf_get_current_pid_tgid

docs/reference_guide.md
Add description of attach_raw_socket.
=> docs: add description of attach_raw_socket

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/fsdist.bpf.c, libbpf-tools/fsdist.c, libbpf-tools/fsdist.h
=> libbpf-tools: add fsdist

src/python/bcc/table.py
Signed-off-by: Edward Wu <edwardwu@realtek.com>
=> Add an option to strip leading zeros from linear histograms

docs/reference_guide.md, src/cc/export/helpers.h, src/cc/frontends/clang/b_frontend_action.cc, tests/cc/test_sock_table.cc
add `msg_redirect_hash()` and `sk_redirect_hash()`.
=> libbcc: add msg_redirect_hash() and sk_redirect_hash() for sockhash

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/bindsnoop.bpf.c, libbpf-tools/bindsnoop.c, libbpf-tools/bindsnoop.h
```shell
sudo ./bindsnoop -t   
TIME(s)  PID     COMM             RET PROTO OPTS  IF   PORT  ADDR                                            
19:08:19 3944603 nc               0   TCP   ...Rr 0    1216  0.0.0.0                                         
19:08:43 3944709 nginx            0   TCP   ...R. 0    80    0.0.0.0                                         
19:08:43 3944709 nginx            0   TCP   ...R. 0    80    ::
```
=> libbpf-tools: add bindsnoop

docs/reference_guide.md, src/cc/export/helpers.h, src/cc/frontends/clang/b_frontend_action.cc, tests/python/test_clang.py, tests/python/test_histogram.py, tests/python/test_perf_event.py
Add atomic_increment()
Discussion on https://github.com/iovisor/bcc/issues/3481
=> libbcc: add atomic_increment()

tools/funclatency.py
Replace `lookup and xadd` with `atomic_increment`
=> tools: funclatency use atomic_increment

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/solisten.bpf.c, libbpf-tools/solisten.c, libbpf-tools/solisten.h
```shell
$ sudo solisten
PID     COMM             RET LAT(us)  BACKLOG PROTO PORT  ADDR                            
241011  netcat           0   12       1       TCPv4 1216  0.0.0.0                         
241158  nginx            0   14       511     TCPv4 80    0.0.0.0                         
241158  nginx            0   4        511     TCPv6 80    ::                              
241158  nginx            0   1        511     TCPv4 80    0.0.0.0                         
241158  nginx            0   1        511     TCPv6 80    ::
```
=> libbpf-tools: add solisten

docs/reference_guide.md
=> Add open parentheses

.github/workflows/publish.yml
This builds on @dalehamel 's https://github.com/iovisor/bcc/pull/3141
=> Fix publish github action on docker registry

libbpf-tools/uprobe_helpers.c
get_elf_func_offset didn't work properly when use with
statically linked binary. It seems like not subtract the
base load address cause the problem. This commits fixes
that like BCC does. see [0] and [1].
[0]: https://github.com/iovisor/bcc/blob/v0.20.0/src/cc/bcc_syms.cc#L751-L764
[1]: https://github.com/iovisor/bcc/blob/v0.20.0/src/cc/bcc_elf.c#L723-L756
=> libbpf-tools: fix uprobe helper get_elf_func_offset

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/filetop.bpf.c, libbpf-tools/filetop.c, libbpf-tools/filetop.h, libbpf-tools/stat.h
```shell
14:24:14 loadavg: 1.31 1.06 1.17 1/1369 837906
TID     COMM             READS  WRITES R_Kb    W_Kb    T FILE
1197    gnome-shell      1      0      0       0       - [timerfd]
811093  Timer            0      1      0       0       -
```
=> libbpf-tools: add filetop

examples/networking/xdp/xdp_drop_count.py
example xdp_drop_count.py adds driver mode support.
=> Add support for driver/native mode

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/tcprtt.bpf.c, libbpf-tools/tcprtt.c, libbpf-tools/tcprtt.h
=> libbpf-tools: add tcprtt

snap/snapcraft.yaml
Minor changes to add bcc commands to snapcraft instrall rules and add snapcraft architectures to build when using snapcraft remote-build
=> refresh snapcraft rules

libbpf-tools/syscount.bpf.c
Signed-off-by: Wei Fu <fuweid89@gmail.com>
=> libbpf-tools/syscount: use atomic_add for counter

tools/readahead.py
=> tools/readahead: Migrate to kfunc/kretfunc

INSTALL.md
By just running `$ sudo amazon-linux-extras install BCC`, dependencies are install.
```
$ sudo amazon-linux-extras install BCC
...
==================================================================================================================================================================
Package                                       Arch                      Version                                 Repository                                  Size
==================================================================================================================================================================
Installing:
bcc                                           x86_64                    0.18.0-1.amzn2.0.3                      amzn2-core                                  28 M …
```
=> simplify AL2 Linux package install command

tests/cc/test_array_table.cc, tests/cc/test_bpf_table.cc, tests/cc/test_cg_storage.cc, tests/cc/test_hash_table.cc, tests/cc/test_map_in_map.cc, tests/cc/test_perf_event.cc, tests/cc/test_pinned_table.cc, tests/cc/test_prog_table.cc, tests/cc/test_queuestack_table.cc, tests/cc/test_shared_table.cc, tests/cc/test_sk_storage.cc, tests/cc/test_sock_table.cc, tests/cc/test_usdt_probes.cc
Generated with:
```
sed -i 's|\([A-Z_a-z]\+\).code() == 0|\1.ok()|' $(grep '\.code() == 0' tests -rl)
sed -i 's|\([A-Z_a-z]\+\).code() != 0|!\1.ok()|' $(grep '\.code() != 0' ./ -rl)
```
=> Replace StatusTuple::code() with StatusTuple::ok() in tests/

examples/cpp/CGroupTest.cc, examples/cpp/CPUDistribution.cc, examples/cpp/FollyRequestContextSwitch.cc, examples/cpp/HelloWorld.cc, examples/cpp/KFuncExample.cc, examples/cpp/KModRetExample.cc, examples/cpp/LLCStat.cc, examples/cpp/RandomRead.cc, examples/cpp/RecordMySQLQuery.cc, examples/cpp/SkLocalStorageIterator.cc, examples/cpp/TCPSendStack.cc, examples/cpp/TaskIterator.cc, examples/cpp/pyperf/PyPerfUtil.cc
Made with:
```
sed -i 's|\([A-Z_a-z]\+\).code() != 0|!\1.ok()|' $(grep '\.code() != 0' examples -rl)
```
=> Replace StatusTuple::code() != 0 with !StatusTuple.ok() in examples/

tests/python/test_tools_smoke.py
The test_tools_smoke script uses bash's 'timeout' command to run bcc
tools for a limited duration, sending a HUP after 5s and a KILL 5s after
that. Currently, when a tool exits in an unexpected way (e.g. we
expected a HUP to be required, but the tool required a KILL), the test
failure message isn't very descriptive.
This adds a more human-readable explanation of what's going on.
=> test_tools_smoke.py: Helpful fail msg for timeout cmd's ret code

tools/tcptop.py
Hi.
First, I hope you are fine and the same for your relatives.
Before this commit, command name was taken from PID using `/proc/PID/comm`.
But this method is not reliable as it does not work all the time, as showed in the following output:
```
16:58:11 loadavg: 3.37 2.84 1.62 1/427 11699
PID      COMM         LADDR                 RADDR                  RX_KB  TX_KB
11668  11668         172.17.0.3:45484      172.67.196.142:443        45      0
11665  11665         172.17.0.3:47668      104.21.92.167:443         45      0
11661   wget         172.17.0.3:47666      104.21.92.167:443         43      0
```
So, this commit takes command name from BPF code using `bpf_get_current_comm()` helper like it is done for biotop:
```
16:58:11 loadavg: 3.37 2.84 1.62 1/427 11699
PID    COMM …
```
=> tools: tcptop: Get command name from BPF code.

man/man8/cpudist.8
-P prints all by process id
-p prints specific process id
=> docs: Fixup cpudist pid example in man page

README.md
=> Delete dead link

INSTALL.md, examples/networking/http_filter/http-parse-complete.c, examples/networking/http_filter/http-parse-simple.c, libbpf-tools/filetop.c, libbpf-tools/oomkill.c, src/cc/perf_reader.c, tools/ext4slower.py
Signed-off-by: Yuntao Wang <ytcoode@gmail.com>
=> remove redundant spaces

tools/memleak.py
=> memleak added mmap and munmap tracing

libbpf-tools/klockstat.c
Add -v(--verbose) option to klockstat to display libbpf log
Signed-off-by: Eunseon Lee <es.lee@lge.com>
=> libbpf-tools/klockstat: Add verbose option

docs/reference_guide.md
=> Add doc on probe name defined by TRACEPOINT_PROBE

examples/tracing/bitehist.py
examples: fix bitehist
Kernel commit 24b83deb29b ("block: move struct request to blk-mq.h")
and be6bfe36db17 ("block: inline hot paths of blk_account_io_*()")
introduce changes which break bitehist.
Like #3748 and #3877 but for bitehist, this commit fixes those issues.
=> examples: fix bitehist

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/tcpsynbl.bpf.c, libbpf-tools/tcpsynbl.c, libbpf-tools/tcpsynbl.h
Signed-off-by: chendotjs <chendotjs@gmail.com>
=> libbpf-tools: convert BCC tcpsynbl to BPF CO-RE version

tools/tcptop.py
add tcp_sendpage support for tcptop tool.
=> add tcp_sendpage for tcptop tool

man/man8/mdflush.8, man/man8/offwaketime.8, man/man8/profile.8, man/man8/swapin.8, man/man8/tcprtt.8, tools/swapin_example.txt
=> [Mdflush man:issue] mdflush manpage states itself as pidpersec manpage

tools/tcpconnect.py
Add IPv6 DNS support for tcpconnect.
Fixes #3933.
=> tools/tcpconnect: Support IPv6 DNS

src/cc/bpf_module_rw_engine.cc
When BCC is compiled with LLVM 15, running BCC tools will cause segfault.
The core dump reveals that the segfault is triggered by the calls to
`getPointerElementType()`. This is because LLVM is moving towards
`Opaque Pointer` ([0]). This commit follows the migration guide to fix
the issue.
[0]: https://llvm.org/docs/OpaquePointers.html
=> Fix segfault and warnings for LLVM 15

tools/funccount_example.txt
=> fixed typo

tools/runqslower.py
When option -t (thread filter) was selected, runqslower raises an invalid read error, which was introduced in #3577
(**pid** was moved to **prev_pid**, while **FILTER_PID** depends on pid). this patch try to fix it.
=> tools: Fix runqslower invalid error when option -t was selected

src/cc/libbpf.c
Without this fix (or one like it): one ends up getting this warning when any bpf program loads
```
WARNING: cannot get prog tag, ignore saving source with program tag 
prog tag mismatch 71d4822dd06c5b8e 1 
```
thus one can't get the source of the bpf programs output to /var/tmp/bcc
Seen on openSUSE 15.4 for bpf programs.
Other OSes cat /proc/self/fdinfo/*
```
pos:    0
flags:  02000002
mnt_id: 15
prog_type:      2
```
On openSUSE SP4 cat /proc/self/fdinfo/*
```
pos:    0
flags:  02000002
mnt_id: 15
ino:       11319
prog_type:      2
```
The additional field causes the prog_tag not to be retrieved properly.
=> Support additional ino field seen on openSUSE 15.4 (to parse the prog_tag)

src/cc/bpf_module.cc
There are two pass managers in LLVM. Currently BCC uses the legacy one.
Switch to the new pass manager because the legacy one will be removed
in upcoming releases of LLVM.
Running the following script:
```python3
bpf_text = '''
static int foobar()
{
bpf_trace_printk("enter vfs_read");
return 0;
}
KFUNC_PROBE(vfs_read)
{
return foobar();
}
'''
BPF(text=bpf_text, debug=1)
```
The IR output is the same with or without this change using LLVM 15:
; ModuleID = 'sscanf'
source_filename = "sscanf"
; ModuleID = '/virtual/main.c'
source_filename = "/virtual/main.c"
target datalayout = "e-m:e-p:64:64-i64:64-i128:128-n32:64-S128"
target triple = "bpf-pc-linux"
@_version = dso_local global i32 332032, section "version", align 4, !dbg !0
@_license = dso_local global [4 x i8] …
=> bcc: Introduce new pass manager

examples/networking/http_filter/http-parse-complete.py
=> http-parse-complete.py replace toHex funtion with binascii.hexlify function

libbpf-tools/bindsnoop.bpf.c, libbpf-tools/bindsnoop.c, libbpf-tools/cpudist.bpf.c, libbpf-tools/cpudist.c, libbpf-tools/cpufreq.bpf.c, libbpf-tools/cpufreq.c, libbpf-tools/execsnoop.bpf.c, libbpf-tools/execsnoop.c, libbpf-tools/exitsnoop.bpf.c, libbpf-tools/exitsnoop.c, libbpf-tools/funclatency.bpf.c, libbpf-tools/funclatency.c, libbpf-tools/hardirqs.bpf.c, libbpf-tools/hardirqs.c, libbpf-tools/runqlat.bpf.c, libbpf-tools/runqlat.c, libbpf-tools/syscount.bpf.c, libbpf-tools/syscount.c
- Previously in #3741 and #3890 - cgroup2 based filtering for libbpf-tools `biolatency` and `biosnoop` was supported
- In this PR support more tools for cgroup2 based filtering.
Kindly review and feedback if any changes required for merge.
=> Support cgroup filtering for libbpf-tools

tools/tcptop.py
add actual send msg size for tcptop
=> add actual send msg size for tcptop

src/cc/api/BPF.cc, src/cc/api/BPF.h, src/cc/bcc_common.cc, src/cc/bcc_common.h, src/cc/bpf_module.cc, src/cc/bpf_module.h, src/python/bcc/__init__.py, src/python/bcc/libbcc.py
Here is a patch that addresses https://github.com/iovisor/bcc/issues/3702
It works fine for my use case and I would like to  gather feedback.
Thanks
=> Support the expected_attach_type attribute

tools/exitsnoop.py
- Remove ctypes cast operation
- Remove `__attribute__((packed))` of struct data_t
=> tools/exitsnoop: Make some improvements for exitsnoop

tools/tcplife.py
=> tools/tcplife: Remove dead code

tools/syscount.py
- remove b''
- change colume width to 22（syscall sched_get_priority_max is the longest, 22 chars）
=> tools/syscount: Beautify output of syscall list

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/core_fixes.bpf.h, libbpf-tools/mdflush.bpf.c, libbpf-tools/mdflush.c, libbpf-tools/mdflush.h
Add libbpf-tool mdflush, this is a replacement for BCC mdflush.
This is part of the solution to #3650.
=> libbpf-tools: Add mdflush

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/tcplife.bpf.c, libbpf-tools/tcplife.c, libbpf-tools/tcplife.h
=> libbpf-tools: Add tcplife

libbpf-tools/trace_helpers.c
the bpf verifier would complain on program exit without initing R0 but the buggy implementation makes up one BPF_EXIT instruction only, which would be rejected by the verifier, and what's worse is that it does not log any err about the try-to-load failure, which makes all tools use this api would silently fall back to kprobe unexpectedly.
this patch fixs it and also prints verbose message about the result of the try.
for instance, if the [init R0 instruction](https://github.com/iovisor/bcc/pull/4070/files#diff-52b43275661eff7b28907ff06ec5011abea3309ea24f5b54fe1cbc079ee0c23aR999) were not added, once we call the fixed version of **fentry_try_attach** , you would get the following hints:
```sh 
failed to try attaching to fentry: 0: (95) exit
R0 !read_ok
processed 1 insns (limit 1000000) …
```
=> libbpf-tools: fix fentry_try_attach bug

tools/profile.py
- remove b''
- decode bytes to str
=> tools/profile: decode bytes to str

tools/stackcount.py
=> tools/stackcount: remove b''

src/cc/bpf_module.cc, src/cc/libbpf.c, src/cc/libbpf.h
https://github.com/libbpf/libbpf/commit/9476dce6fe905a6bf1d4c483f7b2b8575c4ffb2d remove it from libbpf
=> [bcc] stop using deprecated `bpf_load_program_attr`

man/man8/argdist.8, man/man8/funclatency.8, man/man8/trace.8, tools/argdist.py, tools/funccount.py, tools/funclatency.py, tools/offwaketime.py, tools/trace.py, tools/trace_example.txt
* funclatency: fix error at wrong pattern
* argdist: the probe's type field is currently required
* some minor fixes
=> tools: fix typos

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/tcptracer.bpf.c, libbpf-tools/tcptracer.c, libbpf-tools/tcptracer.h
Implement CO-RE version of tcptracer tool.
=> libbpf-tools: Add tcptracer

tools/runqlat.py, tools/runqslower.py
Global variable rq is unused, remove it.
=> tools/runqslower.py: remove unused global variable rq.

man/man8/profile.8, tools/profile.py, tools/profile_example.txt
Just like the perf tool, support multi process or thread may be useful.
=> tools/profile: add multi process/thread support

tools/biolatency.py
Extension summary logic seems a bit redundant, try to simplify it (total already be calculated by FACTOR replacement).
=> tools/biolatency: Simplify extension summary redundant logic

CMakeLists.txt, cmake/CmakeUninstall.cmake.in, src/python/CMakeLists.txt
Usage:
```bash
$ sudo make install
$ sudo make uninstall <<=== New Target
```
=> Add cmake TARGET: uninstall

man/man8/bindsnoop.8, man/man8/compactsnoop.8, man/man8/dirtop.8, man/man8/drsnoop.8, man/man8/funclatency.8, man/man8/opensnoop.8, man/man8/tcpsubnet.8, man/man8/tcptracer.8, man/man8/trace.8, tools/killsnoop_example.txt
Fixes a few documentation issues, mostly options missing from man pages.
=> Fix some documentation issues

docs/tutorial_bcc_python_developer.md
update document  with lastest code example
=> [doc] update python developer tutorial

.gitmodules, CMakeLists.txt, docker/build/Dockerfile.fedora, libbpf-tools/Makefile, libbpf-tools/opensnoop.bpf.c, libbpf-tools/opensnoop.c, libbpf-tools/opensnoop.h
With new option '-c', opensnoop will show the names and line numbers
of the two most inner callers in the userspace if there are.  It
uses BlazeSym to do symbolization.
Signed-off-by: Kui-Feng Lee <kuifeng@fb.com>
=> Show the stacktrace of the userspace in opensnoop.

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/wakeuptime.bpf.c, libbpf-tools/wakeuptime.c, libbpf-tools/wakeuptime.h
Convert wakeuptime python tool to co-re version.
=> libbpf-tools: convert wakeuptime tool

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/tcptop.bpf.c, libbpf-tools/tcptop.c, libbpf-tools/tcptop.h
Hi.
In this PR, I converted `tcptop` from BCC to CO-RE.
Best regards.
=> libbpf-tool: Add tcptop

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/tcpstates.bpf.c, libbpf-tools/tcpstates.c, libbpf-tools/tcpstates.h
Add new libbpf tool tcpstates.
=> libbpf-tools: Add tcpstates

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/biotop.bpf.c, libbpf-tools/biotop.c, libbpf-tools/biotop.h
Hi.
I converted `biotop` from BCC to CO-RE.
I tried to stick with the BCC behavior.
I just have two questions:
1. I only probed on some functions, is this OK? Because I think we cannot try to probe like it it is done here:
https://github.com/iovisor/bcc/blob/ca8240205e175e94cef3c70c3b5c5accbe51512f/tools/biotop.py#L178
2. I am not really satisfied with the way I handle disk name. Sadly it is a bit complicated to use a hash map in C. So if someone sees a way to improve this, feel free to share :D.
Best regards.
=> libbpf-tools: Add biotop tool.

src/cc/frontends/clang/b_frontend_action.cc
getCalleeDecl() may return NULL, so either check it explicitly or use dyn_cast_or_null operator instead of dyn_cast.
This fixes #4234.
=> NULL check CallExpr.getCalleeDecl()

libbpf-tools/klockstat.c
On extremely heavy lock contention, klockstat can be stuck in the loop
in print_stats() since it keeps adding new entries to the stat_map.
Instead of deleting the elements in the loop, process them all and then
delete them at the end.
=> libbpf-tools: Fix klockstat to finish with -R

libbpf-tools/klockstat.c
symbol reallocarray does not exists in ubuntu 16.04,   unable to make the project.
=> fix undefined reference reallocarray

libbpf-tools/biolatency.bpf.c, libbpf-tools/biolatency.c
On kernels without BPF trampoline, let's switch to raw tracepoint instead.
cc @eiffel-fl
=> libbpf-tools: Enable biolatency on kernels without BPF trampoline

tools/runqslower.py
We have encountered an issue while running runqslower for long run test, as you can check the log below. The workload of target platform is running auto test script and launching lots of applications periodically on Android TV. There are several abnormal records of run queue latency, ex. 1311763801.
We have investgated this issue and found the root cuase of this issue is the hash map to store en-queue start time of each task overflowed, and it seems cpudist also encountered such issue before and fix by following pull request.
https://github.com/iovisor/bcc/pull/2568
Apply the similar fix to runqslower, get the max_pid from /proc/sys/kernel/max_pid and pass to BPF C in kernel to create enough entries of hash map to store en-queue start time of each task.
```
(bcc)root@localhost:/# …
```
=> runqslower: create sufficiently large hash table to avoid missing tasks

src/cc/frontends/clang/b_frontend_action.cc
Since version 15, clang issues error for implicit conversion of integer to pointer. Several tools are broken. This patch add explicit pointer cast where needed.
Fixes the following errors:
/virtual/main.c:37:18: error: incompatible integer to pointer conversion initializing 'struct request *' with an expression of type 'unsigned long' [-Wint-conversion]
struct request *req = ctx->di;
^     ~~~~~~~
/virtual/main.c:49:18: error: incompatible integer to pointer conversion initializing 'struct request *' with an expression of type 'unsigned long' [-Wint-conversion]
struct request *req = ctx->di;
^     ~~~~~~~
2 errors generated.
/virtual/main.c:73:19: error: incompatible integer to pointer conversion initializing 'struct pt_regs *' with an expression of type 'unsigned long' [-Wint-conversion] …
=> Fix clang 15 int to pointer conversion errors

README.md, man/man8/ppchcalls.8, tests/python/test_tools_smoke.py, tools/ppchcalls.py, tools/ppchcalls_example.txt
Migrating perf based powerpc-hcalls.py to a more enhanced ebpf variant inspired by existing bcc/tools/syscount.py.
Additional hcalls updated from Linux kernel source.
Signed-off-by: Harsh Prateek Bora (harshpb@linux.ibm.com)
=> tools: Introducing ppchcalls.py for hcall count/latency stats.

docs/tutorial.md
Signed-off-by: Ruihua Dong <dongruihua.drh@alibaba-inc.com>
=> docs/tutorial.md: fix typo

tools/tcpcong.py
support kernel patch(https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net-next.git/commit/?id=15fcdf6ae116) tracepoint for tcp_set_ca_state
=> support tracepoint for tcp_set_ca_state

tools/old/filegone.py
kernel commit 9fe61450972d("namei: introduce struct renamedata") introduce 'struct renamedata', at the same time, the function declarations changed.
Changes:
1. kernel_struct_has_field() function return true if struct exist and field set to and empty string('');
2. use kernel_struct_has_field() to determine if structure 'renamedata' exists, thus solving the vfs_rename using CO-RE way instead of using the kernel version number.
=> tools/filegone: Check btf struct field instead of KERNEL_VERSION macro

tools/statsnoop.py
Add some stat() variants (statx/newlstat).
=> tools/statsnoop: Add some stat() variants

src/cc/frontends/clang/b_frontend_action.cc
1. If arch has syscall wrapper enabled, first argument is pt_regs. The syscall args is then read via bpf_probe_read_kernel.
2. fix first syscall argument for arm64 and s390.
Linux Ref:
1. 1f22a6f9f9a0 ("libbpf: Fix accessing the first syscall argument on s390")
2. fbca4a2f6497 ("libbpf: Fix accessing the first syscall argument on arm64")
3. c5a1ffa0da76 ("libbpf: Add PT_REGS_SYSCALL_REGS macro")
4. 6f5d467d55f0 ("libbpf: improve BPF_KPROBE_SYSCALL macro and rename it to BPF_KSYSCALL")
Suggested-by: Ilya Leoshkevich <iii@linux.ibm.com>
Tested-by: Ilya Leoshkevich <iii@linux.ibm.com>
Signed-off-by: Sumanth Korikkar <sumanthk@linux.ibm.com>
=> clang/b_frontend_action: fix arch_syscall_wrapper

tools/memleak.py
The bellow kernel commit[1] have remove kmem:kmem_cache_alloc_node and kmem:kmem_cache_alloc_node trace points, which cause memleak to break. Fix it by checking whether the above trace points exists and than add it to the BPF program.
Signed-off-by: Shay Drory <shayd@nvidia.com>
=> tools/memleak: Remove deleted trace points (kernels >=6.1)

libbpf-tools/uprobe_helpers.c
`get_pid_lib_path` didn't use path_sz in sscanf, so it may cause buffer overflow when path_sz is smaller than the real lib path. 
For exmample: 
```c
char minpath[1];
get_pid_lib_path(1, "c", minpath, 1);
```
may bring in asan:
```
==83410==ERROR: AddressSanitizer: stack-buffer-overflow on address ....
WRITE of size 25 at ... thread T0
```
=> libbpf-tools: fix uprobe helper possible overflow

docs/kernel_config.md
**Background**
- https://github.com/iovisor/bcc/issues/3484 
- List the kernel configs required for eBPF functionalities
**Changes**
- Added docs/kernel_config.md for the required kernel configs 
Kindly review the doc and let us know for any changes or additions
=>  kernel configs required for eBPF - docs/kernel_config.md

tools/cachestat.py, tools/cachetop.py
Add tracepoint:writeback:writeback_dirty_{page,folio} support.
kernel commit 9fb0a7da0c52("writeback: add more tracepoints") add writeback_dirty_page tracepoint, kernel commit b9b0ff61eef5("mm/writeback: Convert tracing writeback_page_template to folios") replace writeback_dirty_page to writeback_dirty_folio.
Both folio_account_dirtied() and account_page_dirtied() are static functions and they may be gone during compilation and this may introduce some inaccuracy, when attaching kprobe fails, report the running error in time. Instead of getting incorrect statistical results.
=> tools/{cachetop,cachestat}: Introduce tracepoint writeback_dirty_{page,folio}

man/man8/klockstat.8, tools/klockstat.py
Fix two typos in klockstat.8 and klockstat.py
=> Fix typos in klockstat

libbpf-tools/maps.bpf.h
We found out why in some cases the conditional branch was being entered:
```
if (err && err != -EEXIST)
return 0;
```
...while the error was known to have been `-EEXIST`. 
If this criteria is met:
- the architecture is 64-bit
- the helper function return type is long
- the helper function returns the value of a call to a bpf_map_ops func
- the bpf_map_ops function return type is int
- the compiler inlines the helper function
- the compiler does not sign extend the result of the bpf_map_ops func
In the case of `-EEXIST` (-17), the resulting comparison will be done:
`cmp -17, 4294967279`
... since the sign bit was stuck at the 32nd bit of a 64-bit register. as a result the conditional branch will be entered.
we patched this upstream in bpf-next so that affected bpf_map_ops funcs will return …
=> workaround for evaluating errors from bpf helpers

docker/build/Dockerfile.ubuntu
iperf && netperf are duplicated in Dockerfile.ubuntu, remove them.
=> rm duplicated iperf/netperf in dockerfile.ubuntu

libbpf-tools/trace_helpers.c
bcc commit e0291c8d3a16("Filter with available_filter_functions in BPF.get_kprobe_functions()") introduce available_filter_functions filter, also use /sys/kernel/debug/kprobes/blacklist to filter unavailable kprobes. We should keep the kprobe_exists() function of libbpf-tools consistent with the filtering rules in BPF.get_kprobe_functions().
bpftrace commit 5c349664a2e0("Use blacklist to filter unavailable kprobes") [0] do the same thing. Refer to [0], using do_trap() as an example.
[0] https://github.com/iovisor/bpftrace/pull/2573
=> libbpf-tools: Filter with kprobe blacklist for kprobe_exists() api.

tools/offcputime.py, tools/wakeuptime.py
=> tools: Remove unused strftime

INSTALL.md
=> Update INSTALL.md: fix llvm download url

tools/tcpstates.py
Currently while running tcpstates.py, I'll always get BPF verifier error as below while compiling `TRACEPOINT_PROBE(sock, inet_sock_set_state)`:
```
104: (07) r6 += 20
105: (61) r1 = *(u32 *)(r6 +0)
dereference of modified ctx ptr R6 off=20 disallowed
```
This error is caused by llvm optimize load instruction from `r1 = *(u32 *)(r6 + 20)` to `r6 += 20; r1 = *(u32 *)(r6 +0)`, mapping to C code `args->newstate`.
Workaround in this PR is to introduce a local variable `tcp_new_state` and place it ahead, to avoid this llvm optimization.
Please help to review, and kindly clarify is there any better solution for this issue? @yonghong-song 
BTW, I split `event.ports` to `lport` and `dport`, to bypass bit operations needed by `event.ports`.
=> tools/tcpstates: fix context ptr modified error

man/man8/rdmaucma.8, tools/rdmaucma.py, tools/rdmaucma_example.txt
Add rdmaucma tools to trace RDMA UCMA events.
This can be useful to analyze issues on RDMA CM.
=> tools/rdmaucma: Add new command

tools/tcptop.py
In recent kernels, tcp_sendpage() has been replaced by sendmsg(MSG_SPLICE_PAGES). Check the presence of the k(ret)probes before attaching them.
=> tools/tcptop: Check the presence of tcp_sendpage before attaching it

INSTALL.md
Fixing documentation to add a section for Ubuntu 23.04.
Fixes #4744 .
=> Adding needed packages for Ubuntu 23.04

tools/filelife.py
When we try to delete a file with a normal user after creating a file as root (sudo), the deletion of the file fails, but the kprobe:vfs_unlink is triggered, which leads to incorrect file lifecycle tracking.
Reproducing the issue:
```
Terminal 1:
$ sudo ./filelife.py
Terminal 2:
$ sudo touch /etc/a.txt
$ rm /etc/a.txt
rm: remove write-protected regular empty file '/etc/a.txt'? y
rm: cannot remove '/etc/a.txt': Permission denied
Then, terminal 1:
$ sudo ./filelife.py
TIME     PID     COMM             AGE(s)  FILE
12:24:11 4988    rm               7.13    a.txt   <<< wrong statistic
```
However, file 'a.txt' is not removed. This commit solves this problem.
=> tools/filelife: Fix error tracking caused by failed unlink

libbpf-tools/gethostlatency.c
gethostlatency.c cannot handle the path of libc inside other mnt namespaces.
If PID is specified, this commit resolves the path of libc from /proc/[PID]/root.
=> libbpf-tools/gethostlatency: Resolve the path of libc for different namespaces

README.md
to make list of all tools more organized
because flat list of more than 100 tools is too long for comprehension
=> consolidate sublist of storage tools

libbpf-tools/biotop.bpf.c, libbpf-tools/biotop.c
-p option for tracking a specific pid in tools/biotop which filters target PID to avoid message flooding.
So, adding -p option to filter pid is necessary.
=> libbpf-tools/biotop：Add PID filter support

examples/networking/net_monitor.py
- fix c_ulong type handle logic at line 112
- fix ip decimal to human bug at line 101
which should be handled in python way
From: 
```python
def decimal_to_human(input_value):
input_value = int(input_value)
hex_value = hex(input_value)[2:]
pt3 = literal_eval((str('0x'+str(hex_value[-2:]))))
pt2 = literal_eval((str('0x'+str(hex_value[-4:-2]))))
pt1 = literal_eval((str('0x'+str(hex_value[-6:-4]))))
pt0 = literal_eval((str('0x'+str(hex_value[-8:-6])))) <- BUG here
result = str(pt0)+'.'+str(pt1)+'.'+str(pt2)+'.'+str(pt3)
return result
try:
while True :
time.sleep(OUTPUT_INTERVAL)
packet_cnt_output = packet_cnt.items()
output_len = len(packet_cnt_output)
print('\n')
for i in range(0,output_len):
if (len(str(packet_cnt_output[i][0]))) != 30: <- BUG here
continue
temp = …
```
=> fix c_ulong type handle and decimal ip address bugs

libbpf-tools/klockstat.h
It is just weird indent fix patch.
=> libbpf-tools/klockstat: Fix indent

tools/memleak.py
`combined_allocs` map can be modified by multiple threads and it causes data race easily. To prevent this issue, use atomic operation, like `libbpf-tools/memleak.bpf.c` does. This atomic implementation cannot resolve all data race cases but reduce some.
Followings are the way to generate data race issue and the result after applying this patch.
File test.cpp
```c++
#include <iostream>
#include <thread>
#include <unistd.h>
void alloc() {
for (int i = 0; i < 100000; ++i) {
int* a = (int*)malloc(4);
}
}
int main() {
sleep(100);
std::thread t1 {&alloc};
std::thread t2 {&alloc};
t1.join();
t2.join();
sleep(50);
return 0;
}
```
Build the test file
```
$ g++ test.cpp
```
Run test program and `memleak.py` without `--combined-only`
```
$ ./a.out &
[1] 65168
$ sudo python3 memleak.py -p 65168 …
```
=> tools/memleak: Fix data race on --combined-only

.github/workflows/bcc-test.yml, .github/workflows/publish-build-containers.yml
This will increase test coverage for bcc tools.
=> Add llvm17 test on ubuntu 20.04

docs/kernel-versions.md
Added a list of drivers that support xdp along with commit ids and references. 
Please do take a look at the updated list .
=> docs: Updated the documentation on XDP supporting drivers

src/cc/frontends/clang/kbuild_helper.cc
Example testing with a brendan-owned /tmp/kheaders file (note the "ERROR:" message):
```
~/bcc/build$ sudo /usr/share/bcc/tools/biosnoop
ERROR: header file ownership unexpected: /tmp/kheaders-5.15.47-internal
<built-in>:1:10: fatal error: './include/linux/kconfig.h' file not found
#include "./include/linux/kconfig.h"
^~~~~~~~~~~~~~~~~~~~~~~~~~~
File "/usr/share/bcc/tools/biosnoop", line 335, in <module>
File "/usr/lib/python3/dist-packages/bcc-0.1.5+6cd27218-py3.10.egg/bcc/__init__.py", line 479, in __init__
Exception: Failed to compile BPF module <text>
~/bcc/build$ ls -lhd /tmp/kheaders-5.15.47-internal
drwxrwxr-x 2 brendan dev 4.0K Mar  6 02:50 /tmp/kheaders-5.15.47-internal
```
No error when chown'd back to …
=> clang: check header ownership

examples/tracing/undump.py
Use print and %x to print out the data: (Considering compatibility, it is best not to delete the original output method)
```
$ sudo ./undump.py
...
Recv 32 bytes
01 20 c6 5e 01 00 00 00 06 00 00 00 00 00 00 00
01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
```
However, hexdump is the more standard approach:
```
$ sudo ./undump.py --hexdump
...
Recv 32 bytes
1c00eb615b03ad00780100001f6eb420
00000000000000000000000000000000
```
At the same time, remove useless 'import' lines.
=> examples/tracing/undump.py: Add --hexdump argument

src/cc/frontends/clang/b_frontend_action.cc
With llvm15, the tool 'execsnoop.py' failed the compilation with the following error messages:
```
...
/virtual/main.c:103:157: error: expected ')'
data.ppid = ({ typeof(pid_t) _val; __builtin_memset(&_val, 0, sizeof(_val));
bpf_probe_read(&_val, sizeof(_val), (void *)&({ typeof(struct task_struct  btf_type_tag(rcu)*) _val;
__builtin_memset(&_val, 0, sizeof(_val));
bpf_probe_read(&_val, sizeof(_val), (void *)&task->real_parent); _val; })->tgid); _val; });
...
```
The main reason is incorrect type string
```
btf_type_tag(rcu)
```
btf_type_tag is introduced in llvm15 is an attribute. The correct type representation should be
```
__attribute__((btf_type_tag("rcu")))
```
The bug is fixed in llvm16 with [1]. Unfortunately the patch cannot be backported to llvm15 since at that time llvm15 has …
=> Fix btf_type_tag issue with llvm 15

examples/tracing/task_switch.py, src/python/bcc/__init__.py, tests/python/test_trace2.py, tools/exitsnoop.py
=> *.py: fix incorrect regex escaping

tools/memleak.py
Followings are the way to generate data error issue and the result after applying this patch.
File test.cpp
```
#include <iostream>
#include <thread>
#include <unistd.h>
void alloc() {
for (int i = 0; i < 100000; ++i) {
int* a = (int*)malloc(4);
}
}
int main() {
sleep(100);
std::thread t1 {&alloc};
std::thread t2 {&alloc};
t1.join();
t2.join();
sleep(50);
return 0;
}
```
Build the test file
```
$ g++ -g -o test -lpthread test.cpp
```
Run this with --combined-only:
```
sudo ./memleak.py -c ./test --combined-only
Executing './test' and tracing the resulting process. Attaching to pid 194273, Ctrl+C to quit.
[23:36:43] Top 10 stacks with outstanding allocations:
576 bytes in 2 allocations from stack
__GI__dl_allocate_tls+0x2c [ld-2.28.so]
799992 bytes in 199998 allocations from stack …
```
=> tools/memleak: Fix the data error caused by the same key in map

libbpf-tools/syscount.c
In read_vals_batch function, the errno set by bpf_map_lookup_and_delete_batch() may change if the next warn() fails. So the errno of read_vals:240 may be incorrect.
bpf_map_lookup_and_delete_batch() already returns errno with a minus added on failure, so used the return value instead of errno.
=> libbpf-tools/syscount: Fix incorrect errno usage

tools/profile_example.txt
Matches option explanations and examples
```
Document structure before modification
(a) Explain -U and -K option
(b) Show -C option example
(c) Explain (b)
(d) Show -U option example
```
```
Modified document structure
(e) Explain -C option
(b) Show -C option example
(c) Explain (b)
(a) Explain -U and -K option
(d) Show -U option example
```
=> tools/profile_example.txt: Modifies document structure

tools/swapin.py
kernel[0] commit c9bdf768dd93("mm: convert swap_readpage() to swap_read_folio()") convert swap_readpage() to swap_read_folio().
[0] https://github.com/torvalds/linux.git
=> tools/swapin: Support swap_read_folio()

libbpf-tools/profile.bpf.c, libbpf-tools/profile.c, libbpf-tools/profile.h
This is a test example.
```
Sampling at 49 Hertz of PID [1292, 15313] by user + kernel... Hit Ctrl-C to end.
strlen
-                test-strlen (15313)
32
strlen
b
a
main
__libc_start_main
-                test-strlen-abc (1292)
28
strlen
-                test-strlen (15313)
18
strlen
b
a
main
__libc_start_main
-                test-strlen-abc (1292)
17
```
=> libbpf-tools/profile: Add multi process/thread support

INSTALL.md
=> INSTALL.md: Add WSL build dependency `bc`

examples/tracing/mallocstacks.py
=> Make mallocstacks.py output compatible with stackcollapse

libbpf-tools/Makefile, libbpf-tools/memleak.c
=> libbpf-tools: Use `-Werror=undef`

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/fsdist.c, libbpf-tools/fsslower.c
Add zfs based on zfsdist.py and zfsslower.py.
=> Add support for zfs to fsdist and fsslower tools

libbpf-tools/memleak.c
Argument parsing errors are not detected for -p, -o, and -T due to the use of atoi.
So, fixed these to handle invalid arguments by using strtol instead.
Before:
```
using default object: libc.so.6
using page size: 4096
tracing kernel: false
Tracing outstanding memory allocs...  Hit Ctrl-C to end
using default object: libc.so.6
using page size: 4096
tracing kernel: true
Tracing outstanding memory allocs...  Hit Ctrl-C to end
```
After:
```
error arg:p haha
Usage: memleak_new [OPTION...]
Try `memleak_new --help' or `memleak_new --usage' for more information.
error arg:o 99999999999999999999999999999999999999999999999
Usage: memleak_new [OPTION...]
Try `memleak_new --help' or `memleak_new --usage' for more information.
invalid AGE_MS: 9999999999999999
Usage: memleak_new [OPTION...]
Try …
```
=> libbpf-tools/memleak: Fix to handle failure for invalid arguments

README.md
bcc commit d188e07c46e1 ("tools: add numasched: trace task switch between NUMA (#4396)") [1] add tools/numasched.py.
Link: https://github.com/iovisor/bcc/commit/d188e07c46e1e3da71b08f97c5d4f3cf69b16e09 [1]
=> README.md: Add tools/numasched contents

libbpf-tools/hardirqs.bpf.c
=> libbpf-tools/hardirqs: Fix logarithmic calculation issue

docs/tutorial_bcc_python_developer.md, examples/tracing/bitehist.py
Fix the same issue as the commit cccb26e3d69f0b263562c581add517ed23e1834b fixed for disksnoop.py previously.
`blk_account_io_done` became inline function since kernel v5.16 and `blk_account_io_done` has been taken off since v6.4. With this change, only when the code runs on a legacy kernel these `*_io_done functions` will be attached, otherwise it goes for `blk_mq_end_request`.
The tutorial lessons for both bitehist.py and disksnoop.py are updated accordingly.
=> examples/tracing/bitehist.py: Fix kprobe attaching failure

tools/sslsniff.py
BPF compiler fails to compile `min` with error:
cannot call non-static helper function
Fix #5241
=> tools/sslsniff: implement custom min to avoid non-static

tools/tcpdrop.py
This commit fixes an issue where tcpdrop would unexpectedly exit when the
tcp_drop() function is not found, even if the 'skb:kfree_skb' tracepoint
is traceable. Now, tcpdrop will continue running with a warning message
in that case.
=> tcpdrop: fix unexpected exit if tcp_drop() missing

tools/sofdsnoop.py
tools/sofdsnoop: Add argument "--ebpf"
Signed-off-by: yu410621 <lihuanyu410621@gmail.com>
=> tools/sofdsnoop: Add argument "--ebpf"

tools/readahead.py
Since Linux v5.16 (commit 76580b65 "mm/swap: Add folio_mark_accessed()") [1], filemap_read() no longer calls mark_page_accessed() but instead uses folio_mark_accessed(). This change caused the readahead tool to miss tracking accessed pages, resulting in incorrect statistics.
This patch fixes the issue by detecting whether folio_mark_accessed() or mark_page_accessed() is available in the kernel and probing the appropriate function to correctly count page accesses. The implementation maintains compatibility with both pre-v5.16 and post-v5.16 kernels.
This PR is similar to https://github.com/iovisor/bcc/pull/5257 for readahead Python version.
Verified with v5.15.60 (Arch Linux) and v6.8.0 (Ubuntu 2404).
[1]: https://github.com/torvalds/linux/commit/76580b65
=> tools/readahead: Fix incorrect page accessed count since v5.16

docs/kernel-versions.md
=> fix typo in "*precpu* cgroup storage"

libbpf-tools/uprobe_helpers.c
Fix the issue of unreleased resources
=> libbpf-tools: Fix the issue of unreleased resources

libbpf-tools/memleak.c
Extract the print_headers logic into a separate function to improve code maintainability and extensibility.
=> libbpf-tools/memleak: Extract print_headers
