iovisor/bcc

src/python/bcc/usdt.py, tools/tplist.py
Fixes #3478.
USDTProbe objects (and USDTProbeArguments and USDTProbeLocations) are instantiated with data that's sourced from libccc calls. That means that their attributes are bytes-typed, not string-typed.
When a bytes-typed value is rendered into a string with Python's '%s' formatting directive, it gets a wrapped in single quotes and prefixed with b. For example, b'probe-location'. This is visually noisy, but also breaks some tool behavior which uses string-formatted values for stuff like filters.
This is only an issue in Python 3. In Python 2, the bytes type is just an alias for the string type, and so byte sequences from libcc were implicitly decoded as ASCII text.
There are probably more spots like this to be fixed, but maybe we can improve things as we see them.
=> Decode bytes when formatting them as strings

docs/reference_guide.md, examples/networking/sockmap.py, src/python/bcc/__init__.py
In #3479, the `bpf_attach_type` enum was pulled into the `BPF` class so
that its members could be used in `attach_func` and `detach_func`
functions introduced to the Python API.
Unfortunately this caused a redefinition of BPF.XDP, which was similarly
pulled in from `bpf_prog_type` enum, thus breaking program loading
(#3489).
Let's pull these enum- and flag-type class variables out into their own
wrapper classes. For backwards compatibility, keep them all (except for
`bpf_attach_type`, which was merged 2 days ago) defined in the BPF
class, but add a comment to not continue doing this.
=> pull out enums from main BPF class to avoid namespace collisions

src/python/bcc/__init__.py, src/python/bcc/disassembler.py, src/python/bcc/table.py, src/python/bcc/tcp.py, src/python/bcc/usdt.py
1. remove unused imports, remove redundant semicolon
2. attach kprobe/kretprobe should not fail silently
=> bcc/python: fix attach kprobe/kretprobe using regex

libbpf-tools/trace_helpers.c, libbpf-tools/uprobe_helpers.c
Similar to past commits like 667988ce9e2a051ff608b727f6c89a5baa01fa67,
my toolchain complains that `_GNU_SOURCE` is redefined. Let's only
define it when it passes `ifndef`
=> libbpf-tools: Don't redefine _GNU_SOURCE to avoid redefinition warning

src/cc/api/BPF.cc, src/cc/api/BPF.h, src/cc/api/BPFTable.cc, src/cc/api/BPFTable.h, src/cc/export/helpers.h, tests/cc/test_map_in_map.cc, tests/python/CMakeLists.txt, tests/python/test_map_in_map.py
close #3496 
Hi team. I wrote a macro that can use custom key for `BPF_HASH_OF_MAPS`.
But in c++,   `get_map_in_map_table` is shared to `BPF_ARRAY_OF_MAPS`.
So, when using `BPF_ARRAY_OF_MAPS`, we have to declare like this.
```
auto t = bpf.get_map_in_map_table<int>("maps_array");
```
Is it okay?
-- solved --
Maybe I could wrote about `BPF_HASH_OF_MAPS` macro. But `.cc` files have errors. I've never write c++ programs, Can anyone help me?
```Bash
In file included from /home/*/bcc/tests/cc/test_map_in_map.cc:21:
In file included from /home/*/bcc/src/cc/api/BPF.h:25:
/home/*/bcc/src/cc/api/BPFTable.h:487:15: error: function 'ebpf::BPFMapInMapTable<custom_key>::update_value' is used but not defined in this translation unit, and cannot be defined in any other translation unit because its type …
```
=> Allow the use of custom keys in BPF_HASH_OF_MAPS

Dockerfile.tests
https://github.com/iovisor/bcc/runs/2882081015#step:7:133 (https://github.com/iovisor/bcc/runs/2882081015#step:4:1786)
I tested it and found that `python2` reports this error when using the version of `pyroute2` after 0.6.1.
In view of the fact that `python2` is no longer updated, the installation version of all the packages that `python2` depends on is specified here to avoid the test failure caused by the update of the related dependencies. (https://github.com/iovisor/bcc/runs/2515123487#step:4:1741)
=> bcc-test: fix test error

man/man8/tcprtt.8, tools/tcprtt.py, tools/tcprtt_example.txt
Support -v/--avg to show average RTT. Also some minor changes to
make histogram report easy to read. Orinally tcprtt does't show
lable/header without -b/-B option, currently it shows like this:
All Addresses = *******
=> tcprtt: support average RTT

tools/tcprtt.py
Suggested by Yonghong, tcprtt report error on python3:
TypeError: can't concat str to bytes
Both python2 and python3, inet_ntop returns a string type, there is
no need to encode any more.
Test for python2 and python3, both work fine.
=> tcprtt: fix compatibility for python3

libbpf-tools/execsnoop.bpf.c, libbpf-tools/execsnoop.c, libbpf-tools/execsnoop.h
execsnoop displays tid in its output with header PID,
which is wrong and differs from the original BCC tool.
This commit fixes that with some code cleanup.
=> libbpf-tools: display pid instead of tid

tools/argdist.py, tools/biolatency.py, tools/bitesize.py, tools/btrfsdist.py, tools/cachestat.py, tools/cpudist.py, tools/dbstat.py, tools/dcstat.py, tools/ext4dist.py, tools/funccount.py, tools/funcinterval.py, tools/funclatency.py, tools/hardirqs.py, tools/inject.py, tools/nfsdist.py, tools/pidpersec.py, tools/readahead.py, tools/runqlat.py, tools/runqlen.py, tools/softirqs.py, tools/stackcount.py, tools/tcprtt.py, tools/tcpsubnet.py, tools/tcpsynbl.py, tools/vfscount.py, tools/vfsstat.py, tools/wakeuptime.py, tools/xfsdist.py, tools/zfsdist.py
resolve https://github.com/iovisor/bcc/issues/3481
Here are some tools that don't need to be adjusted.
* biolatpts.py: uses per_cpu_map.
* bindsnoop.py:  There is no synchronous writing of the same key.
* cachetop.py: ditto. 
* llcstat.py: ditto.
* biolatpcts.py: ditto.
* offcputime.py: ditto.
* profile.py: ditto.
* offwaketime.py: ditto.
* tcpretrans.py: ditto.
* tcptop.py: ditto.
* tcpconnect.py: ditto.
=> tools: replace add with xadd

README.md, man/man8/kvmexit.8, src/python/bcc/__init__.py, tools/kvmexit.py, tools/kvmexit_example.txt
Display the exit_reason and its statistics of each kvm_exit for all
vcpus of all virtual machines.
Signed-off-by: Fei Li <lifei.shirley@bytedance.com>
=> Add kvmexit.py and kvmexit_example.txt

src/cc/bcc_syms.cc, src/cc/syms.h
As reported in #3487, when `/proc/PID/exe`'s symlink points to a
mountns-relative path from a different mountns than the tracing process,
we can fail to open it as we don't prepend `/proc/PID/root` .
A few potential solutions were discussed in that issue, we settled on
treating the main exe like any other map in `/proc/PID/maps`. Since it's
always the first map we can reuse existing code and get rid of
exe-specific helpers.
While writing this I noticed that the remaining place `get_pid_exe` is used, the USDT code, potentially also has a bug due to `get_pid_exe` and shouldn't be using it either if so. Will follow up
I still need to validate this. Plan on doing so with `libbpf-tools`' offcputime and hopefully some example that can be committed
=> ProcSyms should treat the executable like any other mapped file when symbolizing

tools/deadlock.py
deadlock.py fails on py3 with `TypeError: replace() argument 1 must be str, not bytes`
```
File "/home/oleg/tinfoil.runfiles/libbcc/tools/deadlock.py", line 570, in <module>
main()
File "/home/oleg/tinfoil.runfiles/libbcc/tools/deadlock.py", line 480, in main
text = text.replace(b'MAX_THREADS', str(args.threads));
TypeError: replace() argument 1 must be str, not bytes
```
=> [py3:tools/deadlock.py] fix usage of str.replace() method to make it py3 compatible

libbpf-tools/gethostlatency.bpf.c, libbpf-tools/gethostlatency.c, libbpf-tools/gethostlatency.h
This commit adds a new option to gethostlatency which
allows user to specify which libc to use for tracing.
This is useful when application is not linked against
default libc.
=> libbpf-tools: gethostlatency allow specify libc path

tools/biotop.py, tools/filetop.py, tools/slabratetop.py
Several top tools defined signal handler, but not used.
They work well without signal handler, so just remove it.
=> bcc/tools: remove unused signal handlers

src/python/bcc/containers.py
The filtering by mount namespace implementation relies on the
redefinition of the "struct mnt_namespace" internal kernel structure.
The layout of this structure changed in Linux 5.11 (https://github.com/torvalds/linux/commit/1a7b8969e664d6af328f00fe6eb7aabd61a71d13),
this commit adds a conditional on the kernel version to adapt to this
change.
/cc @alban
=> tools: Fix filtering by mount namespace

debian/changelog
* Support for kernel up to 5.13
* support for debug information from libdebuginfod
* finished support for map elements items_*_batch() APIs
* add atomic_increment() API
* support attach_func() and detach_func() in python
* fix displaying PID instead of TID for many tools
* new tools: kvmexit.py
* new libbpf-tools: gethostlatency, statsnoop, fsdist and solisten
* fix tools ttysnoop/readahead for newer kernels
* doc update and bug fixes
=> update debian changelog for release v0.21.0

man/man8/criticalstat.8, tools/criticalstat.py, tools/criticalstat_example.txt
In kernel 4.19 and later, the CONFIG_PREEMPTIRQ_EVENTS option is unused.
Instead, it requires a kernel built with CONFIG_PREEMPTIRQ_TRACEPOINTS.
=> tools/criticalstat: Add new kconfig option to warning message

tools/mountsnoop.py
this patch just replicates the fix done in
ef330a393be4b472627b1bfa7fbe50934e519e25
=> bcc/tools: update mountsnoop's based on comment in containers.py

tools/profile.py
With 715f7e6ec, `DO_KERNEL_RIP` was removed. That was the only user of the `kernel_ret_ip` field. I believe we can now remove that field.
=> profile.py: Remove unused kernel_ret_ip

tools/mountsnoop.py, tools/mountsnoop_example.txt
It is found that in the production environment, the system() function
or shell command is often used to start the mount process temporarily,
so the PPID field needs to be added to find the corresponding program.
Signed-off-by: Wen Yang <wenyang@linux.alibaba.com>
=> Tools: add the PPID field in mountsnoop

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/mountsnoop.bpf.c, libbpf-tools/mountsnoop.c, libbpf-tools/mountsnoop.h
This commit adds a new libbpf tool mountsnoop.
It has the same functionalities just as its
counterpart in BCC tools. The default output
is the same.
```
$ mountsnoop
COMM             PID     TID     MNT_NS      CALL
dockerd          1827    1903    4026531840  mount("overlay", "/data/docker/overlay2/153e6b58322c64cf4b2aac1b9caba42d390481a7d33a2bffe0eb858943d49fb6-init/merged", "overlay", 0x0, "index=off,lowerdir=/data/docker/overlay2/l/GWTHHZ2C3PYGAJ5GLTWLHMHHKR,upperdir=/data/docker/overlay2/153e6b58322c64cf4b2aac1b9caba42d390481a7d33a2bffe0eb858943d49fb6-init/diff,workdir=/data/docker/overlay2/153e6b58322c64cf4b2aac1b9caba42d390481a7d33a2bffe0eb858943d49fb6-init/work") = 0
dockerd          1827    1903    4026531840  umount("/data/docker/overlay2/153e6b58322c64cf4b2aac1b9caba42d390481a7d …
```
=> libbpf-tools: add mountsnoop

libbpf-tools/readahead.bpf.c
Libbpf readahead tool does not compile with bpftool v5.14. Since
commit 31332ccb756 ("bpftool: Stop emitting static variables in BPF
skeleton"), bpftool gen skeleton does not include static variables
into the skeleton file anymore.
Fixes the following compilation error:
readahead.c: In function 'main':
readahead.c:153:26: error: 'struct readahead_bpf__bss' has no member named 'hist'
153 |         histp = &obj->bss->hist;
|                          ^~
=> libbpf-tools: readahead: don't mark struct hist as static

tools/tcpstates.py
`dport` is network order in the kernel and needs `ntohs` to be unravelled for human consumption. 
`sport` is host order and doesn't need to changing, refer #639
=> tcpstates: incorrect display of dport

src/cc/frontends/clang/loader.cc, src/cc/frontends/clang/loader.h
I'm making some larger modifications to the loader. While reading
through the `do_compile` code I noticed that the common "remapped file"
operations - telling various CompilerInvocations about 'virtual'
includes and the virtual main c file - could be factored out to enhance
clarity.
This patch doesn't change functionality at all, nor does it try to make
any opinionated refactoring changes.
=> ClangLoader: Pull out common remapped file operations

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/exitsnoop.bpf.c, libbpf-tools/exitsnoop.c, libbpf-tools/exitsnoop.h
```shell
$ sudo ./exitsnoop
PCOMM            PID     PPID    TID     AGE(s)  EXIT_CODE
awk              2128720 2128718 2128720 0.01    0
sh               2128718 289432  2128718 0.01    0
zsh              2128721 2126939 2128721 0.00    0
a.out            2128722 2126939 2128722 0.28    signal 11 (Segmentation fault), core dumped
zsh              2128726 2126939 2128726 0.00    0
zsh              2128729 2128728 2128729 0.00    0
wc               2128730 2128728 2128730 0.00    0
zsh              2128728 2128727 2128728 0.01    0
git              2128731 2128727 2128731 0.00    code 1
git              2128732 2128727 2128732 0.00    code 128
```
=> libbpf-tools: add exitsnoop

man/man8/runqslower.8, tools/runqslower.py, tools/runqslower_example.txt
During a task hits schedule delay, in the high probability, the
previous task takes a long time to run. It's possible to dump the
previous task comm and TID by '-P' or '--previous' option.
=> tools/runqslower: add '-P' optional

src/python/bcc/__init__.py, src/python/bcc/perf.py, tests/python/CMakeLists.txt, tests/python/test_attach_perf_event.py, tests/python/test_clang.py, tests/python/test_free_bcc_memory.py, tests/python/test_lpm_trie.py, tests/python/test_map_batch_ops.py, tests/python/test_map_in_map.py, tests/python/test_queuestack.py, tests/python/test_ringbuf.py, tests/python/test_stackid.py, tests/python/test_tools_memleak.py, tests/python/test_tools_smoke.py, tests/python/test_tracepoint.py, tests/python/utils.py
Discussion in #3571 identified some low-hanging fruit improvements to the perf_event_attr ctype. This PR adds these improvements as well as adding the new test from #3571 to CMakeFiles.
First commit focuses on `perf_event_attr` ctype improvements: 
```
bcc/python: extend perf_event_attr ctype
This commit brings the Perf.perf_event_attr ctype in line with version 6
of struct perf_event_attr (see uapi/linux/perf_event.h kernel header).
Specifically:
* All named fields are added, including field names within anonymous
unions and bitfields
* Perf.perf_event_attr now complains when a field which isn't part of
the ctype struct is set.
* Goal here is to prevent users from setting a
recently-added field - which we haven't updated the ctype _fields_ to
include - and getting confused when it …
```
=> bcc/python: Improvements to python perf_event_attr ctype

libbpf-tools/runqslower.bpf.c, libbpf-tools/runqslower.c, libbpf-tools/runqslower.h
Sync change 508d9694ba7ea503cce821175ffca5a7740b832b.
During a task hits schedule delay, in the high probability, the
previous task takes a long time to run. It's possible to dump the
previous task comm and TID by '-P' or '--previous' option.
=> libbpf-tools: runqslow: add '-P' optional

docs/reference_guide.md, src/python/bcc/__init__.py
The uprobe also has a similar problem. I will fix it in a subsequent patch.
=> Add the support for detaching a single kprobe/kretprobe handler

man/man8/tcpretrans.8, tools/tcpretrans.py, tools/tcpretrans_example.txt
This commit adds the ability to print out tcp sequence numbers while
running the tool in normal mode by reading the appropriate fields from
skb. skb is not readily available for TLP, thus the output for that mode
is set to 0.
Signed-off-by: Michael Gugino <mgugino@redhat.com>
=> tools/tcpretrans: add optional tcp seq output

src/python/bcc/containers.py, tools/mountsnoop.py
Hi.
First, I hope you are fine and the same for your relatives.
In  kinvolk/inspektor-gadget#169, I added support for `mountsnoop` gadget.
To be able to use `--selector`, I needed to modify BPF code generated in `mountsnoop.py`.
First, I needed to call `filter_by_containers()` and also add check to `container_should_be_filtered()` in BPF code itself.
As `struct mnt_namespace` is defined in `mountsnoop.py` BPF code (as we want to snoop `mount` operations), I added guard around this definition, so we do not define this structure two times (one time in `mountnsoop.py` and the other in `containers.py`).
I tested these modifications inside `minikube` and using `inspektor-gadget` to interact with `mountsnoop.py`.
If you see any ways to improve this code, feel free to share.
Best regards.
=> Add filtering capabilities to mountsnoop.py

man/man8/argdist.8, tools/argdist.py, tools/argdist_example.txt
It's helpful to measure argdist in multi-thread case, so we can
distinguish workload is balanced of not.
=> toos: argdist: support [-t TID] filter

src/cc/frontends/clang/loader.cc
This is a better check than just checking the presence of the build dir.
In Gentoo Linux, when you remove the kernel source package, the leftover build directory is intentionally left in place. Which means the `/lib/modules/$(uname -r)/build` symlink still remains valid, but there's no `kconfig.h` there anymore[1]. This prevents bcc from using the `kheaders` (`/sys/kernel/kheaders.tar.xz`) fallback, instead making it fail later on:
<built-in>:1:10: fatal error: './include/linux/kconfig.h' file not found
#include "./include/linux/kconfig.h"
^~~~~~~~~~~~~~~~~~~~~~~~~~~
[1] https://bugs.gentoo.org/809347
=> Check for kconfig.h presence, not just build dir

src/python/bcc/containers.py
The filtering by mount namespace logic has to access
current_task->nsproxy->mnt_ns->ns.inum to get the mount namespace id. Before
this commit, that line was written in C natural syntax and we're relying on the
BCC rewriter to transform that to valid eBPF code by emitting some
bpf_probe_read calls.
This support was not working when using opensnoop in systems supporting kfuncs
because in this case the BCC rewriter doesn't transform that line and the
verifier claims about an invalid memory access:
7: (85) call bpf_get_current_task#35; return
current_task->nsproxy->mnt_ns->ns.inum; 8: (79) r1 = *(u64 *)(r0 +2896) R0
invalid mem access 'inv'
This commit fixes that by explicitly using bpf_probe_kernel_read() instead of
the C natural syntax.
--- 
It's not yet 100% clear that this is the best …
=> src/python: fix filtering by containers when kfunc are supported

tools/ttysnoop.py
Kernel commit [1] used ->iter_type and ->data_source instead of ->type
[1] 8cd54c1c8480 iov_iter: separate direction from flavour
Signed-off-by: Sina Radmehr <sina_rad@hamravesh.com>
=> tools/ttysnoop: Fix KFUNC_PROBE to support new iov_iter signature

debian/changelog
* Support for kernel up to 5.14
* add ipv4/ipv6 filter support for tcp trace tools
* add python interface to attach raw perf events
* fix tcpstates for incorrect display of dport
* new options for bcc tools runqslower, argdist
* new libbpf-tools: filetop, exitsnoop, tcprtt
=> update debian changelog for release v0.22.0

tools/threadsnoop.py
Since glibc 2.34, pthread features are integrated in libc directly.
Look for pthread_create there too when it is not found in libpthread.
Fixes #3623
=> threadsnoop: look for pthread_create in libc too

debian/control
There's no `llvm-8.0`, but instead, it's `llvm-8` in Ubuntu.
Ubuntu 16.04 is affected by this change, choosing llvm-8 instead of llvm-3.8.
=> fix debian build settings for LLVM package names

libbpf-tools/ksnoop.c
`ksnoop` is the only libbpf tool which is including both `<linux/bpf.h>` and `<bpf/bpf.h>` - the rest of the tools just include the latter
build fails for me because of redefinition errors as a result. Let's use `<bpf/bpf.h>` like the rest of the tools
=> ksnoop: remove duplicate include

.github/workflows/bcc-test.yml
As per [github](https://github.com/actions/virtual-environments/issues/3287), this is no longer supported. CI fails with errors like
```
This request was automatically failed because there were no enabled runners online to process the request for more than 1 days.
```
I will add 20.04 in a followup PR to match `publish.yml`. Want to keep it separate in case adding 20.04 causes issues, removing 16.04 should be much less likely to.
=> remove ubuntu 16.04 from bcc-test github action

libbpf-tools/bindsnoop.c, libbpf-tools/biosnoop.c, libbpf-tools/drsnoop.c, libbpf-tools/execsnoop.c, libbpf-tools/exitsnoop.c, libbpf-tools/filelife.c, libbpf-tools/filetop.c, libbpf-tools/fsslower.c, libbpf-tools/gethostlatency.c, libbpf-tools/ksnoop.c, libbpf-tools/mountsnoop.c, libbpf-tools/opensnoop.c, libbpf-tools/runqslower.c, libbpf-tools/solisten.c, libbpf-tools/statsnoop.c, libbpf-tools/tcpconnect.c, libbpf-tools/tcpconnlat.c
1. Most of the tools that use perf_buffer__poll() were not handling the
case when it was interrupted by a signal, they were just ending.
We noticed this issue by running the tools inside a container, after
some seconds they will finish:
```
$ time /execsnoop
...
runc             210198 939      0 /usr/sbin/runc --version
docker-init      210205 939      0 /usr/bin/docker-init --version
Error polling perf buffer: -4
real	0m48.913s
user	0m0.020s
sys	0m0.033s
```
This commit fixes that by checking if errno is EINTR after calling
perf_buffer__poll().
2. Many tools were returning non zero when ended by SIG_INT.
```
$ sudo ./execsnoop
PCOMM            PID    PPID   RET ARGS
runc             203967 939      0 /usr/sbin/runc --version
docker-init      203973 939      0 /usr/bin/docker-init …
```
=> libbpf-tools: fix EINTR related issues

tools/kvmexit.py
When Ctrl+C is hit, `^C` messes up the output header. Fix that
by adding a blank line before printing. Also remove unused import
and signal handler.
=> tools/kvmexit: Display header after KeyboardInterrupt

examples/tracing/undump.py
I commit it to "tools/" before(https://github.com/iovisor/bcc/pull/3598), push it here "examples/tracing" better.
1. start up server
[rongtao@localhost tools]$ nc --unixsock /work/workspace/undump3.sock -l
2. start undump.py 
[root@localhost study]# ./undump.py -p $(pidof nc)
Tracing UNIX socket packets ... Hit Ctrl-C to end
PID    COMM
3. startup UNIX  socket client
[rongtao@localhost ~]$ nc --unixsock /work/workspace/undump3.sock
4. input some words
[rongtao@localhost ~]$ nc --unixsock /work/workspace/undump3.sock
Hello, World
5. capture the packet
----------------48 65 6c 6c 6f 2c 20 57 6f 72 6c 64 0a 
----------------recv 13 bytes
153784 nc
=> Capture UNIX domain socket packet

src/cc/CMakeLists.txt, src/cc/link_all.cc
Here's a rather naive attempt to fix #3641 ...
---
When compiling with CMAKE_USE_LIBBPF_PACKAGE=yes and ENABLE_USDT=OFF, linking of test_static will fail due to undefined references to `bcc_usdt_new_frompath`, `bcc_usdt_close` and `bcc_usdt_new_frompid`. The reference comes from link_all.cc which references those functions irrespective of ENABLE_USDT.
As a fix, introduce EXPORT_USDT and wrap references to USDT functions inside link_all.cc within #ifdef.
=> Do not export USDT function when ENABLE_USDT is OFF

src/cc/export/helpers.h, tools/readahead.py, tools/vfsstat.py
Update KFUNC_PROBE and its family to allow instrument kernel
function without specifying arguments. Sometimes, we don't need
to bookkeep arguments at function entry, just store a timestamp.
This fix would allow this use case.
=> bcc: Allow KFUNC_PROBE to instrument function without arguments

src/cc/bpf_module.cc, src/cc/export/helpers.h
B's code generation needs these functions to exist in the object as it
emits some calls to these functions at IR stage, where 'always_inline'
directive results in no symbol for the function being emitted otherwise
as all uses are inlined.
For C, stop putting these helpers in a "helpers" section in object file.
For B, add a `B_WORKAROUND` ifdef check so the "helpers" section is
populated as expected.
There is almost certainly a more elegant way to fix this but would
require digging deep in the b frontend and potentially breaking other
things. Since B frontend hasn't been touched in many years and still
works, let's take the safer but uglier route.
=> export/helpers: only put helpers in special section for B lang

libbpf-tools/gethostlatency.c, libbpf-tools/ksnoop.c, libbpf-tools/ksnoop.h
There are memory leaks when attach a BPF program to multiple
targets in these tools. This is because we misuse the
bpf_program__attach_kprobe function, the returned struct bpf_link
object is not freed after use. Closes #3664.
=> libbpf-tools: Fix memory leaks in ksnoop/gethostlatency

tools/cachestat.py
Fix issue #3687.
The tool cachestat.py doesn't work with 5.15 kernel due to
kprobe function renaming. Adapt to the new function.
Also added a comment that static functions might
get inlined and the result may not be accurate if this happens.
More work can be done in the future to make the tool
more robust.
=> tools: fix cachestat.py with 5.15 kernel

tools/cachetop.py
The tool cachetop.py doesn't work with 5.15 kernel due to
kprobe function renaming. Adapt to the new function.
Commit 61087b961716 ("tools: fix cachestat.py with 5.15 kernel")
fixed a similar issue for cachestat.py.
=> tools: fix cachetop.py with 5.15 kernel

tools/lib/uobjnew.py
=> Fix garbled java class name problem of uobjnew.py

debian/changelog
* Support for kernel up to 5.15
* bcc tools: update for kvmexit.py, tcpv4connect.py, cachetop.py, cachestat.py, etc.
* libbpf tools: update for update for mountsnoop, ksnoop, gethostlatency, etc.
* fix renaming of task_struct->state
* get pid namespace properly for a number of tools
* initial work for more libbpf utilization (less section names)
=> update debian changelog for release v0.23.0

.github/workflows/bcc-test.yml, .github/workflows/publish.yml, tests/cc/test_sk_storage.cc, tests/python/test_rlimit.py, tests/python/test_tools_smoke.py
=> add ubuntu-20.04 to bcc-test.yml

src/cc/libbpf.h
some batch methods are missing in libbpf.h, but it's ok for python because the libbpf.so has these symbols, but i think it's better to add these requisite methods in header file
=> fix: add batch methods into libbpf.h

tests/python/test_call1.py
The test send a udp packet to test tailcalls.
The test may fail due to udp packet loss.
Let us mark the test as mayFail.
=> Mark test_call1.py mayFail

CMakeLists.txt
Since CMake 3.12, `${pkg}_ROOT` is supported if `CMP0074` is set to `NEW`. This allows users to select a particular version of LLVM very easily. For example, `cmake ... -DLLVM_ROOT=/usr/lib/llvm-13`.
See https://cmake.org/cmake/help/latest/policy/CMP0074.html#policy:CMP0074 for details.
=> Enable CMP0074 to allow `${pkg}_ROOT`, especially for LLVM_ROOT

man/man8/sslsniff.8, tools/sslsniff.py, tools/sslsniff_example.txt
This makes few improvements to `sslsniff` tool:
* This can send much larger data payload and also adds `--max-buffer-size` CLI option which allow changing this param.
* Fixes dealing with non ASCII protocols, previously struct was defined as array of chars which made python ctypes treat it as NULL terminated string and it prevents from displaying any data past the null byte (which is very common for http2 protocol).
* Adds more filtering and displaying options (`--print-uid`, `--print-tid`, `--uid <uid>`)
* Avoids printing any data if `SSL_read` have failed with error ( `<= 0` return value), buffer in such cases has meaningless data, since it wasn't really decrypted.
This also deals correctly with rare cases when `bpf_probe_read_user` fails (so buffer should be empty and should not be …
=> tools: improve sslsniff (send buffer & filtering)

src/cc/export/helpers.h
The trailing semicolon of a do-while style macro will cause an if-else condition without braces to fail compilation.
For example, Let's say we have a simple if-else statement:
```
if (condition)
foo(x);
else
bar(x);
```
Now we want to replace the `foo()` function with other macro `FOO`:
```
#define FOO(a)         \
do {                   \
// do something with a \
}   while(0);
if (condition)
FOO(x);
else
bar(x);
```
The above code will fail the compilation because of the redundant semicolon will end the statement of `if` clause, causing an orphan `else` clause.
Also notice that other do-while style macros are free of the trailing semicolon, so I think it's a good idea to make them align.
=> bcc: remove trailing semicolon of macro

libbpf-tools/tcprtt.bpf.c, libbpf-tools/tcprtt.c
Since inet_aton() converts IPv4 numbers-and-dots notation to binary in network byte order, there is no need to do htonl() again.
Signed-off-by: chendotjs <chendotjs@gmail.com>
=> libbpf-tools: fix local/remote address byte ordering in tcprtt

libbpf-tools/tcpconnlat.bpf.c, libbpf-tools/tcpconnlat.c, libbpf-tools/tcpconnlat.h
Add `-L` option introduced in https://github.com/iovisor/bcc/pull/3316 , make libbpf-tools `tcpconnlat` consistent with `tools/tcpconnlat.py`.
Signed-off-by: chendotjs <chendotjs@gmail.com>
=> libbpf-tools: add option to include 'LPORT' in tcpconnlat

src/cc/bpf_module_rw_engine.cc, src/cc/frontends/b/codegen_llvm.cc, src/cc/frontends/b/codegen_llvm.h
Fix issue #3734
llvm upstream commit
89eb85ac6eab [IRBuilder] Remove deprecated methods
deprecated some functions which are used by bcc.
Let us follow the above commit to use the underlying
implementation instead.
Note that I didn't create a common header for the newer
functions since b language support will be removed in
the near future.
=> fix llvm compilation failure

tools/hardirqs.py
Currently, hardirqs will count interrupt event simply while tracepoint
irq:irq_handler_entry triggered, it's fine for system without shared IRQ
event, but it will cause wrong interrupt count result for system with
shared IRQ, because kernel will interate all irq handlers belong to this
IRQ descriptor.
Take an example for system with shared IRQ below.
```
root@localhost:/# cat /proc/interrupts
CPU0
13:     385248     GICv3  39 Level     DDOMAIN ISR, gdma
...
23:      61532     GICv3  38 Level     VGIP ISR, OnlineMeasure ISR
```
DDOMAIN IRQ and gdma shared the IRQ 13, VGIP ISR and OnlineMeasure
shared the IRQ 23, and use 'hardirqs -C' to measure the count of these
interrupt event.
```
root@localhost:/# hardirqs -C 10 1
Tracing hard irq events... Hit Ctrl-C to end.
HARDIRQ …
```
=> hardirqs: fix duplicated count for shared IRQ

tools/hardirqs.py
Currently, hardirqs use tid as key to store information while tracepoint
irq_handler_entry. It works fine if irq is triggered while normal task
running, but there is a chance causing overwrite issue while irq is
triggered while idle task (a.k.a swapper/x, tid=0) running on multi-core
system.
Let's say there are two irq event trigger simultaneously on both CPU
core, irq A @ core #0, irq B @ core #1, and system load is pretty light,
so BPF program will get tid=0 since current task is swapper/x for both cpu
core. In this case, the information of first irq event stored in map could
be overwritten by incoming second irq event.
Use tid and cpu_id together to make sure the key is unique for each
event in this corner case.
Please check for more details at merge request #2804, #3733.
=> hardirqs: fix issue if irq is triggered while idle task (tid=0)

man/man8/trace.8, tools/trace.py, tools/trace_example.txt
This is for issue #3737 .
We should clear up the messy options in `strace.py`, and use `-u` for UID filtering (like opensnoop/execsnoop). But for now I'll just leave it as is to avoid breaking the documents.
=> Add --uid option to filter by user ID

src/cc/api/BPF.cc, src/cc/api/BPFTable.cc, src/cc/api/BPFTable.h, src/cc/bcc_exception.h, src/cc/frontends/b/loader.cc
This is done with the shell command:
```
sed -i 's|\([A-Z_a-z]\+\).code() != 0|!\1.ok()|' $(grep '\.code() != 0' src -rl)
```
This is part of #2697
=> !StatusTuple::ok() replaced StatusTuple::code() != 0 for files under src/ dir

libbpf-tools/biolatency.bpf.c, libbpf-tools/biolatency.c, libbpf-tools/biosnoop.bpf.c, libbpf-tools/biosnoop.c
- There are many libbpf-tools with various options. But we cannot pass cgroups path for filtering processes in cgroup.
- Example: https://github.com/iovisor/bcc/blob/master/libbpf-tools/tcpconnect.c#L177, cgroup is not yet implemented
- On user side:
- Pass cgroup path to user code, 
- Get the fd of cgroup path
- Update the fd to a map of type BPF_MAP_TYPE_CGROUP_ARRAY. This will store the fd of cgroup path.
- On BPF side 
- Using bpf_current_task_under_cgroup, 
- check if current task is not under cgroup fd, then exit
- If current task is under cgroup fd, then continue BPF code
- Build biosnoop 
```
$ cd libbpf-tools/
$ make biolatency biosnoop 
```
- Run biosnoop (**Cgroup default-hierarchy=hybrid**)
```
// Terminal 1 
12:freezer:/
11:cpuset:/
10:net_cls,net_prio:/
9:blkio:/user.slice …
```
=> Filter cgroup2 process to support tracing container

tools/biolatency.py, tools/biolatpcts.py, tools/biosnoop.py, tools/biotop.py
Several BCC bio tools are broken due to kernel change ([0]).
blk_account_io_{start, done} were renamed to __blk_account_io_{start, done},
and the symbols gone from /proc/kallsyms. Fix them by checking symbol existence.
[0]: https://github.com/torvalds/linux/commit/be6bfe36db1795babe9d92178a47b2e02193cb0f
=> tools: Fix BCC bio tools with recent kernel change

docs/reference_guide.md
Fix typo in reference guide, should be BPF_HISTOGRAM.
=> docs: Fix BPF_HISTGRAM typo in reference guide

tools/tcpstates.py
The tool tcpstates contains a struct id_t definition but not
referenced, remove it.
=> tools: Remove unused struct id_t definition in tcpstates

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/bashreadline.bpf.c, libbpf-tools/bashreadline.c, libbpf-tools/bashreadline.h
Bashreadline will print user inputs, returning from readline, of every
instance of bash shell.  Readline is in bash itself, linked
statically, for some devices, while others may link to libreadline.so.
This implementation finds the symbol in bash if possible. Or, it tries
to find libreadline.so using ldd if the symbol is not in bash.
Signed-off-by: Kui-Feng Lee <kuifeng@fb.com>
=> Implement bashreadline with libbpf.

src/cc/api/BPFTable.h
!StatusTuple::code() is equivalent to !StatusTuple::ok().
=> Replace !StatusTuple::code() with StatusTuple::ok() in src/cc/api/BPFTable.h

.github/workflows/bcc-test.yml, Dockerfile.tests, tests/python/test_tools_memleak.py, tests/python/test_tools_smoke.py, tests/python/test_uprobes.py
Move bcc-test github action's `matrix.os` to indicate the OS to run in
the container, not the test runner itself (just pin the latter to
ubuntu-20.04).
Also, fixup some tests that were failing when trying to run on 20.04
manually.
=> docker: Run tests on ubuntu-20.04 as well

src/python/bcc/__init__.py
The functions with prefix __SCT__ are static functions that are not traceable. Hence removed__SCT__ prefix functions in bcc get_kprobe_functions().
=> exclude static functions __SCT__

.github/workflows/bcc-test.yml, docker/Dockerfile.fedora
This makes no attempt to CMake-ify `libbpf-tools/Makefile`, so the build happens as a separate step
There's currently nothing using the generated executables to test, but ostensibly the `tests/python/test_tools_smoke.py` could be extended to do so. May be worth merging independently as there are lots of outstanding libbpf-tools PRs and quick feedback on whether build succeeds would be useful
Why fedora only? Installing `linux-tools-generic` package on Ubuntu, which contains `bpftool` causes problems since Ubuntu's `/usr/sbin/bpftool` is a script wrapper which tries to ensure that the installed bpftool (located in `/usr/lib/linux-tools/...`) kernel version matches the running kernel. Normally a useful thing to check. Also bpftools on 18.04 and 20.04 are too old to gen skel. All can be …
=> Build libbpf tools as part of fedora test run

libbpf-tools/tcprtt.bpf.c, libbpf-tools/tcprtt.c
This commit fixes judgement if tcp_rcv_established fentry exists and fentry prog by introducing BPF_CORE_READ.
Signed-off-by: chendotjs <chendotjs@gmail.com>
=> libbpf-tools: fix fentry prog in tcprtt

src/cc/frontends/clang/b_frontend_action.cc, src/python/bcc/table.py
The llvm commit aee49255074f ([0]) changes array type
from `int [4]` to `int[4]` (with space removed), which
breaks the assumption in BCC. This commit fixes this
issue and adds a comment to the related code. While at
it, also remove execution permission of file `table.py`.
[0]: https://github.com/llvm/llvm-project/commit/aee49255074fd4ef38d97e6e70cbfbf2f9fd0fa7
=> bcc: Fix array type handling due to llvm changes

src/cc/bcc_btf.cc, src/cc/bcc_btf.h
Some btf_ext-related APIs in libbpf are being deprecated because they
make incorrect assumptions. They're being used only by bcc currently, so
vendor them before they get deleted.
After / as part of #3660, may need to revisit the incorrect assumptions
being made here.
The functions and structs were ripped directly from libbpf with minimal
changes:
* Change void* arithmetic to uint8_t
* __u32 -> uint32_t and similar
* Add a wrapping namespace
* `rec_size` functions were not needed - just grab the rec_size
directly since type is no longer opaque to bcc
=> Vendor deprecated btf_ext APIs and structs

docs/reference_guide.md
=> bcc/docs: fix broken links in reference guide

src/cc/bcc_btf.cc, src/cc/libbpf.c
Several libbpf APIs used by BCC are deprecated, which causes
annoying compilation warnings. Update BCC to use the replacement
APIs. The code is mainly borrowed from libbpf itself.
=> bcc: Replace deprecated libbpf APIs

libbpf-tools/biolatency.bpf.c, libbpf-tools/biolatency.c, libbpf-tools/biopattern.bpf.c, libbpf-tools/biopattern.c, libbpf-tools/biosnoop.bpf.c, libbpf-tools/biosnoop.c, libbpf-tools/biostacks.bpf.c, libbpf-tools/biostacks.c, libbpf-tools/bitesize.bpf.c, libbpf-tools/bitesize.c
The vmlinux.h uses u32 to define dev_t. But the user-space process uses
<sys/types.h> which uses 8 bytes for dev_t. When the libbpf uses mapped
memory to update .rodata, it might override other variable's value. We
should use u32 to fix it.
And also fix `biosnoop -d $dev-name` issue.
Signed-off-by: Wei Fu <fuweid89@gmail.com>
=> libbpf-tools: fix dev_t type issue

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/bits.bpf.h, libbpf-tools/klockstat.bpf.c, libbpf-tools/klockstat.c, libbpf-tools/klockstat.h
This is a port of BCC's klockstat.  Differences from BCC:
- can specify a lock by ksym name, using -L
- tracks whichever task had the max time for acquire and hold, outputted
when -s > 1 (otherwise it's cluttered).
- does not reset stats each interval by default.  Can request with -R.
-------------
Usage: klockstat [-hRT] [-p PID] [-t TID] [-c FUNC] [-L LOCK] [-n NR_LOCKS]
[-s NR_STACKS] [-S SORT] [-d DURATION] [-i INTERVAL]
-p, --pid=PID              Filter by process ID
-t, --tid=TID              Filter by thread ID
-c, --caller=FUNC          Filter by caller string prefix
-L, --lock=LOCK            Filter by specific ksym lock name
-n, --locks=NR_LOCKS       Number of locks to print
-s, --stacks=NR_STACKS     Number of stack entries to print per lock
-S, --sort=SORT            Sort by …
=> libbpf-tools: add klockstat

libbpf-tools/klockstat.c
The PR adding the libbpf-tools port of klockstat was sitting in a
mergeable state for some time. Meanwhile, libbpf stopped exposing
rlimit_memlock bumping API and now does the rlimit bump automatically if
necessary. So remove the bump_rlimit_memlock call and set libbpf strict
mode for this tool.
Also, add a comment (from @brho's PR summary in #3688) detailing the
differences in default behavior between the libbpf-tools and bcc-python
versions.
=> libbpf-tools/klockstat: no more rlimit bumping + add comment

src/cc/bcc_syms.cc
Correctly identify VDSO using 'name' vs. 'path'.
Use of path incorrectly compares `/proc/<pid>/root[vdso]` with `[vdso]`.
Signed-off-by: Pete Stevenson <jps@pixielabs.ai>
=> bcc_syms.cc: bug fix; identify VDSO using 'name' vs. 'path'

libbpf-tools/klockstat.c
compile warning 
```bash
CC       klockstat.o
klockstat.c: In function ‘print_stats’:
klockstat.c:396:12: warning: implicit declaration of function ‘reallocarray’; did you mean ‘realloc’? [-Wimplicit-function-declaration]
stats = reallocarray(stats, stats_sz, sizeof(void *));
^~~~~~~~~~~~
realloc
klockstat.c:396:10: warning: assignment to ‘struct stack_stat **’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
stats = reallocarray(stats, stats_sz, sizeof(void *));
^
BINARY   klockstat
```
=> reallocarray: eliminate compilation warnings

libbpf-tools/README.md
An outdated libbpf submodule can cause the libbpf-tools `make` to fail. Adding note to the README on how to update it.
=> libbpf-tools: README how to update libbpf submodule

src/cc/libbpf.c, src/cc/libbpf.h, src/python/bcc/libbcc.py, src/python/bcc/table.py
This commit adds a new option `wakeup_events` to the open_perf_buffer API.
This provides an alternative to solve #3793.
=> bcc: Allow specify wakeup_events for perf buffer

CODEOWNERS
I can't figure out how to get emailed for all PRs, and I'm doing reviews for the whole repo, so add self to codeowners everywhere.
=> Add davemarchevsky to CODEOWNERS for everything

.github/workflows/bcc-test.yml, src/cc/bcc_common.cc, src/cc/bcc_common.h, src/python/bcc/libbcc.py, tests/cc/test_bpf_table.cc, tests/python/test_clang.py
I noticed this the other day. Just pushing this PR up to get signal from GH actions. On my local box, running the tests with this commit results in these failures:
```
The following tests FAILED:                                                                                                                                                                  
3 - test_libbcc (Failed)                                                            
16 - py_test_clang (Failed)                                                          
```
=> Add rwengine=OFF test run, disable tests we expect to fail during it

man/man8/trace.8, tools/trace.py, tools/trace_example.txt
Orignally we can save the backtrace of a specified function into a
text file, then try to analyze the messy trace to guess why the
function is called.
To make the work easier, aggregate amount of trace by -A with -M EVENTS.
A typical example:
1, if we find that the sys CPU utilization is higher by 'top' command
2, then find that the timer interrupt is more normal by 'irqtop' command
3, to confirm kernel timer setting frequence by 'funccount -i 1 clockevents_program_event'
4, to trace timer setting by 'trace clockevents_program_event -K -A -M 1000'
1294576 1294584 CPU 0/KVM       clockevents_program_event
clockevents_program_event+0x1 [kernel]
hrtimer_start_range_ns+0x209 [kernel]
start_sw_timer+0x173 [kvm]
restart_apic_timer+0x6c [kvm]
kvm_set_msr_common+0x442 [kvm]
__kvm_set_msr+0xa2 …
=> tools/trace.py: aggregate trace events by '-A' option

src/cc/libbpf.c
bpf_has_kernel_btf() is used to check whether the kernel has BTF or not.
It's part of the logic that checks if kfunc and lsm programs are supported.
Before this commit it used libbpf_find_vmlinux_btf_id(), this function
calls btf__load_vmlinux_btf() that tries to load the BTF from different
places, the canonical vmlinux in sysfs and other locations.
This is not accurate as kfunc and lsm programs require to have the BTF
file exposed directly by the kernel (CONFIG_DEBUG_INFO_BTF should be set).
This commit updates that function to check if BTF is exposed directly
by the kernel.
This was causing opensnoop to try to use kfunc programs (instead of
kprobes) in systems where they are not supported:
```
$ ls /usr/lib/debug/boot/vmlinux-$(uname -r)
/usr/lib/debug/boot/vmlinux-5.11.0-38-generic
$ …
```
=> libbpf: Fix kernel BTF detection logic

debian/changelog
* Support for kernel up to 5.16
* bcc tools: update for trace.py, sslsniff.py, tcptop.py, hardirqs.py, etc.
* new libbpf tools: bashreadline
* allow specify wakeup_events for perf buffer
* support BPF_MAP_TYPE_{INODE, TASK}_STORAGE maps
* remove all deprecated libbpf function usage
* remove P4/B language support
* major test infra change, using github actions now
=> update debian changelog for release v0.24.0

tools/oomkill.py
The OOM target PID should be task_struct->tgid.
=> tools/oomkill: Use task_struct->tgid as PID

src/cc/api/BPFTable.cc, src/cc/api/BPFTable.h
Like in #3801 and #3805, this patch adds a consume API
which allows user to force reading from perf buffer and
adds wake_events parameter on open_all_cpu API.
=> bcc: Update perf buffer C++ API

libbpf-tools/klockstat.bpf.c, libbpf-tools/klockstat.c
mostly just support for mutex_lock_{killable,interruptible}
=> libbpf-tools: minor klockstat changes

tools/funcslower.py
Walk user/kernel stack in trace_entry rather than trace_return, show the specified function on top of a stack.
```
...
b'kretprobe_trampoline'
b'__x64_sys_write'
b'do_syscall_64'
b'entry_SYSCALL_64_after_hwframe'
```
```
...
b'vfs_write'
b'__x64_sys_write'
b'do_syscall_64'
b'entry_SYSCALL_64_after_hwframe'
```
=> Walk user/kernel stack in trace_entry rather than trace_return

examples/tracing/biolatpcts.py, tools/biolatpcts.py
* `struct request` definition recently moved from blkdev.h to blk-mq.h
breaking both tools/biolatpcts and examples/tracing/biolatpcts. Fix them
by also including blk-mq.h.
* blk_account_io_done() got split into two parts - inline condition checks
and the actual accounting with the latter now done in
__blk_account_io_done(). The kprobe attachment needs to be conditionalized
to work across the change. tools/biolatpcts was already updated but
examples/tracing/biolatpcts wasn't. Fix it.
Signed-off-by: Tejun Heo <tj@kernel.org>
=> biolatpcts: Build fixes on recent kernels

man/man8/sslsniff.8, tools/sslsniff.py, tools/sslsniff_example.txt
Add verbose option to trace additional SSL_do_handshake calls before initial SSL_read or SSL_write, and a new LATms field to show function latency. This is useful for TLS performance analysis. Also correct the output to skip buffer display when it's not filled.
New tools (sslsnoop and ssllatency) are also added in bpftrace to further investigate inside TLS handshake routines for async SSL and cyprto functions.
The use case analysis is here: https://xutao323.github.io/2022/01/06/tls-acceleration-with-new-CPU.html
=> tools/sslsniff: add handshake call trace

libbpf-tools/filetop.bpf.c, libbpf-tools/filetop.h, tools/filetop.py
Different filesystems(partitions) can have files share the same inum.
And for regular files, inode->i_rdev is zero. So the combination of
inode->i_ino and inode->i_rdev is not enough to uniquely identify a file.
Let's use dev and rdev to identify a device. Closes #3824.
=> filetop: Use dev and rdev as device ID

libbpf-tools/bashreadline.c
CentOS Stream 9:
`gcc (GCC) 11.2.1`, 
`clang version 13.0.0`, 
`LLVM version 13.0.0`,
`ldd (GNU libc) 2.34`
```
In function ‘find_readline_so’,
inlined from ‘main’ at bashreadline.c:163:33:
bashreadline.c:135:17: warning: ‘fclose’ called on pointer returned from a mismatched allocation function [-Wmismatched-dealloc]
135 |                 fclose(fp);
|                 ^~~~~~~~~~
bashreadline.c: In function ‘main’:
bashreadline.c:119:14: note: returned from ‘popen’
119 |         fp = popen("ldd /bin/bash", "r");
|              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> popen should be pclose

src/cc/export/helpers.h, tests/cc/test_pinned_table.cc
The BPF_SK_STORAGE map is defined as below:
```
#define BPF_SK_STORAGE(_name, _leaf_type) \
struct _name##_table_t { \
int key; \
_leaf_type leaf; \
void * (*sk_storage_get) (void *, void *, int); \
int (*sk_storage_delete) (void *); \
u32 flags; \
};
```
The structure has two func pointer members, sk_storage_get and
sk_storage_delete, which will be translated to corresponding
bpf helpers by rewriter.
If a BPF_SK_STORAGE map is pinned to bpffs, the map can be
used in another bcc based process with BPF_TABLE_PINNED macro.
```
#define BPF_TABLE_PINNED(_table_type, _key_type, _leaf_type, _name, _max_entries, _pinned) \
BPF_TABLE(_table_type ":" _pinned, _key_type, _leaf_type, _name, _max_entries)
```
Miao Xu reported an issue such that the structure supporting BPF_TABLE
does not have func …
=> Fix issues with pinned sk_storage map

src/cc/export/helpers.h, tests/cc/test_pinned_table.cc
BPF_TABLE_PINNED has a feature to create a map and pin it if
the pinned map doesn't exist. Some maps, e.g., bpf_sk_storage map,
requires a non-zero flag for map creation. This patch extended
the BPF_TABLE_PINNED map to include an optional flags argument
for any pinned map which my require a non-zero flags.
=> extern BPF_TABLE_PINNED to include an optional flags argument

libbpf-tools/runqlen.c
switch the variable type of freq from bool to int depending on usage.
Signed-off-by: Eunseon Lee <es.lee@lge.com>
=> libbpf-tools/runqlen: fix variable type

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/oomkill.bpf.c, libbpf-tools/oomkill.c, libbpf-tools/oomkill.h
libbpf-tools: oomkill is a simple program that traces the Linux out-of-memory (OOM) killer
Total same as oomkill of bcc.
\#./oomkill 
Tracing OOM kills... Ctrl-C to stop.
11:41:47 Triggered by PID 636163 ("perf"), OOM kill of PID 636163 ("mysql"), 321382 pages, loadavg: 0.10 0.13 0.05 4/232 636418
The first line show that PID 321382, with process name "mysql", was OOM killed
when it reached 321382 pages (usually 4 Kbytes per page). This OOM kill
happened to be triggered by PID 636163, process name "perf", doing some memory
allocation.
More information can be exposed to users later through the oomkill tool.
Report bugs to https://github.com/iovisor/bcc/tree/master/libbpf-tools.
=> libbpf-tools: add oomkill tool

src/cc/usdt/usdt.cc
When attaching to a probe that is inlined multiple times without
specifying a pid (which is not always convenient, e.g. when a target
process is not running yet), the following exception occurs:
Exception: can't generate USDT probe arguments; possible cause is missing pid when a probe in a shared object has multiple locations
This is because eBPF programs distinguish between different locations
by doing a switch on an instruction pointer, and in order to get full
probe addresses in presence of ASLR, one has to choose a specific
process and inspect its /proc/{pid}/maps.
However, since shared objects are page-aligned, when all of the probe
locations have different page offsets, these offsets uniquely identify
locations. Adjust Probe::usdt_getarg() to generate a switch on page
offset if this …
=> Use page offsets to distinguish between locations

man/man8/sslsniff.8, tools/sslsniff.py, tools/sslsniff_example.txt
This adds `--extra-lib` flag, which might be quite useful if an application is using custom TLS libraries that is shipped with application or in case of containerized applications. Also want to mention that bcc can determine path to the library [automatically by inspecting](https://github.com/iovisor/bcc/blob/e83019bdf6c400b589e69c7d18092e38088f89a8/src/cc/bcc_proc.c#L419) `/proc/$pid/maps` (if pid has been specified), but this not always works. For example, if application hasn't been started yet (and you need to trace launching process), if you want to trace multiple processes at the same time, or if application hasn't loaded that library at that time.
This flag can specified multiple times (which allows to provide list of libraries), for example:
```
./sslsniff --extra-lib …
```
=> tools/sslsniff: trace extra libraries

tools/tcpaccept.py
Commit bf9765145b85 ("sock: Make sk_protocol a 16-bit value") which
landed in kernel 5.6 reorganized a bit the layout of struct sock. Now
sk_protocol is its own field which directly precedes sk_gso_max_segs and
it in turn directly precedes sk_lingertime. This naturally broke
tcpaccept on kernels starting with 5.6.
Signed-off-by: Nikolay Borisov <nborisov@suse.com>
=> tools/tcpaccept: Fix support for v5.6+ kernels

src/cc/bcc_debug.cc, src/cc/bpf_module_rw_engine.cc
With latest upstream llvm15, we have the following compilation
error:
```
<...>/src/cc/bpf_module_rw_engine.cc: In member function ‘int ebpf::BPFModule::annotate()’:
<...>/src/cc/bpf_module_rw_engine.cc:404:53: error: ‘class llvm::PointerType’ has no member named
‘getElementType’; did you mean ‘getArrayElementType’?
if (StructType *st = dyn_cast<StructType>(pt->getElementType())) {
^~~~~~~~~~~~~~
getArrayElementType
In file included from /usr/include/c++/8/memory:80,
from /<...>/llvm-project/llvm/build/install/include/llvm/ADT/SmallVector.h:28,
from /<...>/llvm-project/llvm/build/install/include/llvm/ADT/MapVector.h:21,
from /<...>/llvm-project/llvm/build/install/include/llvm/DebugInfo/DWARF/DWARFContext.h:12,
from /<...>/src/cc/bcc_debug.cc:22:
/usr/include/c++/8/bits/unique_ptr.h: In …
```
=> fix llvm15 compilation error

src/cc/frontends/clang/loader.cc
llvm14 changed the dwarf default to 5 and this breaks
debug=8 which intends to print out the source annotated
assembly code. For example, for biolatency.py with debug=8,
with llvm14 and latest llvm15, the following error will appear:
```
error: invalid reference to or invalid content in .debug_str_offsets[.dwo]:
insufficient space for 32 bit header prefix
```
Using dwarf-4 can work around the issue and source
annotated asm code can display properly:
```
trace_req_start:
; struct request *req = ctx->di; // Line  37
0:   79 11 70 00 00 00 00 00 r1 = *(u64 *)(r1 + 112)
1:   7b 1a f8 ff 00 00 00 00 *(u64 *)(r10 - 8) = r1
; u64 ts = bpf_ktime_get_ns(); // Line  38
2:   85 00 00 00 05 00 00 00 call 5
3:   7b 0a f0 ff 00 00 00 00 *(u64 *)(r10 - 16) = r0
; bpf_map_update_elem((void …
```
=> use dwarf-4 in compilation flags

src/cc/bcc_debug.cc
llvm upstream https://reviews.llvm.org/D119723 removed
header file llvm/DebugInfo/DWARF/DWARFCompileUnit.h from
llvm/DebugInfo/DWARF/DWARFContext.h and this
caused bcc compilation failure:
```
...
.../src/cc/bcc_debug.cc: In member function ‘void ebpf::SourceDebugger::dump()’:
.../src/cc/bcc_debug.cc:186:69: error: no matching function for call to
‘llvm::DWARFContext::getLineTableForUnit(llvm::DWARFCompileUnit*&)’
const DWARFLineTable *LineTable = DwarfCtx->getLineTableForUnit(CU);
^
In file included from /home/yhs/work/bcc/src/cc/bcc_debug.cc:22:
...
```
Similar to fix in https://reviews.llvm.org/D119723, let us explicitly
add llvm/DebugInfo/DWARF/DWARFCompileUnit.h in the .cc file.
=> fix a llvm compilation error due to header file reshuffle

libbpf-tools/oomkill.c
Current code shows the following warning because of n is not initialized if `f` is NULL.
```
oomkill.c: In function ‘handle_event’:
oomkill.c:49:12: warning: ‘n’ may be used uninitialized in this function [-Wmaybe-uniniti
alized]
49 |         if (n)
|            ^
```
=> libbpf-tools: Fix a compiler warning on oomkill

tools/tcpconnect.py
Kernel commit 8cd54c1c8480 (0) changes iov_iter->type to iov_iter->iter_type,
which breaks tcpconnect. This commit fixes it by detecting kernel struct field
existence.
Closes #3859.
[0]: https://github.com/torvalds/linux/commit/8cd54c1c848031a87820e58d772166ffdf8c08c0
=> tools: Fix tcpconnect with kernel 5.14

tools/bindsnoop.py
Commit bf9765145b85 ("sock: Make sk_protocol a 16-bit value") reorganizes
the layout of struct sock and make sk_protocol a field of u16. This makes
the bindsnoop print `UNKN` for its `PROT` field.
See ([0]) and ([1]) for more details.
[0]: #3845
[1]: https://github.com/torvalds/linux/commit/bf9765145b85
=> tools: Fix bindsnoop for kernel v5.6

src/cc/bcc_debug.cc, src/cc/bcc_debug.h, src/cc/bpf_module.cc, src/cc/bpf_module.h, src/cc/frontends/clang/b_frontend_action.cc, src/cc/frontends/clang/b_frontend_action.h, src/cc/frontends/clang/loader.cc, src/cc/frontends/clang/loader.h
__Context:__ I'm working on a project to enable bcc to create object files which can be loaded by `libbpf`'s loader. This will make enabling "modern" `libbpf` features - e.g. global variables - significantly easier and by its nature would make an AOT-compiled mode for bcc straightforward. bcc programs should be able to use this mode with minimal code changes.
In order to do this we need to support libbpf-style `SEC` attribute annotations, which requires some modification of internal loader/bookkeeping plumbing. The summary of the major commit in this branch elaborates:
```
bcc currently identifies each individual BPF prog in an object file by
putting the prog in a special ".bpf.fn.$FUNC_NAME" section when
preprocessing the AST. After JITting an object file, the location and
size of the …
```
=> bcc internals: Keep track of BPF progs using function instead of section

libbpf-tools/Makefile
Since the dir function returns a path which ends with a trailing slash,
there is no need to add it again.
Signed-off-by: Yuntao Wang <ytcoode@gmail.com>
=> libbpf-tools: remove redundant slash

libbpf-tools/bindsnoop.bpf.c, libbpf-tools/bindsnoop.h
Hi.
I was playing with CO-RE version of `bindsnoop` and I figured out the protocol is stored in an `__u8`.
Nothing really serious but sadly this can not suffice to store some protocol (like `MPTCP`).
So, I preferred to open a PR suggesting this change or at least make people aware of it.
Best regards.
=> libbpf-tools: Use __u16 for bindsnoop protocol.

libbpf-tools/opensnoop.bpf.c
The variable min_us and macro TASK_RUNNING are not used, remove them.
Signed-off-by: Yuntao Wang <ytcoode@gmail.com>
=> libbpf-tools/opensnoop: remove unused variable and macro

tools/biolatency.py, tools/biosnoop.py, tools/biotop.py
Kernel commit 24b83deb29b ("block: move struct request to blk-mq.h")
has moved struct request  from blkdev.h to blk-mq.h. It results in
several bio tools to fail with errors of the following type:
error: incomplete definition of type 'struct request'
Since blk-mq.h had always included blkdev.h. it is safe to simply
replace the inclusion of blkdev.h by blk-mq-h. It works on both older
and newer kernel.
Fixes: #3869
Signed-off-by: Jerome Marchand <jmarchan@redhat.com>
=> tools: include blk-mq.h in bio tools

src/python/bcc/__init__.py
symname is kept as a byte-sring. As such, when the exception message is created, it generates something like:
```
could not determine address of symbol b'function__entry'
```
By decoding the symname variable, the user will get the following message instead:
```
could not determine address of symbol function__entry
```
I took it one step further and added the module to the error message. An example of the new message:
```
could not determine address of symbol function__entry in /usr/bin/python
```
This will make it more clear for users as well as hide the implementation detail of having byte-strings, which shouldn't be exposed to users who simply rely on the tool instead of coding it themselves.
=> Decode symname for exception message when symbol cannot be found

examples/tracing/disksnoop.py
Kernel commit 24b83deb29b ("block: move struct request to blk-mq.h")
and be6bfe36db17 ("block: inline hot paths of blk_account_io_*()")
introduce changes which break disksnoop.
Like #3748 and #3877 but for disksnoop, this commit fixes those issues.
Closes #3825.
=> examples: Fix disksnoop

libbpf-tools/oomkill.c
Add -v(--verbose) and -h option to oomkill to display libbpf log.
Signed-off-by: Eunseon Lee <es.lee@lge.com>
=> libbpf-tools/oomkill: Add verbose and help option

tools/klockstat.py
When `DEBUG_LOCK_ALLOC` is set, mutex_lock is changed to mutex_lock_nested, which means that attaching the kprobe statically to mutex_lock won't work for all kernel configurations.
This change detects the available kprobe functions exposed by the kernel and ensures that the kprobe is attached correctly.
I tested this on a machines with `DEBUG_LOCK_ALLOC` set and without `DEBUG_LOCK_ALLOC` set and this change works correctly on both.
Fixes #3882
=> tools: fix klockstat when DEBUG_LOCK_ALLOC is set

libbpf-tools/runqlen.c
When use -O -C for count run queue occupancy for each CPU separately,
the first cpu statistics are correct; however, the data used by the
subsequent cpus are on top of the accumulation of the previous cpu data,
but not really separate-CPU statistics.
This is because the variables used for calculation are defined outside
the calculation loop body, resulting in the value of each variable being
accumulated on the basis of the previous calculation.
So put them into the loop body  to fix it.
Signed-off-by: Hailong Liu <liuhailong@linux.alibaba.com>
=> libbpf-tools/runqlen: Fix a run queue occupancy count issue with ‘-C’

libbpf-tools/klockstat.c
When CONFIG_DEBUG_LOCK_ALLOC is set ([0]), mutex_lock, mutex_lock_interruptible
and mutex_lock_killable become macro defines and gone from ksyms. Let's use
the *_nested functions as tracing targets instead.
[0]: https://github.com/torvalds/linux/blob/df0cc57e057f18e44dac8e6c18aba47ab53202f9/include/linux/mutex.h#L177-L209
=> libbpf-tools: Fix klockstat when CONFIG_DEBUG_LOCK_ALLOC is set

README.md, man/man8/biopattern.8, tools/biopattern.py, tools/biopattern_example.txt
Add biopattern.py (Based on libbpf-tools/biopattern) to identify random/sequential disk access patterns.
Example:
```
TIME      DISK     %RND  %SEQ    COUNT     KBYTES
22:12:57  vdb         0    99      193        772
22:12:58  vdb         0   100     1119       4476
22:12:59  vdb         0   100     1126       4504
22:13:00  vdb         0   100     1009       4036
22:13:01  vdb         0   100      958       3832
22:13:02  vdb         0    99      957       3856
22:13:03  vdb         0   100     1130       4520
22:13:04  vdb         0   100     1051       4204
22:13:05  vdb         0   100     1158       4632
[...]
```
@yonghong-song @davemarchevsky please help review this pr, thanks.
=> bcc/tools: Add biopattern.py to identify disk access patterns

man/man8/hardirqs.8, man/man8/softirqs.8, tools/hardirqs.py, tools/softirqs.py
Sometimes, I want to trace hard/soft IRQ events on specified CPU rather than all CPUs, for example, check whether they were balance or not. So I add cpu filter (-c CPU) to do this.
`./softirqs -c 1        # sum soft irq event time on CPU 1 only`
`./hardirqs -c 1       # sum hard irq event time on CPU 1 only`
@yonghong-song please help review this pr, thanks.
=> bcc/tools: Add cpu filter (-c CPU) for softirqs & hardirqs

tools/biolatency.py, tools/biolatpcts.py, tools/biosnoop.py, tools/biotop.py
During 5.17 dev cycle, the kernel dropped request->rq_disk. It can now be
accessed through request->q->disk. Fix the python ones in tools/. There are
more usages in other places which need to be fixed too.
Signed-off-by: Tejun Heo <tj@kernel.org>
=> biolatency, biolatpcts, biosnoop, biotop: Build fix for v5.17+

libbpf-tools/cachestat.c
The tool cachestat is broken on kernel 5.15 due to kernel function
renaming. Fix the tool by detecting symbol existence. See #3687 and
#3692.
=> libbpf-tools: Fix cachestat with kernel 5.15

src/cc/bpf_module.cc
llvm upstream patch https://reviews.llvm.org/D118652
did some header file cleanup and this breaks bcc with llvm15
with the following compilation error:
/.../src/cc/bpf_module.cc: In member function ‘void ebpf::BPFModule::dump_ir(llvm::Module&)’:
/.../src/cc/bpf_module.cc:231:39: error: no matching function for call to ‘llvm::legacy::PassManager::add(llvm::Module Pass*)’
PM.add(createPrintModulePass(errs()));
^
In file included from /.../src/cc/bpf_module.cc:25:
/.../include/llvm/IR/LegacyPassManager.h:58:8: note: candidate: ‘virtual void llvm::legacy::PassManager::add(llvm::Pass*)’
void add(Pass *P) override;
^~~
/.../include/llvm/IR/LegacyPassManager.h:58:8: note:   no known conversion for argument 1 from ‘llvm::ModulePass*’ to ‘llvm::Pass*’
Adding the include path "llvm/Pass.h" in …
=> Fix a llvm compilation bug

src/cc/bcc_btf.cc, src/cc/bcc_btf.h
btf__get_map_kv_tids() is deprecated and causes annoying compilation warnings.
Reimplement it in BCC.
=> bcc: Get rid of deprecated libbpf API btf__get_map_kv_tids()

tools/btrfsdist.py, tools/hardirqs.py, tools/xfsdist.py, tools/zfsdist.py
As pr #986,  remove b'' prefix in section header.
For example, hardirq's section header prefixed with b'', use bytes.decode function remove it.
```
hardirq = b'virtio0-input.2'
0 -> 1          : 1        |****************************************|
```
=> tools: Fix bytes<->str mixing in python3

libbpf-tools/Makefile
commit 531b698cdc20 ("libbpf-tools: Enable compilation warnings for
BPF programs") applies CFLAGS to all targets. However, some of the c
flags typically used by distribution are not available to the bpf
target. Add a new BPFCFLAGS macro to take care of that.
Fixes the following compilation error on fedora:
BPF      bashreadline.bpf.o
clang-13: warning: optimization flag '-ffat-lto-objects' is not supported [-Wignored-optimization-argument]
clang-13: warning: argument unused during compilation: '-specs=/usr/lib/rpm/redhat/redhat-hardened-cc1' [-Wunused-command-line-argument]
clang-13: warning: argument unused during compilation: '-specs=/usr/lib/rpm/redhat/redhat-annobin-cc1' [-Wunused-command-line-argument]
clang-13: warning: argument unused during compilation: '-fstack-clash-protection' …
=> libbpf-tools: Allow to use different cflags for bpf targets

src/cc/usdt.h, src/cc/usdt/usdt_args.cc
Support for using xmm registers for USDT args was added to systemtap in
early 2021 (commit 04c99d0d0267f574fa60044c96933b0dd3846aa1 added xmm0-7
and eaa15b047688175a94e3ae796529785a3a0af208 added xmm8-15). As a result
these registers are showing up in probe descriptors on Fedora.
pthread_start probe description on Ubuntu 20.04:
```
stapsdt              0x00000052       NT_STAPSDT (SystemTap probe descriptors)
Provider: libpthread
Name: pthread_start
Location: 0x00000000000095e9, Base: 0x000000000001922c, Semaphore: 0x0000000000000000
Arguments: 8@%rax 8@1600(%rax) 8@1608(%rax)
```
And in the Fedora test container:
```
stapsdt              0x00000053       NT_STAPSDT (SystemTap probe descriptors)
Provider: libpthread
Name: pthread_start
Location: 0x0000000000009280, Base: …
```
=> usdt: support xmm registers as args for x64

tools/biolatency.py, tools/biosnoop.py
Sometimes, req->rq_disk is NULL, for example, scsi cmd with non-data requests. As a consequence, biosnoop/biolatency output show empty disk colume，which may be confusing.
Example 1 (biolatency):
```
disk = b''
16 -> 31         : 0        |                                        |
32 -> 63         : 0        |                                        |
64 -> 127        : 0        |                                        |
128 -> 255        : 0        | …
```
=> tools/biolatency: Use '<unknown>' instead of empty disk name

man/man8/biotop.8, man/man8/cachetop.8, tools/biotop.py, tools/cachetop.py
Currently，xxxtop tools (dirtop, filetop, tcptop) already have PID filter option (-p PID), biotop, cachetop not yet. Sometimes, I just want to focus on a specifed process rathan than top N processes.
For example, use biotop to trace dd only:
```
./biotop.py -p $(pgrep -n dd) 1
```
```
09:00:55 loadavg: 0.97 0.36 0.13 1/459 548233
PID    COMM             D MAJ MIN DISK       I/O  Kbytes  AVGms
547692 dd               W 253 16  vdb       4898 19592.0   1.01
```
=> tools: Add pid filter option (-p PID) for biotop & cachetop

tools/compactsnoop.py, tools/drsnoop.py, tools/hardirqs.py, tools/mountsnoop.py, tools/softirqs.py, tools/syncsnoop.py
When redirect output of hardirqs/softirqs to a file, line buffering (_IOLBF) switched to full buffering (_IOFBF), it may take dozens of seconds to see last output. hardirqs/softirqs write relatively less chars than other tools (such as biosnoop/opensnoop) each second, buffer filling causes poor real-time. For example:
```
/usr/share/bcc/tools/hardirqs -CT 1 > hardirqs.out
```
```
tail -f hardirqs.out
First Output
<after 30s>
Second Output
<after 34s>
Third Output
...
```
As ttysnoop/memleak/biolatpcts, this patch use stdout.flush() to flush stdout explicitly in event loop.
xxxsnoop tools (compactsnoop/drsnoop/mountsnoop/syncsnoop) with low frequency usually, also flush them.
=> tools: Flush stdout explicitly in event loop

tools/bashreadline.py, tools/biosnoop.py, tools/biotop.py, tools/btrfsslower.py, tools/dbslower.py, tools/dcsnoop.py, tools/execsnoop.py, tools/filelife.py, tools/mdflush.py, tools/mysqld_qslower.py, tools/sslsniff.py, tools/swapin.py, tools/tcpconnect.py, tools/tcpconnlat.py, tools/tcpretrans.py, tools/tcptop.py, tools/threadsnoop.py
The "kernel.pid_max" sysctl is now bumped to 4194304 by default, so 6 chars not enough for PID colume. Some tools use %6d, some use %7d. This patch try to unify PID column width by %7d (at most 7 chars).
```
kernel.pid_max = 4194304
```
=> tools: Unify PID column width (at most 7 chars)

man/man8/softirqs.8, tools/softirqs.py, tools/softirqs_example.txt
Sometimes, I just want counts of soft irq events instead of timing. hardirqs has already added event counting support in #1460. This patch try to follow it.
```
Tracing soft irq events... Hit Ctrl-C to end.
^C
SOFTIRQ          TOTAL_count
block                      5
tasklet                    6
net_rx                   402
sched                   5251
rcu                     5748
timer                   9530
```
=> tools/softirqs: Add event counting support

man/man8/cpudist.8, tools/cpudist.py, tools/cpudist_example.txt
1. Fix concurrency issue caused by idle threads
Like #2804, #3740, pid as key not be suitable for multiple idle threads (pid = 0), which may lead to incorrect delta time.  Combines cpu and pid as unique key to avoid this issue.
2. Exclude CPU idle time by default
Currently, cpudist includes CPU idle time by default. When idle threads (pid = 0) mixed with other threads (pid != 0), the output of cpudist is not clear enough, CPU time distribution of idle threads are usually very large on a not busy system (hundreds of milliseconds, even > 1s). 
For example：
```
14:45:36
msecs               : count     distribution
0 -> 1          : 676      |****************************************|
2 -> 3          : 18       |*                                       |
4 -> 7          : 119      |******* …
```
=> tools/cpudist: Fix concurrency issue caused by idle threads & Exclude CPU idle time by default

libbpf-tools/cachestat.c, libbpf-tools/fsdist.c, libbpf-tools/fsslower.c, libbpf-tools/klockstat.c, libbpf-tools/solisten.c, libbpf-tools/tcprtt.c, libbpf-tools/tcpsynbl.c, libbpf-tools/trace_helpers.c, libbpf-tools/trace_helpers.h, libbpf-tools/vfsstat.c
On architectures that lack support for fentry programs, tools should
fall back to using kprobes even if the kernel version is new enough to
include BPF_TRACE_FENTRY, but fentry_exists() cannot currently detect
this case.
Add an additional check verifying that attaching a BPF_TRACE_FENTRY
program can actually succeed.
Signed-off-by: Connor O'Brien <connoro@google.com>
=> libbpf-tools: improve fentry_exists check

docker/Dockerfile.fedora
```
timeout: failed to run command ‘/bcc/tools/argdist.py’: No such file or directory
...
```
The reason for test_bcc_fedora CI failure is that argdist.py and other tools use '#!/usr/bin/python' as interpreter, but /usr/bin/python does not exist in fedora:34 latest image (recently changed), only /usr/bin/python3 exists. Whereas, /usr/bin/python exists in ubuntu image, which refers to /usr/bin/python -> /bin/python3 -> python3.8.
This patch try to create a symbolic links (/usr/bin/python -> python3.9) when building BCC fedora image.
All checks have passed now, please take a look at it. @yonghong-song @davemarchevsky
=> Fix test_bcc_fedora CI failure

tools/mdflush.py
CI failed due to the following error (in mdflush.py, bio->bi_disk not found). I guess CI runtime env (such as kernel version) had changed in recent days.
```
error: no member named 'bi_disk' in 'struct bio'
struct gendisk *bi_disk = bio->bi_disk;
~~~  ^
File "/bcc/tools/mdflush.py", line 54, in <module>
```
Before kernel 4.14, stay the same, just use bio->bi_bdev->bd_disk.
Since kernel 4.14, macro bio_dev begin to appear, which refers to bio->bi_disk. 
Since kernel 5.12, macro bio_dev has changed to bio->bi_bdev->bd_disk (bio->bi_bdev changed back). So, just use '#ifdef bio_dev' could not make the right choice under higher kernel version.
This patch try to fix this error. Please take a look. @davemarchevsky @yonghong-song
=> tools/mdflush: Fix CI build failure

src/cc/usdt.h, src/cc/usdt/usdt.cc, src/cc/usdt/usdt_args.cc
When compiling BCC with clang++, it reports the following warning:
warning: returning address of local temporary object [-Wreturn-stack-address]
Fixes it by returning a statically allocated `const char *`.
Closes #3949.
=> bcc/usdt: Fix returning address of local temporary object

docker/Dockerfile.fedora
Aha, test_bcc_fedora CI failed again, due to fedora image had been changed recently, /usr/bin/python comes back!
```
Step 5/7 : RUN ln -s $(readlink /usr/bin/python3) /usr/bin/python
---> Running in 039641fabbda
ln: failed to create symbolic link '/usr/bin/python': File exists
The command '/bin/sh -c ln -s $(readlink /usr/bin/python3) /usr/bin/python' returned a non-zero code: 1
```
This patch try to fix it. @davemarchevsky please take a look, thanks.
=> Refix test_bcc_fedora CI failure

libbpf-tools/cpudist.c, src/cc/libbpf.c
=> bcc: Replace deprecated libbpf API

examples/tracing/stacksnoop.py, examples/tracing/vfsreadlat.py
For examples/stacksnoop.py:
- Use pid as filter instead of tid, keep consistent with -p option of other tools.
- Make some improvements (remove ctypes & 'b' prefixes).
=> examples: Use pid as filter instead of tid and make some improvements for stacksnoop.py

CMakeLists.txt, tools/biolatency.py, tools/biolatpcts.py, tools/biosnoop.py, tools/biotop.py
BPF.kernel_struct_has_field possible return values: -1 (not support BTF), 1 (has a specified field), 0 (has no specified field).
This patch try to fix current flaws.
=> tools: Fix misuse of BPF.kernel_struct_has_field in bio* tools

man/man8/swapin.8, tools/swapin_example.txt
swapin: Adding missing entries of -T/ -h flag on the man page. The -T/ --notime flag does not show the timestamp (HH:MM:SS). In addition, -h/ --help shows the help message.
Signed-off-by: Vaibhav Nagare <nagarevaibhav@gmail.com>
=> [Man Page]: Add missing entry of -T & -h in man page along with example

man/man8/offwaketime.8, man/man8/swapin.8, tools/swapin_example.txt
offwaketime: Adding missing entry of -d flag in the man page of offwaketime. The -d/ --delimited inserts delimiter between kernel/user stacks
=> offwaketime-manpage: Add support for of -d in the offwaketime man page

man/man8/offwaketime.8, man/man8/profile.8, man/man8/swapin.8, tools/swapin_example.txt
-C CPU is missing in the SYNOPSIS section of the man page
=> profile-manpage: Add missing flag "-C" in the SYNOPSIS section of the man page

man/man8/biosnoop.8, man/man8/bitesize.8, man/man8/mdflush.8, man/man8/offwaketime.8, man/man8/profile.8, man/man8/swapin.8, man/man8/tcprtt.8, tools/swapin_example.txt
Previous man page:
~~~
OPTIONS
-h     Print usage message.
-Q     Include a column showing the time spent quueued in the OS.
~~~
Now:
~~~
OPTIONS
-h     Print usage message.
-Q     Include a column showing the time spent queued in the OS
~~~
=> biosnoop: Fixed the spelling mistake of quueued to queued

libbpf-tools/klockstat.bpf.c, libbpf-tools/klockstat.c
Hello,
This PR adds rwsem support to libbpf-tools/klockstat.  For kernel lock debugging, I found it useful to track rwsem as well as mutex.  This doesn't distinguish read and write to rwsem in the logic but users can see it in the caller info.
Example:
```
$ sudo klockstat -n 3 -s 3
Tracing mutex/rwsem lock events...  Hit Ctrl-C to end
^C
Caller  Avg Wait    Count   Max Wait   Total Wait
mutex_lock+0x5      1422      791      15628      1125030
do_epoll_wait+0x1ce
do_epoll_pwait.part.0+0xc
Max PID 2441, COMM murdockd
Caller  Avg Wait    Count   Max Wait   Total Wait
mutex_lock+0x5      1699      465      14471       790264
do_epoll_wait+0x1ce
__x64_sys_epoll_wait+0x60
Max PID 1864873, COMM svw_NetThreadEv
Caller  Avg Wait    Count   Max Wait   Total Wait
mutex_lock+0x5      1559      144 …
```
=> Add rwsem support to klockstat

libbpf-tools/biolatency.bpf.c, libbpf-tools/biosnoop.bpf.c, libbpf-tools/biostacks.bpf.c, libbpf-tools/bitesize.bpf.c
Since 5.17, The Linux kernel has dropped request->rq_disk, use request->q->disk instead. tools/bioxxx had been fixed not long ago, this patch try to fix libbpf-tools/bioxxx.
=> libbpf-tools: Fix dropped request->rq_disk for kernel 5.17+

tools/bashreadline.py, tools/btrfsslower.py, tools/dbslower.py, tools/ext4slower.py, tools/killsnoop.py, tools/mdflush.py, tools/mysqld_qslower.py, tools/nfsslower.py, tools/offcputime.py, tools/runqlat.py, tools/solisten.py, tools/xfsslower.py, tools/zfsslower.py
Some tools still use u64 as pid field type, this patch try to unify them.
=> tools: Use u32 as pid field type

INSTALL.md
When "make install bcc" in CentOS(7.X) system, we need the versions of llvm and clang to be greater than or equal to 10.0.0. Otherwise, an error will be reported as follows:
```
/tmp/bcc/src/cc/bpf_module.cc: In member function ‘virtual void ebpf::MyMemoryManager::notifyObjectLoaded(llvm::ExecutionEngine*, const llvm::object::ObjectFile&)’:
/tmp/bcc/src/cc/bpf_module.cc:108:46: error: no matching function for call to ‘llvm::object::SectionRef::getName() const’
auto sec_name = section.get()->getName();
```
=> Fix llvm and clang version in INSTALL.md

man/man8/funccount.8
funccount: Adding missing entries of [-c CPU] flag in the man page. This flag trace this CPU only
=> funccount: Add missing entry of [-c CPU]

man/man8/cachetop.8
Man page before:
~~~
FIELDS
PID    Process ID of the process causing the cache activity.
UID    User ID of the process causing the cache activity.
HITS   Number of page cache hits.
~~~
Man page now:
~~~
FIELDS
PID    Process ID of the process causing the cache activity.
UID    User ID of the process causing the cache activity.
CMD    Name of the process.
~~~
=> cachetop: Add missing entry of CMD in the FIELDS section

man/man8/drsnoop.8
Man page before:
~~~
OPTIONS
-h     Print usage message.
-T     Include a timestamp column.
-U     Show UID.
-p PID Trace this process ID only (filtered in-kernel).
-t TID Trace this thread ID only (filtered in-kernel).
-u UID Trace this UID only (filtered in-kernel).
-d DURATION
Total duration of trace in seconds.
-n name
Only print processes where its name partially matches 'name' -v verbose  Run  in  verbose
mode. Will output system memory state
~~~
Man page now:
~~~
OPTIONS
-h     Print usage message.
-T     Include a timestamp column.
-U     Show UID.
-p PID Trace this process ID only (filtered in-kernel).
-t TID Trace this thread ID only (filtered in-kernel).
-u UID Trace this UID only (filtered in-kernel).
-d DURATION
Total duration of trace in seconds.
-n name
Only print processes …
=> drsnoop: Add missing entry of -v in the options section

man/man8/filetop.8
Signed-off-by: Vaibhav Nagare <vnagare@redhat.com>
Man page before:
~~~
SYNOPSIS
filetop [-h] [-C] [-r MAXROWS] [-s {reads,writes,rbytes,wbytes}] [-p PID] [interval] [count]
~~~
Man page now:
~~~
SYNOPSIS
filetop [-h] [-a] [-C] [-r MAXROWS] [-s {reads,writes,rbytes,wbytes}] [-p PID] [interval] [count]
~~~
=> filetop: Add missing entry of -a in the SYNOPSIS section

tools/runqlen.py
When runqlen.py uses the -C parameter to show histograms for each CPU
separately, it can only output information for the first 64 CPUs when
the number of CPUs is large (e.g. AMD Milan has 256 CPUs).
This is because BPF_HISTOGRAM does not set the size of the BPF map
object in the code, and the default size is 64, so it can be fixed by
setting it to the current number of CPUs.
Signed-off-by: Zhiyong Ye <yezhiyong@bytedance.com>
=> tools/runqlen: Set the size of BPF map object according to the number of CPUs

man/man8/syscount.8, tools/syscount.py, tools/syscount_example.txt
For multi-threaded applications, such as MySQL, I just want to focus on syscall stats of a specified thread, rathan than all threads of the mysqld process (I am doing recently some performace optimizations on MySQL). This patch try to add tid filter (option -t) support.
=> tools/syscount: Add TID filter support

examples/tracing/biolatpcts.py, tools/biolatpcts.py
Depending on the inlining decisions made by the compiler, neither blk_account_io_done() or __blk_account_io_done() may be kprobable. Side step the whole thing by attaching to the block_rq_complete tracepoint. It'd be probably a good idea to update other users kprobing blk_account_io_done().
=> biolatpcts: Use block_rq_complete TP instead of kprobing blk_account_io_done()

tests/cc/test_c_api.cc
bcc/tests/cc/test_c_api.cc:159:10: warning: ‘char* strncpy(char*, const char*, size_t)’ specified bound 1024 equals destination size [-Wstringop-truncation]
159 |   strncpy(libpath, lm->l_name, 1024);
|   ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
=> Fix warning of strncpy() size field.

INSTALL.md
Refer the INSTALL.md, when run `cmake .. && make` in Ubuntu 20.04, an error will be reported as follows:
```
/tmp/bcc/src/cc/bpf_module.cc: In member function 'virtual void ebpf::MyMemoryManager::notifyObjectLoaded(llvm::ExecutionEngine*, const llvm::object::ObjectFile&)':
/tmp/bcc/src/cc/bpf_module.cc:117:46: error: no matching function for call to 'llvm::object::SectionRef::getName() const'
117 |       auto sec_name = section.get()->getName();
```
Change the version of llvm and clang from 7 to 10, another error will be reported as follows:
```
/usr/bin/ld: /usr/lib/llvm-10/lib/libclangCodeGen.a(BackendUtil.cpp.o): in function `(anonymous namespace)::EmitAssemblyHelper::EmitAssemblyWithNewPassManager(clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, …
```
=> Fix llvm and clang version for Ubuntu 20.04 in INSTALL.md

src/cc/bpf_module_rw_engine.cc
Compilation warnings:
/home/rongtao/Git/IO-Visor/bcc/src/cc/bpf_module_rw_engine.cc:60:22: warning: ‘llvm::LoadInst* llvm::IRBuilderBase::CreateLoad(llvm::Value*, bool, const llvm::Twine&)’ is deprecated: Use the version that explicitly specifies the loaded type instead [-Wdeprecated-declarations]
60 |   return B.CreateLoad(addr, isVolatile);
|          ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
/home/rongtao/Git/IO-Visor/bcc/src/cc/bpf_module_rw_engine.cc:75:29: warning: ‘llvm::Value* llvm::IRBuilderBase::CreateInBoundsGEP(llvm::Value*, llvm::ArrayRef<llvm::Value*>, const llvm::Twine&)’ is deprecated: Use the version with explicit element type instead [-Wdeprecated-declarations]
75 |   return B.CreateInBoundsGEP(ptr, idxlist);
|          ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
See llvm-project …
=> Fix compilation warnings.

INSTALL.md
Add Jammy(Ubuntu 22.04) package dependency guide.
issued in #4023
=> Add Ubuntu 22.04 package dependency guide

src/cc/bpf_module_rw_engine.cc
```
/home/rongtao/Git/bcc/src/cc/bpf_module_rw_engine.cc: In member function ‘int ebpf::BPFModule::annotate()’:
/home/rongtao/Git/bcc/src/cc/bpf_module_rw_engine.cc:419:63: warning: ‘llvm::Type* llvm::PointerType::getElementType() const’ is deprecated: Pointer element types are deprecated. You can *temporarily* use Type::getPointerElementType() instead [-Wdeprecated-declarations]
419 |       StructType *st = dyn_cast<StructType>(pt->getElementType());
|                                             ~~~~~~~~~~~~~~~~~~^~
In file included from /usr/include/llvm/IR/DataLayout.h:27,
from /usr/include/llvm/ExecutionEngine/ExecutionEngine.h:24,
from /usr/include/llvm/ExecutionEngine/MCJIT.h:17,
from /home/rongtao/Git/bcc/src/cc/bpf_module_rw_engine.cc:20:
/usr/include/llvm/IR/DerivedTypes.h:675:9: …
```
=> Fixed 'getElementType() is deprecated' compile warning.

tools/exitsnoop.py
1. As execsnoop/mountsnoop, use task->real_parent instead of task->parent (when one process being traced, the tracer becomes its parent, so use task->real_parent is more accurate).
2. As #3915, try to unify PID/PPID/TID column width (at most 7 chars).
=> tools/exitsnoop: Use task->real_parent instead of task->parent

man/man8/biolatency.8, tools/biolatency.py, tools/biolatency_example.txt
Sometimes, I just want to focus on a specified disk rather than all disks or per-disk. Refer to libbpf-tools/biolatency, this patch try to add disk filter support.
=> tools/biolatency: Add disk filter support

libbpf-tools/Makefile
Hi team,
This commit is to add cross-compile support, previous related commit is https://github.com/libbpf/libbpf/pull/495
With these 2 commits, I verified cross compilation for arm64 is good.
=> libbpf-tools: add support for cross compilation

libbpf-tools/klockstat.bpf.c, libbpf-tools/klockstat.c
A couple of updates of klockstat in libbpf-tools.  The most important change is the per-thread mode (`-P` option) to track lock wait/hold stats for each task.  Also changed time format to have units.
```
$ sudo klockstat -n 5 -d 3 -P
Tracing mutex/sem lock events...  Hit Ctrl-C to end
Tid              Comm  Avg Wait    Count   Max Wait   Total Wait
8428   IPDL Background    4.8 us      213   379.0 us       1.0 ms
8369    IPC I/O Parent    2.0 us      889   194.5 us       1.8 ms
139151     IPC I/O Child    2.0 us      929   148.0 us       1.8 ms
8400    GLXVsyncThread    3.1 us      182    25.9 us     559.9 us
139148       Web Content    1.5 us     1013    24.0 us       1.5 ms
Tid              Comm  Avg Hold    Count   Max Hold   Total Hold
366280    kworker/u16:32   21.5 us     1760 …
```
=> libbpf-tools/klockstat update

libbpf-tools/biosnoop.c, libbpf-tools/biostacks.c
The tools biosnoop and biostacks are broken due to kernel change ([0]).
blk_account_io_{start, done} were renamed to \_\_blk_account_io_{start, done},
and the symbols gone from vmlinux BTF. Fix them by checking symbol existence.
[0]: https://github.com/torvalds/linux/commit/be6bfe36db1795babe9d92178a47b2e02193cb0f
=> libbpf-tools: Fix bio tools

man/man8/funcinterval.8
Remove executable permission for 'funcinterval.8'.
=> Remove executable permission for 'funcinterval.8'.

tools/xfsslower.py
ENV
* centos-stream9
* kernel 5.14.0-105.el9.x86_64
* bcc: newest
* LLVM version 14.0.0
ERROR:
```
$ sudo ./xfsslower.py
[...]
80: (07) r4 += -104
; bpf_perf_event_output(ctx, bpf_pseudo_fd(1, -2), CUR_CPU_IDENTIFIER, &data, sizeof(data));
81: (bf) r1 = r6
82: (18) r3 = 0xffffffff
84: (b7) r5 = 96
85: (85) call bpf_perf_event_output#25
invalid indirect read from stack R4 off -104+92 size 96
processed 82 insns (limit 1000000) max_states_per_insn 0 total_states 4 peak_states 4 mark_read 3
File "/home/rongtao/Git/rtoax/bcc/tools/./xfsslower.py", line 271, in <module>
b.attach_kretprobe(event="xfs_file_read_iter", fn_name="trace_read_return")
File "/usr/lib/python3.9/site-packages/bcc/__init__.py", line 868, in attach_kretprobe
fn = self.load_func(fn_name, …
```
=> Fix: Failed to load BPF program b'trace_read_return': Permission denied

libbpf-tools/tcpconnect.bpf.c
With the latest clang and bpftool the build of tcpconnect fails as
follows (output patched a bit for readability):
bpftool gen skeleton tcpconnect.bpf.o > tcpconnect.skel.h
Error: Something is wrong for .rodata's variable #1: need offset 0, already at 4.
This happens because the filter_ports variable is declared using a ".rodata hack":
SEC(".rodata") int filter_ports[MAX_PORTS]
This breaks with the recent clang, as the filter_ports variable is placed into
the '.rodata,aw' section. Older clang would put it into '.rodata,a' section
where all 'const volatile' variables are placed. The result is that the
filter_ports variable has a wrong offset of 0 in BTF_KIND_DATASEC.
To hack the hack we can declare the variable as
SEC(".rodata") const int filter_ports[MAX_PORTS]
but, instead, we now can …
=> libbpf-tools: fix tcpconnect build errors

src/python/bcc/__init__.py
Add more hints for error kprobe.
Before:
```
$ sudo ./funccount.py -i 1 'xfs_f*'
cannot attach kprobe, Invalid argument
Failed to attach BPF program b'trace_count_62' to kprobe b'xfs_fs_eofblocks_from_user'
```
Like bpftrace tell more information
```
$ sudo bpftrace -e 'kprobe:xfs_fs_eofblocks_from_user {}'
stdin:1:1-34: WARNING: xfs_fs_eofblocks_from_user is not traceable (either non-existing, inlined, or marked as "notrace"); attaching to it will likely fail
kprobe:xfs_fs_eofblocks_from_user {}
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Attaching 1 probe...
cannot attach kprobe, Invalid argument
ERROR: Error attaching probe: 'kprobe:xfs_fs_eofblocks_from_user'
```
After:
```
$ sudo ./funccount.py -i 1 'xfs_f*'
cannot attach kprobe, Invalid argument
Failed to attach BPF program b'trace_count_10' …
```
=> Add more hints for error kprobe.

src/cc/bpf_module.cc, src/cc/libbpf.c, src/cc/libbpf.h
Since https://github.com/libbpf/libbpf/commit/7e8d4234ac0b24492dd473a2ba80204e175b87df, this structure is gone from libbpf.
BCC uses it as a structure to pass around `bcc_create_map_xattr` and `libbpf_bpf_map_create`.
The alternative would be to modify both libbpf_bpf_map_create and bcc_create_map_xattr to take each arguments, which I am not sure it would be any better.
Renamed the struct from `bpf_create_map_xattr` to `bcc_create_map_xattr` to better reflect this is a bcc-provided struct, not bpf anymore.
=> sync with libbpf + backport `struct bpf_create_map_attr`

tools/tcpdrop.py
Add `tcp_drop_reason()` support, since linux-5.18 https://elixir.bootlin.com/linux/v5.18/source/net/ipv4/tcp_input.c#L4688
=> Add `tracepoint:skb:kfree_skb` support

libbpf-tools/llcstat.bpf.c, libbpf-tools/llcstat.c, libbpf-tools/llcstat.h, man/man8/llcstat.8, tools/llcstat.py, tools/llcstat_example.txt
The tools/llcstat only collect info pre-process, sometimes, I just want to focus on per-thread rather than per-process.
This patch tries to add tid info support.
=> tools/llcstat: Add TID info support

libbpf-tools/filelife.c, libbpf-tools/syscount.bpf.c, libbpf-tools/tcpconnect.bpf.c, libbpf-tools/tcpconnlat.bpf.c, libbpf-tools/tcpconnlat.c
Running some libbpf tools on old kernels (e.g. kernel v5.4) results in error.
This is mainly because the BPF verifiers shipped with old kernels does NOT
smart enough to do dead code elimination and range check, etc. Or missing some
features.
Fixing them by making the BPF verifier happy and do feature detection.
=> libbpf-tools: Various fixes for old kernels

man/man8/biosnoop.8, tools/biosnoop.py, tools/biosnoop_example.txt
It may be useful to focus on a specified disk rather than all disks. Refer to libbpf-tools/biosnoop, this patch try to add disk filter support.
@yonghong-song Please have a look, thanks.
=> tools/biosnoop: Add disk filter support

libbpf-tools/biopattern.bpf.c, libbpf-tools/core_fixes.bpf.h
After kernel commit d5869fdc189f ("block: introduce block_rq_error tracepoint"),
tracepoint block_rq_complete now shares the same argument struct as
`struct trace_event_raw_block_rq_completion` with tracepoint block_rq_error.
Because of that, now biopattern is broken because `struct trace_event_raw_block_rq_complete`
is disappeared from kernel BTF. Fix it by checking type existence.
=> libbpf-tools: Fix biopattern with recent tracepoint change

src/cc/bcc_syms.cc, src/cc/bcc_syms.h, tests/cc/test_c_api.cc
`bcc` does various conversions of "global address" to "module offset" and
vice versa. Previous work (#1670) modified the "global address" ->
"module offset" calculation in `ProcSyms::Module::contains` to account
for differences between the file offset a section is loading bytes from
and the requested start address (relative to the base address of the
`.so`). Unfortunately that change didn't also modify "module offset" ->
"global address" calculations, such as the one in
bcc_resolve_global_addr. Update that calculation to account for the
same.
This calculation discrepancy was most apparent for us in production when
trying to attach USDTs to a shared lib with differing requested start
address and file offset. This patch also adds a test w/ comments
describing our specific situation and …
=> bcc/syms: Fix shared lib module offset <-> global addr conversion

CMakeLists.txt, src/cc/bpf_module.cc
First diff add support to enable building bcc with sanitizer enabled.
The second diff fixes a leak in BPFModule and use the result of the sanitizer run to confirm the leak is gone.
=> Add support to enable sanitizer + fix mem leak

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/slabratetop.bpf.c, libbpf-tools/slabratetop.c, libbpf-tools/slabratetop.h
Total same as [slabratetop(8)](https://github.com/iovisor/bcc/blob/master/tools/slabratetop.py), but add some options params:
```bash
$ sudo ./slabratetop -h
Usage: slabratetop [OPTION...]
Trace slab kmem cache alloc by process.
USAGE: slabratetop [-h] [-p PID] [interval] [count]
EXAMPLES:
slabratetop            # slab rate top, refresh every 1s
slabratetop -p 181     # only trace PID 181
slabratetop -s count   # sort columns by count
slabratetop -r 100     # print 100 rows
slabratetop 5 10       # 5s summaries, 10 times
-C, --noclear              Don't clear the screen
-p, --pid=PID              Process ID to trace
-r, --rows=ROWS            Maximum rows to print, default 20
-s, --sort=SORT            Sort columns, default size [name, count, size]
-v, --verbose              Verbose debug …
```
=> add slabratetop libbpf-tools

tests/python/test_tools_smoke.py, tools/offcputime.py
It's failing on ubuntu 18.04 only. I spent some time trying to figure
out why but was unable to repro in same ubuntu test container on my
host. Let's mayFail it for now so test signal is better.
=> tests/python: @mayFail offcputime in py_smoke_tests

src/python/bcc/__init__.py, tests/python/test_clang.py
Testing: Added a new test to test_clang that loads a program of type `CGROUP_SOCKOPT`
```
16: .
16: ----------------------------------------------------------------------
16: Ran 84 tests in 83.695s
16:
16: OK (skipped=4)
16: 0
16/41 Test #16: py_test_clang ....................   Passed   84.14 sec
```
=> [py] Add support for CGROUP_SOCKOPT program type

src/cc/common.cc
Commit 3087c61ed2c4 ([0]) changes `TASK_COMM_LEN` from macro to enum.
With this change, we have:
field:char comm[TASK_COMM_LEN]; offset:8;       size:16;        signed:1;
in tracepoint format.
If users do NOT include proper headers, will result in:
/virtual/main.c:4:12: error: use of undeclared identifier 'TASK_COMM_LEN'
char comm[TASK_COMM_LEN];
^
Let's handle this with BTF info.
Closes #4092.
[0]: https://github.com/torvalds/linux/commit/3087c61ed2c48548b74dd343a5209b87082c682d
=> bcc: Fix tracepoint struct generation

src/cc/export/helpers.h, src/cc/frontends/clang/arch_helper.h, src/cc/frontends/clang/b_frontend_action.cc, src/cc/frontends/clang/kbuild_helper.cc, src/cc/frontends/clang/loader.cc
In order to fix the issue #4081 , some basic support for RISC-V64 has been added. With this patch, running examples/hello_world.py can get the expected result.
However, BCC tool using bpf_probe_read() helper, which will report an error on RISC-V64 because the ARCH_HAS_NON_OVERLAPPING_ADDRESS_SPACE config option in kernel is not set. This will be resolved by updating the BCC tools and BCC itself with the appropriate bpf_probe_read_{kernel,user}[_str()] helpers.
This PR currently only supports RISCV64.
Signed-off-by: Mingzheng Xing [mingzheng.xing@gmail.com](mailto:mingzheng.xing@gmail.com)
Co-authored-by: Yixun Lan [dlan@gentoo.org](mailto:dlan@gentoo.org)
=> riscv: initial ebpf support

libbpf-tools/ksnoop.c
Running ksnoop with an invalid func will cause
panic, testing with glibc 2.35.
Error:
```
$ ./ksnoop info xxx
Error: [1]    41304 segmentation fault (core dumped)  ./ksnoop info xxx
```
Fixed by changing format string to %s.
Signed-off-by: Chen Yaqi <chendotjs@gmail.com>
=> libbpf-tools: fix ksnoop panic

src/cc/export/helpers.h
Fix #4110 . With this patch, running tools/cachestat on riscv64 can get the expected result.
```
$ sudo ./cachestat 
HITS   MISSES  DIRTIES HITRATIO   BUFFERS_MB  CACHED_MB
0        0        0    0.00%           52       5869
0        0        0    0.00%           52       5869
0        0        0    0.00%           52       5869
0        0        0    0.00%           52       5869
0        0        0    0.00%           52       5869
618        0        0  100.00%           52       5869
0        0        0    0.00%           52       5869
0        0        0    0.00%           52       5869
0        0        0    0.00%           52       5869
0        0        0    0.00%           52       5869
0        0        0    0.00%           52       5869
0        0        0    0.00%           52 …
```
=> riscv:fix user_regs_struct macro issue

src/cc/frontends/clang/b_frontend_action.cc, src/cc/frontends/clang/b_frontend_action.h
According to the bcc Reference Guide [[0]](https://github.com/iovisor/bcc/blob/master/docs/reference_guide.md#rewriter), for non-s390, the rewriter will use bpf_probe_read() for implicit memory access. This is because some existing users may have implicit memory accesses to access user memory, so using bpf_probe_read_kernel() will cause their applications to fail.
In riscv64, we should use the new bpf_probe_read_{kernel|user} function instead of the old bpf_probe_read(). riscv64 does not have overlapping address spaces, but does not have ARCH_HAS_NON_OVERLAPPING_ADDRESS_SPACE set like x86. And bpf_probe_read() is not available in riscv64, so it will cause an error.
This patch works fine to correctly use bpf_probe_read_{kernel|user}() on riscv64 until issues that may break existing user …
=> riscv: using bpf_probe_read_{kernel|user} on riscv64

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/sigsnoop.bpf.c, libbpf-tools/sigsnoop.c, libbpf-tools/sigsnoop.h, libbpf-tools/sigsnoop_example.txt
Add a sigsnoop tool which can be used to trace signals issued
by syscalls system-wide. This tool is a work based on BCC's
killsnoop, but extended to support more signal-related syscalls.
`sigsnoop -k` will behave the same as the killsnoop tool.
Output of killsnoop:
```shell
sudo ./killsnoop
TIME     PID     COMM             SIG  TPID    RESULT
00:00:23 799     rsyslogd         22   799     0
```
Output of sigsnoop:
```shell
sudo ./sigsnoop
TIME     PID     COMM             SIG  TPID    RESULT
22:38:21 830     containerd       23   905     0
22:38:21 178088  gopls            23   178088  0
22:38:24 830     containerd       23   905     0
22:38:24 178088  gopls            23   178088  0
22:38:24 830     containerd       23   906     0
22:38:25 178088  gopls            23   178088  0
``` …
=> libbpf-tools: add sigsnoop

tests/wrapper.sh.in
When working on fixing individual tests, it is useful to be able to tell the test suite to only run that individual test.
The catch framework allows to do this. See https://github.com/catchorg/Catch2/blob/devel/docs/command-line.md#specifying-which-tests-to-run
When the wrapper was originally introduced, it used to pass the list of arguments to the tests as an array.
For some reasons, it got changed in https://github.com/iovisor/bcc/commit/7009b559f390292b1ee4b3970aca88b2272c52fd#diff-29e66e11b6682a5b66d214c108dd3c351a557bc884b64946af004e0e3195d209
This diff, re-introduces passing the list of arguments as an array (`$@`).
Also, it needs to be double-quoted in order to be able to handle space in test names.
Before:
```
$ docker run -ti \
--privileged \
--network=host \
--pid=host \
-v …
```
=> [test] Fix wrapper script to allow testing individual tests

man/man8/cpudist.8, tools/cpudist.py, tools/cpudist_example.txt
Sometimes, I want to known total on-CPU or off-CPU time and count (same as context switch times) at a fixed interval (for example: 1s).
Like #3384, This patch try to add an option -e to show extension summary (average/total/count).
```
0 -> 1          : 4123     |**************                          |
2 -> 3          : 11690    |****************************************|
4 -> 7          : 1668     |*****                                   |
8 -> 15         : 859      |**                                      |
16 -> 31         : 618      |**                                      |
32 -> 63         : 290      |                                        |
64 -> 127        : 247      |                                        |
128 -> 255        : 198 …
```
=> tools/cpudist: Add extension summary support

man/man8/syscount.8, tools/syscount.py, tools/syscount_example.txt
Sometimes, I'd only care about a single syscall rather than all syscalls. Use the --syscall option for this.
```
Tracing syscall 'fsync'... Ctrl+C to quit.
[13:02:24]
SYSCALL                   COUNT        TIME (us)
fsync                       956      2448760.979
[13:02:25]
SYSCALL                   COUNT        TIME (us)
fsync                       979      2387591.025
[13:02:26]
SYSCALL                   COUNT        TIME (us)
fsync                       845      2488404.454
```
@yonghong-song Please take a look, thanks.
=> tools/syscount: Add syscall filter support

src/cc/bcc_elf.c, tests/cc/test_bpf_table.cc, tests/cc/test_c_api.cc, tests/cc/test_usdt_probes.cc
There were some leaks detected when running the test suite. But for `bcc_elf_get_buildid` which did not free the elf object, the rest of the leaks were isolated in the tests themselves which did not free some resources here and there.
This diff clears those leaks. This will allow running the tests suite in the future with LSAN enabled, helping in catching possible future leaks earlier.
Ran the sanitizer using:
```
docker run --privileged \
--pid=host \
-v $(pwd):/bcc \
-v /sys/kernel/debug:/sys/kernel/debug:rw \
-v /lib/modules:/lib/modules:ro \
-v /usr/src:/usr/src:ro \
-v /usr/include/linux:/usr/include/linux:ro \
bcc-docker \
/bin/bash -c \
'mkdir -p /bcc/build && cd /bcc/build && \
cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_LLVM_NATIVECODEGEN=OFF -DCMAKE_SANITIZE_TYPE=leak .. && make …
```
=> [lsan] Fix leaks detected by sanitizer

libbpf-tools/sigsnoop.c
SIGIOT is an alias of SIGABRT so it's assigned to the same number.
However it caused an error in my build setup like below:
libbpf-tools/sigsnoop.c:40:8: error: initializer overrides prior
initialization of this subobject
[-Werror,-Winitializer-overrides]
[6] = "SIGIOT",
^~~~~~~~
libbpf-tools/sigsnoop.c:39:8: note: previous initialization is here
[6] = "SIGABRT",
^~~~~~~~~
Anyway, it's gonna show only single entry.  So let's remove the other.
=> libbpf-tools/sigsnoop: Fix build warning

libbpf-tools/Makefile
We need bpftool for skeleton generation only, let's build and use bootstrap
bpftool like libbpf-bootstrap does ([0]). This avoids the following errors
on old kernels:
skeleton/pid_iter.bpf.c:35:10: error: incomplete definition of type 'struct bpf_link'
return BPF_CORE_READ((struct bpf_link *)ent, id);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[0]: https://github.com/libbpf/libbpf-bootstrap/pull/92
=> libbpf-tools: Build and use lightweight bootstrap version of bpftool

tools/mdflush.py
In recent kernels, i.e. since commit 322cbb50de71 ("block: remove
genhd.h"), genhd.h header has been removed and its content moved to
blkdev.h. Since genhd.h has been included in blkdev.h since forever,
including blkdev instead of genhd in the mdflush tool works for both
older and newer kernel.
=> tools/mdflush: include blkdev.h instead of genhd.h

libbpf-tools/tcpconnect.bpf.c, libbpf-tools/tcpconnect.c, libbpf-tools/tcpconnect.h
Originally, the tcpconnect utility didn't display the source port when tracing
events and ignored it (intentionally) when counting new connections. Add a new
option -s (or --source-port) to display the source port when tracing, or to use
the source port as part of the key when counting connections. This option is
unset by default to provide the original output.
Signed-off-by: Anton Protopopov <a.s.protopopov@gmail.com>
=> libbpf-tools: tcpconnect: take source port into consideration

tools/cpudist.py
With #4131 included, running the tool with -L reports the following warning:
/virtual/main.c:57:28: warning: multi-character character constant [-Wmultichar]
pid_key_t key = {.id = ' + pid + ', .slot = bpf_log2l(delta)};
^
/virtual/main.c:57:28: warning: character constant too long for its type
2 warnings generated.
The `pid` part should not be treated as string literal. Fix it.
=> tools/cpudist: Fix warning introduced by recent change

libbpf-tools/oomkill.c
=> oomkill: Remove trailing newline from output

tools/syscount.py
As libbpf-tools/syscount, use lock_xadd to guarantee atomicity of addition operations (without -P or -p, we can not guarantee atomicity).
=> tools/syscount: Use lock_xadd to guarantee atomicity of addition operations

debian/changelog
* Support for kernel up to 5.19
* bcc tool updates for oomkill.py, biolatpcts.py, sslsniff.py, tcpaccept.py, etc.
* libbpf tool updates for klockstat, opensnoop, tcpconnect, etc.
* new bcc tools: tcpcong
* new libbpf tools: tcpsynbl, mdflush, oomkill, sigsnoop
* usdt: support xmm registers as args for x64
* bpftool as a submodule now
* remove uses of libbpf deprecated APIs
* use new llvm pass manager
* support cgroup filtering libbpf tools
* fix shared lib module offset <-> global addr conversion
* riscv support
* LoongArch support
=> Update debian changelog for release v0.25.0

docker/Dockerfile.fedora
The fedora USDT tests are failing because 1) ruby isn't installed on fedora by default, and 2) fedora's ruby doesn't (didn't) have USDTs when it was installed by default. So let's manually build it with USDTs.
=> Add systemtap header and ruby to fedora docker

CMakeLists.txt, cmake/FindKernelHeaders.cmake, tests/cc/test_sock_table.cc
Those tests have started to fail since kernel 5.15.
The restriction was lifted in https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git/commit/?id=0c48eefae712c2fd91480346a07a1a9cd0f9470b
This diff makes the expected returned value to the call to `update_value` conditional
on the kernel version.
Tested on 5.15 (using a Ubuntu 22.04 host), which is representative of the kernel running in GH CI.
Also tested on Ubuntu 20.04 stock kernel:
```
$ docker run -ti \
--privileged \
--network=host \
--pid=host \
-v $(pwd):/bcc \
-v /sys/kernel/debug:/sys/kernel/debug:rw \
-v /lib/modules:/lib/modules:ro \
-v /usr/src:/usr/src:ro \
-e CTEST_OUTPUT_ON_FAILURE=1 \
bcc-docker-focal \
/bin/bash -c \
'/bcc/build/tests/wrapper.sh \
c_test_all sudo /bcc/build/tests/cc/test_libbcc "test sock*"' …
```
=> [test][sockhash/map] Fix the test to work with kernels >= 5.15

tests/cc/test_usdt_probes.cc
bionic has util-linux 2.31, `unshare` added support for `--kill-child` in 2.32.
This change remove the use of the argument `--kill-child` and instead kills the
child process manually before returning. While this is not going to take care
of all corner cases, it is probably more than enough for when the test is succeeding.
=> [test][usdt_probes][bionic] kill child manually

tests/cc/CMakeLists.txt, tests/cc/test_c_api.cc
The test "searching for modules in /proc/[pid]/maps" was trying to load
`dummy_proc_map.txt` from the current directory.
When running in a container, the current directory is set to `/`.
One way around this in CI would be to use the argument `-w /bcc/build/tests/cc`
so we change current directory.
On the other hand, our CMakeLists.txt file already copy the dummy file to
CMAKE_CURRENT_BINARY_DIR. So we may as well use this.
This diff sets `CMAKE_CURRENT_BINARY_DIR` as a define flag at compilation and
we re-use this within the test itself to load the file properly.
Test:
```
$ docker run -ti \
--privileged \
--network=host \
--pid=host \
-v $(pwd):/bcc \
-v /sys/kernel/debug:/sys/kernel/debug:rw \
-v /lib/modules:/lib/modules:ro \
-v /usr/src:/usr/src:ro \
-e CTEST_OUTPUT_ON_FAILURE=1 \ …
```
=> [test] fix module search test

tests/wrapper.sh.in
In #4126 I solved one problem but essentially pushed it somewhere else.
Now the problem is that when multiple arguments are passed, they all end up
being within the same argument because they get wrapped within the double-quotes.
This is pretty much an escape-hell as we keep on passing the same arguments over
and over through functions and then within `bash -c`.
The reason for the `bash -c` bit is that it allows us to set some envirtonment variable used in the tests.
Those env var are set to the local environment values.
Instead of going an extra layer of indirection, we can tell `sudo` to preserve those
specific env var by using the `--preserve-env` argument this way, we do not have to
re-escape the arguments that are passed within the `bash -c` quoted arg.
Tests:
Confirm that this was …
=> [test] Fix Wrapper script to properly handle arguments

tests/cc/test_bpf_table.cc
This was removed in 6616092255f80fc0918e19e898f0abfe2e3c2840, presumably
because sanitizer complained.
=> test_bpf_table: Re-add deletion of 'bpf' module

tests/wrapper.sh.in
Python tests are failing to import bcc module:
```
41: Test command: /bcc/build/tests/wrapper.sh "py_test_map_in_map" "sudo" "/bcc/tests/python/test_map_in_map.py"
41: Test timeout computed to be: 10000000
41: Traceback (most recent call last):
41:   File "/bcc/tests/python/test_map_in_map.py", line 9, in <module>
41:     from bcc import BPF
41: ModuleNotFoundError: No module named 'bcc'
41: Failed
41/41 Test #41: py_test_map_in_map ...............***Failed    0.03 sec
File "/bcc/tests/python/test_map_in_map.py", line 9, in <module>
ModuleNotFoundError: No module named 'bcc'
Failed
```
This was caused by #4162 . `sudo` has a list of env variables that get reset
regardless of what is in `preserve-env` list. See …
=> [tests] fix python tests

tests/python/test_tools_smoke.py
It fails on ubuntu 18.04 test environment.
=> test_tools_smoke.py: mayFail test_offwaketime

tools/trace.py
```
File "/usr/lib/python3.6/site-packages/bcc/table.py", line 982, in raw_cb_
File "trace.py", line 635, in print_event
msg = self._format_message(bpf, event.tgid, values)
File "trace.py", line 616, in _format_message
values[kp] = bpf.ksym(values[kp], show_offset=True)
TypeError: 'map' object is not subscriptable
```
=> tools/trace: Fix TypeError when format string contains %K or %U

man/man8/execsnoop.8, tools/execsnoop.py, tools/execsnoop_example.txt
- I have a agent which may invoke various external tools. Sometimes, I just want to trace children processes of this agent process.
- Only trace new processes of a bash process may be useful (keep an eye on command aliais).
```
PCOMM            PID     PPID    RET ARGS
ls               884360  874065    0 /usr/bin/ls --color=auto
ip               884395  874065    0 /usr/sbin/ip a
ls               884427  874065    0 /usr/bin/ls --color=auto -l --color=auto
```
This patch try to add an option -P to do this, please take a look.
=> tools/execsnoop: Add PPID filter support

src/cc/frontends/clang/b_frontend_action.cc
With llvm15 and llvm16, the following command line
```
sudo ./trace.py 'smp_call_function_single "%K", arg1'
```
will cause error:
```
/virtual/main.c:60:36: error: incompatible integer to pointer conversion passing 'u64'
(aka 'unsigned long long') to parameter of type 'void *' [-Wint-conversion]
bpf_perf_event_output(ctx, bpf_pseudo_fd(1, -1), CUR_CPU_IDENTIFIER, &__data, sizeof(__data));
^~~~~~~~~~~~~~~~~~~~
Failed to compile BPF module <text>
```
In helpers.h, we have
```
u64 bpf_pseudo_fd(u64, u64) asm("llvm.bpf.pseudo");
```
Apparently, <= llvm14 can tolerate u64 -> 'void *' conversion, but
llvm15 by default will cause an error.
Let us explicitly convert bpf_pseudo_fd to 'void *' to avoid
such errors.
=> Fix bpf_pseudo_fd() type conversion error

.github/workflows/publish.yml
This hasn't succeeded in quite some time. Let's turn it off for now.
=> GH Actions: Stop publishing to quay.io

src/cc/api/BPF.h
When including `bcc/BPF.h` there's a compilation error regarding arithmetic on a pointer to an incomplete type 'ebpf::USDT'.
The fix is straightforward: swap the order of the class declarations in the `bcc/BPF.h` file, after which things compile successfully.
More details are described in the issue #4160
=> fix arithmetic on a pointer to an incomplete type

tools/trace.py
- remove b'' by decoding all field values whose format specifier are 's'.
- remove explicit ctype cast.
```
PID     TID     COMM            FUNC             -
318915  318919  grpc_global_tim open             b'/etc/resolv.conf', 0
318915  318919  grpc_global_tim open             b'/etc/nsswitch.conf', 0
318915  318919  grpc_global_tim open             b'/etc/hosts', 0
```
=> tools/trace: Decode bytes to str and remove explicit ctype cast

scripts/git-clang-format
Old git-clang-format was python2 compatible only.
Support for python2 is getting slowly away from modern distro.
This change sync git-clang-format from https://github.com/llvm-mirror/clang/blob/aa231e4be75ac4759c236b755c57876f76e3cf05/tools/clang-format/git-clang-format
which is python2 and python3 compatible.
=> [scripts] Update git-clang-format

tools/memleak.py
```
File "/share/bcc/tools/memleak", line 568, in <module> 
print_outstanding_combined()
File "share/bcc/tools/memleak", line 541, in print_outstanding_combined 
trace = "\n\t\t".join(trace) 
TypeError: sequence item 0: expected str instance, bytes found
```
fix this.
=> tools/memleak: fix print_outstanding_combined function

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/javagc.bpf.c, libbpf-tools/javagc.c, libbpf-tools/javagc.h
Now usdt tracing has been supported in libbpf, so we add
the javagc monitor as an example with this feature. Normally,
you can use the command "readelf -n binary" to find the
usdt in the binary. The javagc tracing result like this:
Tracing javagc time... Hit Ctrl-C to end.
time:20:15:08, cpu:3, pid:90640, gc time(us):33764
time:20:16:29, cpu:1, pid:90640, gc time(us):42339
time:20:18:10, cpu:0, pid:90640, gc time(us):30843
Signed-off-by: chentao.ct <chentao.kernel@linux.alibaba.com>
=> libbpf-tools: Add javagc monitor

tools/compactsnoop.py
Fix issue #4182.
llvm doesn't support signed division and an assertion error
will happen when the IR contains sdiv. The reason is
due to code
zone - zone_pgdat->node_zones
where zone and zone_pgdat->node_zones are pointers to
struct zone (with size 1664). So effectively the above
is equivalent to
((void *)zone - (void *)zone_pgdat->node_zones)/sizeof(struct zone)
which is converted to sdiv insn.
llvm11 seems okay and I didn't investigate why. But llvm14 and
latest llvm16 failed with compiler fatal error.
To fix the issue let us replace the above '(void *)' as
'(u64)' and then the udiv will be used for the division.
=> Fix a llvm signed division error for compactsnoop tool

tests/python/test_percpu.py
Fixes #4203
The issue goes into more details as to why this change is needed. The TL;DR is
that the implementation of `os.popen` change somewhere between python 3.9 and
3.10 and depending on which version of python is used, either `fork/clone` is
called, or `vfork`.
In both cases, we are going to end up calling `execve`. This change switches
the syscall traced from `clone` to `execve`.
At the same time, it is now a constant that can be used across the tests.
Test plan:
Before https://gist.github.com/chantra/d37f3daa969bdbc07862dc11f8384a38
After https://gist.github.com/chantra/2860e9812f00eaa0758ccdb5d3192689
=> [python][test] change traced syscall from clone to execve

tests/python/test_trace3.py, tools/biosnoop.py
`blk_start_request` is gone since kernel 5. This patch is in the same vein as https://github.com/iovisor/bcc/pull/4124
except that we only conditionally attach to `blk_start_request` but attach also attach to
`blk_mq_start_request`.
=> [test][python] temptatively attach to blk_start_request probe.

.github/workflows/bcc-test.yml
Pull CI containers from GHCR and use them during build.
Example workflow run: https://github.com/chantra/bcc/runs/7844899499?check_suite_focus=true
Logs of the pull step: https://gist.github.com/chantra/b6a13223d530696bb00d40ce58c45fdb#file-gistfile1-txt-L540
depends on #4179
=> [ci] make build CI use docker images from this repo registry

src/cc/frontends/clang/kbuild_helper.cc
On Android the temp directory path is "/data/local/tmp". This pull request makes bcc check $TMPDIR environment variable and unpack kheaders to the directory it points to. If $TMPDIR is not defined then "/tmp" is used as a fallback.
=> extract kheaders to $TMPDIR directory

src/cc/common.cc, src/cc/common.h, src/cc/frontends/clang/tp_frontend_action.cc, src/cc/libbpf.c, src/python/bcc/__init__.py
Tracefs might be available as /sys/kernel/tracing and not /sys/kernel/debug/tracing. This commit makes bcc check whether /sys/kernel/debug/tracing exists and use /sys/kernel/tracing if not.
=> Use /sys/kernel/tracing when debugfs is not available

.github/workflows/publish-build-containers.yml, docker/build/Dockerfile.fedora, docker/build/Dockerfile.ubuntu
Some tests need those binaries to run. Currently those tests are allowed to
fail and we are possibly losing signal.
Once those packages are in the container image, we will be able to enforce
running those test and having them succeed.
=> [ci] Install netperf and iperf

.github/workflows/bcc-test.yml
Fedora 34 is EOL since 2022-06-07: https://docs.fedoraproject.org/en-US/releases/eol/
This diff adds support for F36 (current release).
=> [ci] Enable running CI on Fedora 36

man/man8/opensnoop.8, tools/opensnoop.py, tools/opensnoop_example.txt
List some practical scenarios from my daily work:
- When a process open an file with relative path, I also need to execute **lsof** or **ls -l /proc/pid/cwd** to view current directory (for example: locate MySQL or PostgreSQL config files), so it may be convenient to show full path for an open file with relative path.
- A process open an non-existent config file with relative path, then exits directly. Leave me no chance to view current directory of it.
- A process may change its current directory, and open files with relative path. Only show relative path could not identify full path.
Try to add option -F to solve this, please take a look, thanks. @yonghong-song 
For example:
shell 1:
```
./opensnoop.py -n cat -F
```
shell 2:
```
cd /root/bpf
cat example.c
```
shell 1 shows a full path: …
=> tools/opensnoop: Allow to show full path for an open file with relative path

libbpf-tools/klockstat.bpf.c, libbpf-tools/klockstat.c, libbpf-tools/klockstat.h
The following PR added printing for lock addr and name in max acq/hold times:
* https://github.com/iovisor/bcc/pull/4188
This is how it looks like:
```
$ sudo ./klockstat -d 5 -c down_ -n 2 -s 2 -S hld_total -p 39643
Tracing mutex/sem lock events...  Hit Ctrl-C to end
Caller  Avg Wait    Count   Max Wait   Total Wait
down_read+0x5    8.0 us    10685    83.2 ms      85.0 ms
kernfs_iop_permission+0x27
Max PID 39643, COMM cadvisor, Lock kernfs_rwsem (0xffffffff89f87e00)
Caller  Avg Wait    Count   Max Wait   Total Wait
down_read+0x5    2.1 us    36025    71.1 ms      76.8 ms
kernfs_iop_permission+0x27
Max PID 39643, COMM cadvisor, Lock kernfs_rwsem (0xffffffff89f87e00)
Caller  Avg Hold    Count   Max Hold   Total Hold
down_read_killable+0x5    8.2 us    19386   297.7 us     158.1 ms …
```
=> libbpf-tools/klockstat: accept lock addr as well as lock name

tools/opensnoop.py, tools/opensnoop_example.txt
open() syscalls often invoke at very high frequency in a production system. The fixed size (64 pages) of the perf ring buffer is not enough, which causes the output mixed with some warns, "Possibly lost xxx samples". Add option -b to allow to set size of the perf ring buffer. So we can use large buffer size to avoid event lost.
```
Possibly lost 2 samples
Possibly lost 1 samples
Possibly lost 3 samples
...
Possibly lost 1 samples
Possibly lost 1 samples
```
=> tools/opensnoop: Allow to set size of the perf ring buffer

libbpf-tools/Makefile
See https://github.com/iovisor/bcc/pull/4223, Instead of having this change, maybe we can check whether cargo exists and disable the blazesym feature if not. @chenhengqi 
Like we do in libbpf-bootstrap:
https://github.com/libbpf/libbpf-bootstrap/blob/938651fcef787f3885b7c32792851f8423bf8421/examples/c/Makefile#L24-L32
=> Check whether cargo exists and disable the blazesym feature.

libbpf-tools/runqlat.bpf.c, libbpf-tools/runqlat.c, libbpf-tools/runqslower.bpf.c, libbpf-tools/runqslower.c, libbpf-tools/trace_helpers.c, libbpf-tools/trace_helpers.h
Currently, runqlat and runqslower rely on tp_btf feature (requires kernel v5.5+).
This makes them failed to run on old kernels. Add a probe to detect whether the
target kernel has tp_btf support and fallback to raw tracepoint if not.
=> libbpf-tools: Allow runq tools to run on old kernels

.github/actions/build-container/action.yml, .github/workflows/bcc-test.yml, .github/workflows/publish-build-containers.yml, docker/build/Dockerfile.fedora
When any Dockerfile is modified, we should rebuild the container before running the CI.
Failing to do so, we would need to:
1) land the docker file change in order to incorporate the change
2) land the charge that uses this new dockerfile change
This is cumbersome and it is hard to make sure that changes to the dockerfile are indeed correct.
This change conditionally pull the pre-built image if no dockerfile change happened. Otherwise
it reuses the "build_container" action to build the image.
A first commit will confirm that the old behaviour is unchanged. A subsequent commit will confirm that when a Dockerfile is modified, we rebuild the container.
=> Conditionally rebuild container

libbpf-tools/sigsnoop.c
Running without -n:
```
[rongtao@RT-NUC libbpf-tools]$ sudo ./sigsnoop
TIME     PID     COMM             SIG       TPID    RESULT
...
16:32:48 0       swapper/1        34        2658    0
16:33:08 0       swapper/1        34        2658    0
```
Running with -n, access sig_name[34] cause SEGV, this patch fix it:
```
[rongtao@RT-NUC libbpf-tools]$ sudo ./sigsnoop -n
TIME     PID     COMM             SIG       TPID    RESULT
...
16:42:58 0       swapper/5        KERNEL    2658    0
```
=> Fix libbpf-tools/sigsnoop segment fault

tests/python/test_brb.py, tests/python/utils.py
Some tests are currently allowed to fail with @mayFail because some binaries may be missing.
The problem is that we cannot differenciate between a test failing because some tooling is missing,
or tests legitimately failing.
This diff creates a new decorator that will skip a test if some binaries are not
present, therefore, if the binaries are there and there is any issue, CI will fail.
It will generate a message similar to:
```
docker run -ti \
--privileged \
--network=host \
--pid=host \
-v $(pwd):/bcc \
-v /sys/kernel/debug:/sys/kernel/debug:rw \
-v /lib/modules:/lib/modules:ro \
-v /usr/src:/usr/src:ro \
-e CTEST_OUTPUT_ON_FAILURE=1 \
u34 \
/bin/bash -c \
'/bcc/build/tests/wrapper.sh "py_test_percpu" "sudo" "/bcc/tests/python/test_brb.py" test_brb.c -v'
test_brb …
```
=> Skip test when missing binaries

libbpf-tools/klockstat.bpf.c, libbpf-tools/klockstat.c, libbpf-tools/klockstat.h, libbpf-tools/trace_helpers.c
If fentry is not available, let's fallback to kprobe instead. This would allows the tool to run on old kernels or architectures without BPF trampoline.
cc @namhyung @brho
=> libbpf-tools/klockstat: Fallback to kprobe if fentry is not available

docs/kernel-versions.md
Bounded loop is a main feature because it removes the major restriction of loops in BPF code have to be unrolled. Because of loop unrolling is often hard to reliably apply in practice: On the one hand because loops in code is not always easy to formalize: https://llvm.org/docs/LoopTerminology.html On the other hand, loop unrolling in clang/llvm often is not forcible because of the complexity of code generation and optimization.
Bounded loop allows more reliable verification on BPF code that uses compile-time constants as loop termination conditions. Therefore substantially simplified the writing of BPF code.
=> Added bounded loop into the main bpf features list

examples/networking/vlan_learning/vlan_learning.c
"u16" is enough for vlan_tci and vlan_proto fields and can avoid the padding issue.
Fixes: https://github.com/iovisor/bcc/issues/4243
=> Fix padding field not initialized issue

libbpf-tools/readahead.c
```
$ sudo ./readahead -h
Usage: readahead [OPTION...]
Show fs automatic read-ahead usage.
USAGE: readahead [--help] [-d DURATION]
EXAMPLES:
readahead              # summarize on-CPU time as a histogram
readahead -d 10        # trace for 10 seconds only
-d, --duration=DURATION    Duration to trace
-v, --verbose              Verbose debug output
-?, --help                 Give this help list
--usage                Give a short usage message
-V, --version              Print program version
Mandatory or optional arguments to long options are also mandatory or optional
for any corresponding short options.
Report bugs to https://github.com/iovisor/bcc/tree/master/libbpf-tools.
```
=> Missing a newline('\n')

CMakeLists.txt
Bump CMake minimum version to 2.8.12 to avoid the following warning:
CMake Deprecation Warning at CMakeLists.txt:3 (cmake_minimum_required):
Compatibility with CMake < 2.8.12 will be removed from a future version of
CMake.
Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.
While at it, also use 2-space for indentions for the whole file.
=> bcc: Bump CMake minimum version to 2.8.12

INSTALL.md
A few small changes to the WSL2 installation instructions based on my experience installing bcc in 5.10.102.1-microsoft-standard-WSL2 Ubuntu 22.04:
* Fix a typo "modules" in instructions.
* Add instructions for cloning the WSL2-Linux-Kernel git repo.
* Add sudo for `make modules_install` command.
* Add instructions for renaming /lib/modules/x.y.z-microsoft-standard-WSL2+ even on recent kernels (needed this on 5.10).
With these changes, I was able to compile bcc on WSL2 Ubuntu 22.04 and run `sudo /usr/share/bcc/tools/execsnoop`
=> Edit WSL2 install instructions

tools/biopattern.py
Sometimes,  the sum of %RND and %SEQ not equal to 100 (as follows), which may be a bit of confusion. This patch try to fix it.
```
TIME      DISK     %RND  %SEQ    COUNT     KBYTES
16:08:16  vda       100     0       21        160
16:08:17  vda        75    25        4        248
16:08:19  vda       100     0        2          8
16:08:20  vda        85    14       63       2412
16:08:21  vda        96     3      824      20848
16:08:22  vda        96     3     3239      14496
```
=> tools/biopattern: improve the output of biopattern

src/cc/bcc_syms.cc, src/cc/syms.h
This PR contains two commits. The first one fixes a bug in `ProcStat::is_stale` that caused it to report `true` even if the PID does not exist anymore. The second one modifies `modpath` in `ProcStat::is_stale` to resolve `/proc/.../root` symlink if possible before appending it to `mod->name`, allowing finding the ELF executable even if the process is not running at the time when `ProcSyms::resolve_addr` is called.
These together allow `bcc_symcache_resolve` to work even if the process has already exited by the time of the function call.
=> Enable user symbol resolution on exited processes

man/man8/killsnoop.8, tools/killsnoop.py, tools/killsnoop_example.txt
Support '-t'/'--tpid' to filter the target PID to avoid message flood, ignore other processes we don't care.
=> tools: killsnoop: support target PID filter

src/cc/bcc_syms.cc, src/cc/syms.h
This partially reverts iovisor/bcc#4264.
=> Revert "Enable user symbol resolution on exited processes"

libbpf-tools/Makefile, libbpf-tools/compat.bpf.h, libbpf-tools/compat.c, libbpf-tools/compat.h, libbpf-tools/mountsnoop.bpf.c, libbpf-tools/mountsnoop.c, libbpf-tools/trace_helpers.c, libbpf-tools/trace_helpers.h
This patch introduces bpf_ringbuf to the existing libbpf-tools. Currently, most tools use PERF_EVENT_ARRAY for event-based tracing. For newer kernels, we could use bpf_ringbuf instead, for better performance. In this commit, we introduce two new header files: compat.bpf.h and compat.h, for BPF programs and userspace program respectively, providing uniform APIs for perfbuf/ringbuf handling in a CO-RE way.
=> libbpf-tools: Add support for bpf_ringbuf

.github/workflows/bcc-test.yml, .github/workflows/publish-build-containers.yml, .github/workflows/publish.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
=> GitHub Workflows security hardening

tools/vfsstat.py, tools/vfsstat_example.txt
Currently, this tool traces system-wide VFS calls, which may be useful to focus on a process with lots of file I/O (MySQL、ClickHouse, and so on). Add option -p to filter specified PID.
=> tools/vfsstat: Add PID filter support

man/man8/biosnoop.8, tools/biosnoop.py, tools/biosnoop_example.txt
biosnoop helps me a lot when analysing disk performance problems. Sometimes, I may need to know statistics of sequential/random I/O and it looks not convenient (do some post-processings by sector + bytes columes, or joint use biopattern & biosnoop).
This patch try to add an option -P, to display block I/O pattern as need.
For example (colume 'P', 'R' means random, 'S' means sequential):
```
TIME(s)     COMM           PID     DISK      T SECTOR     BYTES  P LAT(ms)
11.269319   kworker/u16:4  2784813 vda       W 113638304  8192   R    5.49
11.270254   kworker/u16:4  2784813 vda       W 114100936  425984 R    6.68
11.272153   kworker/u16:4  2784813 vda       W 114101768  212992 S    8.51
11.272626   kworker/u16:4  2784813 vda       W 114102184  516096 S    8.92
12.844246   TsysAgent …
```
=> tools/biosnoop: Add support for displaying block I/O pattern

libbpf-tools/compat.h, libbpf-tools/mountsnoop.c, libbpf-tools/oomkill.bpf.c, libbpf-tools/oomkill.c
This enables using ringbuf on recent kernel versions with oomkill by leveraging the changes of https://github.com/iovisor/bcc/pull/4262.
Additionally, this moves `POLL_TIMEOUT_MS` to `compat.h` for oomkill and for the previously migrated mountsnoop example, as presumably all the examples using this header would use this renamed variable.
This was a good point suggested by @eiffel-fl.
I have performed multiple tests, and the changes are working:
```console
Tracing OOM kills... Ctrl-C to stop.
12:36:41 Triggered by PID 3731 ("bash"), OOM kill of PID 3731 ("coredns"), 7702597 pages, loadavg: 1.06 0.39 0.19 3/474 8068
12:36:41 Triggered by PID 3731 ("bash"), OOM kill of PID 3731 ("bash"), 7702597 pages, loadavg: 1.06 0.39 0.19 4/474 8068
```
=> Adding bpf_ringbuf support to oomkill

libbpf-tools/oomkill.c
Fixing https://github.com/iovisor/bcc/pull/4282#discussion_r1004274603.
=> Make warnings consistent by switching to fprintf everywhere in oomkill example

tools/opensnoop.py
I have raised the issue at https://github.com/iovisor/bcc/issues/4292 
After changing the function, opensnoop.py no longer shows empty file names. But I am not sure why the results are different for each function.
Run in background `sudo python opensnoop.py`, then issue `strace cat foobar` in another terminal.
Tested on kernel `5.4.0-105-generic` with `python2.7` and `python3.8`
```
$ sudo python opensnoop.py 
PID    COMM               FD ERR PATH
141983 sh                  3   0 /dev/null
141984 sh                  3   0 /etc/ld.so.cache
141984 sh                  3   0 /lib/x86_64-linux-gnu/libc.so.6
141984 sh                  3   0 /dev/null
141985 sh                  0   0 /dev/null
141985 strace              3   0 /etc/ld.so.cache
141985 strace              3   0 …
```
=> Fix file names being empty

libbpf-tools/offcputime.c, libbpf-tools/trace_helpers.c, libbpf-tools/trace_helpers.h
Add additional information and change format of backtrace
- add symbol base offset, dso name, dso base offset
- symbol and dso info is included if it's available in target binary
- changed format: INDEX ADDR [SYMBOL+OFFSET] (MODULE+OFFSET)
Print backtrace of ip if it failed to get syms.
Before:
```
psiginfo
vscanf
__snprintf_chk
[unknown]
[unknown]
[unknown]
[unknown]
[unknown]
sd_event_exit
sd_event_dispatch
sd_event_run
[unknown]
__libc_start_main
[unknown]
-                systemd-journal (204)
1
xas_load
xas_find
filemap_map_pages
__handle_mm_fault
handle_mm_fault
do_page_fault
do_translation_fault
do_mem_abort
do_el0_ia_bp_hardening
el0_ia
xas_load
--
failed to get syms
-                PmLogCtl (138757)
1
```
After:
```
#0  0xffffffc01018b7e8 __arm64_sys_clock_nanosleep+0x0
#1 …
```
=> libbpf-tools/offcputime: Add dso info and symbol offset to backtrace for -v option

libbpf-tools/tcplife.c
ebpf code depends on these variables when filtered by ports:
https://github.com/iovisor/bcc/blob/dcb34dc51a9336ff88c5a57305bd04758a25808c/libbpf-tools/tcplife.bpf.c#L60-L88
=> libbpf-tools/tcplife: fix filter by ports

examples/networking/CMakeLists.txt
Add missing examples files.
```
$ ls -la /usr/share/bcc/examples/networking/
total 56
drwxr-xr-x 8 root root 4096 Nov  2 18:28 .
drwxr-xr-x 5 root root 4096 Nov  2 18:28 ..
drwxr-xr-x 2 root root 4096 Nov  2 18:28 distributed_bridge
drwxr-xr-x 2 root root 4096 Nov  2 18:28 http_filter
drwxr-xr-x 2 root root 4096 Nov  2 18:28 neighbor_sharing
-rwxr-xr-x 1 root root 3826 Nov  2 18:12 net_monitor.py
-rwxr-xr-x 1 root root  852 Nov  2 18:12 simple_tc.py
-rwxr-xr-x 1 root root 5257 Nov  2 18:12 simulation.py
-rwxr-xr-x 1 root root 3549 Nov  2 18:12 sockmap.py
-rwxr-xr-x 1 root root 2583 Nov  2 18:12 tc_perf_event.py
drwxr-xr-x 2 root root 4096 Nov  2 18:28 tunnel_monitor
drwxr-xr-x 2 root root 4096 Nov  2 18:28 vlan_learning
drwxr-xr-x 2 root root 4096 Nov  2 18:28 xdp
```
=> Add missing examples files

libbpf-tools/offcputime.c, libbpf-tools/wakeuptime.c
It seems that the global signal var `exiting` is of no use here, this PR is going to remove it.
=> wakeuptime: remove unused global var `exiting`

docs/kernel-versions.md
GitHub has better UI for navigation, let's replace all korg links to Github links.
=> docs/kernel-versions.md: Replace korg links with GitHub links

libbpf-tools/cpufreq.c, libbpf-tools/trace_helpers.c
While trying the cpufreq tool under libbpf-tools, the improper initialization of data structure makes the result confusing, correct it, with an additional polish change for data display.
=> Fix libbpf-tools/cpufreq

libbpf-tools/gethostlatency.bpf.c, libbpf-tools/ksnoop.bpf.c
Some tools do not use `BPF_KPROBE` & `BPF_KRETPROBE` to define `SEC` functions. This MR is going to keep them in line.
=> libbpf-tools/gethostlatency&ksnoop: use BPF_KPROBE & BPF_KRETPROBE to define SEC function.

libbpf-tools/biosnoop.c
perf_buffer__poll returns a count or a negative error value. If the loop is broken because of timeout err needs to be zero or else an error is flagged. As the count may be non-zero, and this isn't an error, move the setting of err to zero earlier. This also allows switching a goto to a break.
=> libbpf-tools: fix biosnoop exit code

libbpf-tools/offcputime.c
The comm name, PID and delta will not be printed if hit missed user stack condition. This is going to fix it.
Before fix:
```
sudo ./offcputime -p $(pgrep -f bash)                                                                                                                                                                                                                          
^C    finish_task_switch                                                                                                                                       
schedule_idle                                                                                                                                              
do_idle …
```
=> libbpf-tools/offcputime: fix no comm&delta output if missed user stack

libbpf-tools/cpudist.bpf.c, libbpf-tools/cpudist.c
According to https://github.com/iovisor/bcc/issues/4231
Test OK on Ubuntu 20.04 with 5.4.0-97-generic kernel like this:
```
$ sudo ./cpudist  
libbpf: sched_switch is not found in vmlinux BTF
Tracing on-CPU time... Hit Ctrl-C to end.
^C
0 -> 1          : 5        |**                                      |
2 -> 3          : 6        |**                                      |
4 -> 7          : 14       |*****                                   |
8 -> 15         : 22       |*********                               |
16 -> 31         : 29       |************                            |
32 -> 63         : 28       |***********                             |
64 -> 127        : 51       |*********************                   |
128 -> 255        : 15 …
```
=> libbpf-tools/cpudist: Allow cpudist to run on old kernels

tools/filelife.py
Since kernel commit 6521f8917082("namei: prepare for idmapped mounts"), the vfs_unlink() function add argument 'struct user_namespace'. And add vfs_open() probe if 'f_mode = FMODE_CREATED'.
=> tools: filelife: Check btf struct field for CO-RE and add vfs_open() 

tools/nfsslower.py
nfsslower does not currently print out slow commit operations, which sometimes cause long delays in NFS writes.  This commit adds code to trace slow commit operations.
NFS commits are quite slow and are not performed often, so the patch shouldn't incur visible overhead.
Below is a sample output when writing a large file using dd command. Most commits are issued from kworker threads, so the commit output may be mostly dropped when filtered by PID.
TIME     COMM           PID    T BYTES   OFF_KB   LAT(ms) FILENAME
...
16:46:11 dd             1212   W 1048576 651264     46.58 testfile
16:46:11 dd             1212   W 1048576 653312     54.41 testfile
16:46:11 dd             1212   W 1048576 654336     18.96 testfile
16:46:11 dd             1212   W 1048576 655360     49.05 testfile
16:46:11 …
=> Print slow commit operations in nfsslower

libbpf-tools/fsdist.bpf.c, libbpf-tools/fsdist.c, libbpf-tools/fsdist.h, libbpf-tools/fsslower.bpf.c, libbpf-tools/fsslower.c, libbpf-tools/fsslower.h
On arm64 platform, vmlinux.h already has enumerator 'OPEN', add 'F_' prefix for each 'fs_file_op' enumerator.
Reproduce the problem:
```
$ cd libbpf-tools
$ make
In file included from fsdist.bpf.c:7:
./fsdist.h:8:2: error: redefinition of enumerator 'OPEN'
OPEN,
^
arm64/vmlinux.h:126874:2: note: previous definition is here
OPEN = 41,
^
...
2 warnings and 1 error generated.
```
=> libbpf-tools: fsdist,fsslower: Fix redefinition of enumerator 'OPEN'

libbpf-tools/ksnoop.c
'func->args[i].name' field type 'char name[MAX_STR]' always true.
Compile warning:
```
ksnoop.c: In function ‘trace_to_value’:
ksnoop.c:318:21: warning: the comparison will always evaluate as ‘true’
for the address of ‘name’ will never be NULL [-Waddress]
318 |                 if (!func->args[i].name)
|                     ^
In file included from ksnoop.c:16:
ksnoop.h:62:14: note: ‘name’ declared here
62 |         char name[MAX_STR];
|              ^~~~
```
=> libbpf-tools/ksnoop: remove always 'true' statement

INSTALL.md
Signed-off-by: Furkan <furkan.turkal@trendyol.com>
This PR adds missing installation method for Debian - Binary in INSTALL.md.
=> docs: add installation method for Debian - Binary

tools/runqslower.py
The BPF_ARRAY map type has no delete operation. which may cause long runq delay result because old timestamp can not be deleted
=> tools/runqslower: replace invalid array map delete op by zero update

src/cc/bcc_syms.cc, src/cc/syms.h, tests/cc/test_c_api.cc
Another, better attempt at implementing loading symbols from exited processes, following cc441778d1b77ee0b206751180046fb385f9c9fc. Unlike the previous one, this one should respect mount namespaces. I tried opening a file inside a container-specific tmpfs and it worked using the approach described below.
TODO list:
---
Instead of loading modules from /proc/\<pid\>/root/<path>, open /proc/\<pid\>/root in advance with open(..., O_PATH) first, then use openat to read the module file. This enables the module file to be read even if \<pid\> is not running.
A class named ModulePath is added, which does the openat call and manages the returned file descriptor, enabling functions expecting a path to use /proc/self/fd/... as the path to the module.
Edit: prepend backslash to \< and \> symbols to …
=> Improve ProcSyms module path handling

libbpf-tools/solisten.h
Negative number occurs when short is used as the port type
Current situation:
Correct situation:
=> libbpf-tool/solisten: Modify port type

tools/ttysnoop.py
Check whether kfunc is supported, and decide whether to use kprobe or kfunc based on the test results.
How to reproduce the error:
```
$ sudo ./ttysnoop.py 7
bpf_attach_raw_tracepoint (kfunc): Unknown error 524 Traceback (most recent call last):
File "/home/rongtao/Git/bcc/tools/./ttysnoop.py", line 175, in <module>
File "/usr/lib/python3.9/site-packages/bcc/__init__.py", line 487, in __init__
self._trace_autoload()
File "/usr/lib/python3.9/site-packages/bcc/__init__.py", line 1473, in _trace_autoload
self.attach_kfunc(fn_name=func_name)
File "/usr/lib/python3.9/site-packages/bcc/__init__.py", line 1138, in attach_kfunc
raise Exception("Failed to attach BPF to entry kernel func")
Exception: Failed to attach BPF to entry kernel func
```
=> tools/ttysnoop: Fix kfunc Unknown error

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/capable.bpf.c, libbpf-tools/capable.c, libbpf-tools/capable.h
- BCC supports `capable.py` for tracing security capability checks
- https://github.com/chethanah/bcc/blob/master/tools/capable.py
- We've added support for tracing security capability checks for libbpf-tools as well 
```
$ cd libbpf-tools/
$ make capable 
$ sudo ./capable 
libbpf: elf: skipping relo section(12) .rel.data for section(3) .data
TIME     UID   PID     COMM             CAP     NAME                 AUDIT  
13:44:59 1000  1532    Xorg             21      CAP_SYS_ADMIN        1      
13:44:59 1000  1667    gnome-shell      21      CAP_SYS_ADMIN        1      
13:44:59 1000  1667    gnome-shell      21      CAP_SYS_ADMIN        1      
```
- Supported cli options similar to `capable.py`
- Kernel and user stack trace 
- PID filtering
- Cgroup based filtering
- Print unique output …
=> Support libbpf-tools based capable tool

man/man8/syscount.8, tools/syscount.py, tools/syscount_example.txt
we may need to run some one time command and trace its syscount.
it's not easy to get the pid.  but we can trace the ppid, usually the pid of current shell.
eg:
1. get pid of current shell(shell 1) 
```bash
grep -i ppid /proc/self/status | cut -f2
```
2. run syscount in other shell(shell 2)
```bash
syscount --ppid $pid_of_step_1
```
3. run the target command in shell 1
```bash
curl https://github.com/
```
we can trace the one time curl command with the --ppid option in this way
=> tools/syscount: add --ppid option

libbpf-tools/core_fixes.bpf.h, libbpf-tools/filelife.bpf.c, libbpf-tools/filelife.c
I already open a PR(https://github.com/iovisor/bcc/pull/4339) for `tools/filelife.py`, i think two PR better than single one. After all, `libbpf-tools/filelife` is compiled separately, and `tools/filelife.py` is the python script.
Since kernel commit 6521f8917082("namei: prepare for idmapped mounts"), the vfs_unlink() function add argument 'struct user_namespace'. And add vfs_open() probe if 'f_mode = FMODE_CREATED'.
Link: https://github.com/iovisor/bcc/pull/4339
=> libbpf-tools: filelife: Check btf struct field for CO-RE and add vfs_open() 

debian/changelog
* Support for kernel up to 6.1
* bcc tool updates for biosnoop, opensnoop, biopattern, killsnoop, runqslower, offcputime, wakeuptime, etc.
* libbpf-tools updates for klockstat, sigsnoop, hardirqs, softirqs, opensnoop, statsnoop, offcputime, tcplife, cpufreq, cpudist, etc.
* new libbpf-tools: tcptop, tcpstates, biotop, capable
* ci: add support for fedora 36 container and new workflow for containers
=> Update debian changelog for release v0.26.0

libbpf-tools/biotop.c, libbpf-tools/compat.h, libbpf-tools/klockstat.c, libbpf-tools/trace_helpers.c, libbpf-tools/vfsstat.c
In #4313, there are situations that ensure_core_btf is failed to detect kernel BTF existence. Let's switch to libbpf APIs to perform a best effort searching.
=> libbpf-tools: Detect kernel/modules BTF using libbpf APIs

libbpf-tools/statsnoop.c
The names of syscall tracepoints should be sys_{enter,exit}_${syscall_name}. The last change in statsnoop broke the tool essentially. Fix it.
Signed-off-by: Hengqi Chen <hengqi.chen@gmail.com>
=> libbpf-tools: Fix tracepoint existence check in statsnoop

tools/ttysnoop.py
Kernel provides BPF ringbuf from v5.8, it sloves memory efficiency and event re-ordering problems of the BPF perf buffer.
When using perfbuf it may get lots of 'Possibly lost x samples' on screen if many contents burst out to the snooping tty device. After changing to ringbuf, this issus will disappear.
Signed-off-by: mickey_zhu <mickey_zhu@realsil.com.cn>
=> tools/ttysnoop: add ringbuf

libbpf-tools/runqlen.bpf.c, libbpf-tools/runqlen.c
Currently, runqlen reports runq lenth form nr_running of cfs_rq. However, sometimes the host's runq lenth *rq->nr_running* is expected instead of cgroup's cfs_rq->nr_running.
Signed-off-by: Hailong Liu <liuhailong@linux.alibaba.com>
=> libbpf-tools/runqlen: Add runq lenth of host's rq

man/man8/killsnoop.8, tools/killsnoop.py, tools/killsnoop_example.txt
The -s option is missing from the synopsis of the killsnoop manpage, example file and the comment on top of the tool itself. Also, -T option is missing from the example file.
Signed-off-by: Jerome Marchand <jmarchan@redhat.com>
=> killsnoop: add missing -s and -T options to the synopsis

libbpf-tools/Makefile
Hi,bro!
When i buited these tools in libbpf-tools with yocto 4.x,I got these errors:https://github.com/iovisor/bcc/issues/4417#issue-1518224690.    Finally,I found a bug of libbpf-toos Makefile,the Makefile used 'uname -m' to confirm the ARCH,I think this way is reasonable.such as i buit them with yocto on X86-ubuntu system,the process is a classic cross compile,the ARCH's  value should take the target system  architecture.So i commite my bugfix, i hope you can pass it:)
=> fix the Makefile of libbpf-tools,make it support cross compile

src/python/bcc/table.py
A recent change caused arrays of multi-word types to not be detected properly leading to errors such as:
Type: 'unsigned char[256]' not recognized. Please define the data with ctypes manually
Fix the regular expression to allow multi-word types in arrays.
Fixes: ca1d3fd07a84 ("bcc: Fix array type handling due to llvm changes")
Cc: chenhengqi@outlook.com
Signed-off-by: Adrian Moreno <amorenoz@redhat.com>
=> bcc: Fix multi-word array type handling

libbpf-tools/softirqs.bpf.c, libbpf-tools/softirqs.c
Currently softirq only report the time but not the event counts. If we have both time and counts it will be better understand the frequency and duration of events.
Signed-off-by: Hailong Liu <liuhailong@linux.alibaba.com>
=> libbpf-tools/softirqs: Add event counts report

tools/ttysnoop.py
Since kernel commit fcb14cb1bdac("new iov_iter flavour - ITER_UBUF"), tty_write() will use ITER_UBUF. If do not add support for ITER_UBUF, ttysnoop will not work
=> tools/ttysnoop: Add ITER_UBUF support

src/cc/api/BPF.cc
Sometime uprobe names can be quite long, e.g. when it contains the path to a binary in a docker container. This pull request will truncate a long uprobe name to 208 characters and append a 16 character hash of the name to the end in order to differentiate between similar names.
=> Truncate long uprobe names and append its hash for differentiation

docs/kernel_config.md
Add the kernel config to enable fprobe.
This feature is used by kprobe mulit in the BPF.
=> docs/kernel_config.md: add the config for kprobe multi

tools/ttysnoop.py
ENV: LLVM 13.0.1, Kernel 5.15.67, aarch64
Overview of the error:
The verifier is unhappy, if '(r10 -32)' is not initialized, see also [0].
```bash
$ sudo ./ttysnoop.py 10
3: (7b) *(u64 *)(r10 -8) = r6
4: (7b) *(u64 *)(r10 -16) = r6
5: (7b) *(u64 *)(r10 -24) = r6
6: (bf) r1 = r10
...
91: (67) r0 <<= 32
92: (77) r0 >>= 32
; if (bpf_probe_read_user(&data->buf, BUFSIZE, (void *)buf))
93: (55) if r0 != 0x0 goto pc+356
R0_w=inv0 R6=invP0 R7=map_value(id=0,off=0,ks=4,vs=260,imm=0) R8=map_value(
id=0,off=4,ks=4,vs=260,imm=0) R9=inv256 R10=fp0 fp-8=mmmmmmmm
fp-16=mmmmmmmm fp-24=mmmmmmmm
94: (79) r2 = *(u64 *)(r10 -32)
invalid read from stack R10 off=-32 size=8
processed 593 insns (limit 1000000) max_states_per_insn 1 total_states 48
peak_states 48 …
```
=> tools/ttysnoop: Fix uninitialized 'buf' error

libbpf-tools/wakeuptime.c
The type of value in wakeuptime.c defined as int, it may be overflow and output as a negative numbers. Actually the type of value in map count is u64 defined at wakeuptime.bpf.c. So change the int to __u64 to fix it.
Signed-off-by: Hailong Liu <liuhailong@linux.alibaba.com>
=> libbpf-tools/wakeuptime: Fix the type of the value

libbpf-tools/cachestat.bpf.c, libbpf-tools/cachestat.c
Add kprobes and use fentry_can_attach() to decide whether to use fentry or kprobe.
=> libbpf-tools/cachestat: Fix failed to attach: ERROR: strerror_r(-524)=22

tools/nfsslower.py
The nfs4_file_open tracepoints are part of nfsv4.ko, which may not be loaded on systems using NFSv3 only. Do not attempt to attach probes in this case. For nfsdist.py, a similar issue has already been addressed likewise in commit a433ef945.
Signed-off-by: Daniel Kobras <kobras@puzzle-itc.de>
=> tools/nfsslower: fix on v3-only systems

libbpf-tools/numamove.bpf.c, libbpf-tools/numamove.c
Add kprobe and use fentry_can_attach() to decide whether to use fentry or kprobe.
logs:
```
$ sudo ./numamove
libbpf: prog 'fentry_migrate_misplaced_page': failed to attach: ERROR: strerror_r(-524)=22
libbpf: prog 'fentry_migrate_misplaced_page': failed to auto-attach: -524
failed to attach BPF programs
```
=> libbpf-tools/numamove: Fix failed to attach: ERROR: strerror_r(-524)=22

src/cc/CMakeLists.txt, src/cc/api/CMakeLists.txt, src/cc/frontends/clang/CMakeLists.txt
Installed static libraries, namely libbcc.a, libbcc_bpf.a and libbcc-loader-static.a, do not contain all the symbols that are needed for linking BCC statically into one's project.
The reason for this issue is that in CMake, when linking static library against another library (by using the target_link_libraries statement), the effect is not a combined static library. CMake will only record a dependency from the target library to the source library.
This is why when bcc-static is linked against api-static, the bcc-static library (libbcc.a) does not contain symbols from api-static, making it necessary to install api-static to <prefix>/lib along other library files. Ditto for clang_frontend.
This is not the case when building shared libraries.
This changeset fixes the issue by using a CMake …
=> Fix for incomplete static libraries.

src/cc/export/helpers.h
=> Use explicit type conversion for void * to u64.

tools/compactsnoop.py
kernel commit abd4349ff9b8("mm: compaction: cleanup the compaction trace events") change the arguments of 'mm_compaction_begin' from (start_pfn, migrate_pfn, free_pfn, end_pfn, sync) to (cc, start_pfn, end_pfn, sync), and change the arguments of 'mm_compaction_end' from (start_pfn, migrate_pfn, free_pfn, end_pfn, sync, ret) to (cc, start_pfn, end_pfn, sync, ret).
Replacing RAW_TRACEPOINT_PROBE with TRACEPOINT_PROBE solves this problem and guarantees compatibility.
```
$ sudo ./compactsnoop.py
bpf_attach_raw_tracepoint (mm_compaction_begin): Invalid argument
File "/home/sdb/Git/bcc/tools/./compactsnoop.py", line 292, in <module>
^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/bcc/__init__.py", line 483, in __init__ …
```
=> tools/compactsnoop.py: Fix raw_tracepoint Invalid argument error

tools/nfsslower.py
The verifier is unhappy, if data struct _pad_ is not initialized, see [0][1].
```
$ sudo ./nfsslower.py
...
; bpf_perf_event_output(ctx, (void *)bpf_pseudo_fd(1, -2), CUR_CPU_IDENTIFIER, &data, sizeof(data));
83: (79) r1 = *(u64 *)(r10 -144)      ; R1_w=ctx(off=0,imm=0) R10=fp0
84: (18) r3 = 0xffffffff              ; R3_w=4294967295
86: (b7) r5 = 96                      ; R5_w=96
87: (85) call bpf_perf_event_output#25
invalid indirect read from stack R4 off -136+92 size 96
processed 84 insns (limit 1000000) max_states_per_insn 0 total_states 4 peak_states 4 mark_read 4
...
raise Exception("Failed to load BPF program %s: %s" %
Exception: Failed to load BPF program b'raw_tracepoint__nfs_commit_done': Permission denied
```
[0] https://github.com/iovisor/bcc/issues/2623
[1] …
=> tools/nfsslower.py: Fix uninitialized struct pad error

docker/build/Dockerfile.ubuntu, src/cc/CMakeLists.txt, src/cc/bcc_elf.c, src/cc/bcc_proc.c, src/cc/bcc_zip.c, src/cc/bcc_zip.h, src/cc/libbpf.c, tests/cc/CMakeLists.txt, tests/cc/test_c_api.cc, tests/cc/test_zip.cc
Implement symbol lookup in zipped libraries.
On Android dynamic linker is capable of loading libraries directly from zip archives, provided that they are uncompressed and 4kb aligned. This pull request implements ability to set probes and lookup symbols in such libraries. In particular:
- minimal ZIP parser is added (`bcc_zip.c`)
- `bcc_elf_file` is extended to represent zipped libraries as well
- zip and apk files are checked for libs when parsing process' maps
- `bpf_attach_uprobe` adjusts file offsets and paths accordingly when probing libs inside a zip file
- libraries inside zip files can be referred to using the same notation as implemented in simpleperf: "/path/to/a/zip!/path/within/a/zip". For example: `trace '/data/app/com.example/base.apk!/lib/arm64-v8a/libtest.so:some_function'` …
=> Implement symbol lookup in zipped libraries.

tools/filelife.py
security_inode_create presents only if CONFIG_SECURITY is on. Do not attach to it unconditionally.
=> tools: Fix filelife for kernels without CONFIG_SECURITY

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/memleak.bpf.c, libbpf-tools/memleak.c, libbpf-tools/memleak.h
This is a conversion of the existing memleak.py tool.
The BPF program is structured similarly to the original. One addition is the explicit uprobe definitions. Another notable change is within the `update_statistics_{add,del}()` functions. There seemed to be a need to synchronize the incrementing (or decrementing) of two integer members on the same struct. To avoid having the userspace side potentially seeing inconsistent values, the two members in question were combined within a single u64 bitfield. The `combined_alloc_info` struct (see memleak.h) was changed to a `union` so that access to individual fields (via anonymous struct) and and the combined bits could be performed. It allowed for the atomic incrementing/decrementing of the two original members in question. Open to feedback on …
=> Memleak libbpf port

INSTALL.md
This saves a lot of time & disk space! 😊
=> INSTALL.md - Use a faster & smaller shallow clone when fetching WSL2-Linux-Kernel git repo

libbpf-tools/tcprtt.bpf.c
Running tcprtt with local port/address options causes the following error:
```
$ ./tcprtt -i 1 -p 80
libbpf: prog 'tcp_rcv': BPF program load failed: Permission denied
libbpf: prog 'tcp_rcv': -- BEGIN PROG LOAD LOG --
reg type unsupported for arg#0 function tcp_rcv#20
0: R1=ctx(off=0,imm=0) R10=fp0
; int BPF_PROG(tcp_rcv, struct sock *sk)
0: (79) r6 = *(u64 *)(r1 +0)
func 'tcp_rcv_established' arg0 has btf_id 3984 type STRUCT 'sock'
1: R1=ctx(off=0,imm=0) R6_w=ptr_sock(off=0,imm=0)
; if (targ_sport && targ_sport != inet->inet_sport)
1: (18) r1 = 0xffff9ff6c03b8004       ; R1_w=map_value(off=4,ks=4,vs=17,imm=0)
3: (69) r2 = *(u16 *)(r1 +0)          ; R1_w=map_value(off=4,ks=4,vs=17,imm=0) R2_w=20480
; if (targ_sport && targ_sport != inet->inet_sport)
4: (15) if r2 == 0x0 goto pc+3        ; …
```
=> libbpf-tools/tcprtt: Fix out-of-bounds accessing of inet_sock struct.

tools/cpudist.py
When pid != 0, current cpu should not be used as a part of key, it may run on different CPUs, which causes start.lookup(key) returns NULL. Just pid can be unique key, here we use an invalid value (0xFFFFFFFF) to fill cpu field of struct entry_key_t.
When pid == 0, still use current cpu as key to distinguish different swappers.
@yonghong-song Please take a look, thanks.
=> tools/cpudist: Bugfix incorrect cpu key when pid not equal to 0

libbpf-tools/cachestat.bpf.c, libbpf-tools/cachestat.c
Add tracepoint:writeback:writeback_dirty_{page,folio} support.
kernel commit 9fb0a7da0c52("writeback: add more tracepoints") add writeback_dirty_page tracepoint, kernel commit b9b0ff61eef5("mm/writeback: Convert tracing writeback_page_template to folios") replace writeback_dirty_page to writeback_dirty_folio.
Both folio_account_dirtied() and account_page_dirtied() are static functions and they may be gone during compilation.
=> libbpf-tools/cachestat: Introduce tracepoint writeback_dirty_{page,folio}

src/cc/bpf_module.cc
With llvm17, building bcc hits the following compilation errors:
...
/home/yhs/work/bcc/src/cc/bpf_module.cc:21:10: fatal error: llvm-c/Transforms/IPO.h: No such file or directory
21 | #include <llvm-c/Transforms/IPO.h>
|          ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/yhs/work/bcc/src/cc/bpf_module.cc:48:10: fatal error: llvm/Transforms/IPO/PassManagerBuilder.h: No such file or directory
48 | #include <llvm/Transforms/IPO/PassManagerBuilder.h>
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The above two files are removed by https://reviews.llvm.org/D144970 and https://reviews.llvm.org/D145835
=> Fix compilation error when built with llvm17

INSTALL.md, examples/usdt_sample/usdt_sample.md, examples/usdt_sample/usdt_sample.sh, snap/snapcraft.yaml, src/python/setup.py.in, tests/python/test_rlimit.py, tests/python/test_tools_smoke.py, tests/python/utils.py
Distutils has been deprecated in python 3.10 and will be removed from python 3.12. Distutils itself has for a long time recommended to use setuptools instead.
This patch migrate from distutils to setuptools using the migration advice from PEP 632:
https://peps.python.org/pep-0632/
=> Porting from distutils to setuptools

tools/offcputime.py, tools/offcputime_example.txt
Usually, I want to view symbol & offset (now only symbol printed), for example:
```
tcp_sendmsg+0x1
sock_sendmsg+0x38
sock_write_iter+0x85
__vfs_write+0xe3
vfs_write+0xb8
SyS_write+0x55
entry_SYSCALL_64_fastpath+0x1e
```
Like stackcount, add option -s to show symbol offset: https://github.com/iovisor/bcc/blob/master/tools/stackcount.py#L211
=> tools/offcputime: Add option to show symbol offsets

.github/workflows/publish.yml
elgohr/Publish-Docker-Github-Action@master is not supported anymore
=> Updated elgohr/Publish-Docker-Github-Action to a supported version (v5)

src/cc/bcc_zip.c, tests/cc/test_zip.cc
This pull request fixes infinite loop when trying to parse a short non-zip file as a zip archive.
If `limit` is negative then the loop never breaks as `offset` is unsigned.
=> bcc_zip_archive_open should not loop indefinitely for bad archives

debian/changelog
* Support for kernel up to 6.2
* bcc tool updates for ttysnoop, slabratetop, readahead, nfsslower, cpudist, cachetop, cachestat, etc.
* libbpf-tools updates for mdflush, drsnoop, statsnoop, ttysnoop, softirqs, wakeuptime, cachestat, numamove, etc.
* fix for incomplete static libraries
* implement zip archive support
* upgrade to use c++14 standard
* new libbpf-tools: memleak
* add loongarch support in libbpft-tools
=> Update debian changelog for release v0.27.0

libbpf-tools/memleak.c
We should only kill traced process if it is a child process.
=> libbpf-tools/memleak: don't kill process if attached

tools/wakeuptime.py
libbpf-tools/wakeuptime based on bcc version (tools/wakeuptime), but it's stack output in reversed order. This patch tries to keep consistent with bcc version.
Also see: https://www.brendangregg.com/FlameGraphs/offcpuflamegraphs.html#Wakeup
Please take a look, thanks. @yonghong-song @chenhengqi
=> tools/wakeuptime: Reverse the order of stack output

tools/funcslower.py
When trying to print folded stack, funcslower tries to join bytes to a string. Let's perform that operation with bytes only, and decode before printing.
Also, decode symbols name before printing for the default stack format, to avoid unsightly b'xxx' output.
It fixes the following error:
Exception ignored on calling ctypes callback function: <function PerfEventArray._open_perf_buffer.<locals>.raw_cb_ at 0x7f200541e5e0>
File "/usr/lib/python3.9/site-packages/bcc/table.py", line 982, in raw_cb_
File "/usr/share/bcc/tools/funcslower", line 340, in print_event
print_stack(event)
File "/usr/share/bcc/tools/funcslower", line 324, in print_stack
print("%s %d" % (";".join(line), 1))
TypeError: sequence item 1: expected str instance, …
=> tools/funcslower: fix printing of folded stacks

tools/profile.py, tools/profile_example.txt
`BPF_HASH(counts, struct key_t);` uses default hash storage size 10240, usually not enough to cover heavy workloads in a production environment (many cores and many running threads) for 5 seconds only, hash table becomes full and misses some keys. 
This patch try to improve the situation:
1. Add an warn if hash table is full and remind users to increase hash storage size
2. Add option `--hash-storage-size` to increase hash storage size
3. Use default value 40960 instread of 10240 (10240 often not enough, 40960 covers more cases) 
@yonghong-song @chenhengqi Please take a look, thanks.
=> tools/profile: Allow to increment hash storage size to aviod missing keys

libbpf-tools/memleak.c
'memleak -P' is used to trace percpu allocations, no argument is needed
=> libbpf-tools/memleak: remove unused arg "PERCPU"

src/python/bcc/__init__.py
To fix tools/funccount 'Failed to attach BPF program' error.
bcc commit e16b628bed37("Add more hints for error kprobe") added hint for failed probes, but did not resolve the issue. If the function is untraceable, use /sys/kernel/debug/tracing/available_filter_functions filter it out.
For example:
In the 6.2.9 kernel, vfsuid_gt_kuid() is the inline function, at which point funccount attach vfsuid_gt_kuid() fails, causing the program to fail.
````
$ sudo ./funccount.py -r 'vfs.*'
cannot attach kprobe, Invalid argument
Failed to attach BPF program b'trace_count_1' to kprobe b'vfsuid_eq_kuid'
````
These functions all have the same situation:
````
vfsuid_gt_kuid, vfsgid_eq_kgid, vfsgid_gt_kgid
vfsuid_lt_kuid, vfsuid_eq_kuid, vfsgid_lt_kgid
````
Use available_filter_functions to filter out …
=> Filter with available_filter_functions in BPF.get_kprobe_functions()

INSTALL.md
Change the ssh clone method to https method to fix the problem of git@github.com: Permission denied (publickey).
=> [INSTALL.md] (WSL) Change the ssh clone method to https method

libbpf-tools/tcprtt.bpf.c
Both implementations are identical, then they can be consolidated into a single function that is reused by both programs.
=> tcprtt: Consolidate kprobe and fentry implementations

libbpf-tools/tcpconnlat.bpf.c
If there is not any reply to the connection, the sock entry in the start map is never removed, this commit adds a new probe on tcp{4,6}_sock_destroy to remove the socket from the map in all cases.
```bash
$ sudo ./tcpconnlat 
```
In another terminal:
```bash
$ curl 1.1.2.2 # any IP that wont' reply back
```
```bash
$ sudo bpftool map dump name start
[{
"key": 0xffff9a6ee67c3480,
"value": {
"comm": "curl",
"ts": 19400263786185,
"tgid": 259405,
"pid": 259405,
"mntns_id": 4026535510
}
}
]
```
If the second step is repeated, more and more entries are accumulated on the map. 
Repeat the same steps, now the map doesn't have accumulated entries:
```bash
$ sudo bpftool map dump name start
[]
```
=> tcpconnlat: Remove entries from map in all cases

libbpf-tools/memleak.bpf.c, libbpf-tools/memleak.c
This commit allows the use of 'ksyms' for kernel symbols and 'syms_cache' for userspace application symbols when 'blazesym' is not supported.
=> libbpf-tools/memleak: support ksyms and syms_cache

tools/offcputime.py, tools/offcputime_example.txt, tools/offwaketime.py, tools/offwaketime_example.txt, tools/wakeuptime.py, tools/wakeuptime_example.txt
Nowadays, default stack storage size (1024) often not enough for tools `offwaketime/offcputime/wakeuptime`, even on a not busy production machine, `Consider increasing --stack-storage-size` is a bit annoying. As tools `klockstat/profile`,  this patch try to increment default stack storage size to 16384.
=> tools: Update default stack storage size to reduce frequent warnings

tools/deadlock.c, tools/deadlock.py
Commit 77f5252d ("tools/deadlock: support specifies maxnum of threads and edge cases (#3455)") allow to set the maximum number of threads and edge cases to be able to reduce the memory usage of the deadlock tool. It however let the size of the map of stack traces fixed. It's current size, 640k (actually rounded up to 1M) takes 1Gb of vmalloced kernel memory.
This patch adds an option to make the maximum number of stack traces user defined. It also set the default value to 64k, in line with the current default for the number of edge cases and threads.
It fix the following issue on system with limited memory ressources: could not open bpf map: stack_traces, error: Cannot allocate memory Traceback (most recent call last):
File "/tmp/./deadlock.py", line 577, in <module>
main()
File …
=> tools/deadlock: Add an option to set the maximum number of stack traces

libbpf-tools/funclatency.c
Current libbpf version funclatency does't cleanup histgram record after interval output, this causes the count of each interval output include all counts from funclatency launched. This behavior doesn't match to original bcc version funclatency.
https://github.com/iovisor/bcc/blob/70e879960428f5726067db93f7c742c8b39d4886/tools/funclatency.py#L408
This commit cleanup histgram record every time while output log2 hist.
Verified on x86-64 (5.15.60) and arm64 (5.10.70)
=> libbpf-tools/funclatency: Clear histgram record after interval output

INSTALL.md
The build-from-source instructions for ubuntu do not include `zip`, which is required for the build to complete and not automatically present on ubuntu (at least, 22.04 docker image).
As well, there are some additional libraries and tools that we should include so that users get a fully-featured build automatically.  Note that they are optional in case advanced users want to proceed without them.
Fixes #4598
=> docs: Update build-from-source ubuntu deps to include zip and tools

docs/reference_guide.md, src/cc/export/helpers.h, src/cc/libbpf.c
This patch extends the existing kfunc/kretfunc features.
With the new MODULE_KFUNC_PROBE macro, users are allowed
to attach module kernel functions.
Closes https://github.com/iovisor/bcc/issues/4585.
Signed-off-by: Hengqi Chen <hengqi.chen@gmail.com>
=> bcc: Add module kfunc/kretfunc support

src/cc/frontends/clang/b_frontend_action.cc
Enable the rewriter initialize only the requested function parameters. After verification by the tools/execsnoop, the result is correct.
For example, In `tools/execsnoop`, the `__envp` parameter in the `syscall_execve()` function is not requested, so it is not initialized.
Before:
```
...
__attribute__((section(".bpf.fn.syscall__execve")))
int syscall__execve(struct pt_regs *ctx)
{
#if defined(CONFIG_ARCH_HAS_SYSCALL_WRAPPER)
struct pt_regs * __ctx = (void *)ctx->di;
const char __user *filename; bpf_probe_read(&filename, sizeof(filename), &__ctx->di);
const char __user *const __user *__argv; bpf_probe_read(&__argv, sizeof(__argv), &__ctx->si);
const char __user *const __user *__envp; bpf_probe_read(&__envp, sizeof(__envp), &__ctx->dx);
#else
const char __user *filename = (const char …
```
=> rewriter: Init only the requested parameters

src/cc/libbpf.c
The bpf_attr::attach_btf_obj_fd is set to -1
when loading prog for vmlinux kfunc/kretfunc,
which results in EINVAL. Set it to 0 instead.
Closes #4607.
=> bcc: Fix vmlinux kfunc load

libbpf-tools/funclatency.bpf.c, libbpf-tools/funclatency.c
For tracing kernel functions, funclatency will attempt to use fentry and fallback to kprobes if that fails.  I left the option to force the use of kprobes if you'd like.
Under load, fentry is more efficient:
With kprobes:
cpu:/tmp/b# ./funclatency -u -k bpf_spin_lock
Tracing bpf_spin_lock.  Hit Ctrl-C to exit
^C
usec                : count    distribution
0 -> 1          : 565159   |****************************************|
2 -> 3          : 216204   |***************                         |
4 -> 7          : 306316   |*********************                   |
8 -> 15         : 416990   |*****************************           |
16 -> 31         : 415110   |*****************************           |
32 -> 63         : 170298   |************                            |
64 -> 127        : …
=> libbpf-tools: use fentry in funclatency

tools/cpuunclaimed.py, tools/runqlen.py
runqlen / cpuunclaimed add check_runnable_weight_field() as workaround to check runnable_weight presents in struct cfs_rq in kernel/sched/sched.h by trying to access runnable_weight field of struct
sched_entity in include/linux/sched.h. Please check more details in PR #1510 and #2164.
Unfortunately, the runnable_weight field of struct cfs_rq is removed, but the runnable_weight field of struct sched_entity is remained by following patchset series from Linux version 5.7.0.
- https://yhbt.net/lore/all/20200214152729.6059-4-vincent.guittot@linaro.org/
- https://yhbt.net/lore/all/20200214152729.6059-5-vincent.guittot@linaro.org/
Please also check the source of Linux below.
- include/linux/sched.h - https://elixir.bootlin.com/linux/v5.7/source/include/linux/sched.h#L475
- kernel/sched/sched.h - …
=> runqlen/cpuunclaimed: Fix runnable_weight issue after Linux 5.7

src/python/bcc/table.py
This PR fixes #4613.
The maximum index allowed by `print_linear_hist` is linear_index_max (1025). It obeys this rule when the type of `Key` is not `ct.Structure`. However, when `Key` is `ct.Structure`, it decodes hashtable using `decode_c_struct`. And `decode_c_struct` only supports up to 65 indexes.
So add a param `index_max` for `decode_c_struct` will fix the issue.
=> Python bindings: Fix maximum allowed index for `print_linear_hist`

docs/tutorial_bcc_python_developer.md
=> Fix TypeError: a bytes-like object is required, not 'str'

src/python/bcc/table.py, tests/python/test_map_batch_ops.py
Some tools get errors when kernel supports hash table batch operations and hash key or value is integer type.
`AttributeError: 'long' object has no attribute 'value'`
It's caused by ctypes library from python. For example, when hash tables try to do batch lookup, it will alloc arrays to stores keys and values first. If it is a ctypes integer type, after expanding to array, type of element will be changed to python 'long' or 'int'. When trying to access its value attribute, error message is generated.
```
>>> from ctypes import *
>>> a = c_uint(10)
>>> type(a)
<class 'ctypes.c_uint'>
>>> a.value
10
>>> b = (c_uint * 1)(10)
>>> type(b)
<class '__main__.c_uint_Array_1'>
>>> type(b[0])
<class 'int'>
>>> b[0].value
File "<stdin>", line 1, in <module> …
```
=> Hash table batch operation attribute error

libbpf-tools/core_fixes.bpf.h, libbpf-tools/memleak.bpf.c
To fix issus https://github.com/iovisor/bcc/issues/4628
=> libbpf-tools: memleak: fix tracepoint adjusting after Linux 6.1

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/tcppktlat.bpf.c, libbpf-tools/tcppktlat.c, libbpf-tools/tcppktlat.h, libbpf-tools/tcppktlat_example.txt
Add a new tool to trace latency between TCP received pkt and picked up by userspace thread. It is extremely useful in scenarios where we observe an increase in TCP end-to-end latency and cannot determine the source.
Signed-off-by: Wenbo Zhang [ethercflow@gmail.com](mailto:ethercflow@gmail.com)
=> libbpf-tools: add tcppktlat

tools/argdist.py, tools/argdist_example.txt
Hi,
Thank you for this project.
I would want to use `argdist` but instead of getting the PID I need the process name. The reason being I have short lived processes, and I want to inspect the sockets created by the processes if they are non-blocking. To make it easier to identify the process I want the tool to print the process name, supporting something like `argdist -c -C 't:syscalls:sys_enter_accept4():int,char*,int:args->fd,$COMM,args->flags&00004000'`. I managed to make some code changes in this PR but I am facing an issue with the output, see below
```
t:syscalls:sys_enter_accept4():int,char*,int:args->fd,$COMM,args->flags&00004000
COUNT      EVENT
2          args->fd = 9, $COMM = b'nrf', args->flags&00004000 = 2048
4          args->fd = 9, $COMM = b'nrf', args->flags&00004000 = 2048 …
```
=> argdist: print process name COMM

src/python/bcc/__init__.py
When counting tracepoints, funccount raises such an exception:
```
./funccount.py t:block:*
Tracing 18 functions for "b't:block:*'"... Hit Ctrl-C to end.
^C
FUNC                                    COUNT
'str' object has no attribute 'decode'
```
The main reason is BPF.get_tracepoints() returns a list of str, while other functions  (BPF.get_user_functions_and_addresses) returns a list of bytes, this patch try to fix this.
=> tools/funccount: Fix abort error when counting tracepoints

libbpf-tools/trace_helpers.c
Refer to kernel commit 704bde3cc26a ("uprobes: Use vm_special_mapping to name the XOL vma"), processes setup the [uprobes] special virtual memory area with uprobe events to excute original instruction out of line.
open_elf() would throw a warning of 'Could not open [uprobes]' when attaching uprobes, so remove '[uprobes]' from get_elf_type() to avoid it.
This warning can be reproduced with `memleak -c <command>` or `memleak -p <pid>`, for example
```
~ # memleak -p 57
using default object: libc.so.6
using page size: 4096
tracing kernel: false
Tracing outstanding memory allocs...  Hit Ctrl-C to end
[7:21:3] Top 0 stacks with outstanding allocations:
[7:21:8] Top 3 stacks with outstanding allocations:
4096 bytes in 1 allocations from stack
Could not open [uprobes]
0 [<00ffffff980d6904>] …
```
=> libbpf-tools: Avoid virtual memory area [uprobes] warning

libbpf-tools/cpufreq.c
It results in a targeted freqs initialization, and prevents errors such as missing cpu freq sysfs file of not present, or offline cpus.
=> cpufreq: read initial freqs only of valid links

libbpf-tools/biosnoop.bpf.c, libbpf-tools/biosnoop.c
Add a filter parameter to analyze long tail delay
```sh
$ sudo ./biosnoop -d sde -m 1 -t
TIMESTAMP    COMM           PID     DISK    T    SECTOR     BYTES   LAT(ms)
17:58:57.814 mount          163467  sde     WSM  41944043   524288    1.422
17:58:57.814 mount          163467  sde     WSM  41945067   524288    1.429
17:58:57.814 mount          163467  sde     WSM  41946091   524288    1.749
17:58:57.814 mount          163467  sde     WSM  41947115   524288    1.809
```
=> libbpf-tools: add filter for biosnoop

libbpf-tools/biosnoop.bpf.c
I test biosnoop on riscv and arm64 with linux-6.1, and get some errors
```
~ # biosnoop
libbpf: prog 'block_rq_complete': BPF program load failed: Permission denied
libbpf: prog 'block_rq_complete': -- BEGIN PROG LOAD LOG --
reg type unsupported for arg#0 function block_rq_complete#176
0: R1=ctx(off=0,imm=0) R10=fp0
; int BPF_PROG(block_rq_complete, struct request *rq, int error,
0: (bf) r6 = r1                       ; R1=ctx(off=0,imm=0) R6_w=ctx(off=0,imm=0)
; int BPF_PROG(block_rq_complete, struct request *rq, int error,
1: (79) r1 = *(u64 *)(r6 +0)
func 'block_rq_complete' arg0 has btf_id 5097 type STRUCT 'request'
...
; event.ts = ts;
87: (7b) *(u64 *)(r10 -40) = r3       ; R3_w=scalar() R10=fp0 fp-40_w=mmmmmmmm
; event.sector = rq->__sector;
88: (79) r1 = *(u64 *)(r10 -8)        ; …
```
=> libbpf-tools/biosnoop: Fix out-of-bounds accessing of rq

tools/kvmexit.py
The kvm_exit tracepoint has the following proto ([0]):
TP_PROTO(struct kvm_vcpu *vcpu, u32 isa)
So for raw tracepoint, the first arg is a pointer to kvm_vcpu, not exit_reason. The exit_reason is hidden inside struct vcpu_vmx for Intel CPU (or struct vcpu_svm for AMD CPU). Both structs are not part of the UAPI, so it's hard to extract exit_reason. Let's always use the kvm_exit tracepoint instead.
[0]: https://github.com/torvalds/linux/blob/1ef6663a587b/arch/x86/kvm/trace.h#L296
=> kvmexit: Don't use raw tracepoint

debian/changelog
* Support for kernel up to 6.3.
* new libbpf tool: tcppktlat.
* bcc tool updates: funcslower, wakeuptime, profile, offcputime, deadlock, funccount, argdist, kvmexit, runqlen and cpuunclaimed.
* libbpf tool update: memleak, tcprtt, tcpconnlat, funclatency, syscount, cpufreq, biosnoop.
* support ringbuf_query for bcc tools.
* handle '[uprobes]' memory mapped file properly during stack tracing.
* Fix maximum allowed index for print_linear_hist for bcc tools.
* add module kfunc/kretfunc support.
* clang rewriter: initialize only the requested parameters
* filter with available_filter_functions to make multi-functions kprobes more robust for both bcc and libbpf tools.
* doc update, other bug fixes and tools improvement
=> Update debian changelog for release v0.28.0

libbpf-tools/trace_helpers.c
When testing https://github.com/iovisor/bcc/pull/4659, tracepoint_exists() always return false.
My kernel config shows `CONFIG_DEBUG_FS is not set`, so `/sys/kernel/debug/tracing` is not exist.
Follow libbpf to add `/sys/kernel/tracing` support.
=> libbpf-tools: fallback to tracefs mount point if debugfs is not mounted

libbpf-tools/tcprtt.bpf.c, libbpf-tools/tcprtt.c, libbpf-tools/tcprtt.h
Hi.
With this contribution, I added IPv6 support to `tcprtt`:
```
$ sudo ./tcprtt -b -c '::1'          
Tracing TCP RTT... Hit Ctrl-C to end.
^C
Local Address = ::1 
16 -> 31         : 20       |***                                     |
32 -> 63         : 266      |****************************************|
64 -> 127        : 90       |*************                           |
```
If you see any ways to improve this contribution, feel free to share.
Best regards and thank …
=> libbpf-tools: Add support for IPv6 to tcprtt.

libbpf-tools/core_fixes.bpf.h, libbpf-tools/tcppktlat.bpf.c, libbpf-tools/tcppktlat.c, libbpf-tools/tcppktlat.h
Currently, tcppktlat can only run on kernel v5.12+ because of the usages of bpf_get_socket_cookie().
This commit gets the tool run on old kernels in a CO-RE way. While at it, also adds tcp_destroy_sock tracepoint. This is necessary since there are cases where the socket does not get the chance to reach the tcp_rcv_space_adjust tracepoint and entries in start map never get removed.
cc @ethercflow
=> libbpf-tools: Allow tcppktlat to run on old kernels

libbpf-tools/biosnoop.bpf.c, libbpf-tools/biosnoop.c, libbpf-tools/biostacks.bpf.c, libbpf-tools/biostacks.c, libbpf-tools/biotop.bpf.c, libbpf-tools/biotop.c
Some bio tools fail to kprobe blk_account_io_{start,done} after v5.17, because they become inlined, see [0]. To fix this issue, tracepoints blick_io_{start,done} are introcuded in kernel, see[1].
Update related bio tools to support new tracepoints, and also simplify attach.
[0] Kernel commit 450b7879e345 (block: move blk_account_io_{start,done}
to blk-mq.c)
[1] Kernel commit 5a80bd075f3b (block: introduce
block_io_start/block_io_done tracepoints)
=> libbpf-tools: add block_io_{start,done} tracepoints support to bio tools

src/cc/api/BPF.cc, src/cc/api/BPF.h, src/cc/api/BPFTable.cc, src/cc/api/BPFTable.h, src/python/bcc/table.py, tests/cc/test_perf_event.cc, tests/python/test_perf_event.py
Related to the discussion here: https://github.com/iovisor/bcc/discussions/4673#discussion-5405903
The first commit in this PR adds the `pid` parameter to the `perf_event_open` in both cc and python API.   
The second commit in this PR edits the existing cc and python tests to pass in the PID of the test process as an argument to `perf_event_open`.
=> cc/python-api: Add PID parameter to `perf_event_open`

tools/runqlat.py
ENV
ubuntu 22.04
kernel 6.2.0-26
bcc: newest
LLVM version 14
The issue seems related to data structures initialization with padding ([3651](https://github.com/iovisor/bcc/pull/3651) , [4051](https://github.com/iovisor/bcc/pull/4051))
ERROR:
```
$ sudo /usr/share/bcc/tools/runqlat -P
0: R1=ctx(off=0,imm=0) R10=fp0
[...]
129: (7b) *(u64 *)(r10 -16) = r1      ; R1_w=scalar(umax=4294967295,var_off=(0x0; 0xffffffff)) R10=fp0 fp-16_w=
; pid_key_t key = {.id = tgid, .slot = bpf_log2l(delta)}; ({ typeof(dist.key) _key = key; typeof(dist.leaf) *_leaf = bpf_map_lookup_elem_(bpf_pseudo_fd(1, -2), &_key); if (_leaf) (*_leaf) += 1;else { typeof(dist
.leaf) _zleaf; __builtin_memset(&_zleaf, 0, sizeof(_zleaf)); _zleaf += …
```
=> tools/runqlat: fix data structure initialization with padding

tools/biolatency.py, tools/biosnoop.py, tools/biotop.py
The bio tools currently depends on blk_account_io_done/start functions that can be inlined. To fix that, a couple of tracepoints have been added upstream (block:block_io_start/done). This patch add the support for those tracepoints when they are available.
Unfortunately, the bio tools relies on data that is not available to the tracepoints (mostly the struct request). So the tracepoints can't be used as drop in replacement for blk_account_io_*. Main difference, is that we can't use the struct request as the hash key anymore, so it now uses the couple (dev_t, sector) for that purpose.
For the biolatency tool, the -F option is disabled when only the tracepoints are available because the flags are not all accessible from the tracepoints. Otherwise, all features of the tools should remain. …
=> tools: Add support for the new block_io_* tracepoints

libbpf-tools/execsnoop.bpf.c
The [bpf_probe_read_user_str* manpage](https://man7.org/linux/man-pages/man7/bpf-helpers.7.html) says: 
> On success, the strictly positive length of the output string, including the trailing NUL character. On error, a negative value.
=> libbpf-tools/execsnoop: fix ret type of bpf_probe_read_user*.

tools/slabratetop.py
With recent kernel containing the commit 6801be4f2653 ("slub: Replace cmpxchg_double()"), slabratetop fails to compiles with the following error:
In file included from /virtual/main.c:86:
include/linux/slub_def.h:56:3: error: unknown type name 'freelist_aba_t'
freelist_aba_t freelist_tid;
^
2 warnings and 1 error generated.
File "/usr/share/bcc/tools/slabratetop", line 187, in <module>
^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/bcc/__init__.py", line 479, in __init__
raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>
Adding the definition of freelist_aba_t fixes the issue.
=> tool/slabratetop: add definition of freelist_aba_t

tools/tcprtt.py
tcp_sk() and inet_sk() has been redefined to use the new container_of_const() macro. It confuses something in bcc toolchain.
/virtual/main.c:38:144: error: expected expression
struct tcp_sock *ts = ({ typeof(struct sock) _val; __builtin_memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (void *){ typeof(struct sock) _val; __builtin_memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (void *){ typeof(struct sock) _val; __builtin_memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (void *){ typeof(struct sock) _val; __builtin_memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (void *){ typeof(struct sock) _val; __builtin_memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (void *)cp_sk); _val; })); _val; })); …
=> tools/tcprtt: use simple cast instead of tcp_sk() and inet_sk()

tools/statsnoop.py
The underlying system call employed by the Golang Stat() wrapper function is newfstatat().
See https://cs.opensource.google/go/go/+/refs/heads/master:src/syscall/zsyscall_linux_amd64.go;l=1453;drc=94e40d5603797fe4d9302421682bb5b997d9c568
=> tools/statsnoop: Add more stat() variansts

src/cc/bpf_module.cc
llvm::SectionRef changed the `getName` interface since LLVM10, in particular, in commit llvm/llvm-project@a11d302fa0.
In llvm-9 and early version, `getName` required a StringRef reference as a parameter, and returned a std::error_code.
=> fix. backport compilation with llvm9 and earlier

libbpf-tools/capable.c
This commit adds a cleanup step to free the perf_buffer, fixing a memory leak in the capable.c file.
This is detected by asan.
=> libbpf-tools: fix memory leak in capable.c

examples/perf/ipc.py
The use of hardcoded raw events breaks compatibility as these are tied to specific processors. On other processors, it could also be the case that the raw event codes represent something completely different. Hence, use the generic events for cycles and instructions as these are available on most platforms with a core PMU.
=> examples/perf/ipc: Use generic hardware events

libbpf-tools/tcplife.c, libbpf-tools/tcprtt.c, libbpf-tools/tcpstates.c, tools/tcplife.lua, tools/tcplife.py, tools/tcprtt.py, tools/tcpstates.py, tools/tcptracer.py
Quite a few networking tools have trouble with IPv6. Either it's buggy and or there is no IPv6 support it at all.
Here a re a few fixes. Some more should come.
=> Misc Ipv6 fixes

src/python/bcc/table.py
This PR aims to use the json histogram in custom code.
I am working in custom metrics and the histogram information assembled in `_print_json_hist ` is great for having custom percentiles.
The problem is the method just prints the histogram in STDOUT which complicates the manipulation. So this change splits the responsibilities of the methods to be able to call a public one called `get_json_hist` without breaking any compatibility backwards.
=> [python] Allowing to get the histogram in a variable for deeper work

libbpf-tools/core_fixes.bpf.h, libbpf-tools/filelife.bpf.c, libbpf-tools/filelife.c
commit abf08576afe3("fs: port vfs_*() helpers to struct mnt_idmap") [0] use `struct mnt_idmap *new_mnt_idmap` instead of `struct user_namespace * old_mnt_userns`.
[0] https://github.com/torvalds/linux/commit/abf08576afe3
=> libbpf-tools/filelife: Check btf struct field for CO-RE

tools/profile.py, tools/profile_example.txt
This adds translation logic to perform PID remapping across PID-namespaces.
It is now possible to profile a target process from within a nested PID-namespace (e.g. in a container).
=> tools/profile: add support for PID-namespacing

src/python/CMakeLists.txt
Debian's python, unlike stock python, expects system packages to be installed in `/usr/local/lib/python3.X/dist-packages/` and not `/usr/local/lib/python3.X/site-packages/`. As such debian's python setuptools has a flag `--install-layout deb` which places library files in the correct place. `src/python/CMakeLists.txt` checks if the system is debian and adds this flag.
However, if you're trying to use BCC with a non-system version of python (for example miniconda) the different package layout (and setuptools flag) aren't there. Also, libraries aren't expected to be placed in /usr, but whatever prefix the alternative python install is using.
This PR adds two flags to the CMAke build:
* PY_SKIP_DEB_LAYOUT - which skips adding the `--install-layout deb` flag to the python install command
* …
=> Allow for installing python as a non-system package

src/cc/bcc_proc.c
This drops an hardcoded check for the root user-ID before accessing `/proc/kallsyms`, fixing a bug which is preventing proper kernel symbols resolution by non-root users.
The `/proc/kallsyms` file is generally available to non-privileged users:
```
> runuser -u nobody -- wc -l /proc/kallsyms
217514 /proc/kallsyms
```
Its content is further controlled by the `CAP_SYSLOG` capability
through `/proc/sys/kernel/kptr_restrict`:
https://man7.org/linux/man-pages/man7/capabilities.7.html
As such, it is better to directly open it and rely on `fopen()`
for privileges checking.
=> cc: remove a spurious check for UID 0

tools/nfsslower.py, tools/rdmaucma.py, tools/tcprtt.py, tools/virtiostat.py
Remove the manual definition of `KBUILD_MODNAME` as https://github.com/iovisor/bcc/pull/2974 added the default compiler flag `-DKBUILD_MODNAME="bcc"`
=> tools: Remove manual definition of `KBUILD_MODNAME`

tools/ppchcalls.py
Some new hcalls have been introduced for Powerpc Nested KVM support. The details of these hcalls can be found in this LKML patch - https://lore.kernel.org/kvm/20230807014553.1168699-6-jniethe5@gmail.com/
=> tools/ppchcalls : Add new hcalls introduced for nested KVM support

libbpf-tools/memleak.bpf.c
some of the maps were using tgid as key but should really be using tid so that multithreaded programs can record consistent allocation data.
fixes #4741
=> memleak: use tid instead of tgid as map key

libbpf-tools/ksnoop.bpf.c
bpf_get_func_ip(ctx) will get the function address; use it where available using the BPF core enum value check for the function. This avoids needing to get the caller IP via KSNOOP_IP_FIX() for more up-to-date kernels.
This fixes issue #4746 for kernels newer than 5.13; an additional followup will be needed to address this for older kernels.
Kindly tested by https://github.com/matthew-olson-intel on a recent kernel.
Reported-by: dubeyabhishek (https://github.com/dubeyabhishek)
=> ksnoop: use bpf_get_func_ip() where helper is available

libbpf-tools/memleak.bpf.c, libbpf-tools/memleak.h
updating the license for consistency with its userspace counterpart.
=> memleak: dual license bpf prog

src/cc/bcc_debug.cc
In #4737 I added support for using LLVM_VERSION_MAJOR from llvm-config.h instead of inferred LLVM_MAJOR_VERSION.
This went through CI just fine because CI uses LLVM 14 as the latest LLVM version (through the fedora 36 build).
`bcc_debug.cc` was using LLVM_VERSION_MAJOR before any include that would actually define it, causing LLVM_VERSION_MAJOR to default to 0. This was fine for builds using LLVM < 15, but does not work for LLVM >= 15.
On Ubuntu 23.04, using
```
-- Found LLVM: /usr/lib/llvm-15/include 15.0.7 (Use LLVM_ROOT envronment variable for another version of LLVM)
```
compilation of bcc_debug.cc would fail with:
https://gist.github.com/chantra/d2277d500d150ec2cc863dd412bd3264
This change moves the include of `bpf_module.h` up the file to make sure LLVM_VERSION_MAJOR is defined. …
=> Fix compilation for LLVM >= 15

src/cc/bcc_proc.c
Use PRIx64 and PRIu64 format specifiers to read uint64_t values.
On systems where sizeof(long) == 4, "%lx" only updates the lower 4 bytes of uint64_t fields. Since we don't zero-initialize struct mod_info prior to calling fscanf(), we can end up with bogus start/end addresses, which ultimately causes symbolication to fail. For example:
```
(lldb) p/x *mod
(mod_info) {
name = 0xbeffa642 "/system/lib/libc++.so"
start_addr = 0x00000020b678f000
end_addr = 0x00000003b67ef000
```
=> cc: Fix maps parsing on 32-bit systems

.github/actions/build-container/action.yml, .github/workflows/bcc-test.yml, .github/workflows/publish-build-containers.yml, docker/build/Dockerfile.ubuntu
Currently, only llvm-11 get tested on Ubuntu, on Fedora, it is whatever is the default llvm package of that Fedora release.
Given the checks on LLVM versions in the code base, it would be useful to test different LLVM versions too.
This change allow installing multiple versions when building the Ubuntu docker image, and when building bcc, LLVM_ROOT is used to force building against a specific llvm version.
Ubuntu bionic had failure installing llvm 15, so I ma skipping it for that version of ubuntu.
On the other hand, I am not sure how much value testing on Bionic has. Given the tests are running in docker, the kernel bcc is tested against are the same so.
Also Bionic reached end of standard support https://ubuntu.com/18-04 .
Removing this Ubuntu flavor would make sense in my opinion. …
=> Test multiple LLVM versions

libbpf-tools/bindsnoop.c, libbpf-tools/bindsnoop.h, libbpf-tools/fsslower.c, libbpf-tools/trace_helpers.c
Fix build errors when compiling for 32-bit platforms by making the code more portable.
=> libbpf-tools: Fixes for 32-bit platforms

src/cc/export/bpf_workaround.h
commit b2f557eae9ed ("kasan, arm64: adjust shadow size for tag-based mode") [0] moved KASAN_SHADOW_SCALE_SHIFT definition from kernel headers to arm64 Makefile. This causes compile errors with "undeclared identifier" error for BPF programs on arm64 kasan-enabled kernels as the kernel headers still reference KASAN_SHADOW_SCALE_SHIFT, but the clang frontend does not pass this definition on the commandline unlike Kbuild.
Fixes #3648
[0]: https://github.com/torvalds/linux/commit/b2f557eae9ed
=> arm64: unbreak bcc tools on arm64 kasan-enabled kernels

tests/python/CMakeLists.txt
The support got added in 1f0f7b6, but later removed.
=> Skipping USDT tests for Power processor 

tools/compactsnoop.py
config PPC_BOOK3S_64 skips setting ZONE_DMA for
server processors. NORMAL and MOVABLE zones are
available on Power.
=> Adding memory zones for Power server

libbpf-tools/biolatency.bpf.c, libbpf-tools/biolatency.c
The biolatency has a kernel version check to detect changes in the some block tracepoint format.  But it can be a problem if the old kernel backported the change.  Then the BPF verifier would reject the program due to invalid access to the argument.
We can do better using BTF since it has the type information.  Instead of checking kernel version, it can check the prototype of the tracepoint function.  For example, block_rq_issue tracepoint has this for recent kernels:
typedef void (*btf_trace_block_rq_issue)(void *, struct request *);
Let's check the number of arguments in the prototype - actually it has one more argument for the context.
=> libbpf-tools: Check biolatency tracepoints using BTF

tools/argdist.py, tools/biopattern.py, tools/biotop.py, tools/cachestat.py, tools/cachetop.py, tools/dirtop.py, tools/filetop.py, tools/klockstat.py, tools/netqtop.py, tools/slabratetop.py, tools/stackcount.py, tools/swapin.py, tools/syscount.py, tools/tcprtt.py, tools/tcptop.py, tools/wakeuptime.py
Hash table batch operations are supported, but no tools use this feature for now.
I patch tools directly, maybe there is a better way.
Improvement can be test with the belove commands:
```
```
Before patch filetop, syscall counts are more than 2k.
```
[16:58:42]
SYSCALL                   COUNT
bpf                          55
[16:58:43]
SYSCALL                   COUNT
bpf                        2735
[16:58:44]
SYSCALL                   COUNT
bpf                        2263
```
After patch batch operations, result shows except 1 syscall for syscount
itself, filetop syscall count is reduced to 1.
```
Tracing syscall 'bpf'... Ctrl+C to quit.
[17:00:36]
SYSCALL                   COUNT
bpf                           1
[17:00:37]
SYSCALL                   COUNT
bpf                           2 …
```
=> tools: Add hash table item batch operations support

tools/trace.py
To exit the tool when the maximal number of event is reached (-M option), the tool currently call exit(), which raise a SystemExit exception. The handling of exception from ctype callback doesn't seem straightforward and dependent on python version.
This patch avoid the issue altogether by using a global variable instead.
Closes #3049
=> tools/trace: don't raise an exception in a ctype callback

libbpf-tools/Makefile, libbpf-tools/fsdist.c, libbpf-tools/fsslower.c
F2FS (FlashFriendly File System) is an open source flash file system，designed specifically for NAND-based storage devices and currently used primarily on mobile platforms. 
With the idea of CO-RE (Compile Once, Run Everywhere) being proposed and implemented, the portability of BPF has been improved, and the application of BPF on mobile platforms has become more and more widespread. 
Therefore, I have added support for F2FS to fsdist and fsslower. 
Thank you for your review.
=> Added support for f2fs to fsdist and fsslower tools.

tools/cpudist.py, tools/dcsnoop.py, tools/dcstat.py, tools/offcputime.py, tools/offwaketime.py, tools/runqlat.py, tools/runqslower.py
With python >=3.8 many tools emit warnings on startup:
```
/usr/sbin/dcstat:91: SyntaxWarning: invalid escape sequence '\d'
b.attach_kprobe(event_re="^lookup_fast$|^lookup_fast.constprop.*.\d$", fn_name="count_fast")
```
Fix this by ~properly escaping backslashes~ using raw strings for regular expressions.
=> tools/*.py: fix invalid escape sequences in regexps

src/cc/frontends/clang/loader.cc
If bcc running on v5.17-rc8-13-g156ff4a544ae, '__attribute__((nocf_check))' will be used indirectly in '/virtual/main.c', which requires the compilation option -fcf-protection, otherwise an alarm will be generated at runtime, see linux kernel commit 156ff4a544ae ("x86/ibt: Base IBT bits")
```
// arch/x86/include/asm/ibt.h
#define __noendbr       __attribute__((nocf_check))
```
Warning:
```
$ sudo ./execsnoop.py
In file included from /virtual/main.c:14:
In file included from include/uapi/linux/ptrace.h:183:
In file included from arch/x86/include/asm/ptrace.h:5:
In file included from arch/x86/include/asm/segment.h:7:
arch/x86/include/asm/ibt.h:77:8: warning: 'nocf_check' attribute ignored;
use -fcf-protection to enable the attribute [-Wignored-attributes]
extern __noendbr u64 ibt_save(bool …
```
=> Fix bcc python script run warning: 'nocf_check' attribute ignored

tools/filegone.py
When deleting or renaming a file or folder for which you do not have permissions, vfs_unlink/rename will fail and we should skip the failure.
Reproducing the problem:
Terminal 1:
```
$ sudo ./filegone.py
```
Terminal 2, failed 1,2,3,4:
```
$ sudo touch /etc/a.txt
$ sudo mkdir /etc/a.dir
$ # Permission deny
$ rm -f /etc/a.txt
rm: cannot remove '/etc/a.txt': Permission denied               << 1
$ mv /etc/a.txt /etc/b.txt
mv: cannot move '/etc/a.txt' to '/etc/b.txt': Permission denied << 2
$ rmdir /etc/a.dir
rmdir: failed to remove '/etc/a.dir': Permission denied         << 3
$ mv /etc/a.dir /etc/b.dir
mv: cannot move '/etc/a.dir' to '/etc/b.dir': Permission denied << 4
$ # Success gone
$ sudo mv /etc/a.txt /etc/b.txt
$ sudo rm /etc/b.txt
$ sudo mv /etc/a.dir /etc/b.dir
$ sudo rmdir …
```
=> tools/filegone: Support rename/unlink failed situation

libbpf-tools/.gitignore
commit 5f520fc94005("Added support for f2fs to fsdist and fsslower tools.") add f2fsdist and f2fsslower tools.
=> libbpf-tools: Ignore f2fsdist and f2fsslower

libbpf-tools/filelife.bpf.c, libbpf-tools/filelife.c, libbpf-tools/filelife.h
When we try to delete a file with a normal user after creating a file as root (sudo), the deletion of the file fails, but the kprobe:vfs_unlink is triggered, which leads to incorrect file lifecycle tracking.
This commit makes the same changes [1] as tools/filelife.py, or you can see bcc [2] commit 076ccf079dbb ("tools/filelife: Fix error tracking caused by failed unlink").
```
Terminal 1:
$ sudo ./filelife.py
Terminal 2:
$ sudo touch /etc/a.txt
$ rm /etc/a.txt
rm: remove write-protected regular empty file '/etc/a.txt'? y
rm: cannot remove '/etc/a.txt': Permission denied
Then, terminal 1:
$ sudo ./filelife.py
TIME     PID     COMM             AGE(s)  FILE
12:24:11 4988    rm               7.13    a.txt   <<< wrong statistic
```
[1] https://github.com/iovisor/bcc/pull/4791
[2] …
=> libbpf-tools/filelife: Fix error tracking caused by failed unlink

src/cc/bpf_module_rw_engine.cc, tests/python/test_clang.py
Two tests `test_probe_read_nested_member3`and `test_sscanf_string`  keep failing after we adopt Fedora 38 in CI.
The first one is trival and just fix in place. The second one is much interesting.
The leaf_sscanf function generated does not work properly. See https://github.com/iovisor/bcc/actions/runs/6793034116/job/18475356742?pr=4799 for example:
```
16: ======================================================================
16: FAIL: test_sscanf_string (__main__.TestClang.test_sscanf_string)
16: ----------------------------------------------------------------------
16: Traceback (most recent call last):
16:   File "/bcc/tests/python/test_clang.py", line 226, in test_sscanf_string
16:     self.assertEqual(l.stack[0].name, name)
16: AssertionError: b' ' != b'libxyz'
16: 
16: …
```
=> Fix two CI issues

libbpf-tools/exitsnoop.c
The perf buffer in exit snoop doesn't maintain 8 byte alignment for start_time and exit_time in struct event. When building with "-fsanitize=alignment -fsanitize-undefined-trap-on-error" failures happen in handle_event. Fix these by copying the event from the perf buffer before accessing.
=> libbpf-tools: Fix misaligned pointer accesses in exitsnoop

tests/python/test_tools_memleak.py
Request to allocate 30K bytes to pvalloc(), results in allocating 3*64Kb in return. The test matches for leaked amount to be exactly equal to 30K bytes, whereas on system configured with 64Kb pagesize, leaked memory is much more than 30K bytes.
=> Fixing pvalloc memleak test

src/cc/usdt.h, src/cc/usdt/usdt.cc, src/cc/usdt/usdt_args.cc, tests/cc/test_usdt_args.cc
It is currently not possible to use USDT on risc-v due to lack of support for argument parsing. When trying to connect to USDT the following error occurs: [link](https://github.com/iovisor/bcc/blob/master/src/cc/usdt/usdt_args.cc#L136). This patch provides this implementation.
=> Support for parsing USDT arguments to RISC-V

tools/memleak.py, tools/memleak_example.txt
Add `--sort` option to report ordered in size or count. Available sort key list: size, count
`size` is a default value.
Usage:
./memleak.py --sort count
./memleak.py --sort size
=> tools/memleak: Add --sort option to report ordered in size or count

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/futexctn.bpf.c, libbpf-tools/futexctn.c, libbpf-tools/futexctn.h
Although systemtap already has a futexes.stp tool, it doesn't feel very easy to use. For example, there are only maximum, minimum and average values, but no delay distribution information. In addition, although the mutex address is behind, there is no call stack information, which is inconvenient to check when you cannot use gdb to attach the process.
This tool identifies lock contention information by filtering futex `FUTEX_WAIT` operations and retrieves the call stack information when entering lock contention. The lock contention counter is partitioned based on the call stack, enabling users to locate all path information involved in this lock contention using the printed lock address, which serves as the basis for optimization.
```
➜ ✗ sudo ./futexctn -p 381676 1 1 -mT
15:07:13 …
```
=> libbpf-tools: add futexctn

tools/memleak.py, tools/memleak_example.txt
The third-party allocations, such as jellmalloc that is usually statically linked into redis using the "je_" prefix, so we can specify the prefix string of these symbols to detect memory leaks in softwares using third-party allocs.
=> memleak:support third party alloctions by definitive symbols prefix

CMakeLists.txt, cmake/clang_libs.cmake, src/cc/bpf_module_rw_engine.cc
Latest llvm18 cannot build with bcc now. There are 3 issues:
- In IRBuilder, getInt8PtrTy() renamed to getPtrTy().
- Newly introdeuced clang library libclangAPINotes.a.
- Newly introduced llvm library libLLVMFrontendDriver.a
This patch fixed the above three issues so bcc can be built with llvm18 successfully. I then tried a few bcc tools and they all works fine.
=> Fix various build issues with latest llvm18

debian/changelog
* Support for kernel up to 6.6.
* new bcc tools: rdmaucma
* new libbpf tools: f2fs, futexctn
* bcc tool update: tcpstates, statsnoop, runqlat, bio tools, tcptop, slabratetop, tcprtt, etc.
* libbpf tool update: tcprtt, tcppktlat, bio tools, execsnoop, bindsnoop, exitsnoop, etc.
* s390x support for libbpf-tools
* examples for perf/ipc
* expose pid parameter in bpf_open_perf_event
* allow for installing python as a non-system package
* ci improvement: deprecate ubuntu 18.04 and allow multiple llvm versions
* ci improvement: reitre fedora 34/26 and use fedora 38.
* fix misaligned pointer accesses in some ringbuf using libbpf-tools
* some new  enhancement for powerpc and riscv.
* consolidate tools into different categories: filesystem/storage, networking, cpu and scheduling, etc.
* doc update, …
=> Update debian changelog for release v0.29.0

README.md
because it is redundant
and table of contents looks better without colons.
ToC with colons looks weird:
Subtitle1:
Subtitle2:
Subtitle3:
=> readme: remove colons after subtitles

src/python/CMakeLists.txt
The spurious comma prevents the expression from working as intended.
Fixes: https://github.com/iovisor/bcc/commit/6813fbce8718bede5075272cdc3ab9314eb91b5c
Fixes: https://github.com/iovisor/bcc/issues/4830
=> python/cmake: remove extraneous comma between variables

src/cc/frontends/clang/b_frontend_action.cc
This should allow the use of the %pS format specifier without generating a warning message.
=> add %pS as allowed format specifier

src/python/bcc/perf.py
Allow for the creation of custom perf events.
In my case I need access to the attributes sample_type and branch_sample_type which is not allowed with the current api.
I have tried skipping perf_event_open() and just using _open_for_cpu().
However doing so generates warning as the pid is set outside of the Perf class and it is not part of perf_event_attr's ctypes.
=> bcc/python: add perf_custom_event_open

SPECS/bcc+clang.spec, SPECS/bcc.spec, debian/control, debian/python-bcc.install, debian/python3-bcc.install, debian/rules, docker/Dockerfile.ubuntu
This change was required because current stable Ubuntu versions have
limited support for Python 2.7 (EOL 2020) and the upcoming ones do
not even have Python 2.7 (Ubuntu 23 and Ubuntu 24 do not support it).
Code changes:
* remove python3-bcc package and use python 3 for the python-bcc
* remove python2 packages
* remove Ubuntu 18/20 deb Dockerfile support and add 22.04 support
* use clang / llvm 11, supported by Ubuntu 22.04
=> docker: ubuntu: remove py2 package and build 22.04 docker image

libbpf-tools/trace_helpers.c
`dso__find_sym` function considers elf file is not stripped. So it could find
wrong symbol if the target elf file is stripped. Consider if the start address
of each function `foo`, `bar`, `baz` is `0x1000`, `0x4000`, `0x9000`
respectively, and `bar` is stripped. If user wants to find the symbol of
address `0x4080`, user expected result will be `bar`, and `dso__find_sym`
function expected result will be NULL, but actual result is `foo` which is
incorrect.
To fix this problem, use symbol size on `dso__find_sym` function to check
whether the offset exists within the found symbol range.
`strip` can be used to remove certain non-allocable sections from the elf file.
This reduces file size by throwing away information. static function name is
one of the most popular non-allocable information. …
=> libbpf-tools: Fix trace_helper symbol search bug

libbpf-tools/Makefile
Fedora adds prefix bpf- to the tool names, mainly to distinguish them from the old tools written in Python. Alpine Linux is going to do the same, but for a slightly different reason - there are dozens of these tools, so it's a good idea to add them a common prefix, to make it easier to recognize them among all other commands.
See-Also: https://github.com/iovisor/bcc/pull/3263
See-Also: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/35688
=> libbpf-tools: Allow to install apps with prefixed names

libbpf-tools/opensnoop.c
opensnoop.c:208:79: error: invalid type argument of ‘->’ (have ‘struct event’)
208 |                 { .src_type = SRC_T_PROCESS, .params = { .process = { .pid = e->pid }}},
|                                                                               ^~
=> libbpf-tools: Fix opensnoop compile errors when uses BlazeSym

tools/compactsnoop.py
When we use the -e or --extended_fields option, compactsnoop.py will output some error information. The root cause is that we obtained zone and wmark information but did not update it to the hash table.
before the patch:
./compactsnoop.py -e and echo 1 > /proc/sys/vm/compact_memory
COMM           PID    NODE ZONE         ORDER MODE    FRAGIDX  MIN      LOW      HIGH     FREE       LAT(ms)           STATUS
bash           32559  0    ZONE_DMA     0     SYNC    -1.000   0        0        0        0            0.031         complete
bash           32559  0    ZONE_DMA     0     SYNC    -1.000   0        0        0        0            3.849         complete
bash           32559  0    ZONE_DMA     0     SYNC    -1.000   0        0        0        0           67.697         complete
after the …
=> Fix incorrect output information

libbpf-tools/bindsnoop.bpf.c, libbpf-tools/core_fixes.bpf.h
The freebind field in struct inet_sock gone in recent kernel versions due to some kernel refactor works ([0]). The change breaks the bindsnoop tool. Fix it in a CO-RE way.
This should close #4838.
[0]: https://lore.kernel.org/all/20230816081547.1272409-1-edumazet@google.com/
=> libbpf-tools: Fix bindsnoop for kernel v6.6+

docs/kernel-versions.md
Add kernel version table entries shows when mixing bpf2bpf calls and tailcalls supported for certain architectures.
=> doc: Add mixing bpf2bpf calls and tailcalls

src/python/bcc/perf.py
These changes should remove the incorrect generation of a warining when setting up a perf event.
The warning says that pid is not part of the ctype (which is is not) but it is required to be set by _open_for_cpu.
Therefore I moved the pid to be an extra argument which removes the need for it to be set in attr fixing the error.
=> bcc/python: fix ctype warning when creating perf events

debian/changelog, debian/python-bcc.install
When the tag 0.29.1 was added to the repo, the debian changelog file needed one entry as well, otherwise the .deb build fails.
Also, in github actions environment, the Python3 library path is usr/lib/python3*.
Fixes: https://github.com/iovisor/bcc/issues/4842
=> Fix debian changelog and Python3 library path

libbpf-tools/opensnoop.c
This problem was introduced in commit `16508e5`.
```
opensnoop.c: In function ‘handle_event’:
opensnoop.c:208:65: warning: ‘e.pid’ is used uninitialized in this
function [-Wuninitialized]
208 |   { .src_type = SRC_T_PROCESS, .params = { .process = { .pid =
e.pid }}},
|
```
=> libbpf-tools: Fix uninitialized issue

libbpf-tools/ksnoop.h
In output_trace() bpf_perf_event_output determins its even size
(trace_len in this function) based on the fact that trace->buf
is at the end of struct trace:
> trace_len = sizeof(*trace) + trace->buf_len - MAX_TRACE_BUF;
Commit e9f140f0fea0 ("libbpf-tools: Fix memory leaks in ksnoop/gethostlatency") breaks that rule and we will put 2 pointers size more junk bits into perf buffer. Fix this by moving forward the new added tailing pointers to its proper place(commented as readonly segment).
=> libbpf-tools/ksnoop: perf buffer fix unnecessary junk bits output

tools/memleak.py
As `sizes` and `memptrs` map are to store the temporal information of each thread, use only `tid` portion of the return value of `bpf_get_current_pid_tgid` as a key of `sizes` and `memptrs` map. This change could reduce the key size of each map from 64 bits to 32 bits. The lower 32 bits portion of the return value of `bpf_get_current_pid_tgid` is kernel's view of the `pid`, which in user space is usually presented as the `tid`.
Please refer this document for further information:
https://github.com/iovisor/bcc/blob/master/docs/reference_guide.md#4-bpf_get_current_pid_tgid
=> tools/memleak: Use compact size of key for sizes and memptrs maps

examples/tracing/lbr.py
This script uses the Last Branch Record (LBR) buffer to trace conditional branches executed by syscalls. 
The script takes a snapshot of the LBR and displays the to/ from address to the user.
This can be useful if you want are trying to trace the execution path of a syscall which is returning an error.
If this script is not too niche I would be happy to submit it as a tool as well.
=> examples/tracing: lbr.py trace cond branches executed by syscalls

libbpf-tools/klockstat.h
Define __KLOCKSTAT_H in the header guard.
=> libbpf-tools/klockstat: Fix incomplete header guard

src/python/bcc/libbcc.py
The PR follows the discussion #4873, to add a Python API for bpf_prog_test_run_opts. This will allow implementations of use cases like traffic generators. Below is the sample code using the API.
```c
// trafficgen.bpf.c
#include <uapi/linux/bpf.h>
BPF_PERCPU_ARRAY(txcnt, long, 1);
int xdp_redirect(struct xdp_md *ctx)
{
int action = XDP_ABORTED;
__u32 key = 0;
action = bpf_redirect(3, 0);
long *value = txcnt.lookup(&key);
if (value)
*value += 1;
out:
return action;
}
```
```python
from bcc.libbcc import lib, bpf_test_run_opts
from bcc.utils import printb
import time
from scapy.all import *
import ctypes
import os
BPF_F_TEST_XDP_LIVE_FRAMES = 1 << 1
device = "eth1"
b = BPF(src_file="trafficgen.bpf.c")
func = b.load_func("xdp_redirect", BPF.XDP)
ethernet = …
```
=> Add Python API for bpf_prog_test_run_opts

src/python/bcc/table.py
Nysal reported that the bcc tool offcputime.py does not display userspace stack traces on powerpc. Looking at the bpf program maps showed that stack traces were indeed being captured by the kernel, but were not being displayed by bcc userspace. This turned out to be the case since we were having the second entry in the stack trace as zero, and bcc's stack walker correctly assumes that the stack trace ends when a zero entry is encountered.
However, on powerpc, a perf callchain includes two additional entries after the first so as not to miss any data that may be required for stack unwinding. The first entry is always the nip (next instruction pointer) which is always valid. The second entry is LR, the link register, and the third entry is the value in the LR save area in the (second) stack …
=> Fix userspace stack unwinding on powerpc

tests/python/test_tools_smoke.py
This is a testing patch for failure:
https://buildbot.iovisor.org/jenkins/job/bcc-pr/1071/label=ubuntu1604/console
on ubuntu16.04 with latest libbpf repo.
=> [DEBUG] test newer libbpf change

tools/ttysnoop.py
Jerome Marchand reported that ttysnoop.py won't work properly with newer kernels (#4884). I did some investigation and found that some kernel data structure change caused verification failure. The failure is caused by the following:
```
; kvec  = from->kvec;
// R1=ptr_iov_iter()
15: (79) r1 = *(u64 *)(r1 +16)        ; R1_w=scalar()
; count = kvec->iov_len;
16: (bf) r2 = r1                      ; R1_w=scalar(id=1) R2_w=scalar(id=1)
17: (07) r2 += 8                      ; R2_w=scalar()
18: (05) goto pc+3
;
22: (79) r2 = *(u64 *)(r2 +0)
R2 invalid mem access 'scalar'
```
So basically, loading 'iov_iter + 16' returns a scalar but verifier expects it to be a pointer.
In v6.4, we have
```
struct iovec
{
void __user *iov_base;  /* BSD uses caddr_t (1003.1g requires void *) */
__kernel_size_t …
```
=> [PATCH] Fix ttysnoop.py with newer kernels

INSTALL.md
After LLVM 15.0.7.2 on the Arch Linux, the package maintainer remove the static library default, FYI https://gitlab.archlinux.org/archlinux/packaging/packages/llvm/-/commit/3e452a15b68d156a9ef5608e8f6e1870d192d954
So we need add `-DENABLE_LLVM_SHARED=on` default for the Arch Linux
=> doc: Fix the build guide for the Arch Linux

.github/actions/build-container/action.yml, docker/build/Dockerfile.ubuntu
I already moved the minimum llvm version from 11 to 12 and this particular instance is missed.
=> Use llvm12 when building containers

libbpf-tools/memleak.c
Add -v(--verbose) option to display libbpf log
=> libbpf-tools/memleak: Add verbose option

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/profile.bpf.c, libbpf-tools/profile.c, libbpf-tools/profile.h
It is based on Brendan Gregg's BCC profile and much of the code for it is borrowed from offcputime.c and ruqlen.c.
I'm not sure if libbpf-tools requires a profile. So I'm sharing this just to get some feedback before I finish developing of this patch.
Could you give me your opinion? (if necessary or not)
Thank you.
This is an example of usage. 
```
Sampling at 49 Hertz of all threads by kernel stack... Hit Ctrl-C to end.
^C    
_raw_spin_unlock_irq
finish_task_switch
__schedule
schedule
schedule_timeout
msleep
HDMI21_Tx_EARC_MainThread
kthread
ret_from_fork
-                hdmi21_earc_eng (1427)
1
__pi___clean_dcache_area_poc
dma_direct_map_page
dma_direct_map_sg
dma_buf_unified_map
dma_buf_map_attachment
kbase_mem_umm_map_attachment
kbase_mem_import
kbase_ioctl
__arm64_compat_sys_ioctl …
```
=> libbpf-tools: add profile

docker/Dockerfile.ubuntu, docker/build/Dockerfile.fedora, docker/build/Dockerfile.ubuntu, libbpf-tools/bashreadline.c, tools/bashreadline.py
This Pull Request fixes the issue where the bashreadline tool would lose the first bash command upon startup.
At runtime, bash blocks at the readline function in bash::readline.c. Upon receiving the Enter key signal, it calls the readline_internal_teardown function to retrieve the user's input. Therefore, changing the hook function from readline to readline_internal_teardown resolves the issue of losing the first bash command after startup of bashreadline.
The specific approach is to open the symbol table of bash and check if there is a symbol for readline_internal_teardown function. If not, continue to use the readline function as the hook position.
=> tools/bashreadline: Fix bashreadline

tools/execsnoop.py
In SMP systems, knowing which specific CPU a process is running on can be useful for troubleshooting.
Test it,
```
[root@anylinux ~]# taskset -c 0 sleep 100 &
[1] 2199347
[root@anylinux ~]# taskset -c 1 sleep 100 &
[2] 2199348
```
Now, execsnoop with '-C' option displays that one sleep process is running on CPU 0, the other is running on CPU 1, as expected.
```
[root@anylinux ~]# /usr/share/bcc/tools/execsnoop -C
PCOMM            PID     PPID    CPU  RET ARGS
taskset          2199347 2199222 0      0 /usr/bin/taskset -c 0 sleep 100
sleep            2199347 2199222 0      0 /usr/bin/sleep 100
taskset          2199348 2199222 4      0 /usr/bin/taskset -c 1 sleep 100
sleep            2199348 2199222 1      0 /usr/bin/sleep 100
```
=> tools/execsnoop: display which cpu the processes running on

libbpf-tools/execsnoop.bpf.c, libbpf-tools/futexctn.bpf.c, libbpf-tools/mountsnoop.bpf.c, libbpf-tools/opensnoop.bpf.c, libbpf-tools/sigsnoop.bpf.c, libbpf-tools/statsnoop.bpf.c
In BPF programs, syscall tracepoints returns a local syscall_tp_t structure that's meant to mimic syscall_trace_enter/exit structures. It just happen to have the same offsets for nr and args fields as struct trace_event_raw_sys_enter/exit. However, a change in the trace_entry structure in the linux-rt broke that assumption (ea622076b76f "sched: Add support for lazy preemption").
Program calling syscall tracepoint should have used the right structure in the first place. This patch replace the trace_event_raw_sys_* by their syscall_trace_* counterpart when calling a syscall tracepoint.
=> libbpf-tools: fix syscall tracepoints

SPECS/bcc.spec, debian/control
With commit 6f11bf7e in #4737 bpf_module.h now includes llvm-config.h, hence tools building against libbcc may need the LLVM headers at build time.
Add the LLVM development package as a runtime requirement in the included package specifications to make such dependency explicit.
Context: this problem was encountered when building [procmon](https://github.com/Sysinternals/ProcMon-for-Linux) on openSUSE, and we had to add such dependency for the bcc-devel package https://build.opensuse.org/request/show/1152316
CC @chantra @jeromemarchand
=> Explicitly declare dependency on LLVM header

libbpf-tools/fsdist.c, libbpf-tools/fsslower.c, libbpf-tools/sigsnoop.c
Support for prefixed installs with an `APP_PREFIX` variable was added in https://github.com/iovisor/bcc/pull/4848.
`fsdist`, `fsslower`, and `sigsnoop` support aliased execution but that only works as intended if `basename(prog)` matches the non-prefixed alias exactly:
```
root@test:~# foo-prefix-ext4slower
filesystem must be specified using -t option.
```
This PR simply relaxes that behavior to only find a string match:
```
root@test:~# foo-prefix-ext4slower
Tracing ext4 operations slower than 10 ms... Hit Ctrl-C to end.
...
```
=> libbpf-tools: Fix fsdist, fsslower, and sigsnoop aliases when installed with APP_PREFIX

src/cc/frontends/clang/kbuild_helper.cc
commit 008ea09 (clang: check header ownership) updates file_exists() to file_exists_and_ownedby(), add verifies onwer, but the return value is different from before, causing problems with the original code.
After commit 008ea09 (clang: check header ownership)， `/usr/share/bcc/examples/hello_world.py --help` output is different: (left: old  | right: new)
Because commit 008ea09  changed the return value：
**Old: If file exists, file_exists() return 1;**
```c
static inline int file_exists(const char *f)
{
struct stat buffer;
return (stat(f, &buffer) == 0);  //ret = stat(f, &buffer) == 0
}
```
**New: If file exists, file_exists_and_ownedby() return 0;**
```c
static inline int file_exists_and_ownedby(const char *f, uid_t uid)
{
struct stat buffer;
int ret;
if ((ret = stat(f, &buffer)) == 0) { …
```
=> clang: Fix file_exists_and_ownedby return value

src/cc/frontends/clang/b_frontend_action.cc
Commit 57ca51bdd9c8 ("Fix btf_type_tag issue with llvm 15") fixed an issue where "btf_type_tag(rcu)" should be replaced with "__attribute__((btf_type_tag(\"rcu\")))".
I audited some other bcc tools and found another similar failure pattern during processing funciton arguments. Three tools are dirtop.py, fileslower.py and filetop.py.
The failure pattern for dirtop.py looks like:
```
/virtual/main.c:79:72: error: expected ')'
struct file *file = (struct file *)ctx->di; char __user *buf =
(char  btf_type_tag(user)*)ctx->si; size_t count = (size_t)ctx->dx;
```
Again, the "btf_type_tag(user)" should be replaced with `"__attribute__((btf_type_tag(\"user\")))"`. This patch fixed this issue.
=> Fix another btf_type_tag issue with llvm 15

tools/slabratetop.py
slabratetop.py failed with 6.8 kernel with
```
/virtual/main.c:100:10: fatal error: 'linux/slub_def.h' file not found
100 | #include <linux/slub_def.h>
|          ^~~~~~~~~~~~~~~~~~
```
Actually 'kmem_cache' is also not available to bcc any more. Either copying 'kmem_cache' or using mini-CORE like logic are too complex and error prone ([1]). So let us mark the tool is not supported for >= 6.8 kernel and suggest to use libbpf-tool version of slabratetop if needed.
[1]. https://github.com/iovisor/bcc/pull/4940
=> Mark slabratetop.py not supported for >= 6.8 kernel

debian/control, docker/Dockerfile.ubuntu
- Fixes typo in `debian/control` which was causing deb builds to fail
- add llvm-12-dev package to ubuntu dockerfile
=> fix deb build/docker ubuntu

cmake/FindCompilerFlag.cmake
fix: https://github.com/iovisor/bcc/issues/4931
=> Reomove "-nopie" option workaround for old clang.

debian/changelog
* Support for kernel up to 6.8.
* Set minimum supported llvm version to 12, and add llvm17 test.
* Add workqueue latency observation tool.
* libbpf tool update: f2fsslower, opensnoop, futexctn, bindsnoop, ksnoop, klockstat, offcputime, etc.
* bcc tool update: memleak, ttysnoop, bashreadline, tcpdrop, execsnoop, etc.
* allow more flexible perf event options with new perf_custom_event_open() python API.
* Fix userspace stack unwinding on powerpc.
* add bpf_prog_test_run_opts() python API.
* several deb package related changes.
* Fix btf_type_tag issue with llvm 15.
* Fix several flaky tests.
* classify tools into different sub-categories.
* doc update, other bug fixes and tools improvement.
=> Update debian changelog for release v0.30.0

tools/biolatency.py, tools/biosnoop.py, tools/biotop.py
Since kernel introduce block:block_io_{start,done}, we should use tracepoint first, just like the follow error i got on Fedora 39
```
$ sudo ./biolatency.py
...
cannot attach kprobe, Invalid argument
File "/home/sda/git-repos/bcc/tools/./biolatency.py", line 291, in <module>
b.attach_kprobe(event="blk_account_io_done", fn_name="trace_req_done")
File "/usr/lib/python3.12/site-packages/bcc/__init__.py", line 845, in attach_kprobe
raise Exception("Failed to attach BPF program %s to kprobe %s"
Exception: Failed to attach BPF program b'trace_req_done' to kprobe b'blk_account_io_done',
it's not traceable (either non-existing, inlined, or marked as "notrace")
```
```
rongtao@RT-NUC:~/Git/bcc$ cat /etc/os-release 
NAME="Fedora Linux"
VERSION="39 (Server …
```
=> tools/{biolatency,biosnoop,biotop}: Use tracepoint first

tests/python/test_tools_smoke.py
I observed frequent failure for the following test:
```
FAIL: test_offwaketime (__main__.SmokeTests.test_offwaketime)
File "/bcc/tests/python/test_tools_smoke.py", line 275, in test_offwaketime
self.run_with_duration("offwaketime.py 1")
File "/bcc/tests/python/test_tools_smoke.py", line 40, in run_with_duration
self.assertEqual(0,     # clean exit
AssertionError: 0 != 1
```
The reason is that 'offwaketime.py' may need more time to dump results after 1 second of stack collection. Increase timeout to 30 seconds to tolerate potential long delays.
=> Workround flaky subtest 'offaketime.py 1' in test_tools_smoke.py

tools/zfsdist.py, tools/zfsslower.py
This fixes a regression of #1248: The original fix #1324 assumed that `BPF.get_kprobe_functions` checks the given regex against any substring of the function name, but 2b203ea later changed `get_kprobe_functions` to do `re.fullmatch` instead.
=> fix zfsslower check for zpl_read / zpl_iter (fixes #4952)

libbpf-tools/bashreadline.bpf.c, libbpf-tools/gethostlatency.bpf.c, libbpf-tools/memleak.bpf.c
Replace `BPF_K[RET]PROBE` with `BPF_U[RET]PROBE` for u[ret]probes. 
>  We can also replace `BPF_KPROBE` with `BPF_UPROBE`.
_Originally posted by @chenhengqi in https://github.com/iovisor/bcc/pull/4944#discussion_r1549415087_
The macros `BPF_UPROBE` and `BPF_URETPROBE` are added in [libbpf v1.2.0](https://github.com/libbpf/libbpf/releases/tag/v1.2.0) released on May 1, 2023. They are identical to the `BPF_KPROBE` and `BPF_KRETPROBE` but with a less confusing naming. See the definition at https://github.com/libbpf/libbpf/blob/46eafba62ee380a1f8230e2d5e81f65e0e030f15/src/bpf_tracing.h#L915-L920
=> libbpf-tools: Use `BPF_U[RET]PROBE` for u[ret]probes

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/syncsnoop.bpf.c, libbpf-tools/syncsnoop.c, libbpf-tools/syncsnoop.h, man/man8/syncsnoop.8
This is a CO-RE port of the Brendan Gregg's `syncsnoop` BCC Python tool. The code is heavily inspired by the `runqslower` port, with variables naming and comments style borrowed from other CO-RE tools.
I tried to make it look like existing tools as much as possible, but if there's anything missing please let me know.
=> libbpf-tools: add CO-RE 'syncsnoop'

libbpf-tools/numamove.bpf.c, libbpf-tools/numamove.c
In [0] kernel commit 73eab3ca481e ("mm: migrate: convert migrate_misplaced_page() to migrate_misplaced_folio()") convert migrate_misplaced_page() to migrate_misplaced_folio().
Kernel version:
```
$ git describe 73eab3ca481e5be0f1fd8140365d604482f84ee1
v6.6-rc4-109-g73eab3ca481e
```
[0] https://github.com/torvalds/linux/commit/73eab3ca481e
=> libbpf-tools/numamove: Add folio support

libbpf-tools/futexctn.c, libbpf-tools/memleak.c, libbpf-tools/offcputime.c, libbpf-tools/trace_helpers.c, libbpf-tools/trace_helpers.h
offcputime may display inaccurate DSO information in the stacktrace. Here's an example of the issue:
It shows the same DSO offset for different addresses, which is incorrect.
```
$ ./offcputime -v
..
#14 0x00007f8b912a8c (/usr/lib/libabc.so_0x22afa8c)
#15 0x000044000a3ee0 (/usr/lib/libabc.so_0x22afa8c)
#16 0x000044001fc56c (/usr/lib/libabc.so_0x22afa8c)
```
This is why syms__map_addr_dso simply returns NULL when syms__find_dso also returns NULL. In that case, the values of dso_name and dso_offset are not changed. If the dso_name and dso_offset variables have a garbage value before calling syms__map_addr_dso, those garbage values are maintained after calling syms__map_addr_dso.
To ensure consistent usage of DSO info and symbol info, the prototype of syms__map_addr_dso has been modified to …
=> libbpf-tools/trace_helpers: Fix incorrect DSO information in stacktrace

tools/profile.py
Fix profile.py for older kernels:
`bpf_get_ns_current_pid_tgid()` is not available before Linux 5.7:
https://github.com/iovisor/bcc/blob/master/docs/kernel-versions.md
When the kernel is prior to 5.7, skip PID namespace translation,
as `bpf_get_ns_current_pid_tgid()` would not be available then.
=> Fix profile.py for older kernels: On pre-5.7 kernels, skip pid ns mapping (fallback)

libbpf-tools/.gitignore, libbpf-tools/Makefile, libbpf-tools/fsdist.c, libbpf-tools/fsslower.c
Add support for bcachefs to fsdist and fsslower tools.
```
$ sudo ./bcachefsdist 
Tracing bcachefs operation latency... Hit Ctrl-C to end.
^C
operation = 'read'
0 -> 1          : 1        |                                        |
8 -> 15         : 2359     |****************************************|
16 -> 31         : 453      |*******                                 |
32 -> 63         : 42       |                                        |
64 -> 127        : 1        |                                        |
operation = 'write'
0 -> 1          : 0        | …
```
=> Add support for bcachefs to fsdist and fsslower tools

examples/usdt_sample/usdt_sample.md
Install python3-setuptools is missing a p, so fix.
=> Fix usdt_sample prerequisite list

.github/workflows/bcc-test.yml, .github/workflows/publish-build-containers.yml
This should fix the GitHub actions deprecation warning notices that are shown on the GitHub actions summary page.
=> Fix GitHub actions deprecation warning notices

src/cc/frontends/clang/kbuild_helper.cc
file_exists_and_ownedby() returns -1 when the file exists but its ownership is unexpected, which is very misleading since anything non zero is interpreted as true and a function with such a name is expected to return a boolean. So currently all this does, is write a warning message, and continues as if nothing is wrong.
Make file_exists_and_ownedby() returns false when the ownership is wrong and have get_proc_kheaders() fails when this happen. Also have all the *exists* functions return bool to avoid such issues in the future.
=> clang: fail when the kheaders ownership is wrong (#4928)

libbpf-tools/tcptop.c, libbpf-tools/tcptop_example.txt
Fix PID column alignment when PIDs are large in `libbpf-tools/tcptop`:
Check the maximum width of the PIDs on the system and adjust the format to avoid column misalignment:
```js
PID     COMM         LADDR                 RADDR                  RX_KB  TX_KB
1987802 wget         127.0.0.1:44960       127.0.0.1:443              6      0
1987815 wget         127.0.0.1:44968       127.0.0.1:443              6      0
2770    stunnel      127.0.0.1:51460       127.0.0.1:80               4      0
2770    stunnel      127.0.0.1:51452       127.0.0.1:80               4      0
1936412 sshd         10.71.56.137:22       10.71.8.14:45682           0      2
1987805 curl         127.0.0.1:44964       127.0.0.1:443              1      0
1987818 curl         127.0.0.1:44972       127.0.0.1:443 …
```
=> libbpf tcptop: Fix PID column alignment when pids are large

libbpf-tools/map_helpers.c
Even when the batch read is successful, a non-batch read is performed. Fixed so that non-batch reads are not performed once batch reads are done.
This is the result of testing tcpconnect by adding some logs to map_helpers.
Before:
```
./tcpconnect -c
dump_hash_batch, *count: 3
k: 16777343, v: 1
k: 50331775, v: 0
k: 385875968, v: 1
dump_hash_iter, *count: 3
k: 16777343, v: 1
k: 50331775, v: 0
k: 385875968, v: 1
LADDR                     RADDR                     RPORT                CONNECT
127.0.0.1                 127.0.0.3                 23                   1
127.0.0.1                 127.0.0.1                 23                   1
127.0.0.1                 127.0.0.2                 23                   1
```
After:
```
./tcpconnect -c
dump_hash_batch *count: 2
k: 16777343, v: 1
k: …
```
=> libbpf-tools/map_helpers: Fix duplicate map read operations

tools/kvmexit.py
The linux [0] KVM VMX enable two new VM exit, as follows:
commit 2f4073e08f4c ("KVM: VMX: Enable Notify VM exit")
$ git describe 2f4073e08f4c
v5.19-rc1-95-g2f4073e08f4c
commit fe6b6bc802b4 ("KVM: VMX: Enable bus lock VM exit")
$ git describe fe6b6bc802b4
v5.11-rc3-54-gfe6b6bc802b4
[0] https://github.com/torvalds/linux.git
=> tools/kvmexit: Add BUS_LOCK and NOTIFY reasons

tools/sslsniff.py, tools/sslsniff_example.txt
The `len` field for `SSL_do_handshake` should be zero. 
The current implementation utilizes the return value, which is `1` on success [1].
Cc: @alban 
[1] https://www.openssl.org/docs/manmaster/man3/SSL_do_handshake.html
=> tools/sslsniff: fix length field for handshake

src/cc/frontends/clang/b_frontend_action.cc
llvm [0] startswith() is deprecated in commit 5ac12951b4e9 ("[ADT] Deprecate StringRef::{starts,ends}with (#75491)"), and it's totally removed in commit 4ec9a662d388 ("[ADT] Remove StringRef::{startswith,endswith} (#89548)").
Warning detail:
$ make
[...]
/home/rongtao/Git/iovisor/bcc/src/cc/frontends/clang/b_frontend_action.cc:341:37: warning: ‘bool llvm::StringRef::startswith(llvm::StringRef) const’ is deprecated: Use starts_with instead [-Wdeprecated-declarations]
341 |         if (!A->getName().startswith("maps"))
|              ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
In file included from /usr/include/clang/Basic/DiagnosticIDs.h:19,
from /usr/include/clang/Basic/Diagnostic.h:17,
from /usr/include/clang/AST/NestedNameSpecifier.h:18,
from /usr/include/clang/AST/Type.h:21,
from …
=> Fix: startswith() is deprecated: Use starts_with instead

tools/argdist.py
`tools/argdist.py`: Fix verbose printing `b'bytes'`: decode `bytes` to `str`
The `uprobe` and `kprobe` keys are `bytes` not `str` they need to be decoded on Python3:
```py
print("open uprobes: %s" % list(self.bpf.uprobe_fds.keys()))
print("open kprobes: %s" % list(self.bpf.kprobe_fds.keys()))
```
This fixes the `--verbose` output from `b['key1', b'key2']` to `key1, key2`, as the keys would be printed in Python2 originally:
```py
- print("open uprobes: %s" % list(self.bpf.uprobe_fds.keys()))
- print("open kprobes: %s" % list(self.bpf.kprobe_fds.keys()))
+ print("open uprobes: [%s]" % b", ".join(self.bpf.uprobe_fds.keys()).decode())
+ print("open kprobes: [%s]" % b", ".join(self.bpf.kprobe_fds.keys()).decode())                                                            ```
=> argdist.py: Fix verbose printing `b'bytes'`: decode `bytes` to `str`

tools/inject.py
run `./inject.py kmalloc -v '__x64_sys_mount()` gets the error: "math between map_value pointer and register with unbounded min value is not allowed", as the array len is 2:
```c
struct pid_struct {
u64 curr_call; /* book keeping to handle recursion */
u64 conds_met; /* stack pointer */
u64 stack[2];
};
```
but in `__x64_sys_mount_exit`
/*
* Generate exit logic */
if (p->conds_met < 1 || p->conds_met >= 3)
return 0;
if (p->stack[p->conds_met - 1] == p->curr_call)
p->conds_met--;
The check for the upper bound of the array is 3.
=> inject.py: fix BPF verification fails due to register offset

tools/tcpcong.py
Removed a duplicate import of pack from the struct module in tools/tcpcong.py.
=> Remove duplicate import of 'pack' from struct module

src/cc/usdt/usdt_args.cc
This change fixes parsing of USDT arguments like [x8].
When a memory dereference has no offset or index register, the parsing code skips setting an offset, which causes the argument to be interpreted as simply a register.  This is causes the argument value to not be dereferenced as required.
This change sets an offset constant of 0 so that the address will still be dereferenced.
=> usdt: Fix bare register dereference on aarch64

src/cc/frontends/clang/loader.cc
The linux kernel [0] commit 0e3703630bd3 ("x86/percpu: Fix "const_pcpu_hot" version generation failure") introduce this_cpu_read_const(const_pcpu_hot.current_task) in arch/x86/include/asm/current.h, which will cause the following warnings:
$ sudo ./opensnoop.py
In file included from /virtual/main.c:14:
In file included from include/uapi/linux/ptrace.h:183:
In file included from arch/x86/include/asm/ptrace.h:175:
In file included from arch/x86/include/asm/paravirt_types.h:12:
In file included from arch/x86/include/asm/nospec-branch.h:15:
arch/x86/include/asm/current.h:47:10: warning: multiple identical address spaces specified for type [-Wduplicate-decl-specifier]
47 |                 return this_cpu_read_const(const_pcpu_hot.current_task);
|                        ^ …
=> Fix warning: multiple identical address spaces specified for type on x86

tools/execsnoop.py, tools/execsnoop_example.txt
Sometimes the parent process is executed instantly, and only tracking PPID does not know who executed the command. Adding PCOMM is a good choice. At the same time, rename the original PCOMM to COMM, and use PCOMM as the parent command.
Before:
$ sudo ./execsnoop.py
COMM             PID     PPID    RET ARGS
sh               44789   44682     0 /bin/sh -c cd /home/...
gcc              44788   44682     0 /usr/bin/gcc -DCAPST...
After:
$ sudo ./execsnoop.py -M
COMM             PID     PCOMM            PPID    RET ARGS
sh               44789   make             44682     0 /bin/sh -c cd /home/...
gcc              44788   make             44682     0 /usr/bin/gcc -DCAPST...
^^^^^^^^^^^^^^^^
=> tools/execsnoop: Add -M,--print-pcomm argument

libbpf-tools/wakeuptime.c
Include symbol base offset in the kernel stack trace to accurately pinpoint the location of function calls.
The offset is commonly used in various debugging tools, including those for the Linux kernel.
Before:
```
target:          kworker/1:0
ffffffffc0001239 bpf_prog_01d43570d6219d0c_sched_wakeup
ffffffffc0001239 bpf_prog_01d43570d6219d0c_sched_wakeup
ffffffff8118ca87 bpf_trace_run1
ffffffff810a9804 __traceiter_sched_wakeup
ffffffff810b5dcb ttwu_do_activate.isra.141
ffffffff810b5ec6 sched_ttwu_pending
ffffffff81132c16 __flush_smp_call_function_queue
ffffffff8104ffa3 __sysvec_call_function_single
ffffffff81dc72d9 sysvec_call_function_single
ffffffff81e00dc6 asm_sysvec_call_function_single
waker: test-strlen-abc
77
```
After:
```
target:          kworker/1:0
ffffffffc0001279 …
```
=> libbpf-tools/wakeuptime: Add offset to kernel stack trace

examples/networking/xdp/xdp_drop_count.py
When trying to offload an ebpf xdp program to a Netronome SmartNIC a ctypes error is given. This can be seen when running xdp_drop_count.py:
This is also noted in: https://stackoverflow.com/questions/66628566/trying-to-load-xdp-on-nic-offloaded. However, no solution is provided. According to the merge: https://github.com/iovisor/bcc/pull/2502, this should not be the error given in case of the nic not supporting offload.
The issue is fixable by casting the device interface name to a _const char pointer_. This allows the programs to load correctly:
=> Offload xdp_drop_count.py error

libbpf-tools/tcpconnect.c
The max size of comm is 16 bytes.
=> tcpconnect: increase comm field size

tools/killsnoop.py, tools/killsnoop_example.txt
Currently, the -s option only supports tracing one signal. Now, if we enable the -s option to support a comma-separated list of signals, it will make monitoring more convenient.
=> killsnoop: Allow to trace a signal list

tools/biolatency.py
On WSL2 with the kernel 6.4.8, `biolatency.py` and `biolatency.py -Q` did not work.
In this case, the kernel kprobe functions were inlined and `block:block_io_{start|done}` tracepoints were missing, thus no condition was matched.
This fix adds support for `block:block_bio_queue` and `block:block_rq_complete` tracepoints, corresponding to the blktrace Q event (Queue) and C event (Complete) respectively. Now `biolatency.py` and the `-Q` option are compatible with the kernel.
References: [events](https://elixir.bootlin.com/linux/v6.4.8/source/kernel/trace/blktrace.c#L1465) and [tracepoints](https://elixir.bootlin.com/linux/v6.4.8/source/kernel/trace/blktrace.c#L1113).
=> tools/biolatency: Add support for blktrace events

libbpf-tools/profile.c
Added -f option to display output in folded format for conversion to flame graphs.
This is a test example.
```
test-strlen-abc;__libc_start_main;main;a;b;strlen 34
test-strlen-abc;__libc_start_main;main;a;b;strlen 28
test-strlen-abc;__libc_start_main;main;a;b;strlen 15
test-strlen-abc;__libc_start_main;main;a;b;strlen 12
test-strlen-abc;__libc_start_main;main;a;b;strlen 11
test-strlen-abc;__libc_start_main;main;a;b;strlen 9
test-strlen-abc;__libc_start_main;main;a;b;strlen 5
```
=> libbpf-tools/profile: Add -f option to display output in folded format

docs/reference_guide.md
Fix a typo in the reference guide.
=> docs: fix typo

tools/syncsnoop.py, tools/syncsnoop_example.txt
Add fsync(),fdatasync(),syncfs(),sync_file_range(),msync() syscalls to trace. For example:
$ sudo ./syncsnoop.py
TIME(s)            COMM             CALL
1173253.856512000  worker           fdatasync
1173260.193706000  sync             sync
1173261.478894000  syncfs           syncfs
1173264.231075000  fsync            fsync
1173264.297788000  fsync            fdatasync
1173284.063700000  worker           fdatasync
1173288.229822000  mkfs.ext4        fsync
1173304.818227000  worker           fdatasync
1173315.065319000  journal-offline  fsync
=> tools/syncsnoop: Add more syscalls support

libbpf-tools/javagc.bpf.c
On Debian12 riscv64, the kernel never has asm/errno.h for riscv64, we do not include usdt.bpf.h could solve this problem.
$ make
...
BPF      javagc.bpf.o
In file included from javagc.bpf.c:6:
In file included from /home/rongtao/bcc/libbpf-tools/.output/bpf/usdt.bpf.h:6:
/usr/include/linux/errno.h:1:10: fatal error: 'asm/errno.h' file not found
#include <asm/errno.h>
^~~~~~~~~~~~~
make: *** [Makefile:204: /home/rongtao/bcc/libbpf-tools/.output/javagc.bpf.o] Error 1
=> libbpf-tools/javagc: Fix fatal error: 'asm/errno.h' file not found on riscv64

libbpf-tools/sigsnoop.bpf.c, libbpf-tools/sigsnoop.c
tools/killsnoop supports a signal list(47d7263ec4bb8163c0c5fac70edaca9f1b2307f6), 
it's reasonable to support the same feature in libbpf-tools/sigsnoop.
=> libbpf-tools/sigsnoop: Allow to trace a signal list

libbpf-tools/syncsnoop.bpf.c, libbpf-tools/syncsnoop.c, libbpf-tools/syncsnoop.h
Add fsync(),fdatasync(),syncfs(),sync_file_range(),msync() syscalls to trace. For example:
$ sudo ./syncsnoop
TIME(s)            COMM             CALL
7348.355957031     aria2c           fsync
7350.032226562     ThreadPoolForeg  fdatasync
=> libbpf-tools/syncsnoop: Add more syscalls support

tools/threadsnoop.py
`func == "[unknown]"` always return false, the output column `FUNC` prints `b'[unknown]'` instead of thread start address. 
```
TIME(ms)   PID     COMM             FUNC
3271       1       b'systemd'       b'[unknown]'
3271       1       b'systemd'       b'[unknown]'
3571       2945804 b'mysqld'        b'[unknown]'
3882       2945804 b'mysqld'        b'[unknown]'
3894       2945804 b'mysqld'        b'[unknown]'
3901       2945804 b'mysqld'        b'[unknown]'
3910       2945804 b'mysqld'        b'[unknown]'
3910       2945804 b'mysqld'        b'[unknown]'
```
after fix
```
TIME(ms)   PID     COMM             FUNC
7215       1       systemd          0x55acce4d4990
7215       1       systemd          0x55acce4d4990
7521       2949704 mysqld           0x55775c43c800
7842       2949704 mysqld …
```
=> tools/threadsnoop: Fix unknown thread start address

src/python/bcc/__init__.py
The upstream linux commit[1] implemented syscall wrappers. Currently `get_syscall_prefix` returns unmatched prefix.
The syscall wrappers generates three functions for each system call, one of them is `__riscv_<compat_>sys_<name>`.
So here it can be processed like x86/arm64.
[1] [08d0ce30e0e4](https://github.com/torvalds/linux/commit/08d0ce30e0e4fcb5f06c90fe40387b1ce9324833) ("riscv: Implement syscall wrappers")
=> bcc/python: Fix get_syscall_prefix on riscv for linux-6.6

libbpf-tools/offcputime.c
Print starting message like python version does
But not implement to print `thread_context` and `stack_context`
Python version starting message
```
$ sudo python3 ./offcputime.py
Tracing off-CPU time (us) of all threads by user + kernel stack... Hit Ctrl-C to end.
$ sudo python3 ./offcputime.py 30
Tracing off-CPU time (us) of all threads by user + kernel stack for 30 secs.
```
libbpf-tools version(with this patch) starting message
```
$ sudo ./offcputime
Tracing off-CPU time (us)... Hit Ctrl-C to end.
$ sudo ./offcputime 30
Tracing off-CPU time (us) for 30 secs.
```
=> libbpf-tools/offcputime: Print application starting message

src/cc/bcc_proc.c, src/cc/bcc_proc.h, src/python/bcc/__init__.py, src/python/bcc/libbcc.py, tests/cc/test_c_api.cc
Fixes https://github.com/iovisor/bcc/issues/5013
- Extend `bcc_proc` API. Allow to limit search to specific pid.
- Also extend the Python binding with the same goal.
- The API changes are backwards-compatible.
- Also added a couple of boundary checks for `memcpy`
=> Extend `bcc_proc` API. Allow to limit search to specific pid.

debian/changelog
* Support for kernel up to 6.9.
* Add support for bcachefs to fsdist and fsslower tools
* libbpf tool update: memleak, syncsnoop, numamove, syscount, vfsstat, tcptop, capable, syncsnoop, sigsnoop, etc.
* bcc tool update: biolatency, biosnoop, biotop, vfsstat, kvmexit, sslsniff, swapin, etc.
* build: Remove llvm-dev dependency from libbcc
* build: Remove dependency on LLVM header from libbcc packages
* usdt: Fix bare register dereference on aarch64
* Extend `bcc_proc` API which allows to limit search to specific pid
* Fix several flaky tests.
* doc update, other bug fixes and tools improvement.
=> Update debian changelog for release v0.31.0

libbpf-tools/futexctn.c
The program should be prompted to start running:
$ sudo ./futexctn
Summarize futex contention latency, hit ctrl-c to exit
=> libbpf-tools/futexctn: Hint program is running

libbpf-tools/profile.c
Add additional information and change format of backtrace
- add symbol base offset, dso name, dso base offset
- symbol and dso info is included if it's available in target binary
- changed format:
ADDR [SYMBOL+OFFSET] (MODULE+OFFSET)
before:
```
clocksource_watchdog
call_timer_fn
run_timer_softirq
__softirqentry_text_start
irq_exit_rcu
sysvec_apic_timer_interrupt
asm_sysvec_apic_timer_interrupt
strlen
b
a
main
__libc_start_main
-                test-strlen-abc (26209)
1
```
After:
```
0xffffffff8111f594 clocksource_watchdog+0xd4
0xffffffff81117454 call_timer_fn+0x24
0xffffffff81117de4 run_timer_softirq+0x444
0xffffffff81dd3493 __softirqentry_text_start+0xd3
0xffffffff8108143c irq_exit_rcu+0x6c
0xffffffff81dc738e sysvec_apic_timer_interrupt+0x3e
0xffffffff81e00d46 …
```
=> libbpf-tools/profile: Add additional information to backtrace for -v option

tools/wakeuptime.py
Include symbol base offset in the kernel stack trace to accurately pinpoint the location of function calls.
The offset is commonly used in various debugging tools, including those for the Linux kernel.
Before:
```
target:          kworker/u8:3
ffffffffc0215f96 bpf_prog_6deef7357e7b4530_sd_fw_ingress
ffffffff928e925d bpf_trace_run1
ffffffff9274d7d9 __bpf_trace_sched_wakeup_template
ffffffff9274611b __traceiter_sched_wakeup
ffffffff9275e2c1 ttwu_do_activate
ffffffff9275e4f1 sched_ttwu_pending
ffffffff92827fb3 __flush_smp_call_function_queue
ffffffff92828b3a flush_smp_call_function_queue
ffffffff9277d5a7 do_idle
ffffffff9277d80a cpu_startup_entry
ffffffff926a7349 start_secondary
ffffffff92600279 secondary_startup_64_no_verify
waker:           swapper/3
1508198
```
After:
```
target: …
```
=> tools/wakeuptime: Add offset to kernel stack trace

src/python/bcc/__init__.py
#5077 
Get and add 'larchintrin.h' file directory in cflags if the architecture is loongarch64，fix larchintrin.h not found error.
=> Fix larchintrin.h not found error for loongarch64

tools/readahead.py
In kernel commit b951aaff5035 ("mm: enable page allocation tagging") [1], add _noprof suffix to filemap_alloc_folio.
Link: https://github.com/torvalds/linux/commit/b951aaff503502a7fe066eeed2744ba8a6413c89 [1]
=> tools/readahead: Add filemap_alloc_folio_noprof() support

tools/shmsnoop.py, tools/shmsnoop_example.txt
Print shmctl command:
$ sudo ./shmsnoop.py
PID    COMM        SYS           RET ARGs
16413  writer   SHMGET            31 key: 0xd2032983, size: 4194304, shmflg: 0x3a4 (IPC_CREAT|0644)
16413  writer    SHMAT  7f7f572b8000 shmid: 0x31, shmaddr: 0x0, shmflg: 0x0
16413  writer    SHMDT             0 shmaddr: 0x7f7f572b8000
16418  reader   SHMGET            31 key: 0xd2032983, size: 4194304, shmflg: 0x1a4 (0644)
16418  reader    SHMAT  7f28e81a4000 shmid: 0x31, shmaddr: 0x0, shmflg: 0x0
16418  reader    SHMDT             0 shmaddr: 0x7f28e81a4000
16418  reader   SHMCTL             0 shmid: 0x31, cmd: 0 (IPC_RMID), buf: 0x0
^^^^^^^^^^
=> tools/shmsnoop: Print shmctl command string

libbpf-tools/readahead.bpf.c, libbpf-tools/readahead.c
Close #4700. cc @jeromemarchand who opened the issue. 
This PR accounts for the rename/refactor of the following functions
- `__do_page_cache_readahead` -> `do_page_cache_ra` -> `page_cache_ra_order` by https://github.com/torvalds/linux/commit/8238287eadb2 and https://github.com/torvalds/linux/commit/56a4d67c264e
- `__page_cache_alloc` -> `filemap_alloc_folio` -> `filemap_alloc_folio_noprof` by https://github.com/torvalds/linux/commit/bb3c579e25e5 and https://github.com/torvalds/linux/commit/b951aaff5035. 
Kudos to @Rtoax for the fix for the Python tools: #4457, #5083
=> libpf-tools/readahead: Fix attachment failure since v5.16

tools/offcputime.py
Inspired by the perf-top command, the offcputime tool is enhanced to support tracking multiple processes and threads.
$ man perf-top
-p <pid>, --pid=<pid>
Profile events on existing Process ID (comma separated list).
-t <tid>, --tid=<tid>
Profile events on existing thread ID (comma separated list).
Before:
$ offcputime  -h
optional arguments:
-p PID, --pid PID     trace this PID only
-t TID, --tid TID     trace this TID only
examples:
./offcputime -p 185      # only trace threads for PID 185
./offcputime -t 188      # only trace thread 188
After:
$ offcputime -h
optional arguments:
-p PID, --pid PID     trace these PIDs only, comma separated list
-t TID, --tid TID     trace these TIDs only, comma separated list
examples:
./offcputime -p 185,175,165 # only trace threads for PID 185,175,165 …
=> offcputime: Support tracking specified processes and threads

src/cc/bcc_debug.cc
The upstream commit
https://github.com/llvm/llvm-project/pull/82240
introduced a func signature change for func getFileLineInfoForAddress(). Add proper change to accommodate llvm20 need for additional func arguments.
=> Fix a compilation issue with llvm20

src/cc/bpf_module.cc
Upstream patch
https://github.com/llvm/llvm-project/pull/107008
makes cpu=v3 as the default. Previously cpu=v1 as the default for bcc. Let us mark cpu=v1 explicitly for bcc for now to keep it backword compatible.
=> Set cpu=v1 explicitly

tools/cpudist.py
inspired by the https://github.com/iovisor/bcc/blob/6acb86effa7a6e8029b68eccb805dd1ee60ecc5a/tools/profile.py#L168
if the `cpudist` runs in a pid namespace, the filtered pid/tgid are not as expected.
since the kernel does not provide something like i`int bpf_get_ns_pid_tgid(u64 dev, u64 ino, struct bpf_pidns_info * ns_data, u32 size)`, we can create the mapping for the `current`, then find out the mapped ns pid by the real pid whenever the `prev` is refered.
=> Pid namespace support

examples/cpp/KModRetExample.cc
musl libc has no error.h, but luckily the include is not needed at all and can just be removed.
Previously reported in https://github.com/iovisor/bcc/issues/4594 and more recently in Gentoo at https://bugs.gentoo.org/939453.
=> Remove unneeded error.h include from examples/cpp/KModRetExample.cc to allow build with musl libc

libbpf-tools/profile.c, tools/profile.py
Modify the help message for multi-process/thread support in libbpf-tools/profile and tools/profile.
=> libbpf-tools/profile: Fix the help message for multi process/thread

libbpf-tools/profile.c
Parameter `freq` of `open_and_attach_perf_event` is not in use.  So remove it.
=> libbpf-tools/profile: Remove unnecessary parameter

libbpf-tools/Makefile, libbpf-tools/hardirqs.bpf.c, libbpf-tools/hardirqs.c, libbpf-tools/softirqs.bpf.c, libbpf-tools/softirqs.c
Since tools/hardirqs and tools/softirqs supports a `--cpu` option, it's reasonable to support  a same option in libbpf version.
=> libbpf-tools: add cpu filter for hardirqs/softirqs

tools/tcpcong.py
1: Ports that do not meet the conditions in function "entry_state_update_func" will not be stored in the "start_ipv4" or "start_ipv6", and the "ret_state_update_func" function will not obtain values, so there is no need to perform port filtering again.
2: Sock_store can be directly deleted in function "ret_func".
=> tools/tcpcong: Reduce code redundancy

src/cc/bcc_elf.c, src/cc/bcc_elf.h, src/cc/usdt/usdt.cc, src/cc/usdt/usdt_args.cc
It is not sufficient to determine whether Elf is ET_DYN or not to be a dynamic library in bcc_elf_is_shared_obj() function, because the executable Elf of the PIE type is also ET_DYN.
For example, on fedora 40, /usr/bin/bash is PIE:
```
$ readelf -h /usr/bin/bash
ELF Header:
...
Type:                     DYN (Position-Independent Executable file)
...
```
bcc_elf_is_shared_obj() should not return 'true' for /usr/bin/bash.
This commit add a function bcc_elf_is_pie(), maybe we can provide API in bcc_elf.h.
=> elf: Detect if Elf is PIE

tools/biolatency_example.txt
`#` at the beginning can show that it is a command
Add `#` at the beginning of the example command in biolatenxy_example.txt
=> tools: Add `#` at the beginning of example command

tools/threadsnoop.py, tools/threadsnoop_example.txt
Import argparser and add basic implementation for this. Now user can use `-h` option for threadsnoop tool.
=> tools/threadsnoop: Add -h option

tools/biolatency_example.txt
`-F` option prints a separate histogram for each unique set of request flags. But the explanation right after the `-F` option example is not about this option.
=> tools: Fixes explanation about -F option in biolatency_example.txt

tools/softirqs.py, tools/softirqs_example.txt
Users are usually interested in events that happen frequently and consume more time. So, print the results in descending order.
=> tools/softirqs: Print results in descending order

libbpf-tools/gethostlatency.c, libbpf-tools/offcputime.bpf.c, libbpf-tools/offcputime.c
For kernels without BPF trampoline, let's use raw tracepoint instead.
While at it, also fix a compilation error for gethostlatency.
=> libbpf-tools: Allow offcputime to run on kernels without BPF trampoline

man/man8/filetop.8, tools/filetop.py, tools/filetop_example.txt
Add filter to reverse the output order of filetop, and filters to trace either read or write operations at a time
=> Add filters to filetop

tools/tcpstates.py
Like #3922, there is a use-case to use tcpstates with pipe, but pipe doesn't work well because of buffer.
Test: tcpstates | cat
=> add sys.stdout.flush() during print

tools/cachestat.py, tools/cachetop.py
Since kernel 5.16, `add_to_page_cache_lru/mark_page_accessed` were moved to in mm/folio-compat.c, actually defined in `filemap_add_folio/folio_mark_accessed`:
```
int add_to_page_cache_lru(struct page *page, struct address_space *mapping, pgoff_t index, gfp_t gfp)
{
return filemap_add_folio(mapping, page_folio(page), index, gfp);
}
void mark_page_accessed(struct page *page)
{
folio_mark_accessed(page_folio(page));
}
```
When running on kernel > 5.15, the output is not correct: column `MISSES` always 0 due to `add_to_page_cache_lru` not counted, and `mark_page_accessed` counter less than `folio_mark_accessed`.
Use bpftrace do a simple test (during traced, read a large un-cached file):
```
Attaching 4 probes...
^C
@[filemap_add_folio]: 34623
@[mark_page_accessed]: 113760 …
```
=> tools/cachestat: Fix add_to_page_cache_lru/mark_page_accessed not correct since kernel 5.16

libbpf-tools/javagc.c
Prints a prompt message for not finding jvm.so and opening /proc/PID/maps incorrectly.
=> libbpf-tools: javagc: Hints for more information

src/cc/frontends/clang/loader.cc
Upstream llvm patch
https://github.com/llvm/llvm-project/pull/115852
changed signature for function createDiagnostics(). This patch fixed the issue.
=> Fix LLVM-20 compilation failure

src/cc/compat/linux/virtual_bpf.h
The sync'ed top libbpf commit:
c5f22aca0f3a  ci: remove llvm-17 variant of the workflow
=> bpf: Sync with latest libbpf repo

debian/changelog
* Support for kernel up to 6.11.
* bcc tool update: wakeuptime, readahead, shmsnoop, offcputime, cachestat, cachetop, hardirqs
* libbpf tool update: futexctn, profile, readhead, softirqs, hardirqs
* Multiple enhancements for memleak: better error path checking, adding mremap uprobe, etc.
* Support get pid/tgid in pid namespaces (cpudist, profile)
* multiple pid filtering support: profile, offcputime
* detect whether elf binary is PIE even if the binary is marked as DYN
* Fix several compilation issues with llvm20
* doc update, other bug fixes and tools improvement.
=> Update debian changelog for release v0.32.0

examples/networking/sockmap.py
clang generates such patterns occasionally when it thinks only up to specific size is accessed anyway. Fix the following error:
; .remote_ip4 = skops->remote_ip4, @ main.c:29
7: (79) r2 = *(u64 *)(r1 +24)
Error detail:
$ sudo ./sockmap.py -c /path/to/cgroup/foo
0: R1=ctx() R10=fp0
; if (skops->family != AF_INET) @ main.c:55
0: (61) r2 = *(u32 *)(r1 +20)         ; R1=ctx() R2_w=scalar(smin=0,smax=umax=0xffffffff,var_off=(0x0; 0xffffffff))
1: (55) if r2 != 0x2 goto pc+88       ; R2_w=2
; u32 op = skops->op; @ main.c:52
2: (61) r2 = *(u32 *)(r1 +0)          ; R1=ctx() R2_w=scalar(smin=0,smax=umax=0xffffffff,var_off=(0x0; 0xffffffff))
3: (18) r3 = 0xfffffffe               ; R3_w=0xfffffffe
; switch (op) { @ main.c:58
5: (5f) r2 &= r3 …
=> examples/networking: sockmap.py: Fix invalid bpf_context access off=24 size=8

libbpf-tools/slabratetop.bpf.c, libbpf-tools/slabratetop.c
Convert kmem_cache_alloc() to kmem_cache_alloc_noprof() in commit 7bd230a26648 So the higher version will have the following issues: libbpf: prog 'kmem_cache_alloc': failed to create kprobe 'kmem_cache_alloc+0x0' perf event: No such file or directory libbpf: prog 'kmem_cache_alloc': failed to auto-attach: -2 Failed to attach BPF programs: -2
=> libbpf-tools/slabratetop: Fix failed to create kprobe error

tools/oomkill.py, tools/oomkill_example.txt
Get an application level stack trace on oomkill
Related Issue: #3654
=> tools/oomkill: get application lvl stack trace on oomkill

libbpf-tools/profile.bpf.c, libbpf-tools/profile.c, libbpf-tools/trace_helpers.c, libbpf-tools/trace_helpers.h
Support PID namespace translation as memleak.py does.
=> libbpf-tools/profile: Add support for PID-namespacing

tools/ttysnoop.py
Fix typo from "seperately" to "separately"
=> tools/ttysnoop: Fix a minor typo

tools/klockstat.py
Byte strings are printed directly, leading to output with the 'b' prefix
example:
Caller   Avg Spin  Count   Max spin Total spin
b'ep_poll+0x16b'       1096  26576       8180   29145121
b'drm_fb_helper_damage_work+0x97'       1705     32       2870      54580
b'process_one_work+0x178'       1325     55       2520      72879
b'ext4_evict_inode+0x283'       1625     11       2400      17880
This fix decode the byte strings
After fix:
Caller   Avg Spin  Count   Max spin Total spin
process_one_work+0x178       1569     24       3530      37657
ep_poll+0x16b       1037     12       3090      12450
kthread+0xf2       2336      3       2830       7010
rcu_tasks_kthread+0xa4       1642      5       2490       8210
=> Remove Byte String Prefix in Output

libbpf-tools/mountsnoop.bpf.c, libbpf-tools/mountsnoop.c, libbpf-tools/mountsnoop.h
Do the same thing of bcc commit 60ebaf47347a ("tools/mountsnoop: Support fsopen(2), fsmount(2), fsconfig(2), move_mount(2)")
$ sudo ./mountsnoop
COMM             PID     TID     MNT_NS      CALL
fsmount          431216  431216  4026531841  fsopen("ext4", 0x0) = 5
fsmount          431216  431216  4026531841  fsconfig(5, "FSCONFIG_SET_FLAG", "rw", "", 0) = 0
fsmount          431216  431216  4026531841  fsconfig(5, "FSCONFIG_SET_STRING", "source", "/dev/loop0", 0) = 0
fsmount          431216  431216  4026531841  fsconfig(5, "FSCONFIG_CMD_CREATE", "", "", 0) = 0
fsmount          431216  431216  4026531841  fsmount(5, "0x0", "MOUNT_ATTR_RDONLY") = 6
fsmount          431216  431216  4026531841  move_mount(6, "", AT_FDCWD, "./tmp-dir/", "") = 0
fsmount          431216  431216  4026531841 …
=> libbpf-tools/mountsnoop: Support fsopen,fsconfig,fsmount,move_mount syscalls

tools/profile.py
Add additional information and change format of backtrace
- add symbol base offset, dso name
- symbol and dso info is included if it's available in target binary
- changed format: ADDR [SYMBOL+OFFSET] (MODULE)
before:
```
[unknown]
_PyDict_GetItem_KnownHash
[unknown]
[unknown]
[unknown]
[unknown]
_PyObject_MakeTpCall
_PyObject_CallFunction_SizeT
[unknown]
_PyEval_EvalFrameDefault
PyEval_EvalCode
[unknown]
[unknown]
_PyRun_SimpleFileObject
_PyRun_AnyFileObject
Py_RunMain
Py_BytesMain
__libc_start_call_main
__libc_start_main_impl
_start
-                python3 (384002)
1
[unknown]
[unknown]
[unknown]
[unknown]
[unknown]
[unknown]
-                gnome-shell (2302)
1
```
After:
```
0xffffffff92d5048e apparmor_file_permission+0x4e
0xffffffff92d5048e apparmor_file_permission+0x4e …
```
=> tools/profile: Add additional information to backtrace for -v option

tools/mountsnoop.py
fsmount(2) syscall 'flags' parameter only could be zero or FSMOUNT_CLOEXEC right now.
=> tools/mountsnoop: Fix fsmount printing wrong flags

man/man8/numasched.8, tools/numasched.py, tools/numasched_example.txt
Tasks frequently switch between NUMA, often resulting in poor performance.
programs running on the same NUMA will have better performance (usually at the memory level). If processes are migrating between different CPUs and these CPUs belong to different NUMAs, this tool provides an effective means of tracing to optimize the program or configuration.
```
$ numactl --hardware
available: 4 nodes (0-3)
node 0 cpus: 0 - 23
node 1 cpus: 24 - 47
node 2 cpus: 48 - 71
node 3 cpus: 72 - 95
```
```
$ sudo ./numasched.py
Tracing task NUMA switch...
TIME     PID      SRC_NID     DST_NID  COMM
```
```
$ taskset -c 1 yes >/dev/null &
$ taskset -p 0x1000000 $(pidof yes)
$ taskset -p 0x1000000000000 $(pidof yes)
```
```
$ sudo ./numasched.py
Tracing task NUMA switch...
TIME     PID      SRC_NID …
```
=> tools: add numasched: trace task switch between NUMA

src/cc/syms.h
~ModulePath() does `if (fd_ > 0) close fd_;`. But ModulePath constructor has early return codepath for `!enter_ns` which does not initialize `fd_`.
So `fd_` can potentially have junk value. That junk value could be any FD downstream. bcc cannot be closing random FDs.
See https://dxuuu.xyz/flaky.html for a writeup for the implications.
=> syms: Initialize ModulePath::fd_ to invalid FD

src/cc/frontends/clang/b_frontend_action.cc, src/cc/json_map_decl_visitor.cc
The following is the error message:
```
/home/yhs/work/bcc/src/cc/frontends/clang/b_frontend_action.cc: In member function
‘bool ebpf::BTypeVisitor::VisitBinaryOperator(clang::BinaryOperator*)’:
/home/yhs/work/bcc/src/cc/frontends/clang/b_frontend_action.cc:1383:64: error:
no matching function for call to ‘clang::FieldDecl::getBitWidthValue(clang::ASTContext&)’
1383 |             uint64_t sz = F->isBitField() ? F->getBitWidthValue(C) : C.getTypeSize(F->getType());
|                                             ~~~~~~~~~~~~~~~~~~~^~~
```
This is due to upstream llvm patch:
https://github.com/llvm/llvm-project/pull/122289
This patch fixed the above compilation error.
=> Fix llvm20 compilation error

debian/changelog
* Support for kernel up to 6.12
* Add new bcc tool numasched
* syms: Initialize ModulePath::fd_ to invalid FD
* libbpf-tools/memleak: Fix off-by-one error
* libbpf-tools/slabratetop: Fix failed to create kprobe error
* libbpf_tools/profile: Support PID namespace mapping
* libbpf-tools/mountsnoop: Support fsopen,fsconfig,fsmount,move_mount syscalls
* tools/oomkill: get application level stack trace
* tools/profile: Add additional information to backtrace
* tools/mountsnoop: Fix fsmount printing wrong flags
* tools/compactsnoop: Add aarch64 support
* doc update, other bug fixes and tools improvement.
=> Update debian changelog for release v0.33.0

tools/cpuunclaimed.py
python methods `getpid, system` from os  module unused at tools/cpuunclaimed
=> tools/cpuunclaimed: Remove unused python methods

tools/opensnoop.py, tools/opensnoop_example.txt
When a program creates a file with mode=0000, it cannot even access the file
itself. It would be helpful if we could track the mode value. so we can know
who did it.
Example:
open("a.txt", O_WRONLY | O_EXCL | O_CREAT, 0000);
Then:
$ ls -l a.txt
----------. 1 rongtao rongtao 0 Jan 24 09:07 a.txt
$ cat a.txt
cat: a.txt: Permission denied
$ sudo ./opensnoop.py -e
PID    COMM               FD ERR FLAGS    MODE PATH
673067 open                3   0 00000301 0000 a.txt
^^^^
=> tools/opensnoop: Display mode for -e, --extended_fields

tools/opensnoop.py
O_TMPFILE = 020200000 = __O_TMPFILE | O_DIRECTORY
If flag contains only O_DIRECTORY, the mode value is invalid. The mode value is valid only when flag contains both __O_TMPFILE and O_DIRECTORY.
For example, 02204000 only contains __O_TMPFILE or O_DIRECTORY, will get bad random mode value:
$ sudo ./opensnoop.py -e
PID    COMM               FD ERR FLAGS    MODE PATH
1325   in:imjournal      108   0 02000101 146720225 /var/lib/rsyslog/imjournal.state.tmp
^
__O_TMPFILE
927848 cgroupify           5   0 02204000 22343344131 .
^
O_DIRECTORY
Fix: commit e80ad4d859d4 ("tools/opensnoop: Display mode for -e, --extended_fields (#5196)")
=> tools/opensnoop: Fix bad mode value

libbpf-tools/opensnoop.bpf.c, libbpf-tools/opensnoop.c, libbpf-tools/opensnoop.h
Do the same thing of [1] and add tracepoint/syscalls/sys_enter_openat2 support.
Link: https://github.com/iovisor/bcc/commit/e80ad4d859d4f6bf16709cb664c97f41e3136558 [1]
=> libbpf-tools/opensnoop: Display mode for extended fields

examples/tracing/disksnoop.py
Fix issue #5124 "Exception:Failed to attach BPF program ..." by attaching the function blk_mq_end_request
`blk_account_io_done` became inline function since kernel v5.16 and `blk_account_io_done` has been taken off since v6.4. With this change, only when the code runs on a legacy kernel these `*_io_done` functions will be attached, otherwise it goes for `blk_mq_end_request`.
=> examples/tracing/disksnoop.py: Fix kprobe attaching failure

libbpf-tools/softirqs.bpf.c
Should use log2l.
When there is a function call, R1 unbounded memory access problem occurs, so inline is used.
=> libbpf-tools/softirqs: Fix logarithmic calculation issue

src/lua/CMakeLists.txt
LuaJIT does not generate bytecode deterministically by default, which makes the build of bcc-lua unreproducible. However, support for deterministic bytecode was added to LuaJIT some time ago. This change enables it for bcc-lua.
- https://bugzilla.suse.com/show_bug.cgi?id=1236871
- https://github.com/LuaJIT/LuaJIT/issues/1008
- https://reproducible-builds.org/
=> bcc-lua: enable deterministic bytecode generation

docs/tutorial_bcc_python_developer.md, examples/tracing/setuid_monitor.py, examples/tracing/setuid_monitor_example.txt, examples/tracing/urandomread.py
Fix issue #5211 
Add new examples/tracing/setuid_monitor.py as a demonstration of the usage of `TRACEPOINT_PROBE`, for examples/tracing/urandomread.py does not work since kernel 5.18 in which `tracepoint/random/urandom_read` [has been removed](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=99dea2c664d7bc7e4f6f6947182d0d365165a998).
The tutorial and document are modified accordingly.
Note: examples/tracing/urandomread.py is kept because some long-term kernel versions are still in maintenance, so the code still works.
=> New examples/tracing/setuid_monitor.py: Fix #5211

libbpf-tools/klockstat.bpf.c, libbpf-tools/klockstat.c
The klockstat BPF code contains a hard-coded offset (of 4) for the
captured stack entries, which is supposed to get rid of the topmost
entries that are just locking functions. However, when running the
klockstat tool on RHEL, this offset is not correct, leading to output
like the following:
Caller  Avg Wait    Count   Max Wait   Total Wait
mutex_lock+0x5    1.1 us        3     1.8 us       3.2 us
mutex_lock+0x5    825 ns        5     1.6 us       4.1 us
mutex_lock+0x5    1.1 us        4     1.5 us       4.3 us
Caller  Avg Hold    Count   Max Hold   Total Hold
mutex_lock+0x5   18.0 ms        3    23.0 ms      54.0 ms
mutex_lock+0x5    1.7 ms       15     2.2 ms      25.1 ms
mutex_lock+0x5    1.7 ms       15     2.2 ms      25.1 ms
To fix this, add logic in the userspace component of the …
=> libbpf-tools/klockstat: Search for correct stack offset when printing

tools/tcpdrop.py
I was attempting to use `tcpdrop` on a system where this "warning" was being printed. I waited for a while as the program seemed to be doing something. But it actually wasn't. I think this is really an error that should exit the tool. But I might be wrong.
=> tcpdrop: tcp_drop() not findable is an error.

libbpf-tools/sigsnoop.c
For example:
$ sudo ./sigsnoop --name
TIME     PID     COMM             SIG          TPID    RESULT
10:09:34 431623  SIGRTMAX         SIGRTMIN+15  431623  0
10:09:36 0       swapper/6        SIGRTMIN     2610    0
10:13:46 0       swapper/11       SIGRTMIN     2610    0
10:13:47 432111  SIGRTMAX         SIGRTMAX-10  432111  0
The test program:
```c
#include <stdio.h>
#include <signal.h>
#include <unistd.h>
#include <errno.h>
#define LIBC_SIGRTMIN		(__libc_current_sigrtmin())
#define LIBC_SIGRTMAX		(__libc_current_sigrtmax())
void handler(int sig, siginfo_t *si, void *context)
{
printf("Received signal %d with value %d\n", sig, si->si_value.sival_int);
}
int main(int argc, char *argv[])
{
struct sigaction sa;
sigset_t mask;
int rtoff = 20;
printf("SIGRTMIN = %d, LIBC_SIGRTMIN = %d\n", …
```
=> libbpf-tools: signoop: Support real-time signals

libbpf-tools/statsnoop.bpf.c, libbpf-tools/statsnoop.c, libbpf-tools/statsnoop.h
Display the system call name is more helpful for analysis, like:
$ sudo ./statsnoop
PID     COMM                 RET  ERR  SYSCALL    PATH
83459   code                 -1   2    statx      /home/rongtao/.config/Code/User/tasks.json
2807    terminator           0    0    newfstatat /usr/share/icons
2807    terminator           -1   2    newfstatat /home/rongtao/.local/share/flatpak/exports/share/pixmaps
2807    terminator           -1   2    newfstatat /usr/local/share/pixmaps
2807    terminator           0    0    newfstatat /usr/share/pixmaps
83445   code                 -1   2    statx      /home/sdb/Git/5.10.13/.vscode/c_cpp_properties.json
2525    pool                 0    0    newfstatat /etc/krb5.conf
88285   ls                   0    0    statfs     /sys/fs/selinux
88285   ls …
=> libbpf-tools/statsnoop: Display syscall name

libbpf-tools/klockstat.bpf.c, libbpf-tools/klockstat.c, libbpf-tools/klockstat.h
The klockstat tool is useful to debug stalls on kernel locks, but when
tracking the RTNL lock, a lot of the stack traces will just show
rtnetlink_rcv_msg() or netlink_dump() as the callers that take the lock.
It is not possible to tell from the stack trace which netlink command is
being executed that caused the lock to be taken, which makes it harder
to debug.
To help with this, add probes to those two netlink functions that
capture the nlmsg_type and store it in a hashmap keyed on the current
tid. When accounting a lock operation, store the nlmsg type along with
the max_comm.
On the userspace side, print the message type if it is set. Parse the
vmlinux BTF to turn the values into the constants names for better
readability. This gives output like the following:
Caller  Avg Wait    Count …
=> libbpf-tools/klockstat: Track netlink message types when taking locks

libbpf-tools/statsnoop.bpf.c, libbpf-tools/statsnoop.c, libbpf-tools/statsnoop.h
Added support for fstat system calls, and resolve file names and paths from fd and dirfd in user mode.
Userspace test code:
dirfd = openat(AT_FDCWD, "./", O_RDONLY | O_CLOEXEC);
fstatat(dirfd, argv[0], &buf, AT_SYMLINK_NOFOLLOW);
fstatat(dirfd, "/etc/os-release", &buf, AT_SYMLINK_NOFOLLOW);
fd = open("/etc/os-release", O_RDONLY);
fstat(fd, &buf);
fstat(AT_FDCWD, &buf);
Tracing:
Before:
$ sudo ./statsnoop -s
PID     COMM                 RET  ERR  SYSCALL    PATH
25719   fstatat              0    0    newfstatat ./fstatat        <no cwd>
25719   fstatat              0    0    newfstatat /etc/os-release
< couldn't tracing fstat(2) >
This patch:
$ sudo ./statsnoop -s
PID     COMM                 RET  ERR  SYSCALL    PATH
26794   fstatat              0    0    newfstatat …
=> libbpf-tools: statsnoop: Support fstat(2) and parse fd/dirfd in userspace

libbpf-tools/memleak.c
Add --stack-storage-size and --perf-max-stack-depth options
=> libbpf-tools/memleak: Add options to adjust stack map size

CMakeLists.txt
With CMake 4 the minimum support version is 3.5, and since the current minimum version we set is 2.8.12, it will fail with the following message:
```
CMake Error at CMakeLists.txt:3 (cmake_minimum_required):
Compatibility with CMake < 3.5 has been removed from CMake.
Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
to tell CMake that the project requires at least <min> but has been updated
to work with policies introduced by <max> or earlier.
Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
```
However, instead of bumping the minimum version requirement to 3.5, bump to a slightly higher 3.12 instead to be consistent with `examples/usdt_sample/`.
Also update `cmake_policy()` calls due to this change, dropping CMP0057 since the OLD behavior is …
=> Bump CMake minimum version to 3.12

libbpf-tools/biosnoop.bpf.c
tracepoint block_rq_insert and block_rq_issue changed from 5.10.137, not 5.11
same as merged pr: [libbpf-tools:Fix bitesize dependency on kernel versio](https://github.com/iovisor/bcc/pull/5234)
[v5.10.137 include/trace/events/block.h](https://elixir.bootlin.com/linux/v5.10.137/source/include/trace/events/block.h)
[v5.10.136 include/trace/events/block.h](https://elixir.bootlin.com/linux/v5.10.136/source/include/trace/events/block.h)
from:
```
DEFINE_EVENT(block_rq, block_rq_insert,
TP_PROTO(struct request_queue *q, struct request *rq),
TP_ARGS(q, rq)
);
DEFINE_EVENT(block_rq, block_rq_issue,
TP_PROTO(struct request_queue *q, struct request *rq),
TP_ARGS(q, rq)
);
```
to:
```
DEFINE_EVENT(block_rq, block_rq_insert,
TP_PROTO(struct request *rq),
TP_ARGS(rq)
);
DEFINE_EVENT(block_rq, …
```
=> libbpf-tools:Fix biosnoop dependency on kernel version

tools/sofdsnoop.py
BPF compiler fails to compile `min` with error:
cannot call non-static helper function
Related fo https://github.com/iovisor/bcc/issues/5241
=> tools/sofdsnoop: implement custom min to avoid non-static

tools/tcpdrop.py, tools/tcpdrop_example.txt
This commit adds support for dumping TCP drop reasons. It maps these reasons
to human-readable strings, making it easier to understand why TCP packets
are dropped. In cases where the drop reason is not supported, 'NOT_SPECIFIED'
will be displayed.
=> tcpdrop: add support for dumping TCP drop reasons

libbpf-tools/tcptracer.bpf.c
The `ctx` parameter is unused in both `enter_tcp_connect()` and `exit_tcp_connect()`. Consider removing it to clean up the code.
Fixes：[#5229](https://github.com/iovisor/bcc/issues/5229)
=> libbpf-tools/tcptracer: Remove unused parameter 'ctx'

libbpf-tools/statsnoop.bpf.c
Forgot check dirfd in [1].
Link: https://github.com/iovisor/bcc/commit/55f5bd3ac43fe47f51b0b98ea0dbcb142e3b788e [1]
=> libbpf-tools: statsnoop: Missing dirfd check

libbpf-tools/readahead.bpf.c, libbpf-tools/readahead.c
Since Linux 5.15, `mark_page_accessed` is no longer called in `filemap_read`, which causes increased counts of unused page cache.
(For more detail, please refers to `mark_page_accessed` in Linux Patch1 and `filemap_read` in Linux Patch2.)
This patch attempts to attach `mark_accessed` to `folio_mark_accessed` if it is available; otherwise, it falls back to using `mark_page_accessed`.
Linux Patch1: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=76580b65 
Linux Patch2: https://github.com/torvalds/linux/commit/6020c204be997e3f5129839ff9c801800fb4336e#diff-6f046052d9af59ceb36616faffd8b1920c28195619803cfdb25df7271200ba5e
=> libbpf-tools/readahead: Fix low page usage count since v5.15

libbpf-tools/syscall_helpers.c
Display syscall name on loongarch64, instead of fallback to '[unknown: %u]'.
=> libbpf-tools: syscall_helpers.c: support loongarch64 and add more generic syscall

src/python/bcc/__init__.py
When the event name is too long, such as p:uprobes/p__proc_124566_root_usr_lib64_libruby_so_3_2_2_0xda3ac_124566_bcc_131967, an error will occur when executing the write function of function create_probe_event.
The kernel error path is
probes_write
trace_parse_run_command
create_or_delete_trace_uprobe
trace_uprobe_create
trace_probe_create
__trace_uprobe_create
traceprobe_parse_event_name
else if (len >= MAX_EVENT_NAME_LEN)
Requires less than 64 bytes.
=> libbpf: Fix event name too long error

libbpf-tools/llcstat.bpf.c, libbpf-tools/llcstat.c, libbpf-tools/llcstat.h
Rename key_info to llcsta_key_info, at the same time, in order to ensure the consistency of key-value naming, rename value_info to llvstat_value_info.
$ make
...
BPF      llcstat.bpf.o
In file included from llcstat.bpf.c:7:
./llcstat.h:13:8: error: redefinition of 'key_info'
13 | struct key_info {
|        ^
arm64/vmlinux.h:140310:8: note: previous definition is here
140310 | struct key_info {
|        ^
llcstat.bpf.c:27:6: error: no member named 'cpu' in 'struct key_info'
27 |         key.cpu = bpf_get_smp_processor_id();
|         ~~~ ^
llcstat.bpf.c:28:6: error: no member named 'pid' in 'struct key_info'
28 |         key.pid = pid_tgid >> 32;
|         ~~~ ^
llcstat.bpf.c:30:7: error: no member named 'tid' in 'struct key_info'
30 |                 key.tid = (u32)pid_tgid;
| …
=> libbpf-tools: llcstat: Fix error: redefinition of 'key_info' on aarch64

libbpf-tools/hardirqs.bpf.c, libbpf-tools/hardirqs.c, libbpf-tools/hardirqs.h
Combine the previous count and time into one,
and increase CPU independent statistics and maximum interrupt time
```
Before:
./hardirqs
Tracing hard irq event time... Hit Ctrl-C to end.
^C
HARDIRQ                    TOTAL_usecs
enp0s3                             254
snd_intel8x0                       368
./hardirqs -C
Tracing hard irq events... Hit Ctrl-C to end.
^C
HARDIRQ                    TOTAL_count
enp0s3                              14
ata_piix                             2
After:
./hardirqs
Tracing hard irq event time... Hit Ctrl-C to end.
^C
HARDIRQ                    TOTAL_count TOTAL_usecs MAX_usecs
ata_piix                             2          32        21
enp0s3                              19         318        42
./hardirqs -C
Tracing hard irq event time... Hit Ctrl-C to …
```
=> hardirqs: Optimize output information and increase CPU display

src/cc/common.cc
$ make
...
[  1%] Building CXX object src/cc/CMakeFiles/bpf-static.dir/common.cc.o
/home/rongtao/Git/bcc/src/cc/common.cc: In function ‘ebpf::field_kind_t ebpf::_get_field_kind(const string&, std::__cxx11::string&, std::__cxx11::string&, int*)’:
/home/rongtao/Git/bcc/src/cc/common.cc:178:59: error: no matching function for call to ‘std::__cxx11::basic_string<char>::replace(long unsigned int, long unsigned int, std::__cxx11::basic_string<char>&, int)’
field_name.replace(pos1 + 1, pos2 - pos1 - 1, dim, 0);
^
In file included from /usr/include/c++/7.3.0/string:52:0,
from /usr/include/c++/7.3.0/bits/locale_classes.h:40,
from /usr/include/c++/7.3.0/bits/ios_base.h:41,
from /usr/include/c++/7.3.0/ios:42,
from /usr/include/c++/7.3.0/istream:38,
from /usr/include/c++/7.3.0/fstream:38,
from …
=> Adapt to gcc 7.3.0 std::string.replace()

debian/changelog
* Support for kernel up to 6.13
* Bump cmake minimum version to 3.12
* statsnoop: Display syscall name with -s
* readahead: Fix incorrect page accessed count since kernel 5.16
* libbpf-tools/opensnoop: Add new fields
* libbpf-tools: hardirqs/softirqs: Fix logarithmic calculation issue
* libbpf-tools/hardirqs: have better default display and add CPU column
* libbpf-tools/klockstat: Better stack dump and summary info
* libbpf-tools/sigsnoop: Support real-time signals and thread comm
* libbpf-tools/statsnoop: Support more syscalls
* libbpf-tools/memleak: Some fixes and better messages
* tools/opensnoop: Add new fields and fix bad mode value
* tools/profile: Prioritize using the cpu-cycles hardware event
* tools/tcpdrop: Add support for dumping TCP drop reasons
* Fix event name too long error …
=> Update debian changelog for release v0.34.0

README.md, src/cc/libbpf.c, src/python/bcc/__init__.py, src/python/bcc/libbcc.py, tools/mptcpify.py, tools/mptcpify_example.txt
Multipath TCP (MPTCP) serves as an enhancement to the conventional TCP
protocol, enabling a single transport-layer connection to leverage
multiple network interfaces. This capability makes MPTCP advantageous
for applications requiring bandwidth consolidation, seamless failover
mechanisms, and more robust connectivity solutions.
Linux kernel starts to support MPTCP since v5.6, and it provides a
fmod_ret interface 'update_socket_protocol' to force applications using
MPTCP instead of TCP without modifyiing its code.
So these patches provide a tool named 'mptcpify' which can achieve this.
Using python-BCC is a more easy way for future development, so it is so
important to support 'fmod_ret' in python-BCC.
The first patch is suggested by Yonghong:
‘’‘
On Sun, 2024-08-25 at 21:05 -0700, …
=> Python-BCC: support fmod_ret attaching method, and add a useful tool for mptcp

.github/workflows/publish-build-containers.yml
The ubuntu 20.04 and fedora 38 are not supported any more. So let us upgrade to new releases for CI testing.
=> Use ubuntu 24.04 and fedora 41 for CI testing

src/python/bcc/__init__.py
When executing the bcc script, there exists the following fatal error on LoongArch:
$ sudo /usr/share/bcc/tools/filetop
In file included from <built-in>:4:
In file included from /virtual/include/bcc/helpers.h:54: In file included from arch/loongarch/include/asm/page.h:9: In file included from arch/loongarch/include/asm/addrspace.h:16: arch/loongarch/include/asm/loongarch.h:13:10: fatal error: 'larchintrin.h' file not found
13 | #include <larchintrin.h>
|          ^~~~~~~~~~~~~~~
git log shows that it has been fixed in the commit 8aa9f7072d53 ("Fix larchintrin.h not found error for loongarch64"), but the same error still exists in the latest mainline bcc.
This is because both clang_include_path_str and gcc_include_path_str are False due to subprocess.check_output() …
=> bcc: import subprocess in __init__.py

tools/biosnoop.py
The code to support the block_io tracepoints failed to update some code that is used with the -P option. That code changed the second argument of __trace_req_completion from 'req' to 'key', but in the "#ifdef INCLUDE_PATTERN" block, the use of 'req' remained unchanged. Of course, 'key' should be use here too.
It fixes the following error:
$ biosnoop -P
/virtual/main.c:213:24: error: use of undeclared identifier 'req'
213 |         data.pattern = req->__sector == *sector ? SEQUENTIAL : RANDOM;
|                        ^
/virtual/main.c:216:19: error: use of undeclared identifier 'req'
216 |     last_sector = req->__sector + data.len / 512;
|                   ^
2 errors generated.
File "/usr/share/bcc/tools/biosnoop", line 335, in <module>
b = …
=> tools/biosnoop: Fix biosnoop pattern option

INSTALL.md
Attached `bash` block has no direct references to `xenial`. Minor docs clean-up.
=> Delete outdated comment (INSTALL.md; Ubuntu)

tests/python/test_clang.py, tests/python/test_histogram.py
When running on kernels compiled with GCC 11.4, the `py_test_clang` and `py_test_histogram` tests fail because the `finish_task_switch` function changed to `finish_task_switch.isra.0`.
- Output of `cat /proc/kallsyms | grep finish_task_switch`:
```
0000000000000000 t finish_task_switch.isra.0
0000000000000000 t finish_task_switch.isra.0.cold
```
This problem was reported in [PR #3315](https://github.com/iovisor/bcc/pull/3315). This PR applies the same fix to `py_test_clang` and `py_test_histogram`.
<details><summary>Output of `sudo ctest -R "py_test_clang|py_test_histogram" --output-on-failure` before the fix</summary>
```
Test project /opt/bcc/build
Start 16: py_test_clang
1/2 Test #16: py_test_clang ....................***Failed   64.85 sec
................./virtual/main.c:2:1: error: …
```
=> Fix tests to support finish_task_switch.isra.* suffix

CMakeLists.txt
Configuring bcc in a build directory that is not in the source subtree causes the following warning:
warning: Not a git repository. Use --no-index to compare two paths outside a working tree
This is caused by a subcommand running in the current working directory. Run it in the source directory instead.
Fixes: 3df26a542f80 ("cmake: sync submodule libbpf when do cmake.")
=> Fix running cmake outside of the source subtree

src/cc/frontends/clang/kbuild_helper.cc
On powerpc, many tools fail with an "invalid output constraint '=YZ<>' in asm" error. This come from the following code in arch/powerpc/include/asm/asm-compat.h:
Because CONFIG_CC_IS_CLANG is not defined in the headers, we end up using a constraint that is not understoog by clang.
Defining CONFIG_CC_IS_CLANG in KBuildHelper::get_flags() fixes this error and possibly other similar error.
Suggested-by: Shung-Hsi Yu <shung-hsi.yu@suse.com>
=> clang: Define DCONFIG_CC_IS_CLANG in KBuildHelper::get_flags() (#5172)

tests/cc/test_bpf_table.cc
The test for `bpf_stack_id` was failing due to the system being unable to locate `libc.so.6`. Upon investigation using `strace`, the following error was observed:
newfstatat(AT_FDCWD, "/lib/x86_64-linux-gnu/libc.so.6", 0x7ffdcd475420, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/lib64/libc.so.6", 0x7ffdcd475420, 0) = -1 ENOENT (No such file or directory)
This issue occurs because `libc.so.6` was not found in the expected locations. To resolve this, the location of `libc.so.6` has been added to the custom Yocto images. It is now accessible at: /lib/libc.so.6
This change ensures proper linking and access to `libc.so.6` during runtime in the Yocto custom image.
=> bcc: Fix for test bpf_stack_id when running on custom image in yocto

libbpf-tools/biotop.c, libbpf-tools/map_helpers.c, libbpf-tools/map_helpers.h, libbpf-tools/tcpconnect.c
Replace biotop's two-loop map lookup and deletion with a single dump_hash
call, using bpf_map_lookup_and_delete_batch for atomic processing to
prevent potential concurrency issues. Simplify code using dump_hash.
=> libbpf-tools/biotop: Use dump_hash for map processing

cmake/CmakeUninstall.cmake.in
exec_program() is deprecated since 3.28, see: 'cmake --help-policy CMP0153', and cmake support execute_process() since CMake 2.6.0.
$ sudo make uninstall
....
-- Uninstalling /usr/share/bcc/examples/networking/distributed_bridge/tunnel.py
CMake Warning (dev) at /home/rongtao/Git/bcc/build/CmakeUninstall.cmake:14 (exec_program):
Policy CMP0153 is not set: The exec_program command should not be called.
Run "cmake --help-policy CMP0153" for policy details.  Use the cmake_policy
command to set the policy and suppress this warning.
Use execute_process() instead.
Call Stack (most recent call first):
/home/rongtao/Git/bcc/build/CmakeUninstall.cmake:28 (UninstallManifest)
This warning is for project developers.  Use -Wno-dev to suppress it.
=> uninstall: use execute_process() instead of exec_program()

.github/actions/build-container/action.yml, .github/workflows/bcc-test.yml, .github/workflows/publish-build-containers.yml, docker/build/Dockerfile.fedora, docker/build/Dockerfile.ubuntu
Currently CI does not work since ubuntu 20.04 is end-of-service.
This patch upgraded ubuntu 20.04 to 24.04.
=> ci: Upgrade ubuntu 20.04 to 24.04

tools/xfsslower.py
This patch fixes an issue in xfsslower where write operation traces are overwritten when files are opened with O_SYNC flag. Currently, when a file is opened with O_SYNC, xfsslower fails to track write operations and only shows sync operations.
For example, when testing XFS I/O using this fio command:
[xxx@yyy ~]# fio --name=dsync-write --group_reporting --ioengine=psync --filename=./test --direct=1 --sync=1 --rw=write --bs=32k --size=4G --iodepth=1 --thread=1 --numjobs=1
And tracing with:
[xxx@yyy ~]# /usr/share/bcc/tools/xfsslower 0
The output only shows fsync operations without any write traces:
14:57:16 fio 189921 S 0 0 0.00 test
14:57:16 fio 189921 S 0 0 0.00 test
14:57:16 fio 189921 S 0 0 0.04 test
The root cause is that for O_SYNC files, xfs_file_write_iter calls xfs_file_fsync …
=> Fix the issue where xfsslower cannot track write operations on files opened with the O_SYNC flag

docker/build/Dockerfile.fedora, docker/build/Dockerfile.ubuntu
For ubuntu 24.04, setuptools is not installed by default. So let us install it during Dockerfile.ubuntu preparation. Also, pip3 installation is replaced with package installation so we do not need venv any more.
=> ci: Install python3-setuptools for ubuntu 24.04

src/cc/frontends/clang/b_frontend_action.cc, src/cc/frontends/clang/b_frontend_action.h
When pointer is dereferenced, it ends up with bpf_probe_read_kernel(). However, the data type of source and destination might differ in size for genParamIndirectAssign() and this can cause endianness issue.
Fix the pointer dereference by adjusting offsets of source and destination, when there is a size disparity. Also, as a small optimization, perform memset() only on the required destination part, considering the endianness.
* This is specifically needed for the genParamIndirectAssign(), where size disparity could happen. With the patch, the code generated is shown below:
__attribute__((section(".bpf.fn.syscall__kill")))
int syscall__kill(struct pt_regs *ctx)
{
struct pt_regs * __ctx = (void *)ctx->gprs[2];
int tpid; BCC_PROBE_READ(&tpid, &__ctx->orig_gpr2, bpf_probe_read_kernel);
int …
=> clang: Fix pointer dereference on big-endian machines

libbpf-tools/opensnoop.bpf.c, libbpf-tools/opensnoop.c, libbpf-tools/opensnoop.h
Like commit [1], support display fullpath, for example:
$ cd /var/tmp/
$ touch a.out
$ sudo ./opensnoop -F
PID    COMM              FD ERR PATH
106779 touch              3   0 /var/tmp/a.out
^^^^^^^^^^^^^^
Link: https://github.com/iovisor/bcc/commit/c110a4dd0c8f
=> libbpf-tools: opensnoop: add full-path argument -F

tools/opensnoop.py
Each loop iteration of dentry will send out an event [1], which is too much and unnecessary.
1. Use ringbuf instead of perf buffer. Because the event transmitted at one time is large and the stack space is insufficient, the reservation function of ringbuf is used. And, ringbuf is wildly supported.
2. Each full-path transmits only one event, eliminating unnecessary events. It's good for further developement.
[1] https://github.com/iovisor/bcc/commit/c110a4dd0c8f
Cc: Yonghong Song <yonghong.song@linux.dev>
=> tools/opensnoop: one event is enough for full-path

libbpf-tools/Makefile, libbpf-tools/filelife.bpf.c, libbpf-tools/filelife.c, libbpf-tools/filelife.h, libbpf-tools/opensnoop.bpf.c, libbpf-tools/opensnoop.c, libbpf-tools/opensnoop.h, libbpf-tools/path_helpers.bpf.h, libbpf-tools/path_helpers.c, libbpf-tools/path_helpers.h
There will be many programs that need to get the current working directory
or full-path of file, such as opensnoop, which is already supported.
and other tools like filelife/filetop need it too.
Therefore, it will be helpful to separate the bpf_getcwd function from
opensnoop.bpf.c as a public helper function.
Add functions:
1. bpf_dentry_full_path(): Get the full-path based on the dentry and
vfsmount.
2. bpf_getcwd(): Get the full-path of the current working directory.
3. print_full_path(): Assembling full-path in user space.
Add structures:
1. struct full_path {}: Record the absolute path.
To support full-path, the following operations are performed:
1. First, to support the transmission of larger data, perf-buffer is
replaced with ring-buff.
2. Then, before this patch, events are …
=> libbpf-tools: introduce path helpers and filelife support full-path

tools/filetop.py
Add support to filetop to filter by directory.
Signed-off-by: Srivathsa Dara <srivathsa.d.dara@oracle.com>
=> tools/filetop: Add directory filter

examples/networking/net_monitor.py
Corrects spelling errors in comments:
- "retrieeve" → "retrieve"
- "entires" → "entries"
- "confiremd" → "confirmed"
These minor fixes improve code readability and maintain documentation quality in the BCC example.
=> net_monitor: fix typos in comments

libbpf-tools/filelife.bpf.c
The process that creates the file and the process that deletes the file may be two completely different processes, and their cwds are different. We get the file name from the file dentry and concatenate the cwd to create the full-path. If we use the dentry name of the deleted file + the cwd-dentry of the process that created the file, we will get an incorrect full-path. For example:
$ realpath .
/home/sda/git-repos/iovisor/bcc/libbpf-tools
(1) correct full-path
$ touch a.out               cwd_dentry = /home/sda/git-repos/iovisor/bcc/libbpf-tools
$ cd ..
$ rm libbpf-tools/a.out     dentry = a.out
(2) wrong full-path
$ touch libbpf-tools/a.out  cwd_dentry = /home/sda/git-repos/iovisor/bcc/
$ cd libbpf-tools/
$ rm a.out                  dentry = a.out
$ sudo ./filelife -F
Tracing the …
=> libbpf-tools/filelife: Fix wrong full-path

tests/python/test_tools_memleak.py
Fixes tools_memleak.py which is getting failed due to "**c_src_full = os.path.dirname(sys.argv[0]) + os.path.sep + c_src**" is giving  "**/'test_tools_memleak_leaker_app.c**".
=> bcc:  Fix for test tools_memleak.py

libbpf-tools/klockstat.bpf.c, libbpf-tools/klockstat.c
The klockstat tool fallback on kprobes when fentries are not available, but the fallback doesn't work on debug kernel (CONFIG_DEBUG_LOCK_ALLOC enabled).
Attach kprobes to the debug locking functions (*_nested) when they exists as is done with the fentry code.
=> libbpf-tools/klockstat: Allows kprobe fallback to work with lock debugging

libbpf-tools/ksnoop.bpf.c
On fedora42, llvm 20.1.7, kernel 6.15.4-200.fc42.x86_64 has two verifier errors. Test with command:
$ sudo ./ksnoop trace do_sys_openat2
; last_stack_depth = stack_depth - 1; @ ksnoop.bpf.c:102
108: (bc) w3 = w6                     ; frame1: R3_w=scalar(id=5,smin=smin32=0,smax=umax=smax32=umax32=14,var_off=(0x0; 0xf)) R6=scalar(id=5,smin=smin32=0,smax=umax=smax32=umax32=14,var_off=(0x0; 0xf))
109: (04) w3 += -1                    ; frame1: R3_w=scalar(smin=0,smax=umax=0xffffffff,smin32=-1,smax32=13,var_off=(0x0; 0xffffffff))
110: (bc) w4 = w3                     ; frame1: R3_w=scalar(id=6,smin=0,smax=umax=0xffffffff,smin32=-1,smax32=13,var_off=(0x0; 0xffffffff)) R4_w=scalar(id=6,smin=0,smax=umax=0xffffffff,smin32=-1,smax32=13,var_off=(0x0; 0xffffffff))
111: (54) w4 &= 255 …
=> libbpf-tools: ksnoop: Fix two invalid access to map value

src/python/bcc/exec.py, tools/opensnoop.py, tools/syscount.py
For short-lived processes, specify '-p pid' is difficult to trace. Add support  for executing a program and tracing it. When the newly child process exits, tool itself exists subsequently.
Added to syscount/opensnoop tools this time, other tools as needed.
For example:
`
./syscount.py -i 1 --exec ls -l /tmp
`
@yonghong-song Please take a look, thanks.
=> Add support for executing a program and tracing it

tools/biolatency.py, tools/biosnoop.py, tools/biotop.py
When support for block_io_* tracepoint was added, it used attach_tracepoint() since it was closer to the existing code that attached to kprobes. However, that meant we have to rely on a local prototype of the args structure and  the tool can be broken by a change of the tracepoints format, which is what happens with kernel commit aa6ff4eb7c10d ("block: Add ioprio to block_rq tracepoint") which added a new argument to block tracepoints.
Replace attach_tracepoint() by TRACEPOINT_PROBE() so we don't have to deal with the tracepoint format changes.
=> tools/{biolatency,biosnoop,biotop}: use TRACEPOINT_PROBE() for tracepoints

docs/reference_guide.md
Add descriptions in `docs/reference_guide.md` for using `pid` in `attach_uprobe` and `attach_uretprobe` functions that allows uprobes to be attached to a specific process. The introduced contents were mainly referred by the comments of `attach_probe` function in [bcc/src/python/bcc/\_\_init\_\_.py](https://github.com/iovisor/bcc/blob/78423e1667db202012bbb032c567589175a2796c/src/python/bcc/__init__.py#L1413-L1440). 
I was trying to attach `uprobe` to a specific process but did not find enough useful information in `docs/reference_guide.md`, which blocked me for sometime. I then moved to the source code of `attach_uprobe` ad `attach_uretprobe` in `bcc/src/python/bcc/__init__.py` and found the missing descriptions for `pid` parameter. 
Making this PR to make it clear of how to attach uprobes …
=> docs: Add descriptions for using pid in attach_uprobe and attach_uretprobe

libbpf-tools/klockstat.c
Commit 789e923f ("libbpf-tools/klockstat: Allows kprobe fallback to work with lock debugging (#5359)") add new kprobes to be enabled on debug kernel and disabled on normal kernel. But it forgot to disable them in the fentry code, along with other kprobes.
Disable *_nested kprobes in the fentry code.
Fixes: 789e923f ("libbpf-tools/klockstat: Allows kprobe fallback to work with lock debugging (#5359)")
=> libbpf-tools/klockstat: Disable *_nested kprobes in the fentry code

README.md, man/man8/softirqslower.8, snap/snapcraft.yaml, tests/python/test_tools_smoke.py, tools/softirqslower.py, tools/softirqslower_example.txt
Adds `softirqslower` tool to trace softirq execution performance issues by measuring:
1. **SoftIRQ Runtime**: Handler execution duration 
2. **HardIRQ-to-SoftIRQ Latency**: Delay between wakeup (trigger) and execution start
Diagnosing network latency/stalls requires observing:
- Slow softirq executions (e.g., >10ms NET_RX processing)
- Scheduling delays where softirqs get preempted after wakeup
This closes https://github.com/iovisor/bcc/issues/5353
=> tools: add softirqslower

tools/tcpconnect.py
Tcpconnect with DNS (`-d` flag) does not work with Linux>=6.4. The kernel representation of `struct iov_iter` changed in 6.4.
This PR adapts the iov field depending on the structure. It also removes `inet_sk()` which did not work on a recent kernel (6.6).
=> tools/tcpconnect: fix iov field for DNS with Linux>=6.4

tools/biolatency.py, tools/biosnoop.py, tools/biotop.py, tools/btrfsdist.py, tools/btrfsslower.py, tools/cpuunclaimed.py, tools/criticalstat.py, tools/drsnoop.py, tools/ext4dist.py, tools/ext4slower.py, tools/f2fsslower.py, tools/funclatency.py, tools/nfsdist.py, tools/offcputime.py, tools/offwaketime.py, tools/old/offcputime.py, tools/old/offwaketime.py, tools/old/stackcount.py, tools/old/wakeuptime.py, tools/opensnoop.py, tools/readahead.py, tools/stackcount.py, tools/swapin.py, tools/syscount.py, tools/tcpdrop.py, tools/wakeuptime.py, tools/xfsdist.py, tools/zfsdist.py
Some BCC tools currently exit with status code 0 even when encountering
fatal errors. This makes it impossible to distinguish between success and
failure, which makes smoke tests (and packaging checks) unreliable.
Examples are:
- No kprobe or tracepoint event attached
- Missing required symbols in /proc/kallsyms
- Invalid or conflicting command-line options
This PR updates the BCC python tools to consistently return exit(1) in
these cases. This ensures errors are clearly reported and allows the
tools to be used more effectively in automated workflows such as smoke
testing.
=> Fix exit codes in BCC python tools for reliable error handling
